-- ───────────────────────────────────────────────────────────────────────────
--  Partition accounts.acc_bill_balance by LIST (abl_acc_year)
--
--  20260811080000 deliberately left this table unpartitioned, on the grounds
--  that a bill stays open across financial years and every cross-year
--  settlement would otherwise have to carry a composite key. That decision is
--  reversed here: the bill is partitioned on the FY it was RAISED in, the same
--  way acc_bill_adjustment / acc_voucher_header / acc_tender_detail and the
--  sales documents already are.
--
--  What that costs, stated plainly so nobody has to rediscover it:
--
--    * The row never moves partition. A bill raised in 2025-2026 and settled in
--      2026-2027 stays in the 2025-2026 partition — the partition says "where
--      it started", not "where the money is".
--    * Outstanding and ageing reads are company-wide and carry no year filter,
--      so they scan every partition. Pruning only helps reads that do filter on
--      abl_acc_year.
--    * Detaching a closed year takes its still-open bills with it.
--    * pk_acc_bill_balance is now (abl_id, abl_acc_year): Postgres requires
--      every unique constraint on a partitioned table to contain the partition
--      key, so a bill is addressed by the PAIR from here on. Every caller that
--      said `where: { ablId }` has to say `where: { ablId_ablAccYear }`.
--
--  Three references into the bill therefore gain a year column:
--
--    1. acc_bill_adjustment.abj_bill_id          -> + abj_bill_acc_year
--       and     .abj_against_bill_id             -> + abj_against_bill_acc_year
--       The bill's OWN year, which is exactly the column that differs from
--       abj_acc_year whenever a bill is cleared after year end.
--    2. acc_bill_balance.abl_parent_bill_id      -> + abl_parent_acc_year
--       (the INTEREST / debit-note self-reference), kept null-or-set together
--       by ck_abl_parent_pair.
--    3. acc_vouchers.av_doc_id                   -> av_doc_acc_year, which
--       already exists and is already paired by ck_av_doc_pair; only fk_av_doc
--       changes, back to the composite form it had before 20260811080000.
--
--  Postgres cannot ALTER an ordinary table into a partitioned one, so the table
--  is rebuilt: parked under an `_unpart` name, recreated as a partitioned
--  parent, rows copied over, parked table dropped. acc_bill_adjustment is
--  altered in place — it is already partitioned and its new columns are
--  backfilled from the bill they point at.
--
--  Prisma Migrate can express none of PARTITION BY, composite partition-aware
--  primary keys, generated columns, partial indexes or CHECK constraints, so
--  this migration is hand-written rather than generated by `prisma migrate dev`.
-- ───────────────────────────────────────────────────────────────────────────


-- ───────────────────────────────────────────────────────────────────────────
--  1. Drop every reference into the bill's soon-to-be-replaced key
--
--  All three point at abl_id alone, which stops being a unique constraint the
--  moment the table is partitioned. They come back in sections 6, 7 and 9.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE accounts.acc_vouchers        DROP CONSTRAINT IF EXISTS fk_av_doc;
ALTER TABLE accounts.acc_bill_adjustment DROP CONSTRAINT IF EXISTS fk_abj_bill;
ALTER TABLE accounts.acc_bill_adjustment DROP CONSTRAINT IF EXISTS fk_abj_against_bill;


-- ───────────────────────────────────────────────────────────────────────────
--  2. Park the unpartitioned table
--
--  Constraint names are per-table, but index names are per-schema, so every
--  index the rebuilt table re-declares has to be moved out of the way first.
--  Renaming a constraint renames the index behind it.
--
--  fk_abl_parent is a self-reference and rides along on the parked table; it is
--  dropped with it in section 8.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE accounts.acc_bill_balance RENAME TO acc_bill_balance_unpart;

ALTER TABLE accounts.acc_bill_balance_unpart
    RENAME CONSTRAINT pk_acc_bill_balance TO pk_acc_bill_balance_unpart;

ALTER INDEX accounts.ux_abl_doc_refno RENAME TO ux_abl_doc_refno_unpart;
ALTER INDEX accounts.ix_abl_open      RENAME TO ix_abl_open_unpart;
ALTER INDEX accounts.ix_abl_overdue   RENAME TO ix_abl_overdue_unpart;
ALTER INDEX accounts.ix_abl_voucher   RENAME TO ix_abl_voucher_unpart;
ALTER INDEX accounts.ix_abl_salesman  RENAME TO ix_abl_salesman_unpart;
ALTER INDEX accounts.ix_abl_src_doc   RENAME TO ix_abl_src_doc_unpart;
ALTER INDEX accounts.ix_abl_parent    RENAME TO ix_abl_parent_unpart;


-- ───────────────────────────────────────────────────────────────────────────
--  3. The partitioned parent
--
--  Column list, constraints and comments are carried over unchanged from
--  20260811080000 except for the primary key, the parent self-reference and the
--  new abl_parent_acc_year column.
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE accounts.acc_bill_balance
(
    abl_id                uuid           NOT NULL DEFAULT uuidv7(),
    abl_company_id        uuid           NOT NULL,
    abl_branch_id         uuid           NOT NULL,   -- branch that RAISED it
    abl_tenant_id         uuid,
    abl_acc_year          character(9)   NOT NULL,   -- FY of origin, and the partition key

    -- ── Party ────────────────────────────────────────────────────────────
    abl_party_id          uuid           NOT NULL,
    abl_salesman_id       uuid,
    abl_agent_id          uuid,

    -- ── What kind of bill ────────────────────────────────────────────────
    -- SALES / PURCHASE ........ a real invoice
    -- SALES_RETURN /
    -- PURCHASE_RETURN ......... a credit / debit note. It is a BILL in its own
    --                           right: the RRN tender adjusts an invoice
    --                           against it, which needs both sides to exist
    --                           here (see acc_bill_adjustment).
    -- OPENING ................. lump-sum legacy outstanding brought in at
    --                           migration; the only type with no voucher
    -- ADVANCE ................. money received or paid with no bill yet —
    --                           a sale-order booking, a supplier advance
    -- INTEREST ................ overdue interest raised against a parent bill
    -- JOURNAL ................. a party bill reference opened by a JV
    abl_bill_type         character varying(20) NOT NULL,

    -- ── Source document ──────────────────────────────────────────────────
    -- The business document behind the bill, named directly rather than via
    -- the voucher: an ADVANCE has to be able to say WHICH sale order it was
    -- taken against, and every drill-down from a bill list wants the document
    -- without a hop through acc_voucher_header.
    abl_src_module        character varying(20),
    abl_src_doc_type      character varying(30),
    abl_src_doc_id        uuid,
    abl_src_acc_year      character(9),

    -- INTEREST / a debit note raised against another bill points at it here.
    -- The bill is addressed by (id, year) now, so the year comes with it — and
    -- it is the PARENT's year, which is not abl_acc_year whenever interest is
    -- raised in a later FY than the bill it is charged on.
    abl_parent_bill_id    uuid,
    abl_parent_acc_year   character(9),

    -- ── Posting ──────────────────────────────────────────────────────────
    -- The voucher that opened this bill (posted server-side, after sync).
    -- NULL only for OPENING, which has no voucher — and then the voucher TYPE
    -- is null with it, rather than forcing a dummy type row into the master.
    abl_voucher_id        uuid,
    abl_voucher_line_id   uuid,
    abl_voucher_type_id   integer,
    abl_voucher_no        bigint,
    abl_voucher_date      date,
    abl_voucher_refno     character varying(50),

    -- ── Bill identity ────────────────────────────────────────────────────
    abl_doc_refno         character varying(100) NOT NULL,
    abl_doc_date          date           NOT NULL,
    abl_due_date          date,
    abl_credit_days       smallint       NOT NULL DEFAULT 0,
    abl_grace_days        smallint       NOT NULL DEFAULT 0,
    abl_dr_cr             character(2)   NOT NULL,   -- DR = receivable, CR = payable
    abl_narration         text,

    -- ── Amounts ──────────────────────────────────────────────────────────
    -- The three settled columns are TRIGGER-MAINTAINED from
    -- acc_bill_adjustment. Never written from application code.
    abl_bill_amount       numeric(18,2)  NOT NULL,
    abl_alloc_amount      numeric(18,2)  NOT NULL DEFAULT 0,
    abl_disc_amount       numeric(18,2)  NOT NULL DEFAULT 0,
    abl_writeoff_amount   numeric(18,2)  NOT NULL DEFAULT 0,
    abl_pending_amount    numeric(18,2)
        GENERATED ALWAYS AS (abl_bill_amount - abl_alloc_amount
                             - abl_disc_amount - abl_writeoff_amount) STORED,

    -- Repeats the arithmetic rather than reading abl_pending_amount: a
    -- generated column may not reference another generated column.
    abl_status            character varying(10)
        GENERATED ALWAYS AS (
            CASE WHEN abl_bill_amount - abl_alloc_amount
                      - abl_disc_amount - abl_writeoff_amount <= 0 THEN 'CLOSED'
                 WHEN abl_alloc_amount + abl_disc_amount
                      + abl_writeoff_amount > 0                    THEN 'PARTIAL'
                 ELSE 'OPEN' END) STORED,

    -- When it went to zero. Maintained with the three amounts above, and
    -- CLEARED again if a reversal reopens the bill. Days-to-collect / DSO has
    -- no other source once the row stays open across years, and the partial
    -- indexes below deliberately exclude closed bills.
    abl_settled_on        date,

    -- ── Audit ────────────────────────────────────────────────────────────
    abl_is_active         boolean NOT NULL DEFAULT true,
    abl_is_deleted        boolean NOT NULL DEFAULT false,
    abl_sync_date         timestamp(6) with time zone,
    abl_created_on        timestamp(6) with time zone NOT NULL DEFAULT now(),
    abl_created_by        varchar(50),
    abl_modified_on       timestamp(6) with time zone,
    abl_modified_by       varchar(50),

    -- The partition key joins the key: a unique constraint on a partitioned
    -- table must contain it.
    CONSTRAINT pk_acc_bill_balance PRIMARY KEY (abl_id, abl_acc_year),

    CONSTRAINT fk_abl_voucher FOREIGN KEY (abl_voucher_id, abl_acc_year)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id, avh_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_abl_voucher_type FOREIGN KEY (abl_voucher_type_id)
        REFERENCES accounts.acc_voucher_types (vchr_type_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_abl_party FOREIGN KEY (abl_party_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    -- fk_abl_parent is added in section 6: a self-reference cannot be declared
    -- against a key that does not exist until the table does.

    CONSTRAINT ck_abl_bill_type CHECK (abl_bill_type::text = ANY (ARRAY[
        'SALES'::text, 'PURCHASE'::text,
        'SALES_RETURN'::text, 'PURCHASE_RETURN'::text,
        'OPENING'::text, 'ADVANCE'::text, 'INTEREST'::text, 'JOURNAL'::text])),
    CONSTRAINT ck_abl_dr_cr CHECK (abl_dr_cr = ANY (ARRAY['DR'::bpchar, 'CR'::bpchar])),

    CONSTRAINT ck_abl_acc_year CHECK (
        abl_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(abl_acc_year, 4)::int = LEFT(abl_acc_year, 4)::int + 1),
    CONSTRAINT ck_abl_src_acc_year CHECK (
        abl_src_acc_year IS NULL OR abl_src_acc_year ~ '^[0-9]{4}-[0-9]{4}$'),

    -- OPENING has no source voucher; every other type must have one, and the
    -- voucher type travels with it.
    CONSTRAINT ck_abl_voucher CHECK (
        (abl_bill_type::text = 'OPENING'
             AND abl_voucher_id IS NULL AND abl_voucher_type_id IS NULL)
        OR (abl_bill_type::text <> 'OPENING'
             AND abl_voucher_id IS NOT NULL AND abl_voucher_type_id IS NOT NULL)),

    -- A source document is named by all three parts or by none.
    CONSTRAINT ck_abl_src_doc CHECK (
        (abl_src_doc_id IS NULL AND abl_src_doc_type IS NULL)
        OR (abl_src_doc_id IS NOT NULL AND abl_src_doc_type IS NOT NULL)),

    -- Interest is always raised ON something.
    CONSTRAINT ck_abl_parent CHECK (
        abl_bill_type::text <> 'INTEREST' OR abl_parent_bill_id IS NOT NULL),
    -- The parent pointer addresses a composite key, so both halves move
    -- together.
    CONSTRAINT ck_abl_parent_pair CHECK (
        (abl_parent_bill_id IS NULL) = (abl_parent_acc_year IS NULL)),
    CONSTRAINT ck_abl_no_self_parent CHECK (
        abl_parent_bill_id IS NULL OR abl_parent_bill_id <> abl_id),

    CONSTRAINT ck_abl_amount CHECK (abl_bill_amount > 0),
    CONSTRAINT ck_abl_due_date CHECK (
        abl_due_date IS NULL OR abl_due_date >= abl_doc_date),
    CONSTRAINT ck_abl_days CHECK (abl_credit_days >= 0 AND abl_grace_days >= 0),

    -- The over-settlement guard: a bill can never be edited down below what
    -- has already been settled, discounted or written off against it — and
    -- equally, adjustments can never add up past the bill.
    CONSTRAINT ck_abl_settled CHECK (
        abl_alloc_amount >= 0 AND abl_disc_amount >= 0 AND abl_writeoff_amount >= 0
        AND (abl_alloc_amount + abl_disc_amount + abl_writeoff_amount) <= abl_bill_amount)
) PARTITION BY LIST (abl_acc_year);

ALTER TABLE accounts.acc_bill_balance OWNER to postgres;


-- ───────────────────────────────────────────────────────────────────────────
--  Bill indexes
--
--  Declared on the parent, so partitions created later inherit them. Every
--  predicate is carried over unchanged from 20260811080000; ux_abl_doc_refno
--  already contained abl_acc_year, which is what lets it stay unique on a
--  partitioned table.
-- ───────────────────────────────────────────────────────────────────────────

-- Bill numbers restart each FY, so the FY is part of the key. NOTE: no branch
-- column — outstanding is company-wide for a chain store, which means two
-- branches must never issue the same refno to the same party in one year.
-- Every series in this system is device/branch prefixed, which is what makes
-- that safe; if a plain numeric series is ever introduced, add the branch.
CREATE UNIQUE INDEX ux_abl_doc_refno
    ON accounts.acc_bill_balance USING btree
    (abl_company_id, abl_party_id, abl_bill_type, abl_acc_year, abl_doc_refno)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abl_is_deleted = false;

-- The adjustment screen and the ageing report both live on this index: one
-- party's open bills, oldest first, with everything they show INCLUDEd so the
-- heap is never touched. Neither read filters on the year, so both scan every
-- partition — see the note at the top.
CREATE INDEX ix_abl_open
    ON accounts.acc_bill_balance USING btree
    (abl_company_id, abl_party_id, abl_doc_date)
    INCLUDE (abl_doc_refno, abl_bill_amount, abl_pending_amount, abl_dr_cr)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abl_is_deleted = false AND abl_pending_amount <> 0;

CREATE INDEX ix_abl_overdue
    ON accounts.acc_bill_balance USING btree (abl_company_id, abl_due_date)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abl_is_deleted = false AND abl_pending_amount <> 0;

CREATE INDEX ix_abl_voucher
    ON accounts.acc_bill_balance USING btree (abl_voucher_id, abl_acc_year)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abl_voucher_id IS NOT NULL AND abl_is_deleted = false;

CREATE INDEX ix_abl_salesman
    ON accounts.acc_bill_balance USING btree (abl_company_id, abl_salesman_id)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abl_is_deleted = false AND abl_pending_amount <> 0;

-- Document → its bill. The sale-order screen's advance panel, and every
-- "show me the outstanding this invoice became".
CREATE INDEX ix_abl_src_doc
    ON accounts.acc_bill_balance USING btree (abl_src_doc_type, abl_src_doc_id)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abl_src_doc_id IS NOT NULL AND abl_is_deleted = false;

-- Both halves of the parent key, so fk_abl_parent's cascade check and the
-- "what interest was raised on this bill" drill-down read the index alone.
CREATE INDEX ix_abl_parent
    ON accounts.acc_bill_balance USING btree (abl_parent_bill_id, abl_parent_acc_year)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abl_parent_bill_id IS NOT NULL AND abl_is_deleted = false;


COMMENT ON TABLE accounts.acc_bill_balance IS
    'One row per bill. Partitioned by LIST (abl_acc_year), the FY the bill was raised in. A bill is never carried forward at year end — the same row stays open across financial years, in the partition of the year it started in.';
COMMENT ON COLUMN accounts.acc_bill_balance.abl_acc_year IS
    'FY the bill originated in, and the partition key. A bill outstanding past year end keeps this year and never moves partition.';
COMMENT ON COLUMN accounts.acc_bill_balance.abl_branch_id IS
    'Branch that raised the bill. Settlement may happen at a different branch — that is recorded on acc_bill_adjustment.';
COMMENT ON COLUMN accounts.acc_bill_balance.abl_parent_acc_year IS
    'FY of the parent bill in abl_parent_bill_id — the parent''s own year, not this row''s. Second half of fk_abl_parent, set exactly when abl_parent_bill_id is (ck_abl_parent_pair).';
COMMENT ON COLUMN accounts.acc_bill_balance.abl_alloc_amount IS
    'Trigger-maintained from acc_bill_adjustment. Never write from application code.';
COMMENT ON COLUMN accounts.acc_bill_balance.abl_disc_amount IS
    'Trigger-maintained from acc_bill_adjustment (settlement discount / cash discount allowed on collection).';
COMMENT ON COLUMN accounts.acc_bill_balance.abl_writeoff_amount IS
    'Trigger-maintained from acc_bill_adjustment (bad debt / rounding write-off).';
COMMENT ON COLUMN accounts.acc_bill_balance.abl_settled_on IS
    'Date the bill last reached zero. Cleared again if a reversal reopens it.';


-- ───────────────────────────────────────────────────────────────────────────
--  4. Teach public.ensure_acc_year_partitions about the bill again
--
--  Same helper as 20260804112944 (extended by 20260808132323, 20260810130000,
--  20260810140000, 20260810160000, 20260811060000 and 20260811080000).
--  acc_bill_balance comes back into the list; everything else is unchanged.
--  Idempotent — call it whenever a fiscal year is opened:
--
--      SELECT public.ensure_acc_year_partitions('2027-2028');
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character(9))
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    -- The partition bound is a literal, so the year is validated rather than
    -- interpolated blind. char(9) makes 'YYYY-YYYY' the only well-formed value.
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_charge_detail FOR VALUES IN (%L)',
        'txn_charge_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_hold FOR VALUES IN (%L)',
        'txn_hold_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order FOR VALUES IN (%L)',
        'sale_order_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_item FOR VALUES IN (%L)',
        'sale_order_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_advance_alloc FOR VALUES IN (%L)',
        'sale_order_advance_alloc_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation FOR VALUES IN (%L)',
        'sale_quotation_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation_item FOR VALUES IN (%L)',
        'sale_quotation_item_' || v_suffix, v_year);

    -- The bill is partitioned again as of 20260811090000: on the FY it was
    -- RAISED in, which it keeps for life.
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_bill_balance FOR VALUES IN (%L)',
        'acc_bill_balance_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_bill_adjustment FOR VALUES IN (%L)',
        'acc_bill_adjustment_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_opening_balance FOR VALUES IN (%L)',
        'acc_opening_balance_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_pdc_register FOR VALUES IN (%L)',
        'acc_pdc_register_' || v_suffix, v_year);
END;
$$;

COMMENT ON FUNCTION public.ensure_acc_year_partitions(character(9)) IS
    'Idempotently creates the sale_bill / sale_bill_item / acc_tender_detail / txn_status_log / txn_charge_detail / txn_hold / sale_order / sale_order_item / sale_order_advance_alloc / sale_quotation / sale_quotation_item / acc_bill_balance / acc_bill_adjustment / acc_opening_balance / acc_pdc_register LIST partitions for one accounting year (YYYY-YYYY). Run it whenever a fiscal year is opened.';


-- ───────────────────────────────────────────────────────────────────────────
--  5. Partitions
--
--  Every year on record in fiscal_years, plus — belt and braces — any year the
--  parked rows actually carry, so nothing can fail to find a home below. Every
--  other parent in the helper already has its partitions, and
--  CREATE TABLE IF NOT EXISTS passes straight over them.
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_year text;
    BEGIN
        FOR v_year IN
            SELECT DISTINCT btrim(fy_year_name)
            FROM public.fiscal_years
            WHERE is_deleted = false
              AND btrim(fy_year_name) ~ '^[0-9]{4}-[0-9]{4}$'
            UNION
            SELECT DISTINCT btrim(abl_acc_year) FROM accounts.acc_bill_balance_unpart
            ORDER BY 1
            LOOP
                IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
                    RAISE EXCEPTION 'acc_bill_balance carries accounting year %, which is not YYYY-YYYY', v_year;
                END IF;
                PERFORM public.ensure_acc_year_partitions(v_year::character(9));
            END LOOP;
    END;
$$;


-- ───────────────────────────────────────────────────────────────────────────
--  6. Move the rows over, then close the parent self-reference
--
--  abl_pending_amount and abl_status are generated, so they are neither listed
--  nor copied. abl_parent_acc_year is a new column, read from the parent bill
--  rather than copied — the LEFT JOIN is against the parked table, which still
--  holds every row at this point.
--
--  A parent that no longer exists could not have satisfied the old fk_abl_parent
--  either, and would now fail ck_abl_parent_pair as well, so the dangling
--  pointer is dropped on the way through rather than failing the migration on
--  data that was never valid. (If such a row is an INTEREST bill, ck_abl_parent
--  rejects it and the migration stops — interest with no bill behind it is a
--  data problem somebody has to look at, not one to paper over.)
-- ───────────────────────────────────────────────────────────────────────────

INSERT INTO accounts.acc_bill_balance (
    abl_id, abl_company_id, abl_branch_id, abl_tenant_id, abl_acc_year,
    abl_party_id, abl_salesman_id, abl_agent_id, abl_bill_type,
    abl_src_module, abl_src_doc_type, abl_src_doc_id, abl_src_acc_year,
    abl_parent_bill_id, abl_parent_acc_year,
    abl_voucher_id, abl_voucher_line_id, abl_voucher_type_id, abl_voucher_no,
    abl_voucher_date, abl_voucher_refno,
    abl_doc_refno, abl_doc_date, abl_due_date, abl_credit_days, abl_grace_days,
    abl_dr_cr, abl_narration,
    abl_bill_amount, abl_alloc_amount, abl_disc_amount, abl_writeoff_amount,
    abl_settled_on,
    abl_is_active, abl_is_deleted, abl_sync_date, abl_created_on, abl_created_by,
    abl_modified_on, abl_modified_by
)
SELECT
    old.abl_id, old.abl_company_id, old.abl_branch_id, old.abl_tenant_id, old.abl_acc_year,
    old.abl_party_id, old.abl_salesman_id, old.abl_agent_id, old.abl_bill_type,
    old.abl_src_module, old.abl_src_doc_type, old.abl_src_doc_id, old.abl_src_acc_year,
    CASE WHEN parent.abl_id IS NULL THEN NULL ELSE old.abl_parent_bill_id END,
    parent.abl_acc_year,
    old.abl_voucher_id, old.abl_voucher_line_id, old.abl_voucher_type_id, old.abl_voucher_no,
    old.abl_voucher_date, old.abl_voucher_refno,
    old.abl_doc_refno, old.abl_doc_date, old.abl_due_date, old.abl_credit_days, old.abl_grace_days,
    old.abl_dr_cr, old.abl_narration,
    old.abl_bill_amount, old.abl_alloc_amount, old.abl_disc_amount, old.abl_writeoff_amount,
    old.abl_settled_on,
    old.abl_is_active, old.abl_is_deleted, old.abl_sync_date, old.abl_created_on, old.abl_created_by,
    old.abl_modified_on, old.abl_modified_by
FROM accounts.acc_bill_balance_unpart AS old
LEFT JOIN accounts.acc_bill_balance_unpart AS parent
       ON parent.abl_id = old.abl_parent_bill_id;

ALTER TABLE accounts.acc_bill_balance
    ADD CONSTRAINT fk_abl_parent
        FOREIGN KEY (abl_parent_bill_id, abl_parent_acc_year)
        REFERENCES accounts.acc_bill_balance (abl_id, abl_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT;


-- ───────────────────────────────────────────────────────────────────────────
--  7. The adjustment learns the bill's year
--
--  Altered in place: acc_bill_adjustment is already partitioned and none of its
--  own keys change. abj_bill_acc_year is the FY the bill was RAISED in, which
--  is not abj_acc_year whenever a bill is cleared after year end — that gap is
--  the whole reason the two tables are partitioned on different years.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE accounts.acc_bill_adjustment
    ADD COLUMN IF NOT EXISTS abj_bill_acc_year         character(9),
    ADD COLUMN IF NOT EXISTS abj_against_bill_acc_year character(9);

UPDATE accounts.acc_bill_adjustment AS adj
SET abj_bill_acc_year = bill.abl_acc_year
FROM accounts.acc_bill_balance AS bill
WHERE bill.abl_id = adj.abj_bill_id;

UPDATE accounts.acc_bill_adjustment AS adj
SET abj_against_bill_acc_year = bill.abl_acc_year
FROM accounts.acc_bill_balance AS bill
WHERE adj.abj_against_bill_id IS NOT NULL
  AND bill.abl_id = adj.abj_against_bill_id;

-- A settlement whose bill has vanished could not have existed under the old
-- fk_abj_bill, and abj_bill_id is NOT NULL, so there is nothing to clear —
-- fail loudly instead.
DO
$$
    DECLARE
        v_orphans bigint;
    BEGIN
        SELECT count(*) INTO v_orphans
        FROM accounts.acc_bill_adjustment
        WHERE abj_bill_acc_year IS NULL;
        IF v_orphans > 0 THEN
            RAISE EXCEPTION
                'acc_bill_adjustment has % row(s) pointing at a bill that does not exist', v_orphans;
        END IF;

        SELECT count(*) INTO v_orphans
        FROM accounts.acc_bill_adjustment
        WHERE abj_against_bill_id IS NOT NULL
          AND abj_against_bill_acc_year IS NULL;
        IF v_orphans > 0 THEN
            RAISE EXCEPTION
                'acc_bill_adjustment has % row(s) whose against-bill does not exist', v_orphans;
        END IF;
    END;
$$;

ALTER TABLE accounts.acc_bill_adjustment
    ALTER COLUMN abj_bill_acc_year SET NOT NULL;

ALTER TABLE accounts.acc_bill_adjustment
    ADD CONSTRAINT ck_abj_bill_acc_year CHECK (
        abj_bill_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(abj_bill_acc_year, 4)::int = LEFT(abj_bill_acc_year, 4)::int + 1),
    -- The against-bill pointer addresses a composite key, so both halves move
    -- together. ck_abj_against already decides WHEN it must be set.
    ADD CONSTRAINT ck_abj_against_bill_pair CHECK (
        (abj_against_bill_id IS NULL) = (abj_against_bill_acc_year IS NULL));

ALTER TABLE accounts.acc_bill_adjustment
    ADD CONSTRAINT fk_abj_bill
        FOREIGN KEY (abj_bill_id, abj_bill_acc_year)
        REFERENCES accounts.acc_bill_balance (abl_id, abl_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_abj_against_bill
        FOREIGN KEY (abj_against_bill_id, abj_against_bill_acc_year)
        REFERENCES accounts.acc_bill_balance (abl_id, abl_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT;

-- Both halves of the bill key, so the roll-up and the bill drill-down read the
-- index alone. Replaces the id-only ix_abj_bill from 20260811080000.
DROP INDEX IF EXISTS accounts.ix_abj_bill;
CREATE INDEX ix_abj_bill
    ON accounts.acc_bill_adjustment USING btree
    (abj_bill_id, abj_bill_acc_year, abj_adj_date)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE abj_is_deleted = false;

COMMENT ON COLUMN accounts.acc_bill_adjustment.abj_bill_acc_year IS
    'FY of the bill being settled — the bill''s own year, not abj_acc_year. Second half of fk_abj_bill, which addresses the bill''s composite (abl_id, abl_acc_year) key.';
COMMENT ON COLUMN accounts.acc_bill_adjustment.abj_against_bill_acc_year IS
    'FY of the bill on the other side of a two-sided settlement. Second half of fk_abj_against_bill, set exactly when abj_against_bill_id is (ck_abj_against_bill_pair).';


-- ───────────────────────────────────────────────────────────────────────────
--  8. Prove nothing was lost, then drop the parked table
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_old bigint;
        v_new bigint;
    BEGIN
        SELECT count(*) INTO v_old FROM accounts.acc_bill_balance_unpart;
        SELECT count(*) INTO v_new FROM accounts.acc_bill_balance;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'acc_bill_balance copy lost rows: % -> %', v_old, v_new;
        END IF;
    END;
$$;

DROP TABLE accounts.acc_bill_balance_unpart;


-- ───────────────────────────────────────────────────────────────────────────
--  9. Point acc_vouchers back at the bill's composite key
--
--  av_doc_acc_year already exists and is already paired with av_doc_id by
--  ck_av_doc_pair (20260811060000 added both; 20260811080000 dropped only the
--  foreign key). It is backfilled again here rather than trusted, because
--  nothing enforced it while fk_av_doc addressed abl_id alone.
-- ───────────────────────────────────────────────────────────────────────────

UPDATE accounts.acc_vouchers AS v
SET av_doc_acc_year = bill.abl_acc_year
FROM accounts.acc_bill_balance AS bill
WHERE v.av_doc_id IS NOT NULL
  AND bill.abl_id = v.av_doc_id
  AND (v.av_doc_acc_year IS DISTINCT FROM bill.abl_acc_year);

-- Same reasoning as the parent pointer above: a doc id with no bill behind it
-- could not have satisfied the old fk_av_doc.
UPDATE accounts.acc_vouchers
SET av_doc_id = NULL,
    av_doc_acc_year = NULL
WHERE av_doc_id IS NOT NULL
  AND av_doc_acc_year IS NULL;

ALTER TABLE accounts.acc_vouchers
    ADD CONSTRAINT fk_av_doc FOREIGN KEY (av_doc_id, av_doc_acc_year)
        REFERENCES accounts.acc_bill_balance (abl_id, abl_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT;

COMMENT ON COLUMN accounts.acc_vouchers.av_doc_acc_year IS
    'FY of the bill in av_doc_id — the bill''s own year, not the voucher''s. Second half of fk_av_doc, set exactly when av_doc_id is (ck_av_doc_pair).';
