-- CreateTable
-- sales.sale_bill / sales.sale_bill_item are declaratively partitioned by
-- LIST (acc_year). Prisma Migrate cannot express PARTITION BY, composite
-- partition-aware primary keys, or CHECK constraints, so this migration is
-- hand-written rather than generated by `prisma migrate dev`. Partitions
-- (e.g. sale_bill_2026_2027) must be created separately, per accounting
-- year, before rows can be inserted into the parent tables.
CREATE TABLE IF NOT EXISTS sales.sale_bill
(
    sb_id                 uuid           NOT NULL DEFAULT uuidv7(),
    sb_company_id         uuid           NOT NULL,
    sb_branch_id          uuid           NOT NULL,
    sb_tenant_id          uuid,
    sb_acc_year           character(9)   NOT NULL,

    -- Where it was raised. Counter is NOT NULL: in an offline chain the
    -- counter owns the document and its number series.
    sb_session_id         uuid,
    sb_counter_id         uuid           NOT NULL,
    sb_device_type        character varying(20) NOT NULL,
    sb_device_id          text           NOT NULL,

    -- ── Document identity ────────────────────────────────────────────────
    sb_doc_type           character varying(30)  NOT NULL DEFAULT 'TAX_INVOICE',
    sb_bill_type          character varying(20)  NOT NULL DEFAULT 'CASH',   -- CASH | CREDIT
    sb_category_id        uuid,
    sb_price_level        integer        NOT NULL,
    sb_bill_slno          bigint         NOT NULL,   -- per company/branch/year/COUNTER
    sb_bill_refno         character varying(100) NOT NULL,
    sb_usr_refno          character varying(100),
    sb_bill_date          date           NOT NULL,
    sb_bill_datetime      timestamp(6) with time zone NOT NULL DEFAULT now(),
    sb_due_days           integer,
    sb_due_date           date,

    -- Where it came from: quotation, sales order, delivery challan.
    sb_src_doc_type       character varying(30),
    sb_src_doc_id         uuid,
    sb_src_doc_refno      character varying(100),
    sb_src_doc_date       date,

    -- ── Customer, snapshotted at billing time ────────────────────────────
    sb_cust_id            uuid NOT NULL,
    sb_cust_name          character varying(200) NOT NULL,
    sb_cust_addr          character varying(500),
    sb_cust_place         character varying(100),
    sb_cust_pin           character varying(10),
    sb_cust_phone         character varying(20),
    sb_cust_gstin         character varying(15),
    sb_cust_gst_type      character varying(20),
    sb_cust_stcd          character(2),
    sb_pos_stcd           character(2),          -- place of supply: CGST+SGST vs IGST
    sb_state_name         character varying(100),

    -- ── Options carried on the document ──────────────────────────────────
    sb_has_load           boolean NOT NULL DEFAULT false,
    sb_has_unload         boolean NOT NULL DEFAULT false,
    sb_has_freight        boolean NOT NULL DEFAULT false,
    sb_has_promo          boolean NOT NULL DEFAULT false,
    sb_has_comm           boolean NOT NULL DEFAULT false,
    sb_has_loyalty        boolean NOT NULL DEFAULT false,

    -- ── People ───────────────────────────────────────────────────────────
    sb_user_id            uuid           NOT NULL,
    sb_salesman_id        uuid[],
    sb_agent_id           uuid,
    sb_agent_comm_perc    numeric(15,4),
    sb_agent_comm_amt     numeric(15,2),

    -- ── Delivery ─────────────────────────────────────────────────────────
    sb_driver_id          uuid,
    sb_loadman_id         uuid[],
    sb_packed_id          uuid[],
    sb_supervisor_id      uuid,
    sb_vehicle_id         uuid,
    sb_vehicle_no         character varying(20),

    -- ── Quantities ───────────────────────────────────────────────────────
    sb_tot_items          integer        NOT NULL DEFAULT 0,   -- printed LINES, not split rows
    sb_tot_weight         numeric(15,3)  NOT NULL DEFAULT 0,
    sb_tot_bags           numeric(15,3)  NOT NULL DEFAULT 0,

    -- ── Money ────────────────────────────────────────────────────────────
    sb_gross_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    sb_item_disc          numeric(15,2)  NOT NULL DEFAULT 0,
    sb_spl_disc           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_sch_disc           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_bill_sch_disc      numeric(15,2)  NOT NULL DEFAULT 0,
    sb_addl_disc1         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_addl_disc2         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_cash_disc          numeric(15,2)  NOT NULL DEFAULT 0,

    sb_taxable_amt        numeric(15,2)  NOT NULL DEFAULT 0,   -- POST-charge
    sb_cgst_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_sgst_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_igst_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_cess_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_tax_amt            numeric(15,2)  NOT NULL DEFAULT 0,

    -- Roll-ups of sales.sale_doc_charge rows (reporting without a join).
    sb_freight_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    sb_load_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_unload_amt         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_other_amt1         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_other_amt2         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_round_off          numeric(15,2)  NOT NULL DEFAULT 0,
    sb_bill_amt           numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── Costing (never printed; drives margin reports) ───────────────────
    sb_total_cost         numeric(15,2),
    sb_margin_amt         numeric(15,2),
    sb_margin_amt_wot     numeric(15,2),
    sb_margin_perc        numeric(15,4),
    sb_mrp_savings        numeric(15,3)  DEFAULT 0,
    sb_mrp_savings_perc   numeric(15,4)  DEFAULT 0,

    -- ── Settlement roll-ups ──────────────────────────────────────────────
    -- Tender rows live in accounts.acc_tender_detail; these are caches so a
    -- counter can balance without a join. sb_balance_amt mirrors
    -- accounts.acc_voucher_bills once posted.
    sb_pay_mode           character varying(20),   -- dominant mode, quick filters
    sb_credit_amt         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_surcharge_amt      numeric(15,2)  NOT NULL DEFAULT 0,
    sb_tender_amt         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_refund_amt         numeric(15,2)  NOT NULL DEFAULT 0,
    sb_advance_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    sb_paid_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    sb_balance_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    sb_pay_status         character varying(20) NOT NULL DEFAULT 'UNPAID',

    -- ── Return caches (sales.sale_return is the document) ────────────────
    sb_returned_amt       numeric(15,2)  NOT NULL DEFAULT 0,
    sb_return_status      character varying(20),               -- NULL|PARTIAL|FULL

    -- ── Terms ────────────────────────────────────────────────────────────
    sb_payment_terms      character varying(250),
    sb_delivery_terms     character varying(250),
    sb_terms_conditions   text,
    sb_remarks            character varying(500),

    -- ── Pricing policy, snapshotted as this document was billed ──────────
    sb_freight_calc_type  character varying(12),
    sb_loading_calc_type  character varying(12),
    sb_disc_alter_base    boolean,
    sb_round_off_step     numeric(15,2) NOT NULL DEFAULT 1,

    -- ── Lifecycle ────────────────────────────────────────────────────────
    sb_status             character varying(20) NOT NULL DEFAULT 'DRAFT',
    sb_posted_on          timestamp(6) with time zone,
    sb_posted_voucher_id  uuid,                    -- accounts.acc_voucher_header
    sb_approved_on        timestamp(6) with time zone,
    sb_approved_by        uuid,
    sb_cancelled_on       timestamp(6) with time zone,
    sb_cancelled_by       uuid,
    sb_cancel_reason      character varying(250),
    sb_version_no         integer NOT NULL DEFAULT 1,
    sb_print_count        integer NOT NULL DEFAULT 0,

    -- ── Audit ────────────────────────────────────────────────────────────
    sb_is_deleted         boolean NOT NULL DEFAULT false,
    sb_sync_date          timestamp(6) with time zone,
    sb_created_on         timestamp(6) with time zone NOT NULL DEFAULT now(),
    sb_created_by         varchar    NOT NULL,
    sb_modified_on        timestamp(6) with time zone,
    sb_modified_by        varchar,

    CONSTRAINT pk_sale_bill PRIMARY KEY (sb_id, sb_acc_year),

    CONSTRAINT fk_sb_cust FOREIGN KEY (sb_cust_id)
        REFERENCES sales.customers (cus_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sb_pos_state FOREIGN KEY (sb_pos_stcd)
        REFERENCES fixed.state_codes (state_code) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sb_price_level FOREIGN KEY (sb_price_level)
        REFERENCES inventory.item_price_levels (ipl_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT

    -- ck_sb_doc_type, ck_sb_bill_type, ck_sb_status, ck_sb_pay_status and
    -- ck_sb_return_status are enforced in the application layer instead
    -- (BillService.ensureBillValuesAreAllowed) — see src/modules/sales/bill.
) PARTITION BY LIST (sb_acc_year);

-- ───────────────────────────────────────────────────────────────────────────
--  Lines — one row per BATCH ALLOCATION
--  Printed line = GROUP BY sbi_line_no; stock/GST reads rows as they are.
-- ───────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sales.sale_bill_item
(
    sbi_id                uuid           NOT NULL DEFAULT uuidv7(),
    sbi_bill_id           uuid           NOT NULL,
    sbi_company_id        uuid           NOT NULL,
    sbi_branch_id         uuid           NOT NULL,
    sbi_tenant_id         uuid,
    sbi_acc_year          character(9)   NOT NULL,

    -- The printed line, and which allocation within it. Non-batch items are
    -- always (line, 1).
    sbi_line_no           integer        NOT NULL,
    sbi_split_no           integer        NOT NULL DEFAULT 1,

    -- Which line of which source document this came from (order/quotation).
    sbi_src_doc_type      character varying(30),
    sbi_src_doc_id        uuid,
    sbi_src_doc_refno     character varying(100),
    sbi_src_item_qty      numeric(15,3),
    sbi_src_free_qty      numeric(15,3),

    -- ── What is being sold ───────────────────────────────────────────────
    sbi_item_id           uuid           NOT NULL,
    sbi_item_unit_id      uuid           NOT NULL,
    sbi_to_base_factor    numeric(15,6)  NOT NULL DEFAULT 0,
    sbi_hsn_code          character varying(8),
    sbi_price_level       integer        NOT NULL,
    sbi_ean_code          character varying(100),

    -- ── Where the stock came from ────────────────────────────────────────
    -- sbi_stock_id points at the inventory batch/stock row the quantity was
    -- taken from, so a reversal knows exactly what to put back.
    sbi_godown_id         uuid NOT NULL,
    sbi_stock_id          uuid NOT NULL,
    sbi_batch_no          character varying(100),
    sbi_batch_date        date,
    sbi_expiry_date       date,
    sbi_serial_no         character varying(100),

    -- ── Flags ────────────────────────────────────────────────────────────
    sbi_is_tax_incl       boolean NOT NULL DEFAULT false,
    sbi_is_promo          boolean NOT NULL DEFAULT false,
    sbi_is_free           boolean NOT NULL DEFAULT false,
    sbi_free_type         character varying(20),
    sbi_is_service        boolean NOT NULL DEFAULT false,
    sbi_has_freight       boolean NOT NULL DEFAULT false,

    -- ── Quantities (of THIS allocation) ──────────────────────────────────
    sbi_case_qty          numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_bill_qty          numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_length_qty        numeric(15,3)  DEFAULT 0,
    sbi_net_qty           numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_weight_qty        numeric(15,3)  DEFAULT 0,
    sbi_available_stock   numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_return_qty        numeric(15,3)  NOT NULL DEFAULT 0,   -- cache from sale_return

    -- ── Rates ────────────────────────────────────────────────────────────
    sbi_rate              numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_rate_pre_tax      numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_rate_diff         numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_act_price         numeric(15,4),
    sbi_max_price         numeric(15,4),                        -- MRP
    sbi_min_price         numeric(15,4),
    sbi_cost_price        numeric(15,4),
    sbi_cost_pre_tax      numeric(15,2),

    -- ── Discounts ────────────────────────────────────────────────────────
    sbi_item_disc_perc    numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_item_disc_qty     numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_item_disc_amt     numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_spl_disc_perc     numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_spl_disc_qty      numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_spl_disc_amt      numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_sch_disc_perc     numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_sch_disc_qty      numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_sch_disc_amt      numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_bill_sch_perc     numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_bill_sch_qty      numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_bill_sch_amt      numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_addl_disc1_perc   numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_addl_disc1_amt    numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_addl_disc2_perc   numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_addl_disc2_amt    numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_cash_disc_perc    numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_cash_disc_amt     numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── The charge-distribution trio ─────────────────────────────────────
    -- Goods value after line discounts (pre-charge, pre-tax), then this
    -- line's signed share of the before/after-tax charges.
    sbi_gross_amt         numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_net_gross         numeric(14,4),
    sbi_chrg_before_tax   numeric(14,4),
    sbi_chrg_after_tax    numeric(14,4),

    -- ── Tax (on the POST-charge taxable) ─────────────────────────────────
    sbi_taxable_amt       numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_tax_perc          numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_tax_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_cgst_perc         numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_cgst_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_sgst_perc         numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_sgst_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_igst_perc         numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_igst_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_cess_perc         numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_cess_per_unit     numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_cess_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_acess_perc        numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_acess_per_unit    numeric(15,4)  NOT NULL DEFAULT 0,
    sbi_acess_amt         numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── Per-line charges ─────────────────────────────────────────────────
    sbi_freight_qty       numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_freight_amt       numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_load_qty          numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_load_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_unload_qty        numeric(15,3)  NOT NULL DEFAULT 0,
    sbi_unload_amt        numeric(15,2)  NOT NULL DEFAULT 0,

    sbi_round_off         numeric(15,2)  NOT NULL DEFAULT 0,
    sbi_net_amt           numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── Costing / margin, PER UNIT ───────────────────────────────────────
    sbi_sold_price        numeric(15,4),
    sbi_sold_pre_tax      numeric(15,2),
    sbi_item_profit       numeric(15,2),
    sbi_profit_pre_tax    numeric(15,2),
    sbi_mrp_savings       numeric(15,3),
    sbi_mrp_savings_perc  numeric(15,4),

    -- ── Attribution ──────────────────────────────────────────────────────
    sbi_salesman_id       uuid,
    sbi_scheme_id         uuid,
    sbi_scheme_name       character varying(150),
    sbi_remarks           character varying(250),

    -- ── Audit ────────────────────────────────────────────────────────────
    sbi_is_deleted        boolean NOT NULL DEFAULT false,
    sbi_sync_date         timestamp(6) with time zone,
    sbi_created_on        timestamp(6) with time zone NOT NULL DEFAULT now(),
    sbi_created_by        uuid    NOT NULL,
    sbi_modified_on       timestamp(6) with time zone,
    sbi_modified_by       uuid,

    CONSTRAINT pk_sale_bill_item PRIMARY KEY (sbi_id, sbi_acc_year),

    CONSTRAINT fk_sbi_bill FOREIGN KEY (sbi_bill_id, sbi_acc_year)
        REFERENCES sales.sale_bill (sb_id, sb_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sbi_item FOREIGN KEY (sbi_item_id)
        REFERENCES inventory.item_master (item_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sbi_item_unit FOREIGN KEY (sbi_item_unit_id)
        REFERENCES inventory.item_unit_conversion (iuc_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sbi_price_level FOREIGN KEY (sbi_price_level)
        REFERENCES inventory.item_price_levels (ipl_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT

    -- ck_sbi_free_type, ck_sbi_split_no and ck_sbi_batch_split are enforced in
    -- the application layer instead (BillService.ensureBillItemValuesAreAllowed)
    -- — see src/modules/sales/bill.
) PARTITION BY LIST (sbi_acc_year);
