import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEnum, IsObject } from 'class-validator';
import {
  NullableDate,
  NullableStringStrict,
  NullableUpperMaxString,
  NullableUuid,
  OptionalBoolean,
  OptionalDate,
  OptionalInteger,
  OptionalNumber,
  OptionalTrimmedString,
  OptionalUpperMaxString,
  OptionalUuid,
} from 'src/common/dto/dtoDecorators';
import {
  TxnHoldDocType,
  TxnHoldKind,
  TxnHoldPartyType,
  TxnHoldSrcModule,
  TxnHoldStatus,
} from '../types/txn-hold-api.types';
// txh_acc_year is CHAR(9) 'YYYY-YYYY' — the partition key, so it is exactly the
// nine characters the partition bound is written with.
const ACC_YEAR_LENGTH = 9;
// One txn_hold row. Nothing is required by the decorators except the payload
// itself: a create needs the scope plus the document identity, an update needs
// only txhId and the fields that change, so "required on create" is enforced in
// the service (TxnHoldService.requireField) where the stored row fills the gaps.
export class SaveTxnHoldDto {
  @ApiPropertyOptional({
    format: 'uuid',
    description: 'When provided, updates that hold; otherwise a new hold is created',
  })
  @OptionalUuid()
  txhId?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'Required on create, immutable afterwards' })
  @OptionalUuid()
  txhCompanyId?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'Required on create, immutable afterwards' })
  @OptionalUuid()
  txhBranchId?: string;

  @ApiPropertyOptional({ format: 'uuid', nullable: true })
  @NullableUuid()
  txhTenantId?: string | null;

  @ApiPropertyOptional({
    minLength: ACC_YEAR_LENGTH,
    maxLength: ACC_YEAR_LENGTH,
    example: '2026-2027',
    description:
      'Accounting year the parked work belongs to. Half the primary key and the ' +
      'partition key: required on create, immutable afterwards',
  })
  @OptionalTrimmedString(ACC_YEAR_LENGTH)
  txhAccYear?: string;

  @ApiPropertyOptional({
    enum: TxnHoldKind,
    enumName: 'TxnHoldKind',
    default: TxnHoldKind.HOLD,
    description:
      'HOLD appears in the pick list; AUTOSAVE is the screen’s crash-recovery snapshot and is ' +
      'overwritten in place (one live row per device / operator / document type); TEMPLATE is ' +
      'copied on resume and never consumed',
  })
  @OptionalUpperMaxString(15)
  @IsEnum(TxnHoldKind)
  txhKind?: TxnHoldKind;

  @ApiPropertyOptional({
    enum: TxnHoldSrcModule,
    enumName: 'TxnHoldSrcModule',
    description: 'Module the parked screen belongs to. Required on create',
  })
  @OptionalUpperMaxString(20)
  @IsEnum(TxnHoldSrcModule)
  txhSrcModule?: TxnHoldSrcModule;

  @ApiPropertyOptional({
    enum: TxnHoldDocType,
    enumName: 'TxnHoldDocType',
    description: 'Document this hold will become. Required on create',
  })
  @OptionalUpperMaxString(30)
  @IsEnum(TxnHoldDocType)
  txhDocType?: TxnHoldDocType;

  // ck_txh_hold_no_shape stores it upper-cased and trimmed, so the decorator
  // normalises rather than letting the constraint reject the row.
  @ApiPropertyOptional({
    maxLength: 30,
    description:
      'Printed token number, generated by the till. Required on create and unique per ' +
      'company / branch / accounting year / document type. Stored upper-cased',
  })
  @OptionalUpperMaxString(30)
  txhHoldNo?: string;

  @ApiPropertyOptional({
    minimum: 1,
    description:
      'Raw per-device counter behind txhHoldNo, so an offline till can number a hold with no ' +
      'server round trip. Required on create and unique per device / year / document type',
  })
  @OptionalInteger(1)
  txhHoldSlno?: number;

  @ApiPropertyOptional({
    type: 'string',
    format: 'date-time',
    description: 'When the work was parked. Defaults to now',
  })
  @OptionalDate()
  txhHoldOn?: Date;

  @ApiPropertyOptional({
    format: 'uuid',
    description:
      'fixed.device_master.dev_id — the till that parked the work and owns its number series. ' +
      'Required on create',
  })
  @OptionalUuid()
  txhDeviceId?: string;

  @ApiPropertyOptional({ format: 'uuid', nullable: true, description: 'Till / cash counter' })
  @NullableUuid()
  txhCounterId?: string | null;

  @ApiPropertyOptional({ format: 'uuid', nullable: true, description: 'Shift / day session' })
  @NullableUuid()
  txhSessionId?: string | null;

  @ApiPropertyOptional({
    format: 'uuid',
    description: 'Operator at the screen. Required on create',
  })
  @OptionalUuid()
  txhHeldBy?: string;

  @ApiPropertyOptional({
    enum: TxnHoldPartyType,
    enumName: 'TxnHoldPartyType',
    nullable: true,
    description: 'Which master txhPartyId points into; required once txhPartyId is set',
  })
  @NullableUpperMaxString(15)
  @IsEnum(TxnHoldPartyType)
  txhPartyType?: TxnHoldPartyType | null;

  @ApiPropertyOptional({
    format: 'uuid',
    nullable: true,
    description: 'Customer / supplier / employee / ledger / branch (polymorphic — no FK)',
  })
  @NullableUuid()
  txhPartyId?: string | null;

  @ApiPropertyOptional({
    maxLength: 150,
    nullable: true,
    description: 'Snapshot for the pick list; a walk-in has a name and no party row at all',
  })
  @NullableStringStrict(150)
  txhPartyName?: string | null;

  @ApiPropertyOptional({ maxLength: 20, nullable: true })
  @NullableStringStrict(20)
  txhPartyMobile?: string | null;

  @ApiPropertyOptional({
    format: 'uuid',
    nullable: true,
    description: 'public.employee_master.emp_id — salesman, buyer or technician on the document',
  })
  @NullableUuid()
  txhStaffId?: string | null;

  @ApiPropertyOptional({
    maxLength: 50,
    nullable: true,
    description: 'Free label the floor recognises the hold by: table 7, bay 3, locker 12',
  })
  @NullableStringStrict(50)
  txhRefLabel?: string | null;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: 'Lines parked with the hold' })
  @OptionalInteger(0)
  txhItemCount?: number;

  // ck_txh_amounts — signs only. A half-typed screen is allowed to be
  // arithmetically incomplete; that is the difference between a hold and a
  // document.
  @ApiPropertyOptional({ minimum: 0, default: 0 })
  @OptionalNumber(0)
  txhTotalQty?: number;

  @ApiPropertyOptional({ minimum: 0, default: 0 })
  @OptionalNumber(0)
  txhNetAmount?: number;

  @ApiProperty({
    type: 'object',
    additionalProperties: true,
    description:
      'The module’s own save body, verbatim — header, items, charges, tenders, screen state. ' +
      'Required, and must be an object (ck_txh_payload_object): this module never reads into it',
  })
  @IsObject()
  txhPayload!: Record<string, unknown>;

  @ApiPropertyOptional({
    minimum: 1,
    default: 1,
    description: 'Version of the payload’s own shape, so an old hold stays readable after upgrade',
  })
  @OptionalInteger(1)
  txhPayloadVersion?: number;

  @ApiPropertyOptional({
    enum: TxnHoldStatus,
    enumName: 'TxnHoldStatus',
    default: TxnHoldStatus.HELD,
    description:
      'CONVERTED / EXPIRED / CANCELLED / ABANDONED are terminal — a hold in one of them cannot ' +
      'be reopened. The lease endpoints, not this payload, are what normally move it',
  })
  @OptionalUpperMaxString(15)
  @IsEnum(TxnHoldStatus)
  txhStatus?: TxnHoldStatus;

  @ApiPropertyOptional({ maxLength: 100, nullable: true, description: 'Why it was parked' })
  @NullableStringStrict(100)
  txhHoldReason?: string | null;

  @ApiPropertyOptional({ maxLength: 500, nullable: true })
  @NullableStringStrict(500)
  txhRemarks?: string | null;

  @ApiPropertyOptional({
    type: 'string',
    format: 'date-time',
    nullable: true,
    description:
      'When the sweeper may retire it; must be after txhHoldOn. Null keeps the hold until ' +
      'someone acts on it',
  })
  @NullableDate()
  txhExpiresOn?: Date | null;

  @ApiPropertyOptional({
    default: false,
    description:
      'Does this hold owe stock back? A flag only — the reserved quantities live in the payload, ' +
      'and the sweeper must release the reservation before it retires the row',
  })
  @OptionalBoolean()
  txhIsStockReserved?: boolean;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: 'Token slips printed' })
  @OptionalInteger(0)
  txhPrintCount?: number;

  @ApiPropertyOptional({
    type: 'string',
    format: 'date-time',
    nullable: true,
    description: 'Set exactly when txhPrintCount is non-zero (ck_txh_printed)',
  })
  @NullableDate()
  txhLastPrintedOn?: Date | null;

  @ApiPropertyOptional({
    type: 'string',
    format: 'date-time',
    nullable: true,
    description: 'When this row was pushed by an offline device; null means still pending',
  })
  @NullableDate()
  txhSyncDate?: Date | null;

  // txh_created_by / txh_modified_by are varchar(50), not uuid: the actor is
  // whatever resolveActor settles on — a user id, but equally a name or login
  // the caller passed. The OPERATIONAL actors (txhHeldBy, txhLockedBy,
  // txhResumedBy, txhConvertedBy) are uuid, because screens filter on them.
  @ApiPropertyOptional({
    maxLength: 50,
    nullable: true,
    description: 'Actor id or name; defaults to the caller',
  })
  @NullableStringStrict(50)
  txhCreatedBy?: string | null;

  @ApiPropertyOptional({
    maxLength: 50,
    nullable: true,
    description: 'Actor id or name; defaults to the caller',
  })
  @NullableStringStrict(50)
  txhModifiedBy?: string | null;
}
