import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SalesErrorFieldDto, SalesErrorResponseDto } from 'src/common/utils/module-response.dto';

export { SalesErrorFieldDto as PromotionSchemeErrorFieldDto };
export { SalesErrorResponseDto as PromotionSchemeErrorResponseDto };

export class PromotionSchemeBranchPayloadDto {
  @ApiProperty() prb_id!: string;
  @ApiProperty() prb_prm_id!: string;
  @ApiProperty({ example: 1 }) prb_slno!: number;
  @ApiProperty() prb_branch_id!: string;
  @ApiProperty({ example: false }) prb_is_exclude!: boolean;
  @ApiPropertyOptional({ nullable: true }) prb_notes!: string | null;
  @ApiProperty({ example: true }) prb_is_active!: boolean;
  @ApiProperty({ example: false }) prb_is_deleted!: boolean;
  @ApiPropertyOptional({ nullable: true }) prb_sync_date!: string | null;
  @ApiProperty() prb_created_on!: string;
  @ApiPropertyOptional({ nullable: true }) prb_created_by!: string | null;
  @ApiPropertyOptional({ nullable: true }) prb_modified_on!: string | null;
  @ApiPropertyOptional({ nullable: true }) prb_modified_by!: string | null;
}

export class PromotionSchemePartyPayloadDto {
  @ApiProperty() prp_id!: string;
  @ApiProperty() prp_prm_id!: string;
  @ApiProperty({ example: 1 }) prp_slno!: number;
  @ApiProperty({ example: 'CUSTOMER_GROUP' }) prp_kind!: string;
  @ApiProperty() prp_scope_id!: string;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  prp_cust_id!: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  prp_cust_group_id!: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  prp_area_id!: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  prp_city_id!: string | null;
  @ApiProperty({ example: false }) prp_is_exclude!: boolean;
  @ApiProperty({ example: 1 }) prp_match_priority!: number;
  @ApiPropertyOptional({ nullable: true }) prp_notes!: string | null;
  @ApiProperty({ example: true }) prp_is_active!: boolean;
  @ApiProperty({ example: false }) prp_is_deleted!: boolean;
  @ApiPropertyOptional({ nullable: true }) prp_sync_date!: string | null;
  @ApiProperty() prp_created_on!: string;
  @ApiPropertyOptional({ nullable: true }) prp_created_by!: string | null;
  @ApiPropertyOptional({ nullable: true }) prp_modified_on!: string | null;
  @ApiPropertyOptional({ nullable: true }) prp_modified_by!: string | null;
}

export class PromotionSchemeItemPayloadDto {
  @ApiProperty() pri_id!: string;
  @ApiProperty() pri_prm_id!: string;
  @ApiProperty({ example: 1 }) pri_slno!: number;
  @ApiProperty({ example: 'ITEM_BRAND' }) pri_kind!: string;
  @ApiProperty() pri_scope_id!: string;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  pri_item_id!: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  pri_group_id!: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  pri_category_id!: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  pri_brand_id!: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Generated by the database' })
  pri_section_id!: string | null;
  @ApiPropertyOptional({ nullable: true }) pri_unit_id!: string | null;
  @ApiProperty({ example: false }) pri_is_exclude!: boolean;
  @ApiProperty({ example: 0 }) pri_disc_perc!: number;
  @ApiProperty({ example: 0 }) pri_disc_qty!: number;
  @ApiProperty({ example: 0 }) pri_disc_amt!: number;
  @ApiProperty({ example: 0 }) pri_min_qty!: number;
  @ApiProperty({ example: 1 }) pri_factor!: number;
  @ApiProperty({ example: 0 }) pri_max_benefit!: number;
  @ApiProperty({ example: 3 }) pri_match_priority!: number;
  @ApiPropertyOptional({ nullable: true }) pri_notes!: string | null;
  @ApiProperty({ example: true }) pri_is_active!: boolean;
  @ApiProperty({ example: false }) pri_is_deleted!: boolean;
  @ApiPropertyOptional({ nullable: true }) pri_sync_date!: string | null;
  @ApiProperty() pri_created_on!: string;
  @ApiPropertyOptional({ nullable: true }) pri_created_by!: string | null;
  @ApiPropertyOptional({ nullable: true }) pri_modified_on!: string | null;
  @ApiPropertyOptional({ nullable: true }) pri_modified_by!: string | null;
}

export class PromotionSchemeSlabPayloadDto {
  @ApiProperty() prs_id!: string;
  @ApiProperty() prs_prm_id!: string;
  @ApiProperty({ example: 1 }) prs_slno!: number;
  @ApiProperty({ example: 'DISC_PERC' }) prs_benefit!: string;
  @ApiProperty({ example: 1000 }) prs_exceeds!: number;
  @ApiPropertyOptional({ nullable: true, example: 4999 }) prs_upto!: number | null;
  @ApiProperty({ example: 1 }) prs_each!: number;
  @ApiProperty({ example: false }) prs_is_repeat!: boolean;
  @ApiProperty({ example: 0 }) prs_max_repeats!: number;
  @ApiPropertyOptional({ nullable: true }) prs_free_item_id!: string | null;
  @ApiPropertyOptional({ nullable: true }) prs_free_unit_id!: string | null;
  @ApiProperty({ example: 0 }) prs_free_qty!: number;
  @ApiProperty({ example: true }) prs_free_stock_check!: boolean;
  @ApiProperty({ example: 5 }) prs_disc_perc!: number;
  @ApiProperty({ example: 0 }) prs_disc_qty!: number;
  @ApiProperty({ example: 0 }) prs_disc_amt!: number;
  @ApiPropertyOptional({ nullable: true }) prs_fixed_price!: number | null;
  @ApiProperty({ example: 0 }) prs_max_benefit_amt!: number;
  @ApiPropertyOptional({ nullable: true }) prs_notes!: string | null;
  @ApiProperty({ example: true }) prs_is_active!: boolean;
  @ApiProperty({ example: false }) prs_is_deleted!: boolean;
  @ApiPropertyOptional({ nullable: true }) prs_sync_date!: string | null;
  @ApiProperty() prs_created_on!: string;
  @ApiPropertyOptional({ nullable: true }) prs_created_by!: string | null;
  @ApiPropertyOptional({ nullable: true }) prs_modified_on!: string | null;
  @ApiPropertyOptional({ nullable: true }) prs_modified_by!: string | null;
}

export class PromotionSchemePayloadDto {
  @ApiProperty() prm_id!: string;
  @ApiProperty() prm_comp_id!: string;
  @ApiPropertyOptional({ nullable: true }) prm_branch_id!: string | null;
  @ApiPropertyOptional({ nullable: true }) prm_tenant_id!: string | null;
  @ApiProperty({ example: 'DIWALI25' }) prm_code!: string;
  @ApiProperty({ example: 'Diwali 2025' }) prm_name!: string;
  @ApiProperty({ example: 'DRAFT' }) prm_status!: string;
  @ApiProperty({ example: 'ITEM_QTY' }) prm_apply_on!: string;
  @ApiProperty({ example: 'DISC_PERC' }) prm_benefit!: string;
  @ApiProperty({ example: 1 }) prm_priority!: number;
  @ApiProperty({ example: 'EXCLUSIVE' }) prm_stack_mode!: string;
  @ApiProperty({ example: true }) prm_auto_apply!: boolean;
  @ApiProperty({ example: false }) prm_allow_with_manual_disc!: boolean;
  @ApiProperty({ example: 'NET_AMOUNT' }) prm_calc_on_amount_type!: string;
  @ApiProperty({ example: false }) prm_include_tax!: boolean;
  @ApiProperty({ example: 'ALL' }) prm_bill_type!: string;
  @ApiProperty({ example: 0 }) prm_min_bill_amount!: number;
  @ApiProperty({ example: 0 }) prm_min_qty!: number;
  @ApiProperty({ example: 'ALL' }) prm_branch_scope!: string;
  @ApiProperty({ example: 'ALL' }) prm_cust_scope!: string;
  @ApiProperty({ example: 'ALL' }) prm_item_scope!: string;
  @ApiPropertyOptional({ nullable: true }) prm_price_level_id!: number | null;
  @ApiProperty({ example: 0 }) prm_max_benefit_per_bill!: number;
  @ApiProperty({ example: 0 }) prm_max_uses_total!: number;
  @ApiProperty({ example: 0 }) prm_max_uses_per_cust!: number;
  @ApiProperty({ example: 0 }) prm_budget_amount!: number;
  @ApiPropertyOptional({ nullable: true }) prm_coupon_batch_id!: string | null;
  @ApiProperty({ example: '2025-10-01' }) prm_start_date!: string;
  @ApiProperty({ example: '2025-10-31' }) prm_end_date!: string;
  @ApiPropertyOptional({ nullable: true, example: '22:00:00' })
  prm_valid_from_time!: string | null;
  @ApiPropertyOptional({ nullable: true, example: '04:00:00' }) prm_valid_to_time!: string | null;
  @ApiPropertyOptional({ nullable: true, example: 'MON,TUE' }) prm_valid_weekdays!: string | null;
  @ApiPropertyOptional({ nullable: true }) prm_remarks!: string | null;
  @ApiProperty({ example: true }) prm_is_active!: boolean;
  @ApiProperty({ example: false }) prm_is_deleted!: boolean;
  @ApiPropertyOptional({ nullable: true }) prm_sync_date!: string | null;
  @ApiProperty() prm_created_on!: string;
  @ApiPropertyOptional({ nullable: true }) prm_created_by!: string | null;
  @ApiPropertyOptional({ nullable: true }) prm_modified_on!: string | null;
  @ApiPropertyOptional({ nullable: true }) prm_modified_by!: string | null;
  @ApiPropertyOptional({ nullable: true }) prm_approved_on!: string | null;
  @ApiPropertyOptional({ nullable: true }) prm_approved_by!: string | null;

  @ApiProperty({ type: [PromotionSchemeBranchPayloadDto] })
  branches!: PromotionSchemeBranchPayloadDto[];

  @ApiProperty({ type: [PromotionSchemePartyPayloadDto] })
  parties!: PromotionSchemePartyPayloadDto[];

  @ApiProperty({ type: [PromotionSchemeItemPayloadDto] })
  items!: PromotionSchemeItemPayloadDto[];

  @ApiProperty({ type: [PromotionSchemeSlabPayloadDto] })
  slabs!: PromotionSchemeSlabPayloadDto[];
}

export class PromotionSchemeDeleteResultDto {
  @ApiProperty({ example: true }) deleted!: true;
  @ApiProperty() prm_id!: string;
}

export class PromotionSchemeChildDeleteResultDto extends PromotionSchemeDeleteResultDto {
  @ApiProperty({ description: 'The prb_id / prp_id / pri_id / prs_id that was soft deleted' })
  row_id!: string;
}

export class PromotionSchemeSuccessSingleDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme fetched successfully' }) message!: string;
  @ApiProperty({ type: PromotionSchemePayloadDto }) data!: PromotionSchemePayloadDto;
}

export class PromotionSchemeSuccessDeleteDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme deleted successfully' }) message!: string;
  @ApiProperty({ type: PromotionSchemeDeleteResultDto }) data!: PromotionSchemeDeleteResultDto;
}

export class PromotionSchemeChildSuccessDeleteDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Row deleted successfully' }) message!: string;
  @ApiProperty({ type: PromotionSchemeChildDeleteResultDto })
  data!: PromotionSchemeChildDeleteResultDto;
}

export class PromotionSchemeBranchSuccessListDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme branches saved successfully' }) message!: string;
  @ApiProperty({ type: [PromotionSchemeBranchPayloadDto] })
  data!: PromotionSchemeBranchPayloadDto[];
}

export class PromotionSchemePartySuccessListDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme parties saved successfully' }) message!: string;
  @ApiProperty({ type: [PromotionSchemePartyPayloadDto] })
  data!: PromotionSchemePartyPayloadDto[];
}

export class PromotionSchemeItemSuccessListDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme items saved successfully' }) message!: string;
  @ApiProperty({ type: [PromotionSchemeItemPayloadDto] })
  data!: PromotionSchemeItemPayloadDto[];
}

export class PromotionSchemeSlabSuccessListDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme slabs saved successfully' }) message!: string;
  @ApiProperty({ type: [PromotionSchemeSlabPayloadDto] })
  data!: PromotionSchemeSlabPayloadDto[];
}
