import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SalesErrorFieldDto, SalesErrorResponseDto } from 'src/common/utils/module-response.dto';

export { SalesErrorFieldDto as PromotionSchemeErrorFieldDto };
export { SalesErrorResponseDto as PromotionSchemeErrorResponseDto };

export class PromotionSchemeBranchPayloadDto {
  @ApiProperty() prb_id!: string;
  @ApiProperty() prb_prm_id!: string;
  @ApiProperty({ example: 1 }) prb_slno!: number;
  @ApiProperty() prb_branch_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'branch_master.br_name' })
  prb_branch_name!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'br_code, else br_short' })
  prb_branch_code!: string | null;
  @ApiProperty({ example: false }) prb_is_exclude!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) prb_notes!: string | null;
  @ApiProperty({ example: true }) prb_is_active!: boolean;
  @ApiProperty({ example: false }) prb_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) prb_sync_date!: string | null;
  @ApiProperty() prb_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) prb_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prb_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prb_modified_by!: string | null;
}

export class PromotionSchemePartyPayloadDto {
  @ApiProperty() prp_id!: string;
  @ApiProperty() prp_prm_id!: string;
  @ApiProperty({ example: 1 }) prp_slno!: number;
  @ApiProperty({ example: 'CUSTOMER_GROUP' }) prp_kind!: string;
  @ApiProperty() prp_scope_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  prp_cust_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  prp_cust_group_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  prp_area_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  prp_city_id!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'namakkal',
    description:
      'Display only. The name behind prp_scope_id — cus_name / cgr_name / arm_name / ' +
      'ctm_name, whichever prp_kind names.',
  })
  prp_scope_name!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'gn',
    description: 'Display only. cus_code / cgr_short / arm_short / ctm_short.',
  })
  prp_scope_code!: string | null;
  @ApiProperty({ example: false }) prp_is_exclude!: boolean;
  @ApiProperty({ example: 1 }) prp_match_priority!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) prp_notes!: string | null;
  @ApiProperty({ example: true }) prp_is_active!: boolean;
  @ApiProperty({ example: false }) prp_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) prp_sync_date!: string | null;
  @ApiProperty() prp_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) prp_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prp_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prp_modified_by!: string | null;
}

export class PromotionSchemeItemPayloadDto {
  @ApiProperty() pri_id!: string;
  @ApiProperty() pri_prm_id!: string;
  @ApiProperty({ example: 1 }) pri_slno!: number;
  @ApiProperty({ example: 'ITEM_BRAND' }) pri_kind!: string;
  @ApiProperty() pri_scope_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  pri_item_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  pri_group_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  pri_category_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  pri_brand_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  pri_section_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) pri_unit_id!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'Masala Items',
    description:
      'Display only. item_name_en / itg_name / category_name / brand_name / sec_name, ' +
      'whichever pri_kind names.',
  })
  pri_scope_name!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'Kilogram',
    description: 'Display only. item_unit_master.unit_name behind pri_unit_id.',
  })
  pri_unit_name!: string | null;
  @ApiProperty({ example: false }) pri_is_exclude!: boolean;
  @ApiProperty({ example: 0 }) pri_disc_perc!: number;
  @ApiProperty({ example: 0 }) pri_disc_qty!: number;
  @ApiProperty({ example: 0 }) pri_disc_amt!: number;
  @ApiProperty({ example: 0 }) pri_min_qty!: number;
  @ApiProperty({ example: 1 }) pri_factor!: number;
  @ApiProperty({ example: 0 }) pri_max_benefit!: number;
  @ApiProperty({ example: 3 }) pri_match_priority!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) pri_notes!: string | null;
  @ApiProperty({ example: true }) pri_is_active!: boolean;
  @ApiProperty({ example: false }) pri_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) pri_sync_date!: string | null;
  @ApiProperty() pri_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) pri_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) pri_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) pri_modified_by!: string | null;
}

export class PromotionSchemeSlabPayloadDto {
  @ApiProperty() prs_id!: string;
  @ApiProperty() prs_prm_id!: string;
  @ApiProperty({ example: 1 }) prs_slno!: number;
  @ApiProperty({ example: 'DISC_PERC' }) prs_benefit!: string;
  @ApiProperty({ example: 1000 }) prs_exceeds!: number;
  @ApiPropertyOptional({ type: Number, nullable: true, example: 4999 }) prs_upto!: number | null;
  @ApiProperty({ example: 1 }) prs_each!: number;
  @ApiProperty({ example: false }) prs_is_repeat!: boolean;
  @ApiProperty({ example: 0 }) prs_max_repeats!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) prs_free_item_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prs_free_unit_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Display only.' })
  prs_free_item_name!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Display only.' })
  prs_free_unit_name!: string | null;
  @ApiProperty({ example: 0 }) prs_free_qty!: number;
  @ApiProperty({ example: true }) prs_free_stock_check!: boolean;
  @ApiProperty({ example: 5 }) prs_disc_perc!: number;
  @ApiProperty({ example: 0 }) prs_disc_qty!: number;
  @ApiProperty({ example: 0 }) prs_disc_amt!: number;
  @ApiPropertyOptional({ type: Number, nullable: true }) prs_fixed_price!: number | null;
  @ApiProperty({ example: 0 }) prs_max_benefit_amt!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) prs_notes!: string | null;
  @ApiProperty({ example: true }) prs_is_active!: boolean;
  @ApiProperty({ example: false }) prs_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) prs_sync_date!: string | null;
  @ApiProperty() prs_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) prs_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prs_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prs_modified_by!: string | null;
}

/**
 * The campaign header on its own — every scalar column of promotion_scheme and
 * not one child row. This is what GET /list answers with, one object per
 * scheme; PromotionSchemePayloadDto adds the four grids on top of it.
 */
export class PromotionSchemeSummaryPayloadDto {
  @ApiProperty() prm_id!: string;
  @ApiProperty() prm_comp_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_branch_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'company.comp_name' })
  prm_comp_name!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    description: 'branch_master.br_name — null when the scheme is company-wide',
  })
  prm_branch_name!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_tenant_id!: string | null;
  @ApiProperty({ example: 'DIWALI25' }) prm_code!: string;
  @ApiProperty({ example: 'Diwali 2025' }) prm_name!: string;
  @ApiProperty({ example: 'DRAFT' }) prm_status!: string;
  @ApiProperty({ example: 'ITEM_QTY' }) prm_apply_on!: string;
  @ApiProperty({ example: 'DISC_PERC' }) prm_benefit!: string;
  @ApiProperty({ example: 1 }) prm_priority!: number;
  @ApiProperty({ example: 'EXCLUSIVE' }) prm_stack_mode!: string;
  @ApiProperty({ example: true }) prm_auto_apply!: boolean;
  @ApiProperty({ example: false }) prm_allow_with_manual_disc!: boolean;
  @ApiProperty({ example: 'NET_AMOUNT' }) prm_calc_on_amount_type!: string;
  @ApiProperty({ example: false }) prm_include_tax!: boolean;
  @ApiProperty({ example: 'ALL' }) prm_bill_type!: string;
  @ApiProperty({ example: 0 }) prm_min_bill_amount!: number;
  @ApiProperty({ example: 0 }) prm_min_qty!: number;
  @ApiProperty({ example: 'ALL' }) prm_branch_scope!: string;
  @ApiProperty({ example: 'ALL' }) prm_cust_scope!: string;
  @ApiProperty({ example: 'ALL' }) prm_item_scope!: string;
  @ApiPropertyOptional({ type: Number, nullable: true }) prm_price_level_id!: number | null;
  @ApiProperty({ example: 0 }) prm_max_benefit_per_bill!: number;
  @ApiProperty({ example: 0 }) prm_max_uses_total!: number;
  @ApiProperty({ example: 0 }) prm_max_uses_per_cust!: number;
  @ApiProperty({ example: 0 }) prm_budget_amount!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_coupon_batch_id!: string | null;
  @ApiProperty({ example: '2025-10-01' }) prm_start_date!: string;
  @ApiProperty({ example: '2025-10-31' }) prm_end_date!: string;
  @ApiPropertyOptional({ type: String, nullable: true, example: '22:00:00' })
  prm_valid_from_time!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, example: '04:00:00' }) prm_valid_to_time!:
    | string
    | null;
  @ApiPropertyOptional({ type: String, nullable: true, example: 'MON,TUE' }) prm_valid_weekdays!:
    | string
    | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_remarks!: string | null;
  @ApiProperty({ example: true }) prm_is_active!: boolean;
  @ApiProperty({ example: false }) prm_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_sync_date!: string | null;
  @ApiProperty() prm_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_modified_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_approved_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) prm_approved_by!: string | null;
}

/** The header plus its four grids — what POST /create and GET /get answer with. */
export class PromotionSchemePayloadDto extends PromotionSchemeSummaryPayloadDto {
  @ApiProperty({ type: [PromotionSchemeBranchPayloadDto] })
  branches!: PromotionSchemeBranchPayloadDto[];

  @ApiProperty({ type: [PromotionSchemePartyPayloadDto] })
  parties!: PromotionSchemePartyPayloadDto[];

  @ApiProperty({ type: [PromotionSchemeItemPayloadDto] })
  items!: PromotionSchemeItemPayloadDto[];

  @ApiProperty({ type: [PromotionSchemeSlabPayloadDto] })
  slabs!: PromotionSchemeSlabPayloadDto[];
}

export class PromotionSchemeDeleteResultDto {
  @ApiProperty({ example: true }) deleted!: true;
  @ApiProperty() prm_id!: string;
}

export class PromotionSchemeSuccessSingleDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme fetched successfully' }) message!: string;
  @ApiProperty({ type: PromotionSchemePayloadDto }) data!: PromotionSchemePayloadDto;
}

export class PromotionSchemeSuccessListDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion schemes fetched successfully' }) message!: string;
  @ApiProperty({ type: [PromotionSchemePayloadDto] }) data!: PromotionSchemePayloadDto[];
}

export class PromotionSchemeSuccessDeleteDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme deleted successfully' }) message!: string;
  @ApiProperty({ type: PromotionSchemeDeleteResultDto }) data!: PromotionSchemeDeleteResultDto;
}

export class PromotionSchemeEligibilityPayloadDto {
  @ApiProperty() prm_id!: string;
  @ApiProperty() cus_id!: string;
  @ApiProperty({ example: true }) qualifies!: boolean;
  @ApiProperty({
    enum: ['ALL', 'RULE', 'NO_RULE'],
    description:
      'ALL — the scheme covers everyone, no party row was consulted. RULE — a party row decided ' +
      'it. NO_RULE — the scheme is scoped to a LIST and nothing on it touches this customer.',
  })
  decided_by!: 'ALL' | 'RULE' | 'NO_RULE';
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'AREA',
    description: 'prp_kind of the row that decided it',
  })
  matched_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) matched_row_id!: string | null;
  @ApiPropertyOptional({ type: Number, nullable: true }) match_priority!: number | null;
  @ApiPropertyOptional({ type: Boolean, nullable: true }) is_exclude!: boolean | null;
  @ApiProperty({ example: 'NO — carved out by the AREA rule' }) reason!: string;
}

export class PromotionSchemeEligibilitySuccessDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Promotion scheme eligibility evaluated successfully' })
  message!: string;
  @ApiProperty({ type: PromotionSchemeEligibilityPayloadDto })
  data!: PromotionSchemeEligibilityPayloadDto;
}
