import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { ArrayMaxSize, IsArray, ValidateIf, ValidateNested } from 'class-validator';
import {
  NullableString,
  NullableUuid,
  OptionalInteger,
  OptionalNumber,
  OptionalQueryBoolean,
  OptionalTrimmedString,
  OptionalUuid,
  RequiredUuid,
  TrimmedString,
} from './promotion-scheme-dto.helpers';
import { PRI_KINDS } from '../utils/promotion-scheme.utils';

export class PromotionSchemeItemRowDto {
  @ApiPropertyOptional({ description: 'Present = update that row, absent = insert a new one' })
  @OptionalUuid()
  pri_id?: string;

  @ApiPropertyOptional({ minimum: 1, default: 1 })
  @OptionalInteger(1)
  pri_slno?: number;

  @ApiProperty({ enum: PRI_KINDS, example: 'ITEM_BRAND' })
  @ValidateIf((o: PromotionSchemeItemRowDto) => o.pri_id === undefined || o.pri_kind !== undefined)
  @TrimmedString(20)
  pri_kind?: string;

  @ApiProperty({
    example: '01963d86-caf0-7b26-89f0-58ac380a2d5e',
    description: 'The item, group, category, brand or section — whichever pri_kind names',
  })
  @ValidateIf(
    (o: PromotionSchemeItemRowDto) => o.pri_id === undefined || o.pri_scope_id !== undefined,
  )
  @RequiredUuid()
  pri_scope_id?: string;

  @ApiPropertyOptional({
    nullable: true,
    description:
      'inventory.item_unit_conversion(iuc_id). REQUIRED when pri_kind is ITEM — ten pieces, ' +
      'ten boxes and ten cases are three different offers — and must be null for every other kind.',
  })
  @NullableUuid()
  pri_unit_id?: string | null;

  @ApiPropertyOptional({
    default: false,
    description: 'Kills the line regardless of any broader rule. Forbids any rate on the same row.',
  })
  @OptionalQueryBoolean()
  pri_is_exclude?: boolean;

  @ApiPropertyOptional({ minimum: 0, maximum: 100, default: 0, description: '% off the line' })
  @OptionalNumber(0)
  pri_disc_perc?: number;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: 'Rupees off PER UNIT' })
  @OptionalNumber(0)
  pri_disc_qty?: number;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: 'Flat rupees off the line' })
  @OptionalNumber(0)
  pri_disc_amt?: number;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: 'Quantity floor for THIS item' })
  @OptionalNumber(0)
  pri_min_qty?: number;

  @ApiPropertyOptional({
    default: 1,
    description: 'Scales whatever the band computed for the line. 2.0 = double it.',
  })
  @OptionalNumber(0)
  pri_factor?: number;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: '0 = uncapped, per line' })
  @OptionalNumber(0)
  pri_max_benefit?: number;

  @ApiPropertyOptional({
    minimum: 0,
    maximum: 9,
    description:
      'Most specific wins. Defaults by kind when omitted: ITEM 4, ITEM_BRAND 3, ' +
      'ITEM_CATEGORY 2, ITEM_SECTION 1, ITEM_GROUP 0.',
  })
  @OptionalInteger(0, 9)
  pri_match_priority?: number;

  @ApiPropertyOptional({ nullable: true })
  @NullableString(65535)
  pri_notes?: string | null;

  @ApiPropertyOptional({ default: true })
  @OptionalQueryBoolean()
  pri_is_active?: boolean;

  @ApiPropertyOptional({ maxLength: 50 })
  @OptionalTrimmedString(50)
  pri_created_by?: string;

  @ApiPropertyOptional({ maxLength: 50 })
  @OptionalTrimmedString(50)
  pri_modified_by?: string;
}

/**
 * Read only when the header says prm_item_scope = 'LIST'. Upsert semantics —
 * see SavePromotionSchemeBranchesDto.
 *
 * This array is what makes "20% off own-brand, but nothing on tobacco" one
 * scheme: an ITEM_BRAND include row and an ITEM_CATEGORY exclude row, together.
 *
 * The five FK carriers (pri_item_id, pri_group_id, pri_category_id,
 * pri_brand_id, pri_section_id) are generated by Postgres from pri_kind +
 * pri_scope_id and are not accepted here.
 *
 * A rate may be stated on the row itself (the perc/qty/amt trio, at most one
 * non-zero) instead of on a slab band — that is all "Offer Per Item" ever was.
 * Leave all three at 0 and the row only says "in scope".
 */
export class SavePromotionSchemeItemsDto {
  @ApiProperty({ example: '01963d86-caf0-7b26-89f0-58ac380a2d5e' })
  @RequiredUuid()
  prm_id!: string;

  @ApiProperty({ type: [PromotionSchemeItemRowDto] })
  @IsArray()
  @ArrayMaxSize(1000)
  @ValidateNested({ each: true })
  @Type(() => PromotionSchemeItemRowDto)
  items!: PromotionSchemeItemRowDto[];
}
