type AuditSqlField = readonly [source: string, label: string];

const buildAuditSql = (from: string, fields: readonly AuditSqlField[]): string =>
  [
    'SELECT',
    ...fields.map(
      ([source, label], index) =>
        `    ${source} AS "${label}"${index < fields.length - 1 ? ',' : ''}`,
    ),
    `FROM ${from};`,
  ].join('\n');

export const AUDIT_SCREEN_SQL_BY_NAME = new Map<string, string>([
  [
    'Units Master',
    buildAuditSql('inventory.item_unit_master', [
      ['unit_name', 'Unit Name'],
      ['unit_alias', 'Alias'],
      ['unit_code', 'Code'],
      ['unit_description', 'Description'],
      ['unit_decimal_count', 'Decimal Count'],
      ['unit_weight', 'Weight'],
      ['unit_loading', 'Loading'],
      ['unit_unloading', 'Unloading'],
      ['unit_attach_charge', 'Attach Charge'],
      ['unit_is_pack_unit', 'Is Pack Unit'],
      ['unit_base_unit_id', 'Base Unit ID'],
      ['unit_conversion', 'Conversion Factor'],
      ['unit_is_active', 'Is Active'],
      ['unit_is_deleted', 'Is Deleted'],
      ['unit_sync_date', 'Sync Date'],
      ['unit_created_on', 'Created On'],
      ['unit_created_by', 'Created By'],
      ['unit_modified_on', 'Modified On'],
      ['unit_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Item Group Master',
    buildAuditSql('inventory.item_group_master', [
      ['itg_name', 'Item Group Name'],
      ['itg_alias', 'Item Group Alias'],
      ['itg_short', 'Short Code'],
      ['itg_description', 'Description'],
      ['itg_parent_id', 'Parent Group ID'],
      ['itg_sort', 'Sort Order'],
      ['itg_level', 'Hierarchy Level'],
      ['itg_path_ids_cache', 'Path IDs Cache'],
      ['itg_tax_claim', 'Tax Claim'],
      ['itg_default_tax_id', 'Default Tax ID'],
      ['itg_default_hsn', 'Default HSN Code'],
      ['itg_default_uom_id', 'Default UOM ID'],
      ['itg_photo_url', 'Photo URL'],
      ['itg_is_active', 'Is Active'],
      ['itg_is_deleted', 'Is Deleted'],
      ['itg_sync_date', 'Sync Date'],
      ['itg_created_on', 'Created On'],
      ['itg_created_by', 'Created By'],
      ['itg_modified_on', 'Modified On'],
      ['itg_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Item Brand Master',
    buildAuditSql('inventory.item_brand_master', [
      ['brand_name', 'Brand Name'],
      ['brand_alias', 'Alias'],
      ['brand_short', 'Short Code'],
      ['brand_description', 'Description'],
      ['brand_parent_id', 'Parent Brand ID'],
      ['brand_sort', 'Sort Order'],
      ['brand_level', 'Hierarchy Level'],
      ['brand_path_ids', 'Path IDs'],
      ['brand_photo_url', 'Photo URL'],
      ['brand_is_active', 'Is Active'],
      ['brand_is_deleted', 'Is Deleted'],
      ['brand_sync_date', 'Sync Date'],
      ['brand_created_on', 'Created On'],
      ['brand_created_by', 'Created By'],
      ['brand_modified_on', 'Modified On'],
      ['brand_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Category Master',
    buildAuditSql('inventory.item_category_master', [
      ['category_name', 'Category Name'],
      ['category_alias', 'Alias'],
      ['category_short', 'Short Code'],
      ['category_description', 'Description'],
      ['category_parent_id', 'Parent Category ID'],
      ['category_sort', 'Sort Order'],
      ['category_level', 'Hierarchy Level'],
      ['category_path_ids_cache', 'Path IDs Cache'],
      ['category_photo_url', 'Photo URL'],
      ['category_is_active', 'Is Active'],
      ['category_is_deleted', 'Is Deleted'],
      ['category_sync_date', 'Sync Date'],
      ['category_created_on', 'Created On'],
      ['category_created_by', 'Created By'],
      ['category_modified_on', 'Modified On'],
      ['category_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Item Section Master',
    buildAuditSql('inventory.item_section_master', [
      ['sec_name', 'Section Name'],
      ['sec_alias', 'Alias'],
      ['sec_short', 'Short Code'],
      ['sec_description', 'Description'],
      ['sec_parent_id', 'Parent Section ID'],
      ['sec_sort', 'Sort Order'],
      ['sec_level', 'Hierarchy Level'],
      ['sec_path_ids', 'Path IDs'],
      ['sec_position', 'Position'],
      ['sec_color_code', 'Color Code'],
      ['sec_icon', 'Icon'],
      ['sec_photo_url', 'Photo URL'],
      ['sec_is_active', 'Is Active'],
      ['sec_is_deleted', 'Is Deleted'],
      ['sec_sync_date', 'Sync Date'],
      ['sec_created_on', 'Created On'],
      ['sec_created_by', 'Created By'],
      ['sec_modified_on', 'Modified On'],
      ['sec_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Item Tax Master',
    buildAuditSql('inventory.item_tax_master', [
      ['tax_name', 'Tax Name'],
      ['tax_code', 'Tax Code'],
      ['tax_taxability_type', 'Taxability Type'],
      ['tax_is_reverse_charge', 'Is Reverse Charge'],
      ['tax_cgst_perc', 'CGST %'],
      ['tax_sgst_perc', 'SGST %'],
      ['tax_igst_perc', 'IGST %'],
      ['tax_cgst_pur_perc', 'CGST Purchase %'],
      ['tax_sgst_pur_perc', 'SGST Purchase %'],
      ['tax_igst_pur_perc', 'IGST Purchase %'],
      ['tax_cess_type', 'Cess Type'],
      ['tax_cess_perc', 'Cess %'],
      ['tax_cess_unit', 'Cess Unit'],
      ['tax_cess_pur_perc', 'Cess Purchase %'],
      ['tax_cess_pur_unit', 'Cess Purchase Unit'],
      ['tax_gst_rate_total', 'GST Rate Total'],
      ['tax_is_active', 'Is Active'],
      ['tax_is_deleted', 'Is Deleted'],
      ['tax_sync_date', 'Sync Date'],
      ['tax_created_on', 'Created On'],
      ['tax_created_by', 'Created By'],
      ['tax_modified_on', 'Modified On'],
      ['tax_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Item Tax History',
    buildAuditSql('inventory.item_tax_history', [
      ['ith_item_id', 'Item ID'],
      ['ith_tax_id', 'Tax ID'],
      ['ith_effective_from', 'Effective From'],
      ['ith_effective_to', 'Effective To'],
      ['ith_reason', 'Reason'],
      ['ith_created_on', 'Created On'],
      ['ith_created_by', 'Created By'],
    ]),
  ],
  [
    // Composite Item Master screen: the item row plus its per-unit
    // conversion rows and the EAN / reorder / price rows that hang off
    // each unit conversion (all joined on item_unit_conversion.iuc_id).
    // ItemsMasterService only ever passes the item payload, so the child
    // columns below are null on an Item Master log row — the children's own
    // changes are logged under their own screens and pulled into the same
    // feed by RELATED_AUDIT_SCREENS_BY_SCREEN_NAME in AuditLogService.
    'Item Master',
    buildAuditSql(
      [
        'inventory.item_master im',
        'LEFT JOIN inventory.item_unit_conversion iuc',
        '    ON iuc.iuc_item_id = im.item_id',
        '   AND iuc.iuc_is_deleted = false',
        'LEFT JOIN inventory.item_ean_codes ean',
        '    ON ean.ean_uc_unit_id = iuc.iuc_id',
        '   AND ean.ean_is_deleted = false',
        'LEFT JOIN inventory.item_reorders ir',
        '    ON ir.ir_uc_unit_id = iuc.iuc_id',
        '   AND ir.ir_is_deleted = false',
        'LEFT JOIN inventory.item_price_master ipm',
        '    ON ipm.ipm_uc_unit_id = iuc.iuc_id',
        '   AND ipm.ipm_is_deleted = false',
      ].join('\n'),
      [
        // Item master
        ['im.item_code', 'Item Code'],
        ['im.item_sku', 'Item SKU'],
        ['im.item_name_en', 'Item Name (English)'],
        ['im.item_name_ta', 'Item Name (Tamil)'],
        ['im.item_alias', 'Item Alias'],
        ['im.item_stock_type', 'Stock Type'],
        ['im.item_default_barcode', 'Default Barcode'],
        ['im.item_group_id', 'Item Group ID'],
        ['im.item_category_id', 'Category ID'],
        ['im.item_brand_id', 'Brand ID'],
        ['im.item_section_id', 'Section ID'],
        ['im.item_base_unit_id', 'Base Unit ID'],
        ['im.item_default_tax_id', 'Default Tax ID'],
        ['im.item_hsn_code', 'HSN Code'],
        ['im.item_is_service', 'Is Service'],
        ['im.item_is_batch_based', 'Is Batch Based'],
        ['im.item_is_expiry_item', 'Is Expiry Item'],
        ['im.item_allow_sales', 'Allow Sales'],
        ['im.item_allow_purchase', 'Allow Purchase'],
        ['im.item_is_active', 'Is Active'],
        ['im.item_is_deleted', 'Is Deleted'],
        ['im.item_created_on', 'Created On'],
        ['im.item_created_by', 'Created By'],
        ['im.item_modified_on', 'Modified On'],
        ['im.item_modified_by', 'Modified By'],
        // Unit conversion
        ['iuc.iuc_unit_id', 'Unit ID'],
        ['iuc.iuc_base_unit_id', 'Unit Base Unit ID'],
        ['iuc.iuc_to_base_factor', 'Unit To-Base Factor'],
        ['iuc.iuc_unit_factor', 'Unit Factor'],
        ['iuc.iuc_unit_slno', 'Unit Sl No'],
        ['iuc.iuc_is_default_unit', 'Unit Is Default'],
        ['iuc.iuc_is_base_unit', 'Unit Is Base'],
        ['iuc.iuc_is_big_unit', 'Unit Is Big'],
        ['iuc.iuc_uom_weight', 'Unit UOM Weight'],
        // EAN / barcode
        ['ean.ean_code', 'EAN / Barcode'],
        ['ean.ean_sl_no', 'EAN Sl No'],
        ['ean.ean_is_default', 'EAN Is Default'],
        // Reorder
        ['ir.ir_godown_id', 'Reorder Godown ID'],
        ['ir.ir_min_level', 'Reorder Min Level'],
        ['ir.ir_max_level', 'Reorder Max Level'],
        ['ir.ir_reorder_level', 'Reorder Level'],
        ['ir.ir_reorder_qty', 'Reorder Qty'],
        ['ir.ir_lead_time_days', 'Reorder Lead Time Days'],
        ['ir.ir_reorder_type', 'Reorder Type'],
        // Price master
        ['ipm.ipm_cost_price', 'Cost Price'],
        ['ipm.ipm_sales_price_a', 'Sales Price A'],
        ['ipm.ipm_sales_price_b', 'Sales Price B'],
        ['ipm.ipm_sales_price_c', 'Sales Price C'],
        ['ipm.ipm_sales_price_d', 'Sales Price D'],
        ['ipm.ipm_max_price', 'Max Price'],
        ['ipm.ipm_min_price', 'Min Price'],
        ['ipm.ipm_disc_perc', 'Price Discount %'],
        ['ipm.ipm_profit_type', 'Profit Type'],
      ],
    ),
  ],
  [
    // Child of Item Master: one row per item + unit. Surfaced on the Item
    // Master audit trail through the related-screen expansion in
    // AuditLogService (record_pk carries the item id, not iuc_id).
    'Item Unit Conversion Master',
    buildAuditSql('inventory.item_unit_conversion', [
      ['iuc_item_id', 'Item ID'],
      ['iuc_unit_id', 'Unit ID'],
      ['iuc_base_unit_id', 'Base Unit ID'],
      ['iuc_to_base_factor', 'To-Base Factor'],
      ['iuc_unit_factor', 'Unit Factor'],
      ['iuc_unit_slno', 'Sl No'],
      ['iuc_is_default_unit', 'Is Default Unit'],
      ['iuc_is_base_unit', 'Is Base Unit'],
      ['iuc_is_big_unit', 'Is Big Unit'],
      ['iuc_uom_weight', 'UOM Weight'],
      ['iuc_uom_remarks', 'UOM Remarks'],
      ['iuc_is_active', 'Is Active'],
      ['iuc_is_deleted', 'Is Deleted'],
      ['iuc_sync_date', 'Sync Date'],
      ['iuc_created_on', 'Created On'],
      ['iuc_created_by', 'Created By'],
      ['iuc_updated_on', 'Modified On'],
      ['iuc_updated_by', 'Modified By'],
    ]),
  ],
  [
    // Child of Item Master. ipm_uc_unit_id is a FK to item_unit_conversion
    // (iuc_id), so its 'Unit ID' label resolves through the unitConversion
    // lookup, not the unit master.
    'Item Price Master',
    buildAuditSql('inventory.item_price_master', [
      ['ipm_company_id', 'Company ID'],
      ['ipm_branch_id', 'Branch ID'],
      ['ipm_item_id', 'Item ID'],
      ['ipm_uc_unit_id', 'Unit ID'],
      ['ipm_godown_id', 'Godown ID'],
      ['ipm_sl_no', 'Sl No'],
      ['ipm_cost_price', 'Cost Price'],
      ['ipm_cost_wot', 'Cost Without Tax'],
      ['ipm_sales_price_a', 'Sales Price A'],
      ['ipm_sales_price_b', 'Sales Price B'],
      ['ipm_sales_price_c', 'Sales Price C'],
      ['ipm_sales_price_d', 'Sales Price D'],
      ['ipm_price_a_wot', 'Price A Without Tax'],
      ['ipm_price_b_wot', 'Price B Without Tax'],
      ['ipm_price_c_wot', 'Price C Without Tax'],
      ['ipm_price_d_wot', 'Price D Without Tax'],
      ['ipm_price_a_markup_perc', 'Price A Markup %'],
      ['ipm_price_b_markup_perc', 'Price B Markup %'],
      ['ipm_price_c_markup_perc', 'Price C Markup %'],
      ['ipm_price_d_markup_perc', 'Price D Markup %'],
      ['ipm_max_price', 'Max Price'],
      ['ipm_min_price', 'Min Price'],
      ['ipm_disc_perc', 'Discount %'],
      ['ipm_disc_qty', 'Discount Qty'],
      ['ipm_addl_cess', 'Additional Cess'],
      ['ipm_profit_type', 'Profit Type'],
      ['ipm_round_off', 'Round Off'],
      ['ipm_loading_charge', 'Loading Charge'],
      ['ipm_freight_charge', 'Freight Charge'],
      ['ipm_loyalty_points', 'Loyalty Points'],
      ['ipm_uom_remarks', 'UOM Remarks'],
      ['ipm_cost_remarks', 'Cost Remarks'],
      ['ipm_is_active', 'Is Active'],
      ['ipm_is_deleted', 'Is Deleted'],
      ['ipm_sync_date', 'Sync Date'],
      ['ipm_created_on', 'Created On'],
      ['ipm_created_by', 'Created By'],
      ['ipm_updated_on', 'Modified On'],
      ['ipm_updated_by', 'Modified By'],
    ]),
  ],
  [
    'Item EAN Code Master',
    buildAuditSql('inventory.item_ean_codes', [
      ['ean_item_id', 'Item ID'],
      ['ean_unit_id', 'Unit ID'],
      ['ean_code', 'EAN / Barcode'],
      ['ean_is_default', 'Is Default'],
      ['ean_is_active', 'Is Active'],
      ['ean_is_deleted', 'Is Deleted'],
      ['ean_created_on', 'Created On'],
      ['ean_created_by', 'Created By'],
      ['ean_modified_on', 'Modified On'],
      ['ean_modified_by', 'Modified By'],
      ['ean_remarks', 'Remarks'],
    ]),
  ],
  [
    'Item Customer Rate Master',
    buildAuditSql('public.cust_item_rates', [
      ['csr_branch_id', 'Branch ID'],
      ['csr_customer_id', 'Customer ID'],
      ['csr_unit_rate_id', 'Unit Rate ID'],
      ['csr_rate_type', 'Rate Type'],
      ['csr_item_rate', 'Item Rate'],
      ['csr_disc_perc', 'Discount %'],
      ['csr_disc_qty', 'Discount Qty'],
      ['csr_price_level', 'Price Level'],
      ['csr_valid_from', 'Valid From'],
      ['csr_valid_to', 'Valid To'],
      ['csr_priority', 'Priority'],
      ['csr_is_active', 'Is Active'],
      ['csr_is_deleted', 'Is Deleted'],
      ['csr_created_on', 'Created On'],
      ['csr_created_by', 'Created By'],
      ['csr_modified_on', 'Modified On'],
      ['csr_modified_by', 'Modified By'],
      ['csr_uploaded_at', 'Uploaded At'],
      ['csr_uploaded_by', 'Uploaded By'],
      ['csr_remarks', 'Remarks'],
    ]),
  ],
  [
    'Item Reorder Master',
    buildAuditSql('inventory.item_reorders', [
      ['ir_branch_id', 'Branch ID'],
      ['ir_item_id', 'Item ID'],
      ['ir_godown_id', 'Godown ID'],
      ['ir_unit_id', 'Unit ID'],
      ['ir_min_level', 'Min Level'],
      ['ir_max_level', 'Max Level'],
      ['ir_reorder_level', 'Reorder Level'],
      ['ir_reorder_qty', 'Reorder Qty'],
      ['ir_lead_time_days', 'Lead Time Days'],
      ['ir_review_cycle_days', 'Review Cycle Days'],
      ['ir_reorder_days', 'Reorder Days'],
      ['ir_expiry_buffer_days', 'Expiry Buffer Days'],
      ['ir_reorder_type', 'Reorder Type'],
      ['ir_is_active', 'Is Active'],
      ['ir_is_deleted', 'Is Deleted'],
      ['ir_created_on', 'Created On'],
      ['ir_created_by', 'Created By'],
      ['ir_modified_on', 'Modified On'],
      ['ir_modified_by', 'Modified By'],
      ['ir_remarks', 'Remarks'],
    ]),
  ],
  [
    'Godown Location Master',
    buildAuditSql('inventory.godown_locations', [
      ['gdl_branch_id', 'Branch ID'],
      ['gdl_name', 'Location Name'],
      ['gdl_short', 'Short Code'],
      ['gdl_code', 'Code'],
      ['gdl_type', 'Type'],
      ['gdl_parent_id', 'Parent Location ID'],
      ['gdl_sort', 'Sort Order'],
      ['gdl_level', 'Hierarchy Level'],
      ['gdl_path_ids_cache', 'Path IDs Cache'],
      ['gdl_del_sheet', 'Delivery Sheet'],
      ['gdl_split_stock', 'Split Stock'],
      ['gdl_negative_stock', 'Allow Negative Stock'],
      ['gdl_volume', 'Volume'],
      ['gdl_remarks', 'Remarks'],
      ['gdl_is_active', 'Is Active'],
      ['gdl_is_deleted', 'Is Deleted'],
      ['gdl_created_on', 'Created On'],
      ['gdl_created_by', 'Created By'],
      ['gdl_modified_on', 'Modified On'],
      ['gdl_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Account Group Master',
    buildAuditSql('accounts.acc_group_master', [
      ['acc_group_name', 'Group Name'],
      ['acc_group_alias', 'Alias'],
      ['acc_group_short', 'Short Code'],
      ['acc_group_description', 'Description'],
      ['acc_group_tally_name', 'Tally Name'],
      ['acc_group_primary_name', 'Primary Name'],
      ['acc_group_nature', 'Nature'],
      ['acc_group_tally_guid', 'Tally GUID'],
      ['acc_group_tally_master_id', 'Tally Master ID'],
      ['acc_group_tally_alter_id', 'Tally Alter ID'],
      ['acc_group_type', 'Type'],
      ['acc_group_parent_id', 'Parent Group ID'],
      ['acc_group_sort', 'Sort Order'],
      ['acc_group_child_ids', 'Child IDs'],
      ['acc_group_company_id', 'Company ID'],
      ['acc_group_is_default', 'Is Default'],
      ['acc_group_is_reserved', 'Is Reserved'],
      ['acc_group_behave_as_subledger', 'Behave As Subledger'],
      ['acc_group_net_debit_credit', 'Net Debit/Credit'],
      ['acc_group_used_for_calculation', 'Used For Calculation'],
      ['acc_group_affects_gross_profit', 'Affects Gross Profit'],
      ['acc_group_is_active', 'Is Active'],
      ['acc_group_is_deleted', 'Is Deleted'],
      ['acc_group_sync_date', 'Sync Date'],
      ['acc_group_created_on', 'Created On'],
      ['acc_group_created_by', 'Created By'],
      ['acc_group_modified_on', 'Modified On'],
      ['acc_group_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Company Group Master',
    buildAuditSql('public.company_group_master', [
      ['cog_group_name', 'Company Group Name'],
      ['cog_company_ids', 'Company IDs'],
      ['cog_is_active', 'Is Active'],
      ['cog_is_deleted', 'Is Deleted'],
      ['cog_sync_date', 'Sync Date'],
      ['cog_created_on', 'Created On'],
      ['cog_created_by', 'Created By'],
      ['cog_modified_on', 'Modified On'],
      ['cog_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Company Master',
    buildAuditSql('public.companys', [
      ['comp_code', 'Company Code'],
      ['comp_name', 'Company Name'],
      ['comp_short', 'Short Name'],
      ['comp_legal_name', 'Legal Name'],
      ['comp_gstin_no', 'GSTIN'],
      ['comp_gst_reg_type', 'GST Reg Type'],
      ['comp_pan_no', 'PAN'],
      ['comp_fssai_no', 'FSSAI No'],
      ['comp_addr1', 'Address 1'],
      ['comp_addr2', 'Address 2'],
      ['comp_addr3', 'Address 3'],
      ['comp_city', 'City'],
      ['comp_district', 'District'],
      ['comp_state', 'State'],
      ['comp_state_code', 'State Code'],
      ['comp_pin', 'PIN Code'],
      ['comp_country', 'Country'],
      ['comp_tel', 'Telephone'],
      ['comp_phone', 'Phone'],
      ['comp_mail', 'Email'],
      ['comp_support_email', 'Support Email'],
      ['comp_support_phone', 'Support Phone'],
      ['comp_website_name', 'Website'],
      ['comp_fin_year_from', 'Fin Year From'],
      ['comp_fin_year_to', 'Fin Year To'],
      ['comp_gst_applicable', 'GST Applicable'],
      ['comp_einvoice_applicable', 'E-Invoice Applicable'],
      ['comp_eway_applicable', 'E-Way Applicable'],
      ['comp_currency_code', 'Currency Code'],
      ['comp_currency_symbol', 'Currency Symbol'],
      ['comp_locale_code', 'Locale Code'],
      ['comp_default', 'Is Default'],
      ['comp_is_active', 'Is Active'],
      ['comp_is_deleted', 'Is Deleted'],
      ['comp_sync_date', 'Sync Date'],
      ['comp_created_on', 'Created On'],
      ['comp_created_by', 'Created By'],
      ['comp_modified_on', 'Modified On'],
      ['comp_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Branch Master',
    buildAuditSql('public.branch_master', [
      ['br_code', 'Branch Code'],
      ['br_name', 'Branch Name'],
      ['br_mailing_name', 'Mailing Name'],
      ['br_alias', 'Alias'],
      ['br_short', 'Short Name'],
      ['br_type', 'Branch Type'],
      ['br_is_default', 'Is Default'],
      ['br_is_active', 'Is Active'],
      ['br_addr1', 'Address 1'],
      ['br_addr2', 'Address 2'],
      ['br_addr3', 'Address 3'],
      ['br_city', 'City'],
      ['br_district', 'District'],
      ['br_state', 'State'],
      ['br_state_code', 'State Code'],
      ['br_pin', 'PIN Code'],
      ['br_country', 'Country'],
      ['br_landmark', 'Landmark'],
      ['br_contact_person', 'Contact Person'],
      ['br_tel', 'Telephone'],
      ['br_phone', 'Phone'],
      ['br_mail', 'Email'],
      ['br_bill_prefix', 'Bill Prefix'],
      ['br_rounding_mode', 'Rounding Mode'],
      ['br_rounding_value', 'Rounding Value'],
      ['br_pos_type', 'POS Type'],
      ['br_allow_negative_stock', 'Allow Negative Stock'],
      ['br_fssai_no', 'FSSAI No'],
      ['br_fssai_license_type', 'FSSAI License Type'],
      ['br_fssai_valid_upto', 'FSSAI Valid Upto'],
      ['br_is_deleted', 'Is Deleted'],
      ['br_sync_date', 'Sync Date'],
      ['br_created_on', 'Created On'],
      ['br_created_by', 'Created By'],
      ['br_modified_on', 'Modified On'],
      ['br_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Employee Department Master',
    buildAuditSql('accounts.employee_departments', [
      ['edpt_name', 'Department Name'],
      ['edpt_alias', 'Alias'],
      ['edpt_code', 'Code'],
      ['edpt_remarks', 'Remarks'],
      ['edpt_is_active', 'Is Active'],
      ['edpt_is_deleted', 'Is Deleted'],
      ['edpt_sync_date', 'Sync Date'],
      ['edpt_created_on', 'Created On'],
      ['edpt_created_by', 'Created By'],
      ['edpt_modified_on', 'Modified On'],
      ['edpt_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Employee Designation Master',
    buildAuditSql('accounts.employee_designations', [
      ['ed_name', 'Designation Name'],
      ['ed_code', 'Code'],
      ['ed_is_default', 'Is Default'],
      ['ed_remarks', 'Remarks'],
      ['ed_is_active', 'Is Active'],
      ['ed_is_deleted', 'Is Deleted'],
      ['ed_sync_date', 'Sync Date'],
      ['ed_created_on', 'Created On'],
      ['ed_created_by', 'Created By'],
      ['ed_modified_on', 'Modified On'],
      ['ed_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Employee Master',
    buildAuditSql('sales.emp_master', [
      ['emp_company_id', 'Company ID'],
      ['emp_branch_id', 'Branch ID'],
      ['emp_code', 'Employee Code'],
      ['emp_name', 'Employee Name'],
      ['emp_alias', 'Alias'],
      ['emp_mobile1', 'Mobile 1'],
      ['emp_mobile2', 'Mobile 2'],
      ['emp_email', 'Email'],
      ['emp_addr1', 'Address 1'],
      ['emp_addr2', 'Address 2'],
      ['emp_addr3', 'Address 3'],
      ['emp_city', 'City'],
      ['emp_district', 'District'],
      ['emp_state', 'State'],
      ['emp_pincode', 'PIN Code'],
      ['emp_gender', 'Gender'],
      ['emp_marital_status', 'Marital Status'],
      ['emp_blood_group', 'Blood Group'],
      ['emp_dob', 'Date of Birth'],
      ['emp_department_id', 'Department ID'],
      ['emp_designation_id', 'Designation ID'],
      ['emp_employment_type', 'Employment Type'],
      ['emp_status', 'Status'],
      ['emp_joined_on', 'Date of Joining'],
      ['emp_probation_end_on', 'Probation End On'],
      ['emp_confirmation_on', 'Confirmation On'],
      ['emp_left_on', 'Date of Leaving'],
      ['emp_overtime_allowed', 'Overtime Allowed'],
      ['emp_has_commission', 'Has Commission'],
      ['emp_commission_type', 'Commission Type'],
      ['emp_commission_value', 'Commission Value'],
      ['emp_salary_type', 'Salary Type'],
      ['emp_salary_amount', 'Salary Amount'],
      ['emp_bata_amount', 'Bata Amount'],
      ['emp_km_bata_amount', 'KM Bata Amount'],
      ['emp_pan_no', 'PAN'],
      ['emp_aadhar_no', 'Aadhaar'],
      ['emp_pf_no', 'PF No'],
      ['emp_esi_no', 'ESI No'],
      ['emp_photo_url', 'Photo URL'],
      ['emp_remarks', 'Remarks'],
      ['emp_is_active', 'Is Active'],
      ['emp_is_deleted', 'Is Deleted'],
      ['emp_sync_date', 'Sync Date'],
      ['emp_created_on', 'Created On'],
      ['emp_created_by', 'Created By'],
      ['emp_modified_on', 'Modified On'],
      ['emp_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Account Ledger Master',
    buildAuditSql('accounts.acc_ledger_master', [
      ['led_name', 'Ledger Name'],
      ['led_alias', 'Alias'],
      ['led_short', 'Short Code'],
      ['led_tally_name', 'Tally Name'],
      ['led_category', 'Category'],
      ['led_group_id', 'Group ID'],
      ['led_company_id', 'Company ID'],
      ['led_branch_id', 'Branch ID'],
      ['led_contact_person', 'Contact Person'],
      ['led_email', 'Email'],
      ['led_tel', 'Telephone'],
      ['led_phone1', 'Phone 1'],
      ['led_phone2', 'Phone 2'],
      ['led_whatsapp_no', 'WhatsApp'],
      ['led_addr1', 'Address 1'],
      ['led_addr2', 'Address 2'],
      ['led_addr3', 'Address 3'],
      ['led_city', 'City'],
      ['led_district', 'District'],
      ['led_state_name', 'State'],
      ['led_state_code', 'State Code'],
      ['led_pin', 'PIN Code'],
      ['led_country', 'Country'],
      ['led_gst_party_reg_type', 'GST Reg Type'],
      ['led_gstin_no', 'GSTIN'],
      ['led_pan_no', 'PAN'],
      ['led_aadhar_no', 'Aadhaar'],
      ['led_ecommerce_gstin', 'E-Commerce GSTIN'],
      ['led_is_sez', 'Is SEZ'],
      ['led_holder_name', 'Account Holder'],
      ['led_bank_name', 'Bank Name'],
      ['led_bank_branch', 'Bank Branch'],
      ['led_bank_ac_no', 'Bank Account No'],
      ['led_bank_ifsc', 'Bank IFSC'],
      ['led_upi_id', 'UPI ID'],
      ['led_ob_amount', 'Opening Balance'],
      ['led_ob_type', 'Opening Balance Type'],
      ['led_ob_as_on', 'Opening Balance As On'],
      ['led_total_dr', 'Total Debit'],
      ['led_total_cr', 'Total Credit'],
      ['led_total_balance', 'Total Balance'],
      ['led_is_active', 'Is Active'],
      ['led_is_deleted', 'Is Deleted'],
      ['led_allow_edit', 'Allow Edit'],
      ['led_is_entry', 'Is Entry'],
      ['led_allow_sms', 'Allow SMS'],
      ['led_remarks', 'Remarks'],
      ['led_sync_date', 'Sync Date'],
      ['led_created_on', 'Created On'],
      ['led_created_by', 'Created By'],
      ['led_modified_on', 'Modified On'],
      ['led_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Ledger Bank Account',
    buildAuditSql('accounts.acc_ledger_bank_accounts', [
      ['lba_ledger_id', 'Ledger ID'],
      ['lba_account_holder', 'Account Holder'],
      ['lba_bank_name', 'Bank Name'],
      ['lba_branch_name', 'Bank Branch'],
      ['lba_account_no', 'Account Number'],
      ['lba_ifsc_code', 'IFSC Code'],
      ['lba_micr_code', 'MICR Code'],
      ['lba_account_type', 'Account Type'],
      ['lba_upi_id', 'UPI ID'],
      ['lba_cheque_name', 'Cheque Name'],
      ['lba_is_default', 'Is Default'],
      ['lba_is_active', 'Is Active'],
      ['lba_is_deleted', 'Is Deleted'],
      ['lba_sync_date', 'Sync Date'],
      ['lba_created_on', 'Created On'],
      ['lba_created_by', 'Created By'],
      ['lba_modified_on', 'Modified On'],
      ['lba_modified_by', 'Modified By'],
      ['lba_remarks', 'Remarks'],
    ]),
  ],
  [
    'Ledger Shipping Address',
    buildAuditSql('accounts.acc_ship_addrs', [
      ['saa_company_id', 'Company ID'],
      ['saa_branch_id', 'Branch ID'],
      ['saa_ledger_id', 'Ledger ID'],
      ['saa_addr_type', 'Address Type'],
      ['saa_is_default', 'Is Default'],
      ['saa_sort', 'Sort Order'],
      ['saa_trade_name', 'Trade Name'],
      ['saa_contact_name', 'Contact Name'],
      ['saa_addr1', 'Address 1'],
      ['saa_addr2', 'Address 2'],
      ['saa_addr3', 'Address 3'],
      ['saa_location', 'Location'],
      ['saa_pin', 'PIN Code'],
      ['saa_state_code', 'State Code'],
      ['saa_state_name', 'State Name'],
      ['saa_country_code', 'Country Code'],
      ['saa_distance_km', 'Distance KM'],
      ['saa_phone', 'Phone'],
      ['saa_email', 'Email'],
      ['saa_gstin', 'GSTIN'],
      ['saa_synced_on', 'Sync Date'],
      ['saa_is_active', 'Is Active'],
      ['saa_is_deleted', 'Is Deleted'],
      ['saa_created_on', 'Created On'],
      ['saa_created_by', 'Created By'],
      ['saa_modified_on', 'Modified On'],
      ['saa_modified_by', 'Modified By'],
      ['saa_remarks', 'Remarks'],
    ]),
  ],
  [
    'GSP Provider Master',
    buildAuditSql('fixed.gsp_provider_master', [
      ['gsp_provider_name', 'Provider Name'],
      ['gsp_provider_code', 'Provider Code'],
      ['gsp_base_url', 'Base URL'],
      ['gsp_route', 'Route'],
      ['gsp_ip_address', 'IP Address'],
      ['gsp_user_name', 'Username'],
      ['gsp_is_active', 'Is Active'],
      ['gsp_is_deleted', 'Is Deleted'],
      ['gsp_created_on', 'Created On'],
      ['gsp_created_by', 'Created By'],
      ['gsp_modified_on', 'Modified On'],
      ['gsp_modified_by', 'Modified By'],
    ]),
  ],
  [
    'GSP Company Service',
    buildAuditSql('fixed.gsp_company_service', [
      ['csg_company_id', 'Company ID'],
      ['csg_gsp_provider_id', 'GSP Provider ID'],
      ['csg_service_type', 'Service Type'],
      ['csg_euser_name', 'E-User Name'],
      ['csg_auth_token_valid_till', 'Auth Token Valid Till'],
      ['csg_is_active', 'Is Active'],
      ['csg_is_deleted', 'Is Deleted'],
      ['csg_sync_date', 'Sync Date'],
      ['csg_created_on', 'Created On'],
      ['csg_created_by', 'Created By'],
      ['csg_modified_on', 'Modified On'],
      ['csg_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Tender Type Master',
    buildAuditSql('accounts.acc_tender_types', [
      ['acc_ttm_type_name', 'Tender Type Name'],
      ['acc_ttm_type_short_name', 'Tender Type Short Name'],
      ['acc_ttm_type_is_active', 'Is Active'],
      ['acc_ttm_type_is_deleted', 'Is Deleted'],
      ['acc_ttm_type_sync_date', 'Sync Date'],
      ['acc_ttm_type_created_on', 'Created On'],
      ['acc_ttm_type_created_by', 'Created By'],
      ['acc_ttm_type_modified_on', 'Modified On'],
      ['acc_ttm_type_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Tender Master',
    buildAuditSql('accounts.acc_tender_master', [
      ['acc_tnd_type_id', 'Tender Type ID'],
      ['acc_tnd_tnd_name', 'Tender Name'],
      ['acc_tnd_tnd_short_name', 'Tender Short Name'],
      ['acc_tnd_tnd_ledger_id', 'Ledger ID'],
      ['acc_tnd_tnd_min_amount', 'Min Amount'],
      ['acc_tnd_tnd_max_amount', 'Max Amount'],
      ['acc_tnd_tnd_display_position', 'Display Position'],
      ['acc_tnd_tnd_surcharge_perc', 'Surcharge %'],
      ['acc_tnd_tnd_edit_surcharge', 'Edit Surcharge'],
      ['acc_tnd_tnd_edit_ledger', 'Edit Ledger'],
      ['acc_tnd_tnd_is_active', 'Is Active'],
      ['acc_tnd_tnd_is_deleted', 'Is Deleted'],
      ['acc_tnd_tnd_sync_date', 'Sync Date'],
      ['acc_tnd_tnd_created_on', 'Created On'],
      ['acc_tnd_tnd_created_by', 'Created By'],
      ['acc_tnd_tnd_modified_on', 'Modified On'],
      ['acc_tnd_tnd_modified_by', 'Modified By'],
      ['acc_tnd_tnd_remarks', 'Remarks'],
    ]),
  ],
  [
    'Supplier Group Master',
    buildAuditSql('purchase.supplier_groups', [
      ['spg_name', 'Supplier Group Name'],
      ['spg_alias', 'Alias'],
      ['spg_short', 'Short Code'],
      ['spg_desc', 'Description'],
      ['spg_is_active', 'Is Active'],
      ['spg_is_deleted', 'Is Deleted'],
      ['spg_sync_date', 'Sync Date'],
      ['spg_created_on', 'Created On'],
      ['spg_created_by', 'Created By'],
      ['spg_modified_on', 'Modified On'],
      ['spg_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Supplier Master',
    buildAuditSql('purchase.suppliers', [
      ['sup_company_id', 'Company ID'],
      ['sup_branch_id', 'Branch ID'],
      ['sup_group_id', 'Supplier Group ID'],
      ['sup_purchase_type', 'Purchase Type'],
      ['sup_name', 'Supplier Name'],
      ['sup_short', 'Short Name'],
      ['sup_addr1', 'Address 1'],
      ['sup_addr2', 'Address 2'],
      ['sup_addr3', 'Address 3'],
      ['sup_city', 'City'],
      ['sup_district', 'District'],
      ['sup_state_name', 'State'],
      ['sup_country', 'Country'],
      ['sup_pincode', 'PIN Code'],
      ['sup_tel', 'Telephone'],
      ['sup_phone', 'Phone'],
      ['sup_mail_id', 'Email'],
      ['sup_whatsapp_no', 'WhatsApp'],
      ['sup_website_address', 'Website'],
      ['sup_cheque_pre_name', 'Cheque Prefix Name'],
      ['sup_notes', 'Notes'],
      ['sup_credit_days', 'Credit Days'],
      ['sup_cash_disc_perc', 'Cash Discount %'],
      ['sup_collection_days', 'Collection Days'],
      ['sup_gst_no', 'GSTIN'],
      ['sup_state_code', 'State Code'],
      ['sup_pan_no', 'PAN'],
      ['sup_gst_type', 'GST Type'],
      ['sup_sup_cst', 'CST No'],
      ['sup_drug_liscence_no', 'Drug License No'],
      ['sup_is_active', 'Is Active'],
      ['sup_is_deleted', 'Is Deleted'],
      ['sup_sync_date', 'Sync Date'],
      ['sup_created_on', 'Created On'],
      ['sup_created_by', 'Created By'],
      ['sup_modified_on', 'Modified On'],
      ['sup_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Customer Group Master',
    buildAuditSql('sales.cust_groups', [
      ['cgr_company_id', 'Company ID'],
      ['cgr_branch_id', 'Branch ID'],
      ['cgr_name', 'Customer Group Name'],
      ['cgr_alias', 'Alias'],
      ['cgr_short', 'Short Code'],
      ['cgr_narration', 'Narration'],
      ['cgr_order', 'Sort Order'],
      ['cgr_disc_perc', 'Discount %'],
      ['cgr_collection_days', 'Collection Days'],
      ['cgr_debit_allowed', 'Credit Allowed'],
      ['cgr_debit_days', 'Credit Days'],
      ['cgr_debit_limit', 'Credit Limit'],
      ['cgr_bills_limit', 'Bills Limit'],
      ['cgr_overdue_billing', 'Overdue Billing'],
      ['cgr_is_active', 'Is Active'],
      ['cgr_is_deleted', 'Is Deleted'],
      ['cgr_created_on', 'Created On'],
      ['cgr_modified_on', 'Modified On'],
    ]),
  ],
  [
    'Customer Master',
    buildAuditSql('sales.customers', [
      ['cus_company_id', 'Company ID'],
      ['cus_branch_id', 'Branch ID'],
      ['cus_area_id', 'Area ID'],
      ['cus_group_id', 'Customer Group ID'],
      ['cus_title', 'Title'],
      ['cus_short', 'Short Name'],
      ['cus_code', 'Customer Code'],
      ['cus_name', 'Customer Name'],
      ['cus_addr1', 'Address 1'],
      ['cus_addr2', 'Address 2'],
      ['cus_addr3', 'Address 3'],
      ['cus_city', 'City'],
      ['cus_district', 'District'],
      ['cus_state_name', 'State'],
      ['cus_country', 'Country'],
      ['cus_state_code', 'State Code'],
      ['cus_landmark', 'Landmark'],
      ['cus_pin', 'PIN Code'],
      ['cus_tel', 'Telephone'],
      ['cus_phone1', 'Phone 1'],
      ['cus_phone2', 'Phone 2'],
      ['cus_whatsapp_no', 'WhatsApp'],
      ['cus_email', 'Email'],
      ['cus_contact_person', 'Contact Person'],
      ['cus_credit_allowed', 'Credit Allowed'],
      ['cus_credit_bill_limit', 'Credit Bill Limit'],
      ['cus_credit_amt_limit', 'Credit Amount Limit'],
      ['cus_credit_days', 'Credit Days'],
      ['cus_disc_perc', 'Discount %'],
      ['cus_allow_promotion', 'Allow Promotion'],
      ['cus_allow_loyalty', 'Allow Loyalty'],
      ['cus_allow_discount', 'Allow Discount'],
      ['cus_gst_no', 'GSTIN'],
      ['cus_pan_no', 'PAN'],
      ['cus_gst_type', 'GST Type'],
      ['cus_ecommerce_gstin', 'E-Commerce GSTIN'],
      ['cus_tcs_applicable', 'TCS Applicable'],
      ['cus_price_level_id', 'Price Level ID'],
      ['cus_notes', 'Notes'],
      ['cus_is_active', 'Is Active'],
      ['cus_is_deleted', 'Is Deleted'],
      ['cus_sync_date', 'Sync Date'],
      ['cus_created_on', 'Created On'],
      ['cus_created_by', 'Created By'],
      ['cus_modified_on', 'Modified On'],
      ['cus_modified_by', 'Modified By'],
    ]),
  ],
  [
    'State Master',
    buildAuditSql('sales.state_master', [
      ['stm_name', 'State Name'],
      ['stm_alias', 'Alias'],
      ['stm_short', 'Short Code'],
      ['stm_order', 'Sort Order'],
      ['stm_is_active', 'Is Active'],
      ['stm_is_deleted', 'Is Deleted'],
      ['stm_sync_date', 'Sync Date'],
      ['stm_created_on', 'Created On'],
      ['stm_created_by', 'Created By'],
      ['stm_modified_on', 'Modified On'],
      ['stm_modified_by', 'Modified By'],
    ]),
  ],
  [
    'City Master',
    buildAuditSql('sales.city_master', [
      ['ctm_name', 'City Name'],
      ['ctm_alias', 'Alias'],
      ['ctm_short', 'Short Code'],
      ['ctm_state_id', 'State ID'],
      ['ctm_order', 'Sort Order'],
      ['ctm_is_active', 'Is Active'],
      ['ctm_is_deleted', 'Is Deleted'],
      ['ctm_sync_date', 'Sync Date'],
      ['ctm_created_on', 'Created On'],
      ['ctm_created_by', 'Created By'],
      ['ctm_modified_on', 'Modified On'],
      ['ctm_modified_by', 'Modified By'],
    ]),
  ],
  [
    'Area Master',
    buildAuditSql('sales.area_master', [
      ['arm_name', 'Area Name'],
      ['arm_alias', 'Alias'],
      ['arm_short', 'Short Code'],
      ['arm_city_id', 'City ID'],
      ['arm_sort', 'Sort Order'],
      ['arm_distance_km', 'Distance KM'],
      ['arm_collection_days', 'Collection Days'],
      ['arm_is_active', 'Is Active'],
      ['arm_is_deleted', 'Is Deleted'],
      ['arm_sync_date', 'Sync Date'],
      ['arm_created_on', 'Created On'],
      ['arm_created_by', 'Created By'],
      ['arm_modified_on', 'Modified On'],
      ['arm_modified_by', 'Modified By'],
    ]),
  ],
]);

export const getAuditScreenSql = (screenName: string): string | undefined =>
  AUDIT_SCREEN_SQL_BY_NAME.get(screenName);
