-- CreateTable
-- public.txn_hold is the parking bay for half-finished transactional work: a
-- POS sale the operator pressed Hold on, a screen's own crash-recovery
-- snapshot, or a saved template that is copied on resume. One row is one
-- parked document; the document body lives verbatim in txh_payload and is read
-- back only by the module that wrote it.
--
-- It REPLACES public.transaction_hold (20260804131134, widened by
-- 20260805110000 / 20260805120639), which was sales/POS-only, unpartitioned,
-- keyed on a varchar device id, and kept its screen state in an untyped
-- th_ui_state. Nothing references that table by FK and its rows are counter
-- scratch, so it is dropped rather than migrated.
--
-- Like public.txn_status_log / sales.sale_bill / sales.sale_order, this table
-- is declaratively partitioned by LIST (txh_acc_year). Prisma Migrate cannot
-- express PARTITION BY, partition-aware composite primary keys, CHECK
-- constraints, partial indexes or index storage parameters, so this migration
-- is hand-written rather than generated by `prisma migrate dev` (see
-- prisma/public/txnHold.prisma for the model plus documentation of everything
-- that is DB-only).
--
-- The partitions themselves are created at the tail of this file, by extending
-- public.ensure_acc_year_partitions() (added in 20260804112944) to cover this
-- table too — without them every insert fails with "no partition of relation
-- \"txn_hold\" found for row".

DROP TABLE IF EXISTS public.transaction_hold;


CREATE TABLE IF NOT EXISTS public.txn_hold
(
    txh_id                  uuid           NOT NULL DEFAULT uuidv7(),
    txh_company_id          uuid           NOT NULL,
    txh_branch_id           uuid           NOT NULL,
    txh_tenant_id           uuid,
    txh_acc_year            character(9)   NOT NULL,   -- the WORK's year

    -- ── What kind of parked work ─────────────────────────────────────────
    -- HOLD      operator pressed Hold; appears in the pick list.
    -- AUTOSAVE  the screen's own crash-recovery snapshot; invisible to the
    --           pick list, at most one live row per screen (ux_txh_autosave),
    --           overwritten in place — see txh_revision.
    -- TEMPLATE  a saved starting point (standing order, repeat basket) that
    --           is copied on resume and never consumed.
    txh_kind                character varying(15) NOT NULL DEFAULT 'HOLD',

    -- Which document this will become. Same vocabulary as txn_status_log's
    -- tsl_src_module / tsl_src_doc_type, so one join reads a hold's trail.
    txh_src_module          character varying(20) NOT NULL,
    txh_doc_type            character varying(30) NOT NULL,

    -- ── Identity of the hold itself ──────────────────────────────────────
    -- txh_hold_no is what gets printed on the token slip the customer walks
    -- away with. txh_hold_slno is the raw per-device counter behind it, kept
    -- separate so an offline till can number holds with no server round trip
    -- (same split as sale_order's so_order_slno / so_order_refno).
    txh_hold_no             character varying(30) NOT NULL,
    txh_hold_slno           integer        NOT NULL,
    txh_hold_on             timestamp(6) with time zone NOT NULL DEFAULT now(),

    -- ── Where it was parked ──────────────────────────────────────────────
    -- The device owns the number series, so RESTRICT on the FK: a till can be
    -- blocked or retired, never unlinked from its holds.
    -- Device TYPE is deliberately absent (the old th_device_type): it is one
    -- join into fixed.device_master and would otherwise go stale here.
    txh_device_id           uuid           NOT NULL,
    txh_counter_id          uuid,                      -- till / cash counter
    txh_session_id          uuid,                      -- shift / day session
    txh_held_by             uuid           NOT NULL,   -- operator at the screen

    -- ── Party snapshot, for the pick list only ───────────────────────────
    -- PARTY, not customer: the same row parks a purchase entry (supplier), a
    -- stock transfer (branch), a receipt (ledger) or a job card (employee).
    -- txh_party_type says which master txh_party_id points into — there is no
    -- FK, for the same reason there is none to the converted document: the
    -- reference is polymorphic and the API layer owns it.
    -- Denormalised on purpose: the picker must render without opening the
    -- payload or joining any master, and a walk-in has no party row at all —
    -- only a name typed at the counter.
    txh_party_type          character varying(15),
    txh_party_id            uuid,
    txh_party_name          character varying(150),
    txh_party_mobile        character varying(20),
    -- Salesman on a sales document, buyer on a purchase one, technician on a
    -- job card — always public.employee_master, so this one keeps its FK.
    txh_staff_id            uuid,
    -- Free label the floor recognises the hold by: table 7, bay 3, locker 12.
    txh_ref_label           character varying(50),

    -- ── Roll-up caches (pick list + sweeper) ─────────────────────────────
    -- Three numbers, because three is what a pick list shows: how many lines,
    -- how much stuff, how much money. Every other total — gross, discount,
    -- charge, tax, what was already tendered — is in the payload, where the
    -- module that computed it can be trusted to read it back the same way.
    -- Duplicating them here would mean two answers to one question.
    txh_item_count          integer        NOT NULL DEFAULT 0,
    txh_total_qty           numeric(18,3)  NOT NULL DEFAULT 0,
    txh_net_amount          numeric(18,2)  NOT NULL DEFAULT 0,

    -- ── The document itself ──────────────────────────────────────────────
    -- txh_payload is the module's own save body, verbatim — header, items,
    -- charges, tenders, and whatever screen state the module chooses to put
    -- there. Read by that module and no one else; this table never
    -- interprets it.
    txh_payload             jsonb          NOT NULL,
    -- Version of the payload's own shape. An old hold resumed after a client
    -- upgrade is readable because the reader knows which shape it is looking
    -- at — the alternative is an unversioned blob nobody dares change.
    txh_payload_version     smallint       NOT NULL DEFAULT 1,
    -- Bumped on every overwrite of the same hold. An offline till that
    -- re-syncs an older snapshot loses to the higher revision.
    txh_revision            integer        NOT NULL DEFAULT 1,

    -- ── State ────────────────────────────────────────────────────────────
    txh_status              character varying(15) NOT NULL DEFAULT 'HELD',
    txh_hold_reason         character varying(100),    -- typed at hold time
    txh_remarks             character varying(500),
    -- When the sweeper may retire it. NULL = keeps until someone acts.
    txh_expires_on          timestamp(6) with time zone,

    -- ── Lease (see the lifecycle note in the header) ─────────────────────
    txh_locked_by           uuid,
    txh_locked_device_id    uuid,
    txh_locked_on           timestamp(6) with time zone,
    txh_lock_expires_on     timestamp(6) with time zone,
    txh_lock_token          uuid,                      -- proves the releaser

    -- ── Resume ───────────────────────────────────────────────────────────
    txh_resumed_by          uuid,
    txh_resumed_on          timestamp(6) with time zone,
    txh_resume_count        integer        NOT NULL DEFAULT 0,

    -- ── Conversion — the hold's one and only exit into a real document ───
    -- No converted DOC TYPE: a hold becomes the document it was parked as, so
    -- txh_doc_type already names the table these ids point into.
    txh_converted_doc_id    uuid,
    txh_converted_acc_year  character(9),              -- may differ from txh_acc_year
    txh_converted_refno     character varying(100),
    txh_converted_on        timestamp(6) with time zone,
    txh_converted_by        uuid,

    -- ── Stock held against the parked work ───────────────────────────────
    -- A flag only: does this hold owe stock back? A shop that reserves on
    -- hold sets it, and the sweeper must release the reservation before it
    -- retires the row. Who reserved and when is a txn_status_log event; the
    -- reserved quantities themselves are in the payload.
    txh_is_stock_reserved   boolean        NOT NULL DEFAULT false,

    -- ── Token slip ───────────────────────────────────────────────────────
    txh_print_count         smallint       NOT NULL DEFAULT 0,
    txh_last_printed_on     timestamp(6) with time zone,

    -- ── Audit ────────────────────────────────────────────────────────────
    -- created_by/modified_by are varchar(50) to match every other table in
    -- this schema set; the OPERATIONAL actors above (held/locked/resumed/
    -- converted _by) are uuid, like txn_status_log's tsl_changed_by, because
    -- screens filter and report on them.
    txh_is_deleted          boolean NOT NULL DEFAULT false,
    txh_sync_date           timestamp(6) with time zone,
    txh_created_on          timestamp(6) with time zone NOT NULL DEFAULT now(),
    txh_created_by          character varying(50) NOT NULL,
    txh_modified_on         timestamp(6) with time zone,
    txh_modified_by         character varying(50),

    CONSTRAINT pk_txn_hold PRIMARY KEY (txh_id, txh_acc_year),

    CONSTRAINT fk_txh_device FOREIGN KEY (txh_device_id)
        REFERENCES fixed.device_master (dev_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_txh_lock_device FOREIGN KEY (txh_locked_device_id)
        REFERENCES fixed.device_master (dev_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE SET NULL,
    -- SET NULL, not RESTRICT: an unattended hold must never pin a master row.
    CONSTRAINT fk_txh_staff FOREIGN KEY (txh_staff_id)
        REFERENCES public.employee_master (emp_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT ck_txh_kind CHECK (txh_kind::text = ANY (ARRAY[
        'HOLD'::text, 'AUTOSAVE'::text, 'TEMPLATE'::text])),

    CONSTRAINT ck_txh_src_module CHECK (txh_src_module::text = ANY (ARRAY[
        'SALES'::text, 'PURCHASE'::text, 'INVENTORY'::text, 'ACCOUNTS'::text,
        'POS'::text, 'SERVICE'::text, 'OTHER'::text])),

    -- Kept in step with ck_tsl_src_doc_type in 20260808120000. 'OTHER' is
    -- legitimate, so a new document type never forces an ALTER on this table.
    CONSTRAINT ck_txh_doc_type CHECK (txh_doc_type::text = ANY (ARRAY[
        'QUOTATION'::text, 'SALES_ORDER'::text, 'DELIVERY_CHALLAN'::text,
        'SALE_BILL'::text, 'SALE_RETURN'::text,
        'PURCHASE_ORDER'::text, 'PURCHASE_BILL'::text, 'PURCHASE_RETURN'::text,
        'STOCK_TRANSFER'::text, 'STOCK_ADJUSTMENT'::text,
        'RECEIPT'::text, 'PAYMENT'::text, 'JOURNAL'::text,
        'OTHER'::text])),

    -- EXPIRED: retired by the sweeper. CANCELLED: killed by a human.
    -- ABANDONED: its device/session went away and never came back.
    CONSTRAINT ck_txh_status CHECK (txh_status::text = ANY (ARRAY[
        'HELD'::text, 'LOCKED'::text, 'RESUMED'::text, 'CONVERTED'::text,
        'EXPIRED'::text, 'CANCELLED'::text, 'ABANDONED'::text])),

    -- Which master txh_party_id points into. 'OTHER' keeps a new party kind
    -- from forcing an ALTER, exactly as it does on txh_doc_type.
    CONSTRAINT ck_txh_party_type CHECK (txh_party_type IS NULL OR
        txh_party_type::text = ANY (ARRAY[
        'CUSTOMER'::text, 'SUPPLIER'::text, 'EMPLOYEE'::text,
        'LEDGER'::text, 'BRANCH'::text, 'OTHER'::text])),
    -- An id with no type is unresolvable — there is no FK to tell you which
    -- master it came from. A type with no id is fine: a walk-in CUSTOMER.
    CONSTRAINT ck_txh_party_typed CHECK (
        txh_party_id IS NULL OR txh_party_type IS NOT NULL),

    -- Shape, not vocabulary — the same guard txn_status_log uses, so a hold
    -- number never differs from itself by a stray space or case.
    CONSTRAINT ck_txh_hold_no_shape CHECK (
        txh_hold_no = upper(btrim(txh_hold_no)) AND length(txh_hold_no) > 0),
    CONSTRAINT ck_txh_hold_slno CHECK (txh_hold_slno >= 1),

    -- ── Payload invariants ───────────────────────────────────────────────
    -- An object, not an array or a bare scalar: every module's save body is
    -- an object, and a reader that has to guess is a reader that crashes.
    CONSTRAINT ck_txh_payload_object CHECK (jsonb_typeof(txh_payload) = 'object'),
    CONSTRAINT ck_txh_payload_version CHECK (txh_payload_version >= 1),
    CONSTRAINT ck_txh_revision CHECK (txh_revision >= 1),

    -- ── Amount invariants ────────────────────────────────────────────────
    -- Signs only. A half-typed screen is allowed to be arithmetically
    -- incomplete — that is the difference between a hold and a document.
    CONSTRAINT ck_txh_amounts CHECK (
        txh_item_count >= 0 AND txh_total_qty >= 0 AND txh_net_amount >= 0),
    CONSTRAINT ck_txh_print_count CHECK (txh_print_count >= 0),

    -- ── Lifecycle invariants ─────────────────────────────────────────────
    CONSTRAINT ck_txh_expires_after_hold CHECK (
        txh_expires_on IS NULL OR txh_expires_on > txh_hold_on),

    -- A lease is all-or-nothing, and a lease with no end is the bug this
    -- column set exists to prevent.
    CONSTRAINT ck_txh_lock_block CHECK (
        (txh_locked_by IS NULL AND txh_locked_on IS NULL AND
         txh_lock_expires_on IS NULL AND txh_lock_token IS NULL)
        OR
        (txh_locked_by IS NOT NULL AND txh_locked_on IS NOT NULL AND
         txh_lock_expires_on IS NOT NULL AND txh_lock_token IS NOT NULL
         AND txh_lock_expires_on > txh_locked_on)),
    CONSTRAINT ck_txh_locked_status CHECK (
        txh_status::text <> 'LOCKED' OR txh_locked_by IS NOT NULL),

    CONSTRAINT ck_txh_resume_count CHECK (txh_resume_count >= 0),
    CONSTRAINT ck_txh_resume_block CHECK (
        (txh_resumed_by IS NULL) = (txh_resumed_on IS NULL)),

    -- Converting is the one transition that must leave a complete trail:
    -- which document it became (id + YEAR — the type is txh_doc_type), who
    -- did it and when. A CONVERTED hold missing any of it is unauditable.
    CONSTRAINT ck_txh_converted_block CHECK (
        (txh_converted_doc_id IS NULL AND txh_converted_acc_year IS NULL AND
         txh_converted_on IS NULL AND txh_converted_by IS NULL)
        OR
        (txh_converted_doc_id IS NOT NULL AND txh_converted_acc_year IS NOT NULL AND
         txh_converted_on IS NOT NULL AND txh_converted_by IS NOT NULL)),
    CONSTRAINT ck_txh_converted_status CHECK (
        txh_status::text <> 'CONVERTED' OR txh_converted_doc_id IS NOT NULL),

    CONSTRAINT ck_txh_printed CHECK (
        (txh_last_printed_on IS NULL) = (txh_print_count = 0))
) PARTITION BY LIST (txh_acc_year);

ALTER TABLE IF EXISTS public.txn_hold OWNER to postgres;


-- ───────────────────────────────────────────────────────────────────────────
--  Indexes.
--
--  Every UNIQUE index includes txh_acc_year — the partition key must be part
--  of it (PostgreSQL requirement), and it is the right key anyway: hold
--  numbers restart with the accounting year.
-- ───────────────────────────────────────────────────────────────────────────

-- The printed token number. Unique per company/branch/year/doc type; partial
-- so a purged (soft-deleted) hold frees its number for reuse.
CREATE UNIQUE INDEX IF NOT EXISTS ux_txh_hold_no
    ON public.txn_hold USING btree
    (txh_company_id, txh_branch_id, txh_acc_year, txh_doc_type, txh_hold_no)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_is_deleted = false;

-- The offline series behind it: each device numbers its own holds with no
-- server round trip, exactly like ux_so_slno on sale_order.
CREATE UNIQUE INDEX IF NOT EXISTS ux_txh_device_slno
    ON public.txn_hold USING btree
    (txh_company_id, txh_branch_id, txh_acc_year, txh_device_id,
     txh_doc_type, txh_hold_slno)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_is_deleted = false;

-- At most ONE live autosave per screen (device + operator + document type).
-- This is what makes crash recovery an UPSERT: the screen posts its snapshot
-- every few seconds and the row is overwritten in place (txh_revision++),
-- instead of the local file-per-device store growing without bound.
CREATE UNIQUE INDEX IF NOT EXISTS ux_txh_autosave
    ON public.txn_hold USING btree
    (txh_acc_year, txh_device_id, txh_held_by, txh_doc_type)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_kind = 'AUTOSAVE' AND txh_status = 'HELD'
      AND txh_is_deleted = false;

-- The pick list: "what is held on this counter right now", newest first.
-- The query the till runs every time Hold-Recall opens.
CREATE INDEX IF NOT EXISTS ix_txh_pick_list
    ON public.txn_hold USING btree
    (txh_company_id, txh_branch_id, txh_doc_type, txh_status, txh_hold_on DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_kind = 'HOLD' AND txh_is_deleted = false;

-- One device's own parked work — including its autosave — after a restart.
CREATE INDEX IF NOT EXISTS ix_txh_device_open
    ON public.txn_hold USING btree
    (txh_company_id, txh_branch_id, txh_device_id, txh_status, txh_hold_on DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_is_deleted = false;

-- Shift close: nothing may still be held when a session is settled.
CREATE INDEX IF NOT EXISTS ix_txh_counter_session
    ON public.txn_hold USING btree
    (txh_counter_id, txh_session_id, txh_status)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_is_deleted = false;

-- The expiry sweeper's queue.
CREATE INDEX IF NOT EXISTS ix_txh_expiry
    ON public.txn_hold USING btree (txh_expires_on)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_expires_on IS NOT NULL
      AND txh_status::text = ANY (ARRAY['HELD'::text, 'LOCKED'::text])
      AND txh_is_deleted = false;

-- The lease reaper's queue — a till that died mid-resume.
CREATE INDEX IF NOT EXISTS ix_txh_lock_expiry
    ON public.txn_hold USING btree (txh_lock_expires_on)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_status = 'LOCKED' AND txh_lock_expires_on IS NOT NULL;

-- "Which hold became this bill" — the reverse lookup from a document. The id
-- is a uuidv7 and unique on its own, so the doc type adds nothing here.
CREATE INDEX IF NOT EXISTS ix_txh_converted_doc
    ON public.txn_hold USING btree
    (txh_converted_doc_id)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_converted_doc_id IS NOT NULL;

-- "Do I have anything held for this party?" — party type leads, so a
-- supplier lookup never walks the counter's customer holds.
CREATE INDEX IF NOT EXISTS ix_txh_party
    ON public.txn_hold USING btree
    (txh_company_id, txh_branch_id, txh_party_type, txh_party_id,
     txh_hold_on DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_party_id IS NOT NULL AND txh_is_deleted = false;
-- Asked at the counter by phone number as often as by name.
CREATE INDEX IF NOT EXISTS ix_txh_party_mobile
    ON public.txn_hold USING btree
    (txh_company_id, txh_branch_id, txh_party_mobile)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_party_mobile IS NOT NULL AND txh_is_deleted = false;

-- Reserved stock that is still parked — what the sweeper must give back
-- before it retires a hold.
CREATE INDEX IF NOT EXISTS ix_txh_stock_reserved
    ON public.txn_hold USING btree
    (txh_company_id, txh_branch_id, txh_hold_on DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_is_stock_reserved = true AND txh_is_deleted = false;

-- Offline chain: rows this device has not pushed yet.
CREATE INDEX IF NOT EXISTS ix_txh_sync_pending
    ON public.txn_hold USING btree (txh_device_id, txh_modified_on)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE txh_sync_date IS NULL;

-- No GIN index on txh_payload. Nothing queries INTO a hold's document — the
-- module opens the row it already picked. A GIN index here would cost every
-- autosave write for a search that never happens.


-- ───────────────────────────────────────────────────────────────────────────
--  Partitions — the same April 1st ritual as every other transaction table.
--
--  Extend the year-partition helper added in 20260804112944 (last extended by
--  20260810130000) so txn_hold is provisioned alongside the bill / tender /
--  status-log / order / quotation parents. Still idempotent, still the one
--  call to make when a fiscal year opens:
--
--      SELECT public.ensure_acc_year_partitions('2027-2028');
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character(9))
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    -- The partition bound is a literal, so the year is validated rather than
    -- interpolated blind. char(9) makes 'YYYY-YYYY' the only well-formed value.
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order FOR VALUES IN (%L)',
        'sale_order_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_item FOR VALUES IN (%L)',
        'sale_order_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_advance_alloc FOR VALUES IN (%L)',
        'sale_order_advance_alloc_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation FOR VALUES IN (%L)',
        'sale_quotation_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation_item FOR VALUES IN (%L)',
        'sale_quotation_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_hold FOR VALUES IN (%L)',
        'txn_hold_' || v_suffix, v_year);
END;
$$;

COMMENT ON FUNCTION public.ensure_acc_year_partitions(character(9)) IS
    'Idempotently creates the sale_bill / sale_bill_item / acc_tender_detail / txn_status_log / sale_order / sale_order_item / sale_order_advance_alloc / sale_quotation / sale_quotation_item / txn_hold LIST partitions for one accounting year (YYYY-YYYY). Run it whenever a fiscal year is opened.';

-- Bootstrap every accounting year on record. fiscal_years is the authority on
-- which years exist; deleted rows are skipped. Re-running the helper for years
-- whose other partitions exist is a no-op for those and creates only the new
-- txn_hold ones.
DO
$$
    DECLARE
        v_year text;
    BEGIN
        FOR v_year IN
            SELECT DISTINCT btrim(fy_year_name)
            FROM public.fiscal_years
            WHERE is_deleted = false
              AND btrim(fy_year_name) ~ '^[0-9]{4}-[0-9]{4}$'
            ORDER BY 1
            LOOP
                PERFORM public.ensure_acc_year_partitions(v_year::character(9));
            END LOOP;
    END;
$$;
