-- Convert the four remaining accounts tables --
--
--   accounts.acc_bill_adjustment   settlement rows against a bill
--   accounts.acc_bills_balance     one row per bill
--   accounts.acc_opening_balance   per-ledger opening balance per FY
--   accounts.acc_pdc_register      post-dated instrument register
--
-- -- to declaratively LIST-partitioned tables keyed on their own acc_year
-- column, the way acc_voucher_header / acc_vouchers / acc_tender_detail and
-- the sales documents already are. Each keeps the year it was created in:
--
--   acc_bills_balance   -> abl_acc_year (FY the bill originated in)
--   acc_bill_adjustment -> aba_acc_year (FY the settlement happened in)
--   acc_opening_balance -> op_acc_year  (the FY the balance opens)
--   acc_pdc_register    -> apd_acc_year (FY the instrument was received in)
--
-- Worth knowing before a year is ever detached: three of these four are
-- cross-year by nature. A bill stays open across year end, a settlement
-- routinely lands in a later FY than the bill it clears, and a cheque matures
-- in a later FY than the one it arrived in. The row never moves partition, so
-- the partition says "where it started", not "where the money is". Outstanding
-- and ageing reads are company-wide and carry no year filter, so they scan
-- every partition; and detaching a closed year takes still-open bills with it.
-- Pruning only helps reads that do filter on the year column.
--
-- Postgres cannot ALTER an ordinary table into a partitioned one, so all four
-- are rebuilt: the existing tables are parked under `_unpart` names, the
-- partitioned parents are created with the same columns, their rows are copied
-- over, and the parked tables are dropped.
--
-- What changes beyond the storage layout:
--
--   1. Every primary key gains the partition key -- pk_acc_bills is now
--      (abl_id, abl_acc_year), pk_acc_bill_adjustment (aba_id, aba_acc_year),
--      pk_acc_opening (op_id, op_acc_year) and pk_acc_pdc_register
--      (apd_id, apd_acc_year). Postgres requires every unique constraint on a
--      partitioned table to contain the partition key, so callers address a row
--      by the pair, not by the id alone.
--   2. ux_aba_voucher_row gains aba_acc_year for the same reason. A settlement
--      row carries the FY of its own voucher, so "one row per voucher line
--      position" is unchanged in practice. ux_abl_bill_refno, ux_op_scope and
--      ux_apd_instrument already contained the year.
--   3. fk_aba_bill points at a composite key now, so acc_bill_adjustment gains
--      aba_bill_acc_year -- the FY of the BILL, which is exactly the column
--      that differs from aba_acc_year when a bill is cleared after year end.
--   4. fk_av_doc (acc_vouchers -> acc_bills_balance) likewise, so acc_vouchers
--      gains av_doc_acc_year, kept null-or-set together with av_doc_id
--      (ck_av_doc_pair).
--   5. fk_apd_replaced_by -- the replacement self-reference -- gains
--      apd_replaced_by_acc_year, kept null-or-set together with
--      apd_replaced_by_id (ck_apd_replaced_pair). This mirrors
--      sq_parent_acc_year on sale_quotation (20260810130000).
--
-- The rebuild also restores what acc_bills_balance lost when
-- 20260811052010_account_vouchersfiled_name_changed_table recreated it through
-- `prisma migrate dev`: the generated abl_pending_amount column, the five
-- indexes and every CHECK constraint declared in 20260806090000. They are
-- listed as DB-only objects in prisma/accounts/AccountBillsBalance.prisma and
-- had silently gone missing from the database.
--
-- Prisma Migrate can express none of PARTITION BY, composite partition-aware
-- primary keys, generated columns, partial indexes or CHECK constraints, so
-- this migration is hand-written rather than generated by `prisma migrate dev`.


-- ───────────────────────────────────────────────────────────────────────────
--  1. Park the unpartitioned tables
--
--  Constraint names are per-table, but index names are per-schema, so every
--  index the rebuilt tables re-declare has to be moved out of the way first.
--  Renaming a constraint renames the index behind it.
--
--  fk_av_doc lives on acc_vouchers, which is not being rebuilt, so it is
--  dropped outright and re-added against the composite key further down.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE accounts.acc_vouchers DROP CONSTRAINT fk_av_doc;

ALTER TABLE accounts.acc_bills_balance   RENAME TO acc_bills_balance_unpart;
ALTER TABLE accounts.acc_bill_adjustment RENAME TO acc_bill_adjustment_unpart;
ALTER TABLE accounts.acc_opening_balance RENAME TO acc_opening_balance_unpart;
ALTER TABLE accounts.acc_pdc_register    RENAME TO acc_pdc_register_unpart;

ALTER TABLE accounts.acc_bills_balance_unpart
    RENAME CONSTRAINT pk_acc_bills TO pk_acc_bills_unpart;
ALTER TABLE accounts.acc_bill_adjustment_unpart
    RENAME CONSTRAINT pk_acc_bill_adjustment TO pk_acc_bill_adjustment_unpart;
ALTER TABLE accounts.acc_opening_balance_unpart
    RENAME CONSTRAINT pk_acc_opening TO pk_acc_opening_unpart;
ALTER TABLE accounts.acc_pdc_register_unpart
    RENAME CONSTRAINT pk_acc_pdc_register TO pk_acc_pdc_register_unpart;

ALTER INDEX accounts.ux_aba_voucher_row RENAME TO ux_aba_voucher_row_unpart;
ALTER INDEX accounts.ix_aba_bill        RENAME TO ix_aba_bill_unpart;
ALTER INDEX accounts.ix_aba_voucher     RENAME TO ix_aba_voucher_unpart;
ALTER INDEX accounts.ix_aba_party       RENAME TO ix_aba_party_unpart;
ALTER INDEX accounts.ix_aba_salesman    RENAME TO ix_aba_salesman_unpart;
ALTER INDEX accounts.ix_aba_pdc         RENAME TO ix_aba_pdc_unpart;

ALTER INDEX accounts.ux_op_scope        RENAME TO ux_op_scope_unpart;
ALTER INDEX accounts.ix_op_lookup       RENAME TO ix_op_lookup_unpart;
ALTER INDEX accounts.ix_op_stale        RENAME TO ix_op_stale_unpart;

ALTER INDEX accounts.ux_apd_instrument  RENAME TO ux_apd_instrument_unpart;
ALTER INDEX accounts.ix_apd_due         RENAME TO ix_apd_due_unpart;
ALTER INDEX accounts.ix_apd_party       RENAME TO ix_apd_party_unpart;
ALTER INDEX accounts.ix_apd_bank        RENAME TO ix_apd_bank_unpart;
ALTER INDEX accounts.ix_apd_bounced     RENAME TO ix_apd_bounced_unpart;
ALTER INDEX accounts.ix_apd_branch      RENAME TO ix_apd_branch_unpart;
ALTER INDEX accounts.ix_apd_voucher     RENAME TO ix_apd_voucher_unpart;
ALTER INDEX accounts.ix_apd_replaced    RENAME TO ix_apd_replaced_unpart;

-- acc_bills_balance carries no index but its primary key: the rebuild in
-- 20260811052010 dropped ux_abl_bill_refno, ix_abl_open, ix_abl_overdue,
-- ix_abl_voucher and ix_abl_salesman along with the rest of the DDL. Nothing
-- to park; section 3 recreates them.


-- ───────────────────────────────────────────────────────────────────────────
--  2. Partitioned parents
--
--  Column lists follow prisma/accounts/*.prisma field order, which is also the
--  order 20260806090000 created them in.
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE accounts.acc_bills_balance
(
    abl_id                uuid           NOT NULL DEFAULT uuidv7(),
    abl_company_id        uuid           NOT NULL,
    abl_branch_id         uuid           NOT NULL,   -- branch that RAISED it
    abl_tenant_id         uuid,
    abl_acc_year          character(9)   NOT NULL,   -- FY of origin

    -- ── Party ────────────────────────────────────────────────────────────
    abl_party_id          uuid           NOT NULL,
    abl_salesman_id       uuid,
    abl_agent_id          uuid,

    -- ── Source document ──────────────────────────────────────────────────
    abl_bill_type         character varying(20) NOT NULL,
    abl_voucher_id        uuid,                      -- NULL for OPENING
    abl_voucher_line_id   uuid,
    abl_voucher_type_id   integer        NOT NULL,
    abl_voucher_no        bigint,
    abl_doc_date          date,
    abl_doc_refno         character varying(50),

    -- ── Bill identity ────────────────────────────────────────────────────
    abl_bill_refno        character varying(100) NOT NULL,
    abl_bill_date         date           NOT NULL,
    abl_due_date          date,
    abl_credit_days       smallint       NOT NULL DEFAULT 0,
    abl_grace_days        smallint       NOT NULL DEFAULT 0,
    abl_dr_cr             character(2)   NOT NULL,   -- DR = receivable, CR = payable
    abl_narration         text,

    -- ── Amounts (the settled columns are maintained from the adjustments) ─
    abl_bill_amount       numeric(18,2)  NOT NULL,
    abl_alloc_amount      numeric(18,2)  NOT NULL DEFAULT 0,
    abl_disc_amount       numeric(18,2)  NOT NULL DEFAULT 0,
    abl_writeoff_amount   numeric(18,2)  NOT NULL DEFAULT 0,
    abl_pending_amount    numeric(18,2)
        GENERATED ALWAYS AS (abl_bill_amount - abl_alloc_amount
                             - abl_disc_amount - abl_writeoff_amount) STORED,

    -- ── Audit ────────────────────────────────────────────────────────────
    abl_is_active         boolean        NOT NULL DEFAULT true,
    abl_is_deleted        boolean        NOT NULL DEFAULT false,
    abl_sync_date         timestamp(6) with time zone,
    abl_created_on        timestamp(6) with time zone NOT NULL DEFAULT now(),
    abl_created_by        character varying(50),
    abl_modified_on       timestamp(6) with time zone,
    abl_modified_by       character varying(50),

    CONSTRAINT pk_acc_bills PRIMARY KEY (abl_id, abl_acc_year),

    CONSTRAINT fk_abl_voucher FOREIGN KEY (abl_voucher_id, abl_acc_year)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id, avh_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_abl_voucher_type FOREIGN KEY (abl_voucher_type_id)
        REFERENCES accounts.acc_voucher_types (vchr_type_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_abl_party FOREIGN KEY (abl_party_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_abl_bill_type CHECK (abl_bill_type::text = ANY (ARRAY[
        'SALES'::text, 'PURCHASE'::text, 'OPENING'::text,
        'ADVANCE'::text, 'INTEREST'::text])),
    CONSTRAINT ck_abl_dr_cr     CHECK (abl_dr_cr = ANY (ARRAY['DR'::bpchar, 'CR'::bpchar])),

    CONSTRAINT ck_abl_acc_year  CHECK (
        abl_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(abl_acc_year, 4)::int = LEFT(abl_acc_year, 4)::int + 1),

    -- OPENING has no source voucher; every other type must have one.
    CONSTRAINT ck_abl_voucher   CHECK (
        (abl_bill_type::text = 'OPENING' AND abl_voucher_id IS NULL)
        OR (abl_bill_type::text <> 'OPENING' AND abl_voucher_id IS NOT NULL)),

    CONSTRAINT ck_abl_amount    CHECK (abl_bill_amount > 0),
    CONSTRAINT ck_abl_due_date  CHECK (abl_due_date IS NULL OR abl_due_date >= abl_bill_date),

    -- The over-settlement guard: a bill can never be edited down below what
    -- has already been settled, discounted or written off against it.
    CONSTRAINT ck_abl_settled   CHECK (
        abl_alloc_amount >= 0 AND abl_disc_amount >= 0 AND abl_writeoff_amount >= 0
        AND (abl_alloc_amount + abl_disc_amount + abl_writeoff_amount) <= abl_bill_amount)
) PARTITION BY LIST (abl_acc_year);

ALTER TABLE accounts.acc_bills_balance OWNER to postgres;


CREATE TABLE accounts.acc_bill_adjustment
(
    aba_id                uuid           NOT NULL DEFAULT uuidv7(),
    aba_company_id        uuid           NOT NULL,
    aba_branch_id         uuid           NOT NULL,   -- branch that COLLECTED
    aba_tenant_id         uuid,
    aba_acc_year          character(9)   NOT NULL,   -- FY of the SETTLEMENT

    -- ── What is being settled ────────────────────────────────────────────
    -- aba_bill_acc_year completes the reference to the bill's composite key.
    -- It is the FY the bill was RAISED in, which is not aba_acc_year whenever
    -- a bill is cleared after year end.
    aba_bill_id           uuid           NOT NULL,
    aba_bill_acc_year     character(9)   NOT NULL,
    aba_party_id          uuid           NOT NULL,   -- denormalised from the bill
    aba_salesman_id       uuid,                      -- who collected, for commission

    -- ── The voucher doing the settling ───────────────────────────────────
    aba_voucher_id        uuid           NOT NULL,
    aba_voucher_acc_year  character(9)   NOT NULL,   -- header is partitioned
    aba_voucher_line_id   uuid,
    aba_voucher_type_id   integer        NOT NULL,
    aba_voucher_no        bigint,
    aba_voucher_refno     character varying(50),
    aba_row_no            integer        NOT NULL,
    aba_adj_date          date           NOT NULL,

    aba_adj_type          character varying(20) NOT NULL DEFAULT 'AGAINST_REF',
    aba_dr_cr             character(2)   NOT NULL,

    -- ── Amounts: these three roll up onto acc_bills_balance ──────────────
    aba_alloc_amount      numeric(18,2)  NOT NULL DEFAULT 0,
    aba_disc_amount       numeric(18,2)  NOT NULL DEFAULT 0,
    aba_writeoff_amount   numeric(18,2)  NOT NULL DEFAULT 0,
    aba_profit_amount     numeric(18,2)  NOT NULL DEFAULT 0,

    -- Where the non-cash part of the settlement is posted:
    -- Discount Allowed / Bad Debts Written Off / Interest Waived
    aba_effect_ledger_id  uuid,

    -- ── How the money arrived ────────────────────────────────────────────
    aba_settlement_mode   character varying(20),     -- CASH/CHEQUE/UPI/NEFT/CARD
    aba_settlement_ledger_id uuid        NOT NULL,   -- cash or bank ledger
    aba_is_post_dated     boolean        NOT NULL DEFAULT false,
    aba_pdc_due_date      date,
    aba_narration         text,

    -- ── Audit ────────────────────────────────────────────────────────────
    aba_is_active         boolean        NOT NULL DEFAULT true,
    aba_is_deleted        boolean        NOT NULL DEFAULT false,
    aba_sync_date         timestamp(6) with time zone,
    aba_created_on        timestamp(6) with time zone NOT NULL DEFAULT now(),
    aba_created_by        character varying(50),
    aba_modified_on       timestamp(6) with time zone,
    aba_modified_by       character varying(50),

    CONSTRAINT pk_acc_bill_adjustment PRIMARY KEY (aba_id, aba_acc_year),

    -- fk_aba_bill is added in section 6, once the bills have been copied over.
    CONSTRAINT fk_aba_voucher FOREIGN KEY (aba_voucher_id, aba_voucher_acc_year)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id, avh_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_aba_voucher_type FOREIGN KEY (aba_voucher_type_id)
        REFERENCES accounts.acc_voucher_types (vchr_type_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_aba_party FOREIGN KEY (aba_party_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_aba_effect_ledger FOREIGN KEY (aba_effect_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_aba_settle_ledger FOREIGN KEY (aba_settlement_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_aba_adj_type CHECK (aba_adj_type::text = ANY (ARRAY[
        'AGAINST_REF'::text, 'ADVANCE_ADJ'::text, 'DISCOUNT'::text,
        'WRITE_OFF'::text, 'CREDIT_NOTE'::text, 'INTEREST_WAIVER'::text])),
    CONSTRAINT ck_aba_dr_cr  CHECK (aba_dr_cr = ANY (ARRAY['DR'::bpchar, 'CR'::bpchar])),
    CONSTRAINT ck_aba_row_no CHECK (aba_row_no >= 1),

    CONSTRAINT ck_aba_acc_year CHECK (
        aba_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(aba_acc_year, 4)::int = LEFT(aba_acc_year, 4)::int + 1),
    CONSTRAINT ck_aba_bill_acc_year CHECK (
        aba_bill_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(aba_bill_acc_year, 4)::int = LEFT(aba_bill_acc_year, 4)::int + 1),
    CONSTRAINT ck_aba_voucher_acc_year CHECK (
        aba_voucher_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(aba_voucher_acc_year, 4)::int = LEFT(aba_voucher_acc_year, 4)::int + 1),

    -- Non-negative, and the row must actually do something.
    CONSTRAINT ck_aba_amounts CHECK (
        aba_alloc_amount >= 0 AND aba_disc_amount >= 0 AND aba_writeoff_amount >= 0
        AND (aba_alloc_amount + aba_disc_amount + aba_writeoff_amount) > 0),

    -- The amount column must match what the row claims to be.
    CONSTRAINT ck_aba_type_amount CHECK (
        (aba_adj_type::text IN ('AGAINST_REF','ADVANCE_ADJ','CREDIT_NOTE')
             AND aba_alloc_amount > 0
             AND aba_disc_amount = 0 AND aba_writeoff_amount = 0)
        OR (aba_adj_type::text = 'DISCOUNT'
             AND aba_disc_amount > 0
             AND aba_alloc_amount = 0 AND aba_writeoff_amount = 0)
        OR (aba_adj_type::text IN ('WRITE_OFF','INTEREST_WAIVER')
             AND aba_writeoff_amount > 0
             AND aba_alloc_amount = 0 AND aba_disc_amount = 0)),

    -- Non-cash settlements must name the P&L ledger they land in.
    CONSTRAINT ck_aba_effect_ledger CHECK (
        aba_adj_type::text NOT IN ('DISCOUNT','WRITE_OFF','INTEREST_WAIVER')
        OR aba_effect_ledger_id IS NOT NULL),

    -- Cash settlements must name where the money went.
    CONSTRAINT ck_aba_settle_ledger CHECK (
        aba_adj_type::text NOT IN ('AGAINST_REF')
        OR aba_settlement_ledger_id IS NOT NULL),

    CONSTRAINT ck_aba_pdc CHECK (
        aba_is_post_dated = false OR aba_pdc_due_date IS NOT NULL)
) PARTITION BY LIST (aba_acc_year);

ALTER TABLE accounts.acc_bill_adjustment OWNER to postgres;


CREATE TABLE accounts.acc_opening_balance
(
    op_id             uuid           NOT NULL DEFAULT uuidv7(),

    op_company_id     uuid           NOT NULL,
    op_branch_id      uuid,                          -- NULL = company level
    op_acc_year       character(9)   NOT NULL,       -- '2025-2026'
    op_ledger_id      uuid           NOT NULL,

    op_amount         numeric(18,2)  NOT NULL DEFAULT 0,
    op_dr_cr          character(1)   NOT NULL,

    -- CARRY_FORWARD rows are owned by the generator and may be rewritten.
    -- MANUAL and MIGRATION rows are owned by a human and must never be
    -- touched by regeneration.
    op_source         character varying(20) NOT NULL DEFAULT 'CARRY_FORWARD',

    op_is_stale       boolean        NOT NULL DEFAULT false,
    op_stale_since    timestamp(6) with time zone,
    op_generated_at   timestamp(6) with time zone,
    op_generated_by   character varying(50),
    op_remarks        text,

    op_is_deleted     boolean        NOT NULL DEFAULT false,
    op_created_at     timestamp(6) with time zone NOT NULL DEFAULT now(),
    op_created_by     character varying(50),
    op_modified_at    timestamp(6) with time zone,
    op_modified_by    character varying(50),

    CONSTRAINT pk_acc_opening PRIMARY KEY (op_id, op_acc_year),
    CONSTRAINT ck_op_dr_cr    CHECK (op_dr_cr IN ('D','C')),
    CONSTRAINT ck_op_amount   CHECK (op_amount >= 0),
    CONSTRAINT ck_op_source   CHECK (op_source IN ('CARRY_FORWARD','MANUAL','MIGRATION')),

    -- '2025-2026' only: right year must be left year + 1.
    CONSTRAINT ck_op_acc_year CHECK (
        op_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(op_acc_year, 4)::int = LEFT(op_acc_year, 4)::int + 1)
) PARTITION BY LIST (op_acc_year);

ALTER TABLE accounts.acc_opening_balance OWNER to postgres;


CREATE TABLE accounts.acc_pdc_register
(
    apd_id                uuid           NOT NULL DEFAULT uuidv7(),
    apd_company_id        uuid           NOT NULL,
    apd_branch_id         uuid           NOT NULL,   -- branch that took it in
    apd_tenant_id         uuid,
    apd_acc_year          character(9)   NOT NULL,   -- FY it was received in

    -- R = receivable (a customer's cheque we hold),
    -- P = payable (our cheque handed to a supplier)
    apd_tra_type          character(1)   NOT NULL,
    apd_party_id          uuid           NOT NULL,
    apd_salesman_id       uuid,

    -- ── The instrument ───────────────────────────────────────────────────
    apd_instrument_type   character varying(20) NOT NULL DEFAULT 'CHEQUE',
    apd_instrument_no     character varying(30) NOT NULL,
    -- The post-date written on the cheque -- the maturity date the due-list
    -- works from, not the date it was received.
    apd_instrument_date   date           NOT NULL,
    apd_amount            numeric(18,2)  NOT NULL,
    apd_bank_name         character varying(100),
    apd_bank_branch       character varying(100),
    apd_ifsc              character varying(11),
    apd_micr              character varying(9),
    apd_drawer_name       character varying(150),
    apd_received_on       date           NOT NULL,

    -- Our own bank ledger: where it will be deposited (R) or drawn on (P)
    apd_bank_ledger_id    uuid,

    -- ── Accounting linkage ───────────────────────────────────────────────
    apd_posting_mode      character varying(15) NOT NULL DEFAULT 'ON_CLEARING',
    apd_voucher_id        uuid,
    apd_voucher_acc_year  character(9),
    -- acc_tender_detail row. No FK: that table is partitioned on a composite
    -- key this column cannot address on its own.
    apd_tender_id         uuid,

    -- ── Lifecycle ────────────────────────────────────────────────────────
    apd_status            character varying(15) NOT NULL DEFAULT 'HELD',
    apd_status_on         timestamp(6) with time zone,
    apd_status_by         character varying(50),
    -- How many times it has been sent to the bank.
    apd_present_count     integer        NOT NULL DEFAULT 0,

    apd_deposit_date      date,
    apd_deposit_slip_no   character varying(50),

    apd_clear_date        date,
    apd_clear_voucher_id  uuid,
    apd_clear_acc_year    character(9),

    apd_bounce_date       date,
    apd_bounce_reason     character varying(150),
    apd_bounce_charges    numeric(18,2)  NOT NULL DEFAULT 0,
    apd_bounce_voucher_id uuid,
    apd_bounce_acc_year   character(9),
    apd_charge_voucher_id uuid,
    apd_charge_acc_year   character(9),

    -- apd_replaced_by_acc_year completes the reference to the replacement's
    -- composite key; it is set exactly when apd_replaced_by_id is.
    apd_replaced_by_id    uuid,
    apd_replaced_by_acc_year character(9),
    apd_cancel_date       date,
    apd_cancel_reason     character varying(250),
    apd_remarks           text,

    -- ── Audit ────────────────────────────────────────────────────────────
    apd_is_active         boolean        NOT NULL DEFAULT true,
    apd_is_deleted        boolean        NOT NULL DEFAULT false,
    apd_sync_date         timestamp(6) with time zone,
    apd_created_on        timestamp(6) with time zone NOT NULL DEFAULT now(),
    apd_created_by        character varying(50),
    apd_modified_on       timestamp(6) with time zone,
    apd_modified_by       character varying(50),

    CONSTRAINT pk_acc_pdc_register PRIMARY KEY (apd_id, apd_acc_year),

    CONSTRAINT fk_apd_party FOREIGN KEY (apd_party_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_apd_bank_ledger FOREIGN KEY (apd_bank_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_apd_voucher FOREIGN KEY (apd_voucher_id, apd_voucher_acc_year)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id, avh_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_apd_clear_voucher FOREIGN KEY (apd_clear_voucher_id, apd_clear_acc_year)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id, avh_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_apd_bounce_voucher FOREIGN KEY (apd_bounce_voucher_id, apd_bounce_acc_year)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id, avh_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_apd_charge_voucher FOREIGN KEY (apd_charge_voucher_id, apd_charge_acc_year)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id, avh_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    -- fk_apd_replaced_by is added in section 6, once the rows are back and the
    -- new year column has been backfilled.

    CONSTRAINT ck_apd_tra_type CHECK (apd_tra_type = ANY (ARRAY['R'::bpchar, 'P'::bpchar])),
    CONSTRAINT ck_apd_instrument CHECK (apd_instrument_type::text = ANY (ARRAY[
        'CHEQUE'::text, 'DD'::text, 'PAY_ORDER'::text,
        'ECS'::text, 'NACH'::text, 'UPI_MANDATE'::text])),
    CONSTRAINT ck_apd_status CHECK (apd_status::text = ANY (ARRAY[
        'HELD'::text, 'DEPOSITED'::text, 'CLEARED'::text, 'BOUNCED'::text,
        'RETURNED'::text, 'CANCELLED'::text, 'REPLACED'::text])),
    CONSTRAINT ck_apd_posting_mode CHECK (apd_posting_mode::text = ANY (ARRAY[
        'ON_RECEIPT'::text, 'ON_CLEARING'::text])),

    CONSTRAINT ck_apd_amount   CHECK (apd_amount > 0),
    CONSTRAINT ck_apd_charges  CHECK (apd_bounce_charges >= 0),
    CONSTRAINT ck_apd_present  CHECK (apd_present_count >= 0),
    CONSTRAINT ck_apd_acc_year CHECK (
        apd_acc_year ~ '^[0-9]{4}-[0-9]{4}$'
        AND RIGHT(apd_acc_year, 4)::int = LEFT(apd_acc_year, 4)::int + 1),

    -- A post-dated instrument is dated on or after the day it arrived.
    CONSTRAINT ck_apd_dates CHECK (apd_instrument_date >= apd_received_on),

    -- ── Status consistency ───────────────────────────────────────────────
    CONSTRAINT ck_apd_deposited CHECK (
        apd_status::text NOT IN ('DEPOSITED','CLEARED','BOUNCED')
        OR apd_deposit_date IS NOT NULL),
    CONSTRAINT ck_apd_cleared CHECK (
        apd_status::text <> 'CLEARED'
        OR (apd_clear_date IS NOT NULL AND apd_clear_voucher_id IS NOT NULL)),
    CONSTRAINT ck_apd_bounced CHECK (
        apd_status::text <> 'BOUNCED'
        OR (apd_bounce_date IS NOT NULL AND apd_bounce_reason IS NOT NULL)),
    CONSTRAINT ck_apd_replaced CHECK (
        apd_status::text <> 'REPLACED' OR apd_replaced_by_id IS NOT NULL),
    CONSTRAINT ck_apd_cancelled CHECK (
        apd_status::text NOT IN ('CANCELLED','RETURNED')
        OR apd_cancel_reason IS NOT NULL),
    CONSTRAINT ck_apd_self CHECK (
        apd_replaced_by_id IS NULL OR apd_replaced_by_id <> apd_id),
    -- The replacement pointer addresses a composite key, so both halves move
    -- together.
    CONSTRAINT ck_apd_replaced_pair CHECK (
        (apd_replaced_by_id IS NULL) = (apd_replaced_by_acc_year IS NULL)),

    -- ON_RECEIPT means a voucher exists from day one.
    CONSTRAINT ck_apd_posting CHECK (
        apd_posting_mode::text <> 'ON_RECEIPT'
        OR (apd_voucher_id IS NOT NULL AND apd_voucher_acc_year IS NOT NULL)),

    CONSTRAINT ck_apd_seq CHECK (
        (apd_clear_date  IS NULL OR apd_deposit_date IS NULL OR apd_clear_date  >= apd_deposit_date)
        AND (apd_bounce_date IS NULL OR apd_deposit_date IS NULL OR apd_bounce_date >= apd_deposit_date))
) PARTITION BY LIST (apd_acc_year);

ALTER TABLE accounts.acc_pdc_register OWNER to postgres;


-- ───────────────────────────────────────────────────────────────────────────
--  3. Indexes
--
--  Declared on the parents, so partitions created later inherit them. Every
--  predicate is carried over unchanged from 20260806090000 except
--  ux_aba_voucher_row and ix_aba_bill, which gain a year column.
-- ───────────────────────────────────────────────────────────────────────────

-- Bill numbers restart each FY, so the FY is part of the key.
CREATE UNIQUE INDEX ux_abl_bill_refno ON accounts.acc_bills_balance (
    abl_company_id, abl_party_id, abl_bill_type, abl_acc_year, abl_bill_refno
) WHERE abl_is_deleted = false;

-- Adjustment screen and ageing report both live on this index.
-- No branch column: outstanding is company-wide for a chain store.
CREATE INDEX ix_abl_open ON accounts.acc_bills_balance (
    abl_company_id, abl_party_id, abl_bill_date
) INCLUDE (abl_bill_refno, abl_bill_amount, abl_pending_amount, abl_dr_cr)
  WHERE abl_is_deleted = false AND abl_pending_amount <> 0;

CREATE INDEX ix_abl_overdue ON accounts.acc_bills_balance (abl_company_id, abl_due_date)
    WHERE abl_is_deleted = false AND abl_pending_amount <> 0;

CREATE INDEX ix_abl_voucher ON accounts.acc_bills_balance (abl_voucher_id, abl_acc_year)
    WHERE abl_voucher_id IS NOT NULL AND abl_is_deleted = false;

CREATE INDEX ix_abl_salesman ON accounts.acc_bills_balance (abl_company_id, abl_salesman_id)
    WHERE abl_is_deleted = false AND abl_pending_amount <> 0;

-- One row per voucher line position. aba_acc_year joins the key because the
-- index is unique and the table is partitioned on it; a settlement row carries
-- the year of its own voucher, so the rule itself is unchanged.
CREATE UNIQUE INDEX ux_aba_voucher_row ON accounts.acc_bill_adjustment (
    aba_voucher_id, aba_voucher_acc_year, aba_row_no, aba_acc_year
) WHERE aba_is_deleted = false;

-- Drives the bill roll-up and the bill drill-down screen. Both halves of the
-- bill key are here, so the roll-up reads the index alone.
CREATE INDEX ix_aba_bill ON accounts.acc_bill_adjustment (aba_bill_id, aba_bill_acc_year)
    INCLUDE (aba_alloc_amount, aba_disc_amount, aba_writeoff_amount)
    WHERE aba_is_deleted = false;

CREATE INDEX ix_aba_voucher ON accounts.acc_bill_adjustment (
    aba_voucher_id, aba_voucher_acc_year
) WHERE aba_is_deleted = false;

-- Collection register, party-wise receipt history.
CREATE INDEX ix_aba_party ON accounts.acc_bill_adjustment (
    aba_company_id, aba_party_id, aba_adj_date
) WHERE aba_is_deleted = false;

-- Collection-basis commission for the salesman.
CREATE INDEX ix_aba_salesman ON accounts.acc_bill_adjustment (
    aba_company_id, aba_salesman_id, aba_adj_date
) WHERE aba_is_deleted = false AND aba_salesman_id IS NOT NULL;

-- Post-dated cheques still to mature.
CREATE INDEX ix_aba_pdc ON accounts.acc_bill_adjustment (
    aba_company_id, aba_pdc_due_date
) WHERE aba_is_post_dated = true AND aba_is_deleted = false;

-- Branch NULL must still collide with branch NULL, so COALESCE it.
CREATE UNIQUE INDEX ux_op_scope ON accounts.acc_opening_balance (
    op_company_id,
    COALESCE(op_branch_id, '00000000-0000-0000-0000-000000000000'::uuid),
    op_acc_year,
    op_ledger_id
) WHERE op_is_deleted = false;

-- Ledger statement reads exactly one row; keep it index-only.
CREATE INDEX ix_op_lookup ON accounts.acc_opening_balance (
    op_company_id, op_acc_year, op_ledger_id
) INCLUDE (op_amount, op_dr_cr, op_is_stale)
  WHERE op_is_deleted = false;

CREATE INDEX ix_op_stale ON accounts.acc_opening_balance (op_company_id, op_acc_year)
    WHERE op_is_stale = true AND op_is_deleted = false;

-- The same cheque number cannot be registered twice for one party in one FY.
CREATE UNIQUE INDEX ux_apd_instrument ON accounts.acc_pdc_register (
    apd_company_id, apd_party_id, apd_instrument_type,
    apd_instrument_no, apd_acc_year
) WHERE apd_is_deleted = false AND apd_status <> 'CANCELLED';

-- The screen everyone opens every morning: what matures today or is overdue.
CREATE INDEX ix_apd_due ON accounts.acc_pdc_register (
    apd_company_id, apd_instrument_date
) INCLUDE (apd_party_id, apd_amount, apd_instrument_no, apd_bank_name)
  WHERE apd_status IN ('HELD','DEPOSITED') AND apd_is_deleted = false;

-- Party-wise PDC held, for the credit-limit check.
CREATE INDEX ix_apd_party ON accounts.acc_pdc_register (
    apd_company_id, apd_party_id, apd_instrument_date
) WHERE apd_status IN ('HELD','DEPOSITED') AND apd_is_deleted = false;

-- Deposit slip: which cheques go to which of our banks.
CREATE INDEX ix_apd_bank ON accounts.acc_pdc_register (
    apd_company_id, apd_bank_ledger_id, apd_instrument_date
) WHERE apd_status = 'HELD' AND apd_is_deleted = false;

-- Bounce history, and the follow-up worklist.
CREATE INDEX ix_apd_bounced ON accounts.acc_pdc_register (
    apd_company_id, apd_bounce_date
) WHERE apd_status = 'BOUNCED' AND apd_is_deleted = false;

CREATE INDEX ix_apd_branch ON accounts.acc_pdc_register (
    apd_company_id, apd_branch_id, apd_status
) WHERE apd_is_deleted = false;

CREATE INDEX ix_apd_voucher ON accounts.acc_pdc_register (
    apd_voucher_id, apd_voucher_acc_year
) WHERE apd_voucher_id IS NOT NULL;

CREATE INDEX ix_apd_replaced ON accounts.acc_pdc_register (
    apd_replaced_by_id, apd_replaced_by_acc_year
) WHERE apd_replaced_by_id IS NOT NULL;


-- ───────────────────────────────────────────────────────────────────────────
--  4. Table / column comments
-- ───────────────────────────────────────────────────────────────────────────

COMMENT ON TABLE accounts.acc_bills_balance IS
    'One row per bill. Partitioned by LIST (abl_acc_year), the FY the bill was raised in. A bill is never carried forward at year end — the same row stays open across financial years, in the partition of the year it started in.';
COMMENT ON COLUMN accounts.acc_bills_balance.abl_acc_year IS
    'FY the bill originated in, and the partition key. A bill outstanding past year end keeps this year.';
COMMENT ON COLUMN accounts.acc_bills_balance.abl_branch_id IS
    'Branch that raised the bill. Settlement may happen at a different branch — that is recorded on the adjustment table.';
COMMENT ON COLUMN accounts.acc_bills_balance.abl_alloc_amount IS
    'Maintained from the adjustment table. Never write from application code.';

COMMENT ON TABLE accounts.acc_bill_adjustment IS
    'Settlement rows: what a receipt, payment, credit note or journal did to a bill. Partitioned by LIST (aba_acc_year), the FY of the SETTLEMENT — which is not the bill''s year whenever a bill is cleared after year end.';
COMMENT ON COLUMN accounts.acc_bill_adjustment.aba_acc_year IS
    'FY the settlement happened in, and the partition key. Differs from the bill FY whenever a bill is cleared after year end.';
COMMENT ON COLUMN accounts.acc_bill_adjustment.aba_bill_acc_year IS
    'FY of the bill being settled. Second half of fk_aba_bill, which addresses the bill''s composite (abl_id, abl_acc_year) key.';
COMMENT ON COLUMN accounts.acc_bill_adjustment.aba_branch_id IS
    'Branch where the money was collected. May differ from the bill branch — that is the whole point of the chain-store split.';
COMMENT ON COLUMN accounts.acc_bill_adjustment.aba_effect_ledger_id IS
    'P&L ledger for the non-cash part: Discount Allowed, Bad Debts Written Off, Interest Waived.';

COMMENT ON TABLE  accounts.acc_opening_balance IS
    'Opening balance per ledger per financial year, partitioned by LIST (op_acc_year). Balance-sheet ledgers only; P&L ledgers always start at zero.';
COMMENT ON COLUMN accounts.acc_opening_balance.op_acc_year IS
    'Financial year label in YYYY-YYYY form, matching fiscal_years.fy_code. The partition key.';
COMMENT ON COLUMN accounts.acc_opening_balance.op_source IS
    'Regeneration updates CARRY_FORWARD rows only. MANUAL and MIGRATION rows are never overwritten.';

COMMENT ON TABLE accounts.acc_pdc_register IS
    'Post-dated cheques and mandates, in both directions. Partitioned by LIST (apd_acc_year), the FY the instrument was received in — an instrument routinely matures, clears or bounces in a later financial year, and stays in the partition of the year it arrived in.';
COMMENT ON COLUMN accounts.acc_pdc_register.apd_acc_year IS
    'FY the instrument was received in, and the partition key. Clearing and bouncing may happen in a later year; those carry their own voucher year columns.';
COMMENT ON COLUMN accounts.acc_pdc_register.apd_instrument_date IS
    'The post-date written on the cheque. This is the maturity date the due-list works from, not the date it was received.';
COMMENT ON COLUMN accounts.acc_pdc_register.apd_present_count IS
    'How many times it has been sent to the bank. A bounced cheque can be re-presented; this is what distinguishes a first bounce from a repeat.';
COMMENT ON COLUMN accounts.acc_pdc_register.apd_posting_mode IS
    'ON_RECEIPT posts a receipt into a Cheques in Hand ledger immediately. ON_CLEARING posts nothing until the bank clears it, leaving the party outstanding.';
COMMENT ON COLUMN accounts.acc_pdc_register.apd_replaced_by_acc_year IS
    'FY of the replacement instrument. Second half of fk_apd_replaced_by, set exactly when apd_replaced_by_id is.';


-- ───────────────────────────────────────────────────────────────────────────
--  5. Teach public.ensure_acc_year_partitions about the four new parents
--
--  Same helper the bill / tender / order / quotation tables use
--  (20260804112944, extended by 20260808132323 and 20260810130000).
--  Idempotent -- call it whenever a fiscal year is opened:
--
--      SELECT public.ensure_acc_year_partitions('2027-2028');
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character(9))
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    -- The partition bound is a literal, so the year is validated rather than
    -- interpolated blind. char(9) makes 'YYYY-YYYY' the only well-formed value.
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order FOR VALUES IN (%L)',
        'sale_order_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_item FOR VALUES IN (%L)',
        'sale_order_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_advance_alloc FOR VALUES IN (%L)',
        'sale_order_advance_alloc_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation FOR VALUES IN (%L)',
        'sale_quotation_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation_item FOR VALUES IN (%L)',
        'sale_quotation_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_bills_balance FOR VALUES IN (%L)',
        'acc_bills_balance_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_bill_adjustment FOR VALUES IN (%L)',
        'acc_bill_adjustment_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_opening_balance FOR VALUES IN (%L)',
        'acc_opening_balance_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_pdc_register FOR VALUES IN (%L)',
        'acc_pdc_register_' || v_suffix, v_year);
END;
$$;

COMMENT ON FUNCTION public.ensure_acc_year_partitions(character(9)) IS
    'Idempotently creates the sale_bill / sale_bill_item / acc_tender_detail / txn_status_log / sale_order / sale_order_item / sale_order_advance_alloc / sale_quotation / sale_quotation_item / acc_bills_balance / acc_bill_adjustment / acc_opening_balance / acc_pdc_register LIST partitions for one accounting year (YYYY-YYYY). Run it whenever a fiscal year is opened.';


-- ───────────────────────────────────────────────────────────────────────────
--  6. Partitions
--
--  Every year on record in fiscal_years, plus -- belt and braces -- any year
--  the parked rows actually carry, so nothing can fail to find a home below.
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_year text;
    BEGIN
        FOR v_year IN
            SELECT DISTINCT btrim(fy_year_name)
            FROM public.fiscal_years
            WHERE is_deleted = false
              AND btrim(fy_year_name) ~ '^[0-9]{4}-[0-9]{4}$'
            UNION
            SELECT DISTINCT btrim(abl_acc_year) FROM accounts.acc_bills_balance_unpart
            UNION
            SELECT DISTINCT btrim(aba_acc_year) FROM accounts.acc_bill_adjustment_unpart
            UNION
            SELECT DISTINCT btrim(op_acc_year)  FROM accounts.acc_opening_balance_unpart
            UNION
            SELECT DISTINCT btrim(apd_acc_year) FROM accounts.acc_pdc_register_unpart
            ORDER BY 1
            LOOP
                IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
                    RAISE EXCEPTION 'accounts tables carry accounting year %, which is not YYYY-YYYY', v_year;
                END IF;
                PERFORM public.ensure_acc_year_partitions(v_year::character(9));
            END LOOP;
    END;
$$;


-- ───────────────────────────────────────────────────────────────────────────
--  7. Move the rows over
--
--  Bills first: the adjustments read their aba_bill_acc_year straight off the
--  bill they settle. abl_pending_amount is generated, so it is neither listed
--  nor copied.
-- ───────────────────────────────────────────────────────────────────────────

INSERT INTO accounts.acc_bills_balance (
    abl_id, abl_company_id, abl_branch_id, abl_tenant_id, abl_acc_year,
    abl_party_id, abl_salesman_id, abl_agent_id, abl_bill_type, abl_voucher_id,
    abl_voucher_line_id, abl_voucher_type_id, abl_voucher_no, abl_doc_date,
    abl_doc_refno, abl_bill_refno, abl_bill_date, abl_due_date, abl_credit_days,
    abl_grace_days, abl_dr_cr, abl_narration, abl_bill_amount, abl_alloc_amount,
    abl_disc_amount, abl_writeoff_amount, abl_is_active, abl_is_deleted,
    abl_sync_date, abl_created_on, abl_created_by, abl_modified_on, abl_modified_by
)
SELECT
    abl_id, abl_company_id, abl_branch_id, abl_tenant_id, abl_acc_year,
    abl_party_id, abl_salesman_id, abl_agent_id, abl_bill_type, abl_voucher_id,
    abl_voucher_line_id, abl_voucher_type_id, abl_voucher_no, abl_doc_date,
    abl_doc_refno, abl_bill_refno, abl_bill_date, abl_due_date, abl_credit_days,
    abl_grace_days, abl_dr_cr, abl_narration, abl_bill_amount, abl_alloc_amount,
    abl_disc_amount, abl_writeoff_amount, abl_is_active, abl_is_deleted,
    abl_sync_date, abl_created_on, abl_created_by, abl_modified_on, abl_modified_by
FROM accounts.acc_bills_balance_unpart;

-- aba_bill_acc_year is a new column, so it is read from the bill rather than
-- copied. A settlement whose bill has vanished could not have existed under
-- fk_aba_bill; the row-count check in section 8 fails the migration if the
-- join drops anything.
INSERT INTO accounts.acc_bill_adjustment (
    aba_id, aba_company_id, aba_branch_id, aba_tenant_id, aba_acc_year,
    aba_bill_id, aba_bill_acc_year, aba_party_id, aba_salesman_id,
    aba_voucher_id, aba_voucher_acc_year, aba_voucher_line_id, aba_voucher_type_id,
    aba_voucher_no, aba_voucher_refno, aba_row_no, aba_adj_date, aba_adj_type,
    aba_dr_cr, aba_alloc_amount, aba_disc_amount, aba_writeoff_amount,
    aba_profit_amount, aba_effect_ledger_id, aba_settlement_mode,
    aba_settlement_ledger_id, aba_is_post_dated, aba_pdc_due_date, aba_narration,
    aba_is_active, aba_is_deleted, aba_sync_date, aba_created_on, aba_created_by,
    aba_modified_on, aba_modified_by
)
SELECT
    old.aba_id, old.aba_company_id, old.aba_branch_id, old.aba_tenant_id, old.aba_acc_year,
    old.aba_bill_id, bill.abl_acc_year, old.aba_party_id, old.aba_salesman_id,
    old.aba_voucher_id, old.aba_voucher_acc_year, old.aba_voucher_line_id, old.aba_voucher_type_id,
    old.aba_voucher_no, old.aba_voucher_refno, old.aba_row_no, old.aba_adj_date, old.aba_adj_type,
    old.aba_dr_cr, old.aba_alloc_amount, old.aba_disc_amount, old.aba_writeoff_amount,
    old.aba_profit_amount, old.aba_effect_ledger_id, old.aba_settlement_mode,
    old.aba_settlement_ledger_id, old.aba_is_post_dated, old.aba_pdc_due_date, old.aba_narration,
    old.aba_is_active, old.aba_is_deleted, old.aba_sync_date, old.aba_created_on, old.aba_created_by,
    old.aba_modified_on, old.aba_modified_by
FROM accounts.acc_bill_adjustment_unpart AS old
JOIN accounts.acc_bills_balance AS bill ON bill.abl_id = old.aba_bill_id;

ALTER TABLE accounts.acc_bill_adjustment
    ADD CONSTRAINT fk_aba_bill FOREIGN KEY (aba_bill_id, aba_bill_acc_year)
        REFERENCES accounts.acc_bills_balance (abl_id, abl_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT;


INSERT INTO accounts.acc_opening_balance (
    op_id, op_company_id, op_branch_id, op_acc_year, op_ledger_id, op_amount,
    op_dr_cr, op_source, op_is_stale, op_stale_since, op_generated_at,
    op_generated_by, op_remarks, op_is_deleted, op_created_at, op_created_by,
    op_modified_at, op_modified_by
)
SELECT
    op_id, op_company_id, op_branch_id, op_acc_year, op_ledger_id, op_amount,
    op_dr_cr, op_source, op_is_stale, op_stale_since, op_generated_at,
    op_generated_by, op_remarks, op_is_deleted, op_created_at, op_created_by,
    op_modified_at, op_modified_by
FROM accounts.acc_opening_balance_unpart;


INSERT INTO accounts.acc_pdc_register (
    apd_id, apd_company_id, apd_branch_id, apd_tenant_id, apd_acc_year,
    apd_tra_type, apd_party_id, apd_salesman_id, apd_instrument_type,
    apd_instrument_no, apd_instrument_date, apd_amount, apd_bank_name,
    apd_bank_branch, apd_ifsc, apd_micr, apd_drawer_name, apd_received_on,
    apd_bank_ledger_id, apd_posting_mode, apd_voucher_id, apd_voucher_acc_year,
    apd_tender_id, apd_status, apd_status_on, apd_status_by, apd_present_count,
    apd_deposit_date, apd_deposit_slip_no, apd_clear_date, apd_clear_voucher_id,
    apd_clear_acc_year, apd_bounce_date, apd_bounce_reason, apd_bounce_charges,
    apd_bounce_voucher_id, apd_bounce_acc_year, apd_charge_voucher_id,
    apd_charge_acc_year, apd_replaced_by_id, apd_cancel_date, apd_cancel_reason,
    apd_remarks, apd_is_active, apd_is_deleted, apd_sync_date, apd_created_on,
    apd_created_by, apd_modified_on, apd_modified_by
)
SELECT
    apd_id, apd_company_id, apd_branch_id, apd_tenant_id, apd_acc_year,
    apd_tra_type, apd_party_id, apd_salesman_id, apd_instrument_type,
    apd_instrument_no, apd_instrument_date, apd_amount, apd_bank_name,
    apd_bank_branch, apd_ifsc, apd_micr, apd_drawer_name, apd_received_on,
    apd_bank_ledger_id, apd_posting_mode, apd_voucher_id, apd_voucher_acc_year,
    apd_tender_id, apd_status, apd_status_on, apd_status_by, apd_present_count,
    apd_deposit_date, apd_deposit_slip_no, apd_clear_date, apd_clear_voucher_id,
    apd_clear_acc_year, apd_bounce_date, apd_bounce_reason, apd_bounce_charges,
    apd_bounce_voucher_id, apd_bounce_acc_year, apd_charge_voucher_id,
    apd_charge_acc_year, apd_replaced_by_id, apd_cancel_date, apd_cancel_reason,
    apd_remarks, apd_is_active, apd_is_deleted, apd_sync_date, apd_created_on,
    apd_created_by, apd_modified_on, apd_modified_by
FROM accounts.acc_pdc_register_unpart;

UPDATE accounts.acc_pdc_register AS replaced
SET apd_replaced_by_acc_year = replacement.apd_acc_year
FROM accounts.acc_pdc_register AS replacement
WHERE replaced.apd_replaced_by_id IS NOT NULL
  AND replacement.apd_id = replaced.apd_replaced_by_id;

-- A replacement that no longer exists cannot get a year, and both
-- ck_apd_replaced_pair and fk_apd_replaced_by would reject the row. Such a
-- pointer was already dangling under the old FK; clear it rather than fail the
-- migration on data that was never valid. ck_apd_replaced then forces the row
-- off the REPLACED status, which is what it now is: not replaced by anything.
UPDATE accounts.acc_pdc_register
SET apd_replaced_by_id = NULL,
    apd_status = CASE WHEN apd_status = 'REPLACED' THEN 'HELD' ELSE apd_status END
WHERE apd_replaced_by_id IS NOT NULL
  AND apd_replaced_by_acc_year IS NULL;

ALTER TABLE accounts.acc_pdc_register
    ADD CONSTRAINT fk_apd_replaced_by
        FOREIGN KEY (apd_replaced_by_id, apd_replaced_by_acc_year)
        REFERENCES accounts.acc_pdc_register (apd_id, apd_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT;


-- ───────────────────────────────────────────────────────────────────────────
--  8. Prove nothing was lost, then drop the parked tables
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_old bigint;
        v_new bigint;
    BEGIN
        SELECT count(*) INTO v_old FROM accounts.acc_bills_balance_unpart;
        SELECT count(*) INTO v_new FROM accounts.acc_bills_balance;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'acc_bills_balance copy lost rows: % -> %', v_old, v_new;
        END IF;

        SELECT count(*) INTO v_old FROM accounts.acc_bill_adjustment_unpart;
        SELECT count(*) INTO v_new FROM accounts.acc_bill_adjustment;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'acc_bill_adjustment copy lost rows: % -> % (a settlement pointing at a bill that does not exist)', v_old, v_new;
        END IF;

        SELECT count(*) INTO v_old FROM accounts.acc_opening_balance_unpart;
        SELECT count(*) INTO v_new FROM accounts.acc_opening_balance;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'acc_opening_balance copy lost rows: % -> %', v_old, v_new;
        END IF;

        SELECT count(*) INTO v_old FROM accounts.acc_pdc_register_unpart;
        SELECT count(*) INTO v_new FROM accounts.acc_pdc_register;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'acc_pdc_register copy lost rows: % -> %', v_old, v_new;
        END IF;
    END;
$$;

DROP TABLE accounts.acc_bill_adjustment_unpart;
DROP TABLE accounts.acc_pdc_register_unpart;
DROP TABLE accounts.acc_opening_balance_unpart;
DROP TABLE accounts.acc_bills_balance_unpart;


-- ───────────────────────────────────────────────────────────────────────────
--  9. Re-point acc_vouchers at the bill's composite key
--
--  av_doc_id is the hard link from a ledger line to the bill it belongs to.
--  The bill is addressed by (abl_id, abl_acc_year) now, so the year comes
--  along -- and it is the BILL's year, not av_acc_year, which is the voucher's.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE accounts.acc_vouchers ADD COLUMN av_doc_acc_year character(9);

UPDATE accounts.acc_vouchers AS v
SET av_doc_acc_year = bill.abl_acc_year
FROM accounts.acc_bills_balance AS bill
WHERE v.av_doc_id IS NOT NULL
  AND bill.abl_id = v.av_doc_id;

-- Same reasoning as the PDC replacement pointer above: a doc id with no bill
-- behind it could not have satisfied the old fk_av_doc.
UPDATE accounts.acc_vouchers
SET av_doc_id = NULL
WHERE av_doc_id IS NOT NULL
  AND av_doc_acc_year IS NULL;

ALTER TABLE accounts.acc_vouchers
    ADD CONSTRAINT ck_av_doc_pair CHECK (
        (av_doc_id IS NULL) = (av_doc_acc_year IS NULL));

ALTER TABLE accounts.acc_vouchers
    ADD CONSTRAINT fk_av_doc FOREIGN KEY (av_doc_id, av_doc_acc_year)
        REFERENCES accounts.acc_bills_balance (abl_id, abl_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT;

COMMENT ON COLUMN accounts.acc_vouchers.av_doc_acc_year IS
    'FY of the bill in av_doc_id — the bill''s own year, not the voucher''s. Second half of fk_av_doc, set exactly when av_doc_id is (ck_av_doc_pair).';
