-- CreateTable
-- public.txn_status_log is the append-only status trail for every
-- transactional document. It is declaratively partitioned by
-- LIST (tsl_acc_year), like sales.sale_bill / sales.sale_bill_item /
-- accounts.acc_tender_detail. Prisma Migrate cannot express PARTITION BY,
-- partition-aware composite primary keys, CHECK constraints, partial indexes
-- or index storage parameters, so this migration is hand-written rather than
-- generated by `prisma migrate dev` (see prisma/public/txnStatusLog.prisma for
-- the model plus documentation of everything that is DB-only).
--
-- The partitions themselves are created at the tail of this file, by extending
-- public.ensure_acc_year_partitions() (added in 20260804112944) to cover this
-- table too — without them every insert fails with "no partition of relation
-- \"txn_status_log\" found for row".

CREATE TABLE IF NOT EXISTS public.txn_status_log
(
    tsl_id                  uuid           NOT NULL DEFAULT uuidv7(),
    tsl_company_id          uuid           NOT NULL,
    tsl_branch_id           uuid           NOT NULL,   -- branch that made the change
    tsl_tenant_id           uuid,
    tsl_acc_year            character(9)   NOT NULL,   -- the SOURCE DOCUMENT's year

    -- ── Which document ───────────────────────────────────────────────────
    tsl_src_module          character varying(20) NOT NULL,
    tsl_src_doc_type        character varying(30) NOT NULL,
    tsl_src_doc_id          uuid           NOT NULL,
    tsl_src_doc_refno       character varying(100),    -- snapshot, so a trail reads alone
    tsl_seq_no              integer        NOT NULL,   -- 1..n within the document

    -- ── What happened ────────────────────────────────────────────────────
    tsl_event               character varying(30) NOT NULL,
    tsl_from_status         character varying(20),     -- NULL on the first row
    tsl_to_status           character varying(20) NOT NULL,
    tsl_changed_on          timestamp(6) with time zone NOT NULL DEFAULT now(),
    tsl_changed_by          uuid           NOT NULL,   -- the approver / canceller
    tsl_remarks             character varying(500),    -- cancel / reject reason lives here

    -- Where it happened, for a device-level audit in an offline chain.
    tsl_device_id           uuid,
    tsl_session_id          uuid,

    -- ── Party notification that accompanied the step ─────────────────────
    tsl_notify_channel      character varying(20),     -- SMS | WHATSAPP | EMAIL | NONE
    tsl_notified_on         timestamp(6) with time zone,
    tsl_notify_ref          character varying(100),    -- gateway message id

    -- ── Audit ────────────────────────────────────────────────────────────
    -- No modified_on/by: a log row is written once and never edited.
    -- Correcting history means appending a row, not rewriting one.
    tsl_is_deleted          boolean NOT NULL DEFAULT false,
    tsl_sync_date           timestamp(6) with time zone,
    tsl_created_on          timestamp(6) with time zone NOT NULL DEFAULT now(),
    tsl_created_by          character varying(50) NOT NULL,

    CONSTRAINT pk_txn_status_log PRIMARY KEY (tsl_id, tsl_acc_year),

    CONSTRAINT fk_tsl_device FOREIGN KEY (tsl_device_id)
        REFERENCES fixed.device_master (dev_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE SET NULL,

    -- Same module vocabulary as accounts.acc_tender_detail's ck_td_src_module.
    CONSTRAINT ck_tsl_src_module CHECK (tsl_src_module::text = ANY (ARRAY[
        'SALES'::text, 'PURCHASE'::text, 'INVENTORY'::text, 'ACCOUNTS'::text,
        'POS'::text, 'SERVICE'::text, 'OTHER'::text])),

    -- The sales five (kept in step with ck_sdc_src_doc_type in 01) plus the
    -- other modules' documents. 'OTHER' is a legitimate value, so a new
    -- document type never forces an ALTER on this table.
    CONSTRAINT ck_tsl_src_doc_type CHECK (tsl_src_doc_type::text = ANY (ARRAY[
        'QUOTATION'::text, 'SALES_ORDER'::text, 'DELIVERY_CHALLAN'::text,
        'SALE_BILL'::text, 'SALE_RETURN'::text,
        'PURCHASE_ORDER'::text, 'PURCHASE_BILL'::text, 'PURCHASE_RETURN'::text,
        'STOCK_TRANSFER'::text, 'STOCK_ADJUSTMENT'::text,
        'RECEIPT'::text, 'PAYMENT'::text, 'JOURNAL'::text,
        'OTHER'::text])),

    CONSTRAINT ck_tsl_seq_no CHECK (tsl_seq_no >= 1),

    -- Shape, not vocabulary — see note 3 in the header. Non-blank, upper case,
    -- no leading/trailing space, so the same status always compares equal.
    CONSTRAINT ck_tsl_event_shape CHECK (
        tsl_event = upper(btrim(tsl_event)) AND length(tsl_event) > 0),
    CONSTRAINT ck_tsl_to_status_shape CHECK (
        tsl_to_status = upper(btrim(tsl_to_status)) AND length(tsl_to_status) > 0),
    CONSTRAINT ck_tsl_from_status_shape CHECK (
        tsl_from_status IS NULL OR
        (tsl_from_status = upper(btrim(tsl_from_status)) AND length(tsl_from_status) > 0)),

    -- A cancellation, closure or rejection must say why — that is the whole
    -- point of the row. This is where sales.sale_order's old
    -- ck_so_cancel_reason went; it no longer needs a duplicate column on any
    -- document header to exist.
    CONSTRAINT ck_tsl_reason_required CHECK (
        tsl_event::text <> ALL (ARRAY['CANCELLED'::text, 'CLOSED'::text,
                                      'REJECTED'::text])
        OR length(btrim(coalesce(tsl_remarks, ''))) > 0),

    CONSTRAINT ck_tsl_notify_channel CHECK (tsl_notify_channel IS NULL OR
        tsl_notify_channel::text = ANY (ARRAY[
            'SMS'::text, 'WHATSAPP'::text, 'EMAIL'::text, 'NONE'::text])),
    CONSTRAINT ck_tsl_notified CHECK (
        tsl_notified_on IS NULL OR tsl_notify_channel IS NOT NULL)
) PARTITION BY LIST (tsl_acc_year);

ALTER TABLE IF EXISTS public.txn_status_log OWNER to postgres;


-- ───────────────────────────────────────────────────────────────────────────
--  Indexes
-- ───────────────────────────────────────────────────────────────────────────

-- One document's trail in order — the History button's exact query, and the
-- uniqueness of the sequence within a document. Intentionally NOT partial:
-- see the note at the tail of this file.
CREATE UNIQUE INDEX IF NOT EXISTS ux_tsl_doc_seq
    ON public.txn_status_log USING btree
    (tsl_src_doc_type, tsl_src_doc_id, tsl_acc_year, tsl_seq_no)
    WITH (fillfactor=100, deduplicate_items=True);

-- Same trail, newest first, when a screen shows only the last few steps.
CREATE INDEX IF NOT EXISTS ix_tsl_doc_recent
    ON public.txn_status_log USING btree
    (tsl_src_doc_type, tsl_src_doc_id, tsl_changed_on DESC)
    WITH (fillfactor=100, deduplicate_items=True);

-- The audit-trail screen: everything one branch did in a period.
CREATE INDEX IF NOT EXISTS ix_tsl_branch_period
    ON public.txn_status_log USING btree
    (tsl_company_id, tsl_branch_id, tsl_acc_year, tsl_changed_on DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE tsl_is_deleted = false;

-- "Who cancelled things this month" / per-user accountability.
CREATE INDEX IF NOT EXISTS ix_tsl_user_event
    ON public.txn_status_log USING btree
    (tsl_changed_by, tsl_event, tsl_changed_on DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE tsl_is_deleted = false;

-- Per-module event reporting (cancellations by module, approval counts).
CREATE INDEX IF NOT EXISTS ix_tsl_module_event
    ON public.txn_status_log USING btree
    (tsl_src_module, tsl_event, tsl_acc_year, tsl_changed_on DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE tsl_is_deleted = false;

-- Notification retry queue: steps that asked for a message and never got one.
CREATE INDEX IF NOT EXISTS ix_tsl_notify_pending
    ON public.txn_status_log USING btree (tsl_changed_on)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE tsl_notify_channel IS NOT NULL
      AND tsl_notify_channel <> 'NONE'
      AND tsl_notified_on IS NULL;


-- ───────────────────────────────────────────────────────────────────────────
--  Partitions
-- ───────────────────────────────────────────────────────────────────────────
-- Extend the year-partition helper added in 20260804112944 so txn_status_log
-- is provisioned alongside sale_bill / sale_bill_item / acc_tender_detail.
-- Still idempotent, still the one call to make when a fiscal year opens:
--
--   SELECT public.ensure_acc_year_partitions('2027-2028');

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character(9))
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    -- The partition bound is a literal, so the year is validated rather than
    -- interpolated blind. char(9) makes 'YYYY-YYYY' the only well-formed value.
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);
END;
$$;

COMMENT ON FUNCTION public.ensure_acc_year_partitions(character(9)) IS
    'Idempotently creates the sale_bill / sale_bill_item / acc_tender_detail / txn_status_log LIST partitions for one accounting year (YYYY-YYYY). Run it whenever a fiscal year is opened.';

-- Bootstrap every accounting year on record. fiscal_years is the authority on
-- which years exist; deleted rows are skipped. Re-running the helper for years
-- that already have their other three partitions is a no-op for those and
-- creates only the new txn_status_log ones.
DO
$$
    DECLARE
        v_year text;
    BEGIN
        FOR v_year IN
            SELECT DISTINCT btrim(fy_year_name)
            FROM public.fiscal_years
            WHERE is_deleted = false
              AND btrim(fy_year_name) ~ '^[0-9]{4}-[0-9]{4}$'
            ORDER BY 1
            LOOP
                PERFORM public.ensure_acc_year_partitions(v_year::character(9));
            END LOOP;
    END;
$$;
