import type { ModuleApiErrorDetail, ModuleApiErrorResponse, ModuleApiSuccessResponse } from 'src/common/types/module-api.types';
export type ItemBatchStockErrorDetail = ModuleApiErrorDetail;
export type ItemBatchStockErrorResponse = ModuleApiErrorResponse<ItemBatchStockErrorDetail>;
export type ItemBatchStockSuccessResponse<T> = ModuleApiSuccessResponse<T, never, never>;

export interface ItemBatchStockPayload {
  ibs_id: string;
  ibs_acc_year: string;
  ibs_company_id: string;
  ibs_branch_id: string;
  ibs_godown_id: string;
  ibs_item_id: string;
  ibs_unit_id: string;
  ibs_batch_id: string;
  ibs_batch_no: string | null;
  ibs_mfg_batch_no: string | null;
  ibs_batch_date: string | null;
  ibs_serial_no: string | null;
  ibs_mfg_date: string | null;
  ibs_expiry_date: string | null;
  ibs_mrp: number;
  ibs_barcode: string | null;
  ibs_stock_bucket: string;
  ibs_opening_qty: number;
  ibs_in_qty: number;
  ibs_out_qty: number;
  ibs_closing_qty: number;
  ibs_opening_free_qty: number;
  ibs_free_in_qty: number;
  ibs_free_out_qty: number;
  ibs_free_closing_qty: number;
  ibs_reserved_qty: number;
  ibs_available_qty: number;
  book_qty: number;
  book_base_qty: number;
  book_free_qty: number;
  book_free_base_qty: number;
  book_reserved_qty: number;
  book_reserved_base_qty: number;
  book_available_qty: number;
  book_available_base_qty: number;
  ibs_opening_avg_rate: number;
  ibs_avg_stock_rate: number;
  ibs_opening_value: number;
  ibs_stock_value: number;
  ibs_last_in_date: string | null;
  ibs_last_out_date: string | null;
  ibs_is_active: boolean;
  ibs_is_deleted: boolean;
  ibs_row_version: string;
  ibs_created_on: string;
  ibs_created_by: string | null;
  ibs_updated_on: string | null;
  ibs_updated_by: string | null;
}
