import type { LedGstPartyRegType, LedObType } from './account-ledger-master-enum';
import type { AccLedgerProfile } from '../../accountsGroup/types/account-group-enum';
import type { LedgerBankAccountPayload } from '../../ledgerBankAccount/types/ledger-bank-account-api.types';
export type { AccountsErrorDetail as AccountLedgerMasterErrorDetail } from 'src/common/types/module-api.types';
export type { AccountsErrorResponse as AccountLedgerMasterErrorResponse } from 'src/common/types/module-api.types';
export type { AccountsSuccessResponse as AccountLedgerMasterSuccessResponse } from 'src/common/types/module-api.types';
export { LedGstPartyRegType, LedObType, BankAccountType } from './account-ledger-master-enum';
export type { LedgerBankAccountPayload } from '../../ledgerBankAccount/types/ledger-bank-account-api.types';
export interface AccountLedgerMasterPayload {
  ledId: string;
  ledCompanyId: string | null;
  ledCompanyName: string | null;
  ledBranchId: string | null;
  ledBranchName: string | null;
  ledGroupId: string;
  ledGroupName: string | null;
  ledGroupLedgerProfile: AccLedgerProfile | null;
  ledName: string;
  ledAlias: string | null;
  ledShort: string | null;
  ledTallyName: string | null;
  ledTallyGroupName: string | null;
  ledTallyGuid: string | null;
  ledTallyMasterId: string | null;
  ledTallyAlterId: string | null;
  ledCategory: string;
  ledLedgerType: string | null;
  ledMailingName: string | null;
  ledIsBillByBill: boolean;
  ledIsCostCenterReq: boolean;
  ledIsInterestApplicable: boolean;
  ledInterestRate: number | null;
  ledContactPerson: string | null;
  ledEmail: string | null;
  ledTel: string | null;
  ledPhone1: string | null;
  ledPhone2: string | null;
  ledWhatsappNo: string | null;
  ledAddr1: string | null;
  ledAddr2: string | null;
  ledAddr3: string | null;
  ledCity: string | null;
  ledDistrict: string | null;
  ledStateName: string | null;
  ledStateCode: string | null;
  ledPin: string | null;
  ledCountry: string | null;
  ledRegionName: string | null;
  ledRegionAddr1: string | null;
  ledRegionAddr2: string | null;
  ledRegionAddr3: string | null;
  ledRegionCity: string | null;
  ledRegionDistrict: string | null;
  ledRegionStateName: string | null;
  ledRegionCountry: string | null;
  ledGstPartyRegType: LedGstPartyRegType | null;
  ledGstinNo: string | null;
  ledPanNo: string | null;
  ledAadharNo: string | null;
  ledEcommerceGstin: string | null;
  ledIsSez: boolean;
  ledTypeOfSupply: string | null;
  ledHsnSac: string | null;
  ledGstRate: number | null;
  ledTaxability: string | null;
  ledGstPartyType: string | null;
  ledTanNo: string | null;
  ledCin: string | null;
  ledUdyamNo: string | null;
  ledMsmeType: string | null;
  ledGstDutyHead: string | null;
  ledTaxRate: number | null;
  ledRoundingMethod: string | null;
  ledRoundingLimit: number | null;
  ledIsTdsApplicable: boolean;
  ledTdsDeducteeType: string | null;
  ledTdsNatureOfPayment: string | null;
  ledIsTcsApplicable: boolean;
  ledObAmount: number;
  ledObType: LedObType;
  ledObAsOn: string | null;
  ledTotalDr: number;
  ledTotalCr: number;
  ledTotalBalance: number;
  ledSortOrder: number | null;
  ledIsActive: boolean;
  ledIsDeleted: boolean;
  ledAllowEdit: boolean;
  ledIsEntry: boolean;
  ledAllowSms: boolean;
  ledRemarks: string | null;
  ledSyncDate: string | null;
  ledCreatedOn: string;
  ledCreatedBy: string | null;
  ledModifiedOn: string;
  ledModifiedBy: string | null;
  ledgerBankAccount: LedgerBankAccountPayload[];
}
