import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SalesErrorFieldDto, SalesErrorResponseDto } from 'src/common/utils/module-response.dto';

export { SalesErrorFieldDto as PromotionLoyaltyPointsErrorFieldDto };
export { SalesErrorResponseDto as PromotionLoyaltyPointsErrorResponseDto };

export class LoyaltySchemeBranchPayloadDto {
  @ApiProperty() lsb_id!: string;
  @ApiProperty() lsb_lsc_id!: string;
  @ApiProperty({ example: 1 }) lsb_slno!: number;
  @ApiProperty() lsb_branch_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'branch_master.br_name' })
  lsb_branch_name!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'br_code, else br_short' })
  lsb_branch_code!: string | null;
  @ApiProperty({ example: false }) lsb_is_exclude!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lsb_notes!: string | null;
  @ApiProperty({ example: true }) lsb_is_active!: boolean;
  @ApiProperty({ example: false }) lsb_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lsb_sync_date!: string | null;
  @ApiProperty() lsb_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) lsb_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsb_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsb_modified_by!: string | null;
}

export class LoyaltySchemePartyPayloadDto {
  @ApiProperty() lsp_id!: string;
  @ApiProperty() lsp_lsc_id!: string;
  @ApiProperty({ example: 1 }) lsp_slno!: number;
  @ApiProperty({ example: 'CUSTOMER_GROUP' }) lsp_kind!: string;
  @ApiProperty() lsp_scope_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  lsp_cust_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  lsp_cust_group_id!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'Wholesale',
    description: 'Display only. cus_name or cgr_name, whichever lsp_kind names.',
  })
  lsp_scope_name!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    description: 'Display only. cus_code or cgr_short.',
  })
  lsp_scope_code!: string | null;
  @ApiProperty({ example: false }) lsp_is_exclude!: boolean;
  @ApiProperty({ example: 1 }) lsp_match_priority!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) lsp_notes!: string | null;
  @ApiProperty({ example: true }) lsp_is_active!: boolean;
  @ApiProperty({ example: false }) lsp_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lsp_sync_date!: string | null;
  @ApiProperty() lsp_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) lsp_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsp_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsp_modified_by!: string | null;
}

export class LoyaltySchemeItemPayloadDto {
  @ApiProperty() lsi_id!: string;
  @ApiProperty() lsi_lsc_id!: string;
  @ApiProperty({ example: 1 }) lsi_slno!: number;
  @ApiProperty({ example: 'ITEM_BRAND' }) lsi_kind!: string;
  @ApiProperty() lsi_scope_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  lsi_item_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  lsi_group_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  lsi_category_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  lsi_brand_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Generated by the database' })
  lsi_section_id!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'Masala Items',
    description:
      'Display only. item_name_en / itg_name / category_name / brand_name / sec_name, ' +
      'whichever lsi_kind names.',
  })
  lsi_scope_name!: string | null;
  @ApiProperty({ example: false }) lsi_is_exclude!: boolean;
  @ApiProperty({ example: 2 }) lsi_factor!: number;
  @ApiProperty({ example: 0 }) lsi_points!: number;
  @ApiProperty({ example: 0 }) lsi_max_points!: number;
  @ApiProperty({ example: 3 }) lsi_match_priority!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) lsi_notes!: string | null;
  @ApiProperty({ example: true }) lsi_is_active!: boolean;
  @ApiProperty({ example: false }) lsi_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lsi_sync_date!: string | null;
  @ApiProperty() lsi_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) lsi_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsi_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsi_modified_by!: string | null;
}

export class LoyaltySchemeSlabPayloadDto {
  @ApiProperty() lss_id!: string;
  @ApiProperty() lss_lsc_id!: string;
  @ApiProperty({ example: 1 }) lss_slno!: number;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    description: 'NULL = the band applies to the whole bill',
  })
  lss_item_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lss_unit_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Display only.' })
  lss_item_name!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Display only.' })
  lss_unit_name!: string | null;
  @ApiProperty({ example: 1000 }) lss_exceeds!: number;
  @ApiPropertyOptional({ type: Number, nullable: true, example: 4999 }) lss_upto!: number | null;
  @ApiProperty({ example: 100 }) lss_each!: number;
  @ApiProperty({ example: 2 }) lss_points!: number;
  @ApiProperty({ example: 1 }) lss_factor!: number;
  @ApiProperty({ example: 0 }) lss_max_points!: number;
  @ApiPropertyOptional({ type: String, nullable: true }) lss_notes!: string | null;
  @ApiProperty({ example: true }) lss_is_active!: boolean;
  @ApiProperty({ example: false }) lss_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lss_sync_date!: string | null;
  @ApiProperty() lss_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) lss_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lss_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lss_modified_by!: string | null;
}

export class LoyaltySchemeGiftPayloadDto {
  @ApiProperty() lsg_id!: string;
  @ApiProperty() lsg_lsc_id!: string;
  @ApiProperty({ example: 1 }) lsg_slno!: number;
  @ApiProperty() lsg_item_id!: string;
  @ApiProperty({ description: 'item_unit_conversion.iuc_id, as on a bill line' })
  lsg_unit_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Display only.' })
  lsg_item_name!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'Display only.' })
  lsg_unit_name!: string | null;
  @ApiProperty({ example: 1 }) lsg_item_qty!: number;
  @ApiProperty({ example: 500 }) lsg_redeem_points!: number;
  @ApiProperty({ example: false }) lsg_repeat!: boolean;
  @ApiProperty({ example: 0 }) lsg_max_qty_per_bill!: number;
  @ApiProperty({ example: true }) lsg_stock_check!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true, example: '2025-10-01' })
  lsg_valid_from!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, example: '2025-10-31' })
  lsg_valid_upto!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsg_notes!: string | null;
  @ApiProperty({ example: true }) lsg_is_active!: boolean;
  @ApiProperty({ example: false }) lsg_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lsg_sync_date!: string | null;
  @ApiProperty() lsg_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) lsg_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsg_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsg_modified_by!: string | null;
}

/**
 * The campaign header on its own — every scalar column of loyalty_scheme and
 * not one child row. LoyaltySchemePayloadDto adds the five grids on top of it.
 */
export class LoyaltySchemeSummaryPayloadDto {
  @ApiProperty() lsc_id!: string;
  @ApiProperty() lsc_comp_id!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_branch_id!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, description: 'company.comp_name' })
  lsc_comp_name!: string | null;
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    description: 'branch_master.br_name — null when the scheme is company-wide',
  })
  lsc_branch_name!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_tenant_id!: string | null;
  @ApiProperty({ example: 'DIWALI25' }) lsc_code!: string;
  @ApiProperty({ example: 'Diwali 2025' }) lsc_name!: string;
  @ApiProperty({ example: 'BOTH' }) lsc_type!: string;
  @ApiProperty({ example: 'DRAFT' }) lsc_status!: string;
  @ApiProperty({ example: 1 }) lsc_priority!: number;
  @ApiProperty({ example: true }) lsc_auto_apply!: boolean;
  @ApiProperty({ example: 'BILL_AMOUNT' }) lsc_apply_on!: string;
  @ApiProperty({ example: 'NET_AMOUNT' }) lsc_calc_on_amount_type!: string;
  @ApiProperty({ example: false }) lsc_include_tax!: boolean;
  @ApiProperty({ example: 'ALL' }) lsc_bill_type!: string;
  @ApiProperty({ example: 0 }) lsc_min_bill_amount!: number;
  @ApiProperty({ example: 0 }) lsc_max_earn_points!: number;
  @ApiProperty({ example: true }) lsc_earn_on_discounted!: boolean;
  @ApiProperty({ example: false }) lsc_earn_on_charges!: boolean;
  @ApiProperty({ example: false }) lsc_earn_with_redeem!: boolean;
  @ApiProperty({ example: 'FLOOR' }) lsc_rounding_method!: string;
  @ApiProperty({ example: 2 }) lsc_points_decimals!: number;
  @ApiProperty({ example: 'ALL' }) lsc_branch_scope!: string;
  @ApiProperty({ example: 'ALL' }) lsc_cust_scope!: string;
  @ApiProperty({ example: 'ALL' }) lsc_item_scope!: string;
  @ApiPropertyOptional({ type: Number, nullable: true }) lsc_price_level_id!: number | null;
  @ApiProperty({ example: 'COMPANY' }) lsc_pool_mode!: string;
  @ApiProperty({ example: true }) lsc_allow_cross_branch_redeem!: boolean;
  @ApiProperty({ example: false }) lsc_allow_point_redeem!: boolean;
  @ApiProperty({ example: false }) lsc_allow_gift_redeem!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_redeem_tender_id!: string | null;
  @ApiProperty({ example: 0.25 }) lsc_redeem_value_per_point!: number;
  @ApiProperty({ example: 0 }) lsc_min_redeem_points!: number;
  @ApiProperty({ example: 0 }) lsc_max_redeem_points!: number;
  @ApiProperty({ example: 100 }) lsc_max_redeem_perc!: number;
  @ApiProperty({ example: 0 }) lsc_redeem_min_bill_amount!: number;
  @ApiProperty({ example: 0 }) lsc_redeem_multiple!: number;
  @ApiProperty({ example: 'EARN_DATE' }) lsc_expiry_basis!: string;
  @ApiProperty({ example: 365 }) lsc_points_valid_days!: number;
  @ApiProperty({ example: 0 }) lsc_activation_days!: number;
  @ApiProperty({ example: 'REVERSE' }) lsc_return_mode!: string;
  @ApiProperty({ example: '2025-10-01' }) lsc_start_date!: string;
  @ApiProperty({ example: '2025-10-31' }) lsc_end_date!: string;
  @ApiPropertyOptional({ type: String, nullable: true, example: '22:22:00' })
  lsc_valid_from_time!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, example: '04:44:00' })
  lsc_valid_to_time!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true, example: 'MON,TUE' })
  lsc_valid_weekdays!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_remarks!: string | null;
  @ApiProperty({ example: true }) lsc_is_active!: boolean;
  @ApiProperty({ example: false }) lsc_is_deleted!: boolean;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_sync_date!: string | null;
  @ApiProperty() lsc_created_on!: string;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_created_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_modified_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_modified_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_approved_on!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) lsc_approved_by!: string | null;
}

/** The header plus its five grids — what POST /create and GET /get answer with. */
export class LoyaltySchemePayloadDto extends LoyaltySchemeSummaryPayloadDto {
  @ApiProperty({ type: [LoyaltySchemeBranchPayloadDto] })
  branches!: LoyaltySchemeBranchPayloadDto[];

  @ApiProperty({ type: [LoyaltySchemePartyPayloadDto] })
  parties!: LoyaltySchemePartyPayloadDto[];

  @ApiProperty({ type: [LoyaltySchemeItemPayloadDto] })
  items!: LoyaltySchemeItemPayloadDto[];

  @ApiProperty({ type: [LoyaltySchemeSlabPayloadDto] })
  slabs!: LoyaltySchemeSlabPayloadDto[];

  @ApiProperty({ type: [LoyaltySchemeGiftPayloadDto] })
  gifts!: LoyaltySchemeGiftPayloadDto[];
}

export class LoyaltySchemeDeleteResultDto {
  @ApiProperty({ example: true }) deleted!: true;
  @ApiProperty() lsc_id!: string;
}

export class LoyaltySchemeSuccessSingleDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Loyalty scheme fetched successfully' }) message!: string;
  @ApiProperty({ type: LoyaltySchemePayloadDto }) data!: LoyaltySchemePayloadDto;
}

export class LoyaltySchemeSuccessListDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Loyalty schemes fetched successfully' }) message!: string;
  @ApiProperty({ type: [LoyaltySchemePayloadDto] }) data!: LoyaltySchemePayloadDto[];
}

export class LoyaltySchemeSuccessDeleteDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Loyalty scheme deleted successfully' }) message!: string;
  @ApiProperty({ type: LoyaltySchemeDeleteResultDto }) data!: LoyaltySchemeDeleteResultDto;
}

export class LoyaltySchemeEligibilityPayloadDto {
  @ApiProperty() lsc_id!: string;
  @ApiProperty() cus_id!: string;
  @ApiProperty({ example: true }) qualifies!: boolean;
  @ApiProperty({
    enum: ['ALL', 'RULE', 'NO_RULE'],
    description:
      'ALL — the scheme covers everyone, no party row was consulted. RULE — a party row decided ' +
      'it. NO_RULE — the scheme is scoped to a LIST and nothing on it touches this customer.',
  })
  decided_by!: 'ALL' | 'RULE' | 'NO_RULE';
  @ApiPropertyOptional({
    type: String,
    nullable: true,
    example: 'CUSTOMER_GROUP',
    description: 'lsp_kind of the row that decided it',
  })
  matched_by!: string | null;
  @ApiPropertyOptional({ type: String, nullable: true }) matched_row_id!: string | null;
  @ApiPropertyOptional({ type: Number, nullable: true }) match_priority!: number | null;
  @ApiPropertyOptional({ type: Boolean, nullable: true }) is_exclude!: boolean | null;
  @ApiProperty({ example: 'NO — carved out by the CUSTOMER rule' }) reason!: string;
}

export class LoyaltySchemeEligibilitySuccessDto {
  @ApiProperty({ example: true }) success!: true;
  @ApiProperty({ example: 'Loyalty scheme eligibility evaluated successfully' }) message!: string;
  @ApiProperty({ type: LoyaltySchemeEligibilityPayloadDto })
  data!: LoyaltySchemeEligibilityPayloadDto;
}
