import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { ValidateIf } from 'class-validator';
import {
  NullableString,
  OptionalInteger,
  OptionalNumber,
  OptionalQueryBoolean,
  OptionalTrimmedString,
  OptionalUuid,
  RequiredUuid,
  TrimmedString,
} from './loyalty-dto.helpers';
import { LSI_KINDS } from '../utils/loyalty.utils';

/**
 * One row of the `items` array on POST /create.
 *
 * Read only when the header says lsc_item_scope = 'LIST'. The array is what
 * makes "double points on own-brand, but nothing on tobacco" ONE scheme: an
 * ITEM_BRAND include row and an ITEM_CATEGORY exclude row, together — something
 * the predecessor table could not express at all.
 *
 * The five FK carriers (lsi_item_id, lsi_group_id, lsi_category_id,
 * lsi_brand_id, lsi_section_id) are generated by Postgres from lsi_kind +
 * lsi_scope_id and are not accepted here.
 *
 * There is deliberately no unit column: this row scales what a slab computed,
 * and the slab is where a unit belongs.
 */
export class LoyaltySchemeItemRowDto {
  @ApiPropertyOptional({ description: 'Present = update that row, absent = insert a new one' })
  @OptionalUuid()
  lsi_id?: string;

  @ApiPropertyOptional({ minimum: 1, default: 1 })
  @OptionalInteger(1)
  lsi_slno?: number;

  @ApiProperty({ enum: LSI_KINDS, example: 'ITEM_BRAND' })
  @ValidateIf((o: LoyaltySchemeItemRowDto) => o.lsi_id === undefined || o.lsi_kind !== undefined)
  @TrimmedString(20)
  lsi_kind?: string;

  @ApiProperty({
    example: '01963d86-caf0-7b26-89f0-58ac380a2d5e',
    description: 'The item, group, category, brand or section — whichever lsi_kind names',
  })
  @ValidateIf(
    (o: LoyaltySchemeItemRowDto) => o.lsi_id === undefined || o.lsi_scope_id !== undefined,
  )
  @RequiredUuid()
  lsi_scope_id?: string;

  @ApiPropertyOptional({
    default: false,
    description: 'Earns nothing regardless of any broader rule. Forbids any rate on the same row.',
  })
  @OptionalQueryBoolean()
  lsi_is_exclude?: boolean;

  @ApiPropertyOptional({
    default: 1,
    description: 'Multiplies whatever the slab computed for the line. 2.0 = double points.',
  })
  @OptionalNumber(0)
  lsi_factor?: number;

  @ApiPropertyOptional({
    minimum: 0,
    default: 0,
    description: 'Non-zero REPLACES the slab result outright instead of scaling it',
  })
  @OptionalNumber(0)
  lsi_points?: number;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: '0 = uncapped, per line' })
  @OptionalNumber(0)
  lsi_max_points?: number;

  @ApiPropertyOptional({
    minimum: 0,
    maximum: 9,
    description:
      'Most specific wins. Defaults by kind when omitted: ITEM 4, ITEM_BRAND 3, ' +
      'ITEM_CATEGORY 2, ITEM_SECTION 1, ITEM_GROUP 0.',
  })
  @OptionalInteger(0, 9)
  lsi_match_priority?: number;

  @ApiPropertyOptional({ type: String, nullable: true })
  @NullableString(65535)
  lsi_notes?: string | null;

  @ApiPropertyOptional({ default: true })
  @OptionalQueryBoolean()
  lsi_is_active?: boolean;

  @ApiPropertyOptional({ maxLength: 50 })
  @OptionalTrimmedString(50)
  lsi_created_by?: string;

  @ApiPropertyOptional({ maxLength: 50 })
  @OptionalTrimmedString(50)
  lsi_modified_by?: string;
}
