import type { LedgerBankAccountPayload } from '../../../accountsModule/accountLedgerMasters/types/account-ledger-master-api.types';
export type { PurchaseErrorDetail as SupplierErrorDetail } from 'src/common/types/module-api.types';
export type { PurchaseErrorResponse as SupplierErrorResponse } from 'src/common/types/module-api.types';
export type { PurchaseSuccessResponse as SupplierSuccessResponse } from 'src/common/types/module-api.types';
export type { LedgerBankAccountPayload } from '../../../accountsModule/accountLedgerMasters/types/account-ledger-master-api.types';
export interface SupplierPayload {
  supId: string;
  supCompanyId: string | null;
  supCompanyName?: string | null;
  supBranchId: string | null;
  supBranchName?: string | null;
  supGroupId: string;
  supGroupName?: string | null;
  supPurchaseType: string;
  supName: string;
  supShort: string | null;
  supAddr1: string | null;
  supAddr2: string | null;
  supAddr3: string | null;
  supCity: string | null;
  supDistrict: string | null;
  supStateName: string;
  supCountry: string | null;
  supPincode: string | null;
  supTel: string | null;
  supPhone: string | null;
  supMailId: string | null;
  supWhatsappNo: string | null;
  supWebsiteAddress: string | null;
  supChequePreName: string | null;
  supNotes: string | null;
  supCreditDays: number;
  supCashDiscPerc: number;
  supCollectionDays: number[];
  supGstNo: string | null;
  supStateCode: string;
  supPanNo: string | null;
  supGstType: string;
  supSupCst: string | null;
  supDrugLiscenceNo: string | null;
  supRegionName: string | null;
  supRegionAddr1: string | null;
  supRegionAddr2: string | null;
  supRegionAddr3: string | null;
  supRegionCity: string | null;
  supRegionDistrict: string | null;
  supRegionStateName: string | null;
  supRegionCountry: string | null;
  supBilledDate: string | null;
  supSortOrder: number | null;
  supIsActive: boolean;
  supIsDeleted: boolean;
  supSyncDate: string | null;
  supCreatedOn: string;
  supCreatedBy: string | null;
  supModifiedOn: string;
  supModifiedBy: string | null;
  ledgerBankAccount: LedgerBankAccountPayload[];
}
