-- CreateTable
-- accounts.acc_tender_detail is declaratively partitioned by LIST (td_acc_year),
-- like sales.sale_bill / sales.sale_bill_item. Prisma Migrate cannot express
-- PARTITION BY, composite partition-aware primary keys, or CHECK constraints,
-- so this migration is hand-written rather than generated by
-- `prisma migrate dev` (see prisma/accounts/accountTenderDetail.prisma for the
-- model + documentation of what's DB-only). Partitions (e.g.
-- acc_tender_detail_2026_2027) must be created separately, per accounting
-- year, before rows can be inserted into the parent table.
--
-- Note: fk_td_voucher was changed from the originally spec'd composite FK
-- (td_voucher_id, td_acc_year) -> acc_voucher_header(avh_voucher_id,
-- avh_acc_year) to a single-column FK on avh_voucher_id alone.
-- acc_voucher_header has no unique constraint matching that exact 2-column
-- pair (only a PK on avh_voucher_id alone, and a 4-column tenant-scoped
-- unique constraint), so the composite FK cannot be created. Every other FK
-- to acc_voucher_header in this codebase (acc_voucher_bills, acc_vouchers,
-- acc_voucher_cheques, opening_stock_header, ...) references avh_voucher_id
-- alone for the same reason.

CREATE TABLE IF NOT EXISTS accounts.acc_tender_detail
(
    td_id                 uuid           NOT NULL DEFAULT uuidv7(),
    td_company_id         uuid           NOT NULL,
    td_branch_id          uuid           NOT NULL,
    td_tenant_id          uuid,
    td_acc_year           character(9)   NOT NULL,

    -- The document this money belongs to (works for DRAFT docs too).
    td_src_module         character varying(20) NOT NULL,
    td_src_doc_type       character varying(30) NOT NULL,
    td_src_doc_id         uuid           NOT NULL,
    td_row_no             integer        NOT NULL,
    td_doc_date           date           NOT NULL,          -- snapshot, src doc is polymorphic
    td_party_ledger_id    uuid           NOT NULL,           -- customer/supplier snapshot

    -- Filled at posting; same accounting year as the tender's document.
    td_voucher_id         uuid,

    -- ── What was tendered ────────────────────────────────────────────────
    td_tender_id          uuid           NOT NULL,
    td_tender_type_id     integer        NOT NULL,           -- snapshot (is_cash reports)
    td_tender_ledger_id   uuid           NOT NULL,           -- snapshot; master may allow override
    td_dr_cr              character(2)   NOT NULL,
    td_amount             numeric(18,2)  NOT NULL DEFAULT 0,
    td_surcharge_perc     numeric(6,3)   NOT NULL DEFAULT 0,
    td_surcharge_amt      numeric(18,2)  NOT NULL DEFAULT 0,
    td_total_amt          numeric(18,2)  NOT NULL DEFAULT 0,

    -- ── Cash over-tender / change ────────────────────────────────────────
    td_received_amt       numeric(18,2)  NOT NULL DEFAULT 0,  -- what hit the drawer
    td_change_amt         numeric(18,2)  NOT NULL DEFAULT 0,  -- change handed back

    -- ── Non-cash equivalents (loyalty / voucher) ─────────────────────────
    td_units_used         numeric(18,4)  NOT NULL DEFAULT 0,  -- points / voucher units
    td_conversion_rate    numeric(10,4)  NOT NULL DEFAULT 1,  -- units -> INR

    -- ── Instrument / gateway reference (day reconciliation) ──────────────
    td_ref_no             character varying(100),   -- UPI txn id / card RRN / cheque no
    td_auth_code          character varying(50),
    td_card_last4         character varying(4),
    td_bank_name          character varying(150),
    td_payer_vpa          character varying(100),   -- UPI payer handle
    td_instrument_date    date,                     -- cheque date (PDC)
    td_is_pdc             boolean NOT NULL DEFAULT false,

    -- ── Settlement ───────────────────────────────────────────────────────
    td_settle_status      character varying(20) NOT NULL DEFAULT 'NA',
    td_settle_ledger_id   uuid,                     -- clearing ledger snapshot
    td_expected_settle_on date,                     -- doc_date + tnd_settlement_days
    td_settled_on         date,
    td_settle_amount      numeric(18,2),            -- net credited by acquirer
    td_mdr_amt            numeric(18,2)  NOT NULL DEFAULT 0,
    td_settle_ref_no      character varying(100),   -- bank batch / UTR
    td_settle_voucher_id  uuid,                     -- JV that moved clearing -> bank

    -- ── Where / who ──────────────────────────────────────────────────────
    td_session_id         uuid,
    td_device_id          character varying(250),
    td_user_id            uuid           NOT NULL,
    td_notes              character varying(250),

    -- ── Audit ────────────────────────────────────────────────────────────
    td_is_deleted         boolean NOT NULL DEFAULT false,
    td_sync_date          timestamp(6) with time zone,
    td_created_on         timestamp(6) with time zone NOT NULL DEFAULT now(),
    td_created_by         character varying(50) NOT NULL,
    td_modified_on        timestamp(6) with time zone,
    td_modified_by        character varying(50),

    CONSTRAINT pk_acc_tender_detail PRIMARY KEY (td_id, td_acc_year),

    CONSTRAINT fk_td_tender FOREIGN KEY (td_tender_id)
        REFERENCES accounts.acc_tender_master (tnd_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_td_tender_type FOREIGN KEY (td_tender_type_id)
        REFERENCES accounts.acc_tender_types (ttm_type_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_td_ledger FOREIGN KEY (td_tender_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_td_settle_ledger FOREIGN KEY (td_settle_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_td_party_ledger FOREIGN KEY (td_party_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_td_voucher FOREIGN KEY (td_voucher_id)
        REFERENCES accounts.acc_voucher_header (avh_voucher_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT ck_td_src_module CHECK (td_src_module::text = ANY (ARRAY[
        'SALES'::text, 'ACCOUNTS'::text, 'POS'::text, 'SERVICE'::text, 'OTHER'::text])),
    CONSTRAINT ck_td_src_doc_type CHECK (td_src_doc_type::text = ANY (ARRAY[
        'SALES_ORDER'::text, 'SALE_BILL'::text, 'SALE_RETURN'::text,
        'RECEIPT'::text, 'PAYMENT'::text, 'OTHER'::text])),
    CONSTRAINT ck_td_dr_cr CHECK (td_dr_cr = ANY (ARRAY['DR'::bpchar, 'CR'::bpchar])),
    CONSTRAINT ck_td_settle_status CHECK (td_settle_status::text = ANY (ARRAY[
        'NA'::text, 'PENDING'::text, 'SETTLED'::text, 'PARTIAL'::text, 'FAILED'::text])),
    CONSTRAINT ck_td_amounts CHECK (
        td_amount >= 0 AND td_surcharge_amt >= 0 AND td_total_amt >= 0),
    CONSTRAINT ck_td_row_no CHECK (td_row_no >= 1),

    CONSTRAINT ck_td_total_amt CHECK (
        td_total_amt = round(td_amount + td_surcharge_amt, 2)),
    CONSTRAINT ck_td_cash_change CHECK (
        td_received_amt >= 0 AND td_change_amt >= 0
        AND (td_received_amt = 0 OR td_received_amt >= td_change_amt)),
    CONSTRAINT ck_td_units CHECK (
        td_units_used >= 0 AND td_conversion_rate > 0),
    CONSTRAINT ck_td_settle_amount CHECK (
        td_settle_amount IS NULL OR td_settle_amount >= 0),
    CONSTRAINT ck_td_mdr CHECK (td_mdr_amt >= 0),
    CONSTRAINT ck_td_settled_on CHECK (
        (td_settle_status <> 'SETTLED') OR td_settled_on IS NOT NULL),
    CONSTRAINT ck_td_pdc CHECK (
        td_is_pdc = false OR td_instrument_date IS NOT NULL),
    CONSTRAINT ck_td_card_last4 CHECK (
        td_card_last4 IS NULL OR td_card_last4 ~ '^[0-9]{4}$')
) PARTITION BY LIST (td_acc_year);
