-- ═══════════════════════════════════════════════════════════════════════════
--  accounts.acc_ledger_map  —  fill it, all 22 roles
--
--  ── Why this exists ──────────────────────────────────────────────────────
--  accounts.acc_ledger_role has 22 roles. accounts.acc_ledger_map has ZERO
--  rows. So resolveLedgerForRole() (ledger-map.helper.ts) answers null for
--  every role, and every posting path that asks for a ledger by role gets
--  nothing back:
--
--      · the sale bill's revenue, tax, round-off and discount legs
--      · the receipt / payment / cheque flows
--      · the voucher register
--      · the opening-balance screen's plug (OPENING_DIFFERENCE) and
--        carry-forward's profit destination (RETAINED_EARNINGS), which
--        20260915090000 added roles for and nothing has ever answered
--
--  ── Why the work is in a FUNCTION and not in this file's body ────────────
--  Migrations run BEFORE seeds (`db:deploy` = migrate deploy && seed:run),
--  and the chart of accounts is a SEED — prisma/seed/Account_Groups.sql. On a
--  fresh database, and on the shadow database `migrate dev` replays into,
--  accounts.acc_group_master is empty while this migration runs, so there is
--  nothing here to hang a ledger under. A migration that inserted directly
--  would either fail the replay or quietly map nothing.
--
--  So the mapping ships as two functions, and BOTH callers use them:
--
--      accounts.fn_ledger_map_catalogue()  role -> ledger name, and how to
--                                          create that ledger if it is absent.
--                                          The 22-row configuration itself.
--      accounts.fn_seed_ledger_map()       applies the catalogue. Idempotent.
--
--  This file calls it once, in "skip if the chart is not there yet" mode, so
--  an existing database is mapped at migrate time and a fresh one is not
--  failed. prisma/seed/Acc_Ledger_Map.sql calls it in strict mode on every
--  boot, straight after Account_Groups.sql — which is what actually maps a
--  fresh database, and what re-asserts the map on every deploy afterwards.
--
--  Changing a mapping means CREATE OR REPLACE on the catalogue in a NEW
--  migration, then letting the seed re-run. Do not edit this file once it has
--  been applied — see §5 at the bottom for what is deliberately not here.
--
--  ── The one thing to understand before reading the catalogue ─────────────
--  There is NO TRIGGER on acc_ledger_map. 20260911070000's header promises
--  accounts.fn_check_role_ledger and a guard built on it; neither was ever
--  written (the 20260911071000 folder it names does not exist, and pg_proc
--  has no such function). The check lives in TypeScript —
--  ledger-role.helper.ts — which nothing reaches when rows arrive by SQL.
--  So nothing in the database stops SALES being pointed at a bank account.
--
--  fn_seed_ledger_map therefore checks the fit ITSELF, against each role's own
--  alr_want_type / alr_want_duty / alr_want_nature, and a pair that does not
--  fit ABORTS rather than being skipped: a silently skipped role is exactly
--  the null that caused this. If the guard is ever added those checks become
--  redundant, which is the right direction for them to become wrong in.
--
--  ── Scope columns ────────────────────────────────────────────────────────
--  alm_company_id / alm_branch_id are left NULL on every row. The chart is
--  shared, so a role has one answer for the whole business; those columns
--  exist so a single company or branch could be given its own ledger later
--  without a migration, and the resolver already prefers the more specific
--  row. alm_supply_nature is NULL too — set it only if the chart ever
--  separates 'Local Sales' from 'Interstate Sales'. This one does not.
--
--  PostgreSQL 18.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
--  1 · THE CATALOGUE — the configuration, and the only place to edit it
--
--  One row per role in accounts.acc_ledger_role. Each names the ledger that
--  role posts to, plus what that ledger must look like if it has to be
--  created: its led_ledger_type, its led_gst_duty_head, and the global
--  account group it hangs under.
--
--  Ten of these ledgers already exist on a chart that has been in use — Sales
--  Account, Sales Return, the four Output taxes, Round Off, Discount Allowed,
--  Bad Debts Written Off, Customer Advances Received. They are listed anyway,
--  with the shape they already have, so that a FRESH database gets them too;
--  fn_seed_ledger_map matches by name and leaves an existing one untouched.
--  The other twelve do not exist anywhere yet.
--
--  ── Why the tax ledgers sit under a Liabilities group ────────────────────
--  Input CGST is economically a receivable, but Tally puts both sides under
--  Duties & Taxes and so does this chart — and the role does not care: the tax
--  roles set alr_want_duty and alr_want_type and leave alr_want_nature NULL,
--  precisely so the chart may place them where the accountant expects.
--
--  ── The two FUTURE roles ─────────────────────────────────────────────────
--  TCS_PAYABLE and TDS_PAYABLE are in acc_ledger_role's FUTURE group and
--  nothing posts to them yet. They are here anyway, because a role with a
--  ledger costs nothing and the alternative is discovering the gap on the day
--  TDS arrives. The cost is two ledgers sitting at zero in the trial balance.
--  If that is unwanted, drop their two rows — this is the only place either
--  name appears — and fn_seed_ledger_map will then refuse the pair as an
--  uncovered role, which is the loud failure that decision deserves.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION accounts.fn_ledger_map_catalogue()
RETURNS TABLE (
    role_code   text,   -- accounts.acc_ledger_role.alr_role
    ledger_name text,   -- accounts.acc_ledger_master.led_name, global
    ledger_type text,   -- led_ledger_type      (chk_led_ledger_type)
    duty_head   text,   -- led_gst_duty_head    (chk_led_gst_duty_head)
    group_name  text    -- acc_group_master.acc_group_name, global
)
LANGUAGE sql
IMMUTABLE
AS $cat$
    SELECT *
      FROM (VALUES
        -- role                 ledger name                       type        duty head         group
        -- ── REVENUE ────────────────────────────────────────────────────────
        ('SALES',              'Sales Account',                  'INCOME',   NULL,             'Sales Accounts'),
        ('SALES_RETURN',       'Sales Return',                   'INCOME',   NULL,             'Sales Accounts'),
        -- ── OUTPUT_TAX ─────────────────────────────────────────────────────
        ('OUTPUT_CGST',        'Output CGST',                    'TAX',      'Central Tax',    'Duties & Taxes'),
        ('OUTPUT_SGST',        'Output SGST',                    'TAX',      'State Tax',      'Duties & Taxes'),
        ('OUTPUT_IGST',        'Output IGST',                    'TAX',      'Integrated Tax', 'Duties & Taxes'),
        ('OUTPUT_CESS',        'Output Cess',                    'TAX',      'Cess',           'Duties & Taxes'),
        ('OUTPUT_ACESS',       'Output State Cess',              'TAX',      'State Cess',     'Duties & Taxes'),
        -- ── PURCHASE ───────────────────────────────────────────────────────
        ('PURCHASE',           'Purchase Account',               'EXPENSE',  NULL,             'Purchase Accounts'),
        ('PURCHASE_RETURN',    'Purchase Return',                'EXPENSE',  NULL,             'Purchase Accounts'),
        -- ── INPUT_TAX ──────────────────────────────────────────────────────
        ('INPUT_CGST',         'Input CGST',                     'TAX',      'Central Tax',    'Duties & Taxes'),
        ('INPUT_SGST',         'Input SGST',                     'TAX',      'State Tax',      'Duties & Taxes'),
        ('INPUT_IGST',         'Input IGST',                     'TAX',      'Integrated Tax', 'Duties & Taxes'),
        ('INPUT_CESS',         'Input Cess',                     'TAX',      'Cess',           'Duties & Taxes'),
        ('INPUT_ACESS',        'Input State Cess',               'TAX',      'State Cess',     'Duties & Taxes'),
        -- ── SHARED ─────────────────────────────────────────────────────────
        ('ROUND_OFF',          'Round Off',                      'ROUNDOFF', NULL,             'Indirect Expenses'),
        ('DISCOUNT_ALLOWED',   'Discount Allowed',               'DISCOUNT', NULL,             'Indirect Expenses'),
        ('WRITE_OFF',          'Bad Debts Written Off',          'EXPENSE',  NULL,             'Indirect Expenses'),
        ('ADVANCE_RECEIVED',   'Customer Advances Received',     'GENERAL',  NULL,             'Current Liabilities'),
        -- The suspense the opening-balance screen offers as its plug. A
        -- Suspense A/c group is exactly what it is: a balance that has not
        -- yet been explained, shown as a row rather than hidden in a total.
        ('OPENING_DIFFERENCE', 'Difference in Opening Balances', 'GENERAL',  NULL,             'Suspense A/c'),
        -- Where a closed year's profit lands when carry-forward opens the
        -- next one. Reserves & Surplus, not Capital Account: it is accumulated
        -- result, not what the proprietor put in.
        ('RETAINED_EARNINGS',  'Retained Earnings',              'GENERAL',  NULL,             'Reserves & Surplus'),
        -- ── FUTURE — nothing posts to these yet ────────────────────────────
        ('TCS_PAYABLE',        'TCS Payable',                    'TAX',      NULL,             'Duties & Taxes'),
        ('TDS_PAYABLE',        'TDS Payable',                    'TAX',      NULL,             'Duties & Taxes')
      ) AS v(role_code, ledger_name, ledger_type, duty_head, group_name);
$cat$;

COMMENT ON FUNCTION accounts.fn_ledger_map_catalogue() IS
    'Role -> ledger, one row per accounts.acc_ledger_role, with the shape each ledger must have if it does not exist yet. The configuration accounts.fn_seed_ledger_map() applies; edit it with CREATE OR REPLACE in a new migration.';


-- ═══════════════════════════════════════════════════════════════════════════
--  2 · THE SEEDER — applies the catalogue, re-runnably
--
--  Run it twice, get the same rows. Everything resolves BY NAME against the
--  GLOBAL chart (company IS NULL), so no uuids are carried between
--  environments.
--
--  p_skip_if_no_chart = true  is for the call at the bottom of this file, and
--  for any other caller that may run before prisma/seed/Account_Groups.sql
--  has ever run. It turns ONE condition — "the account groups the catalogue
--  names are not there yet" — from an exception into a no-op, and nothing
--  else. A ledger that does not fit its role still aborts either way: that is
--  not "not ready", it is wrong.
--
--  ── Why NOT EXISTS and not ON CONFLICT, in §2.2 ──────────────────────────
--  acc_ledger_master's unique index is (led_company_id, led_name) — a PLAIN
--  unique, so a NULL company means NULL <> NULL and two global ledgers MAY
--  share a name. There is no constraint for ON CONFLICT to target and a second
--  run would silently create duplicates. (The chart already carries five
--  ledgers called 'opening stock' for exactly this reason.) NOT EXISTS is what
--  makes this safe to call on every boot.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION accounts.fn_seed_ledger_map(
    p_skip_if_no_chart boolean DEFAULT false,
    p_created_by       varchar DEFAULT 'system')
RETURNS text
LANGUAGE plpgsql
AS $fn$
DECLARE
    v_bad          text;
    v_new_ledgers  int := 0;
    v_new_maps     int := 0;
    v_roles        int;
BEGIN
    -- ── 2.1 · PREFLIGHT ──────────────────────────────────────────────────
    --  Everything below resolves by name. A missing prerequisite would
    --  otherwise show up as a role that quietly stayed unmapped, which is the
    --  failure this whole file is fixing.
    SELECT count(*) INTO v_roles FROM accounts.acc_ledger_role;
    IF v_roles = 0 THEN
        RAISE EXCEPTION
            'accounts.acc_ledger_role is empty — migration 20260911070000 has not run.';
    END IF;

    --  Each group the catalogue names must resolve to EXACTLY ONE global,
    --  undeleted row. There is no unique index on acc_group_name, so two
    --  global groups of the same name would silently double every ledger
    --  §2.2 creates under it.
    SELECT string_agg(format('%s (%s)', t.group_name,
                             CASE WHEN t.n = 0 THEN 'not found'
                                  ELSE t.n || ' matches' END),
                      ', ' ORDER BY t.group_name)
      INTO v_bad
      FROM (SELECT DISTINCT c.group_name,
                   (SELECT count(*)
                      FROM accounts.acc_group_master g
                     WHERE g.acc_group_name = c.group_name
                       AND g.acc_group_company_id IS NULL
                       AND NOT g.acc_group_is_deleted) AS n
              FROM accounts.fn_ledger_map_catalogue() c) t
     WHERE t.n <> 1;

    IF v_bad IS NOT NULL THEN
        IF p_skip_if_no_chart THEN
            RAISE NOTICE
                'accounts.fn_seed_ledger_map: chart of accounts not ready (%) — deferred to prisma/seed/Acc_Ledger_Map.sql.',
                v_bad;
            RETURN format('skipped: %s', v_bad);
        END IF;
        RAISE EXCEPTION
            'Each account group the catalogue names needs exactly one global row: %. Run prisma/seed/Account_Groups.sql first.',
            v_bad;
    END IF;

    -- ── 2.2 · The ledgers that do not exist yet ──────────────────────────
    --  Created GLOBAL (led_company_id NULL) to match the shared-chart model
    --  every other posting ledger follows, and the model §2.4's join assumes.
    INSERT INTO accounts.acc_ledger_master
           (led_group_id, led_name, led_company_id, led_ledger_type,
            led_gst_duty_head, led_is_active, led_is_deleted,
            led_remarks, led_created_by, led_modified_by)
    SELECT g.acc_group_id, c.ledger_name, NULL, c.ledger_type,
           c.duty_head, true, false,
           format('Posting ledger for the %s role.', c.role_code),
           p_created_by, p_created_by
      FROM accounts.fn_ledger_map_catalogue() c
      JOIN accounts.acc_group_master g
        ON g.acc_group_name = c.group_name
       AND g.acc_group_company_id IS NULL
       AND NOT g.acc_group_is_deleted
     WHERE NOT EXISTS (
            SELECT 1 FROM accounts.acc_ledger_master l
             WHERE l.led_name = c.ledger_name
               AND l.led_company_id IS NULL
               AND NOT l.led_is_deleted);
    GET DIAGNOSTICS v_new_ledgers = ROW_COUNT;

    -- ── 2.3 · Every active role must be in the catalogue ─────────────────
    --  Catches a role added to acc_ledger_role without being given a home,
    --  which would otherwise become another silent null at posting time.
    SELECT string_agg(r.alr_role, ', ' ORDER BY r.alr_role)
      INTO v_bad
      FROM accounts.acc_ledger_role r
     WHERE r.alr_is_active
       AND NOT EXISTS (SELECT 1 FROM accounts.fn_ledger_map_catalogue() c
                        WHERE c.role_code = r.alr_role);
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION
            'These active roles are not in accounts.fn_ledger_map_catalogue(): %. Add them there.',
            v_bad;
    END IF;

    -- ── 2.4 · Every named ledger must exist, exactly once, globally ──────
    SELECT string_agg(format('%s -> "%s" (%s)', c.role_code, c.ledger_name,
                             CASE WHEN x.n = 0 THEN 'not found'
                                  ELSE x.n || ' matches' END),
                      E'\n  ' ORDER BY c.role_code)
      INTO v_bad
      FROM accounts.fn_ledger_map_catalogue() c
      CROSS JOIN LATERAL (
            SELECT count(*) AS n
              FROM accounts.acc_ledger_master l
             WHERE l.led_name = c.ledger_name
               AND l.led_company_id IS NULL
               AND NOT l.led_is_deleted) x
     WHERE x.n <> 1;
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION E'Each role needs exactly one global ledger of that name:\n  %', v_bad;
    END IF;

    -- ── 2.5 · Every pair must FIT its role ───────────────────────────────
    --  There is no trigger doing this. See the header. Read alr_want_* as:
    --  NULL means "not checked on this axis".
    SELECT string_agg(
             format('%s -> "%s": %s', c.role_code, c.ledger_name,
                    concat_ws('; ',
                      CASE WHEN r.alr_want_type IS NOT NULL
                            AND l.led_ledger_type IS DISTINCT FROM r.alr_want_type
                           THEN format('wants led_ledger_type %L, ledger is %L',
                                       r.alr_want_type, l.led_ledger_type) END,
                      CASE WHEN r.alr_want_duty IS NOT NULL
                            AND l.led_gst_duty_head IS DISTINCT FROM r.alr_want_duty
                           THEN format('wants duty head %L, ledger is %L',
                                       r.alr_want_duty, l.led_gst_duty_head) END,
                      CASE WHEN r.alr_want_nature IS NOT NULL
                            AND g.acc_group_nature IS DISTINCT FROM r.alr_want_nature
                           THEN format('wants group nature %L, ledger sits under %L which is %L',
                                       r.alr_want_nature, g.acc_group_name,
                                       g.acc_group_nature) END)),
             E'\n  ' ORDER BY c.role_code)
      INTO v_bad
      FROM accounts.fn_ledger_map_catalogue() c
      JOIN accounts.acc_ledger_role   r ON r.alr_role = c.role_code
      JOIN accounts.acc_ledger_master l ON l.led_name = c.ledger_name
                                       AND l.led_company_id IS NULL
                                       AND NOT l.led_is_deleted
      LEFT JOIN accounts.acc_group_master g ON g.acc_group_id = l.led_group_id
     WHERE (r.alr_want_type   IS NOT NULL AND l.led_ledger_type   IS DISTINCT FROM r.alr_want_type)
        OR (r.alr_want_duty   IS NOT NULL AND l.led_gst_duty_head IS DISTINCT FROM r.alr_want_duty)
        OR (r.alr_want_nature IS NOT NULL AND g.acc_group_nature  IS DISTINCT FROM r.alr_want_nature);
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION E'These ledgers do not fit their role:\n  %', v_bad;
    END IF;

    -- ── 2.6 · Write the map ──────────────────────────────────────────────
    --  ux_alm_role is UNIQUE (company, branch, role, supply_nature) NULLS NOT
    --  DISTINCT WHERE NOT deleted, so a second live row for the same role IS
    --  refused and ON CONFLICT would be safe here. NOT EXISTS is used anyway,
    --  for the same reason as §2.2 and so a re-run reports 0 rather than
    --  swallowing a conflict.
    --
    --  A row that has been retired by hand (alm_is_deleted, or alm_is_active
    --  false) is left alone: the NOT EXISTS below only skips a LIVE row, so a
    --  soft-deleted mapping is replaced, while an inactive one is not — an
    --  operator who switched a role off keeps it off, and §2.7 then names it.
    INSERT INTO accounts.acc_ledger_map
           (alm_company_id, alm_branch_id, alm_supply_nature,
            alm_role, alm_ledger_id, alm_remarks, alm_created_by)
    SELECT NULL, NULL, NULL,
           c.role_code, l.led_id,
           'seeded from the global chart by name',
           p_created_by
      FROM accounts.fn_ledger_map_catalogue() c
      JOIN accounts.acc_ledger_master l
        ON l.led_name = c.ledger_name
       AND l.led_company_id IS NULL
       AND NOT l.led_is_deleted
     WHERE NOT EXISTS (
            SELECT 1 FROM accounts.acc_ledger_map x
             WHERE x.alm_role          = c.role_code
               AND x.alm_company_id    IS NULL
               AND x.alm_branch_id     IS NULL
               AND x.alm_supply_nature IS NULL
               AND NOT x.alm_is_deleted);
    GET DIAGNOSTICS v_new_maps = ROW_COUNT;

    -- ── 2.7 · VERIFY — every role must resolve ───────────────────────────
    SELECT string_agg(r.alr_role, ', ' ORDER BY r.alr_sort_order)
      INTO v_bad
      FROM accounts.acc_ledger_role r
     WHERE r.alr_is_active
       AND NOT EXISTS (
            SELECT 1 FROM accounts.acc_ledger_map x
             WHERE x.alm_role = r.alr_role
               AND NOT x.alm_is_deleted AND x.alm_is_active);
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION
            'Still unmapped after seeding: %. A row for it exists but is inactive — reactivate it, or delete it and re-run.',
            v_bad;
    END IF;

    SELECT count(*) INTO v_roles FROM accounts.acc_ledger_role WHERE alr_is_active;
    RAISE NOTICE 'accounts.fn_seed_ledger_map: % ledger(s) created, % role(s) mapped, all % active roles resolve.',
        v_new_ledgers, v_new_maps, v_roles;

    RETURN format('%s ledger(s) created, %s role(s) mapped, %s active role(s) resolve',
                  v_new_ledgers, v_new_maps, v_roles);
END;
$fn$;

COMMENT ON FUNCTION accounts.fn_seed_ledger_map(boolean, varchar) IS
    'Applies accounts.fn_ledger_map_catalogue(): creates any missing global posting ledger, then maps every active role in acc_ledger_role. Re-runnable. Aborts on a ledger that does not fit its role; p_skip_if_no_chart only downgrades "the account groups are not seeded yet" to a no-op.';


-- ═══════════════════════════════════════════════════════════════════════════
--  3 · APPLY, where there is a chart to apply it to
--
--  On an existing database this maps all 22 roles now. On a fresh one — and
--  on the shadow database `migrate dev` replays into — acc_group_master is
--  still empty at this point, so it says so and does nothing;
--  prisma/seed/Acc_Ledger_Map.sql maps it at first boot instead.
-- ═══════════════════════════════════════════════════════════════════════════
SELECT accounts.fn_seed_ledger_map(p_skip_if_no_chart => true);


-- ═══════════════════════════════════════════════════════════════════════════
--  4 · WHAT THIS DELIBERATELY DOES NOT DO
--
--  · It does not touch inventory.tax_rate_ledger or tax_rate_master's ledger
--    columns. Whether revenue splits per GST rate is a business decision, and
--    leaving them NULL falls through to this map — which is today's behaviour
--    exactly.
--
--  · It does not set alm_company_id / alm_branch_id. See the header.
--
--  · It does not add the missing guard trigger on acc_ledger_map, nor
--    accounts.fn_check_role_ledger. That is a schema change with its own
--    blast radius — every existing row would have to pass it — and it belongs
--    in its own migration. §2.5 checks the same thing for the rows written
--    here, and nothing else writes rows to acc_ledger_map yet.
--
--  · It does not create a UI. Until a Posting Ledgers screen exists (it can
--    build itself from alr_group / alr_sort_order), the catalogue IS the
--    configuration, and changing a mapping means CREATE OR REPLACE on
--    accounts.fn_ledger_map_catalogue() in a new migration.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Read-back: paste this after running ──────────────────────────────────
--
-- SELECT r.alr_group, r.alr_sort_order, r.alr_role, r.alr_label,
--        l.led_name AS posts_to, g.acc_group_name AS under
--   FROM accounts.acc_ledger_role r
--   LEFT JOIN accounts.acc_ledger_map x ON x.alm_role = r.alr_role
--                                      AND NOT x.alm_is_deleted AND x.alm_is_active
--   LEFT JOIN accounts.acc_ledger_master l ON l.led_id = x.alm_ledger_id
--   LEFT JOIN accounts.acc_group_master  g ON g.acc_group_id = l.led_group_id
--  WHERE r.alr_is_active
--  ORDER BY r.alr_sort_order, r.alr_role;
