-- CreateTable
-- sales.sale_order / sales.sale_order_item / sales.sale_order_advance_alloc are
-- declaratively partitioned by LIST (acc_year), like sale_bill / sale_bill_item
-- / acc_tender_detail / txn_status_log. Prisma Migrate cannot express PARTITION
-- BY, partition-aware composite primary keys, CHECK constraints or partial
-- indexes, so this migration is hand-written rather than generated by
-- `prisma migrate dev`. The partitions are created at the end of this file by
-- public.ensure_acc_year_partitions, which is extended here to cover the three
-- new tables.
--
-- Table owners are not set here: the repo's other partitioned-table migrations
-- (20260731070026, 20260808120000) leave ownership to the role running the
-- migration, so a non-superuser deploy role still works.

CREATE TABLE IF NOT EXISTS sales.sale_order
(
    so_id                   uuid           NOT NULL DEFAULT uuidv7(),
    so_company_id           uuid           NOT NULL,
    so_branch_id            uuid           NOT NULL,   -- branch that TOOK the order
    so_tenant_id            uuid,
    so_acc_year             character(9)   NOT NULL,

    -- Where it was raised. The DEVICE is the counter — there is no separate
    -- counter id: fixed.device_master is the register of billing points, and
    -- so_device_id keys the per-device number series (ux_so_slno). NOT NULL,
    -- because in an offline chain the device owns the document and its series.
    --
    -- Device name / type / platform / MAC are NOT snapshotted here; they are
    -- reachable through the FK and a device does not change identity.
    so_session_id           uuid,
    so_device_id            uuid           NOT NULL,

    -- ── Document identity ────────────────────────────────────────────────
    so_doc_type             character varying(30)  NOT NULL DEFAULT 'SALES_ORDER',
    so_order_type           character varying(20)  NOT NULL DEFAULT 'CASH',   -- CASH | CREDIT
    so_price_level          integer        NOT NULL,
    so_order_slno           bigint         NOT NULL,   -- per company/branch/year/DEVICE
    so_order_refno          character varying(100) NOT NULL,
    so_usr_refno            character varying(100),
    so_order_date           date           NOT NULL,
    so_order_datetime       timestamp(6) with time zone NOT NULL DEFAULT now(),

    -- ── Delivery window ──────────────────────────────────────────────────
    -- The date agreed with the customer (legacy ord_del_date). Lines may
    -- carry their own when an order is delivered in parts — see
    -- soi_delivery_date.
    so_delivery_date        date,
    so_delivery_slot        character varying(30),   -- 'FN' | 'AN' | '10-12' ... free text by design
    so_priority             character varying(10) NOT NULL DEFAULT 'NORMAL',
    so_valid_until          date,                    -- unclaimed booking lapses

    -- Where it came from: quotation (usually), or an imported/marketplace
    -- order. Polymorphic, so no FK — but the source's OWN accounting year is
    -- kept, because a March quotation can become an April order.
    so_src_doc_type         character varying(30),
    so_src_doc_id           uuid,
    so_src_doc_acc_year     character(9),
    so_src_doc_refno        character varying(100),
    so_src_doc_date         date,

    -- How the goods reach the customer. The branch that takes the order is
    -- the branch that supplies and bills it — inter-branch movement is an
    -- inventory transfer document with no link to this one.
    so_delivery_mode        character varying(20) NOT NULL DEFAULT 'STORE_PICKUP',

    -- ── Customer, snapshotted at order time ──────────────────────────────
    so_cust_id              uuid           NOT NULL,
    so_cust_name            character varying(200) NOT NULL,
    so_cust_addr            character varying(500),
    so_cust_place           character varying(100),
    so_cust_pin             character varying(10),
    so_cust_phone           character varying(20),
    so_cust_email           character varying(150),
    so_cust_gstin           character varying(15),
    so_cust_gst_type        character varying(20),
    so_cust_stcd            character(2),
    so_pos_stcd             character(2),          -- place of supply: CGST+SGST vs IGST
    so_state_name           character varying(100),
    so_contact_person       character varying(150),
    so_contact_phone        character varying(20),

    -- ── Ship-to, snapshotted separately from the billing address ─────────
    so_ship_name            character varying(200),
    so_ship_addr            character varying(500),
    so_ship_place           character varying(100),
    so_ship_pin             character varying(10),
    so_ship_phone           character varying(20),
    so_ship_stcd            character(2),
    so_ship_landmark        character varying(250),
    so_ship_lat             numeric(9,6),
    so_ship_lng             numeric(9,6),

    -- ── Options carried on the document ──────────────────────────────────
    so_has_load             boolean NOT NULL DEFAULT false,
    so_has_unload           boolean NOT NULL DEFAULT false,
    so_has_freight          boolean NOT NULL DEFAULT false,
    so_has_promo            boolean NOT NULL DEFAULT false,
    so_has_comm             boolean NOT NULL DEFAULT false,
    so_has_loyalty          boolean NOT NULL DEFAULT false,

    -- ── People ───────────────────────────────────────────────────────────
    so_user_id              uuid           NOT NULL,
    so_salesman_id          uuid[],
    so_agent_id             uuid,
    so_agent_comm_perc      numeric(15,4),
    so_agent_comm_amt       numeric(15,2),
    so_packed_id            uuid[],
    -- Delivery crew and vehicle are NOT here: an order is a commitment, not a
    -- despatch. Who loaded it and what it went on is the bill's / delivery
    -- challan's fact (sale_bill.sb_driver_id, sb_vehicle_id, sb_loadman_id).

    -- ── Quantities ───────────────────────────────────────────────────────
    so_tot_items            integer        NOT NULL DEFAULT 0,   -- ordered LINES
    so_delivered_items      integer        NOT NULL DEFAULT 0,   -- fully delivered LINES
    so_tot_weight           numeric(15,3)  NOT NULL DEFAULT 0,
    so_tot_bags             numeric(15,3)  NOT NULL DEFAULT 0,

    -- ── Money (same shape and order as sale_bill) ────────────────────────
    so_gross_amt            numeric(15,2)  NOT NULL DEFAULT 0,
    so_item_disc            numeric(15,2)  NOT NULL DEFAULT 0,
    so_spl_disc             numeric(15,2)  NOT NULL DEFAULT 0,
    so_sch_disc             numeric(15,2)  NOT NULL DEFAULT 0,
    so_bill_sch_disc        numeric(15,2)  NOT NULL DEFAULT 0,
    so_addl_disc1           numeric(15,2)  NOT NULL DEFAULT 0,
    so_addl_disc2           numeric(15,2)  NOT NULL DEFAULT 0,
    so_cash_disc_perc       numeric(15,4)  NOT NULL DEFAULT 0,
    so_cash_disc            numeric(15,2)  NOT NULL DEFAULT 0,

    so_taxable_amt          numeric(15,2)  NOT NULL DEFAULT 0,   -- POST-charge
    so_cgst_amt             numeric(15,2)  NOT NULL DEFAULT 0,
    so_sgst_amt             numeric(15,2)  NOT NULL DEFAULT 0,
    so_igst_amt             numeric(15,2)  NOT NULL DEFAULT 0,
    so_cess_amt             numeric(15,2)  NOT NULL DEFAULT 0,
    so_tax_amt              numeric(15,2)  NOT NULL DEFAULT 0,

    -- Roll-ups of sales.sale_doc_charge rows (reporting without a join).
    so_freight_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    so_load_amt             numeric(15,2)  NOT NULL DEFAULT 0,
    so_unload_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    so_other_amt1           numeric(15,2)  NOT NULL DEFAULT 0,
    so_other_amt2           numeric(15,2)  NOT NULL DEFAULT 0,
    so_round_off            numeric(15,2)  NOT NULL DEFAULT 0,
    so_order_amt            numeric(15,2)  NOT NULL DEFAULT 0,   -- the order value

    -- ── Costing (never printed; drives margin reports) ───────────────────
    so_total_cost           numeric(15,2),
    so_margin_amt           numeric(15,2),
    so_margin_amt_wot       numeric(15,2),
    so_margin_perc          numeric(15,4),
    so_margin_perc_wot      numeric(15,4),
    so_mrp_savings          numeric(15,3)  DEFAULT 0,
    so_mrp_savings_perc     numeric(15,4)  DEFAULT 0,

    -- ── Advance payment ──────────────────────────────────────────────────
    -- Policy is snapshotted per order because it is negotiated per order
    -- (a custom-cut order takes 50%, a stocked item takes a token).
    so_advance_policy       character varying(10) NOT NULL DEFAULT 'NONE',
    so_advance_perc         numeric(15,4)  NOT NULL DEFAULT 0,
    so_advance_required     numeric(15,2)  NOT NULL DEFAULT 0,
    so_advance_due_date     date,
    so_is_advance_mandatory boolean        NOT NULL DEFAULT false,
    so_advance_ledger_id    uuid,                    -- customer-advance liability ledger

    -- Roll-ups. Received comes from accounts.acc_tender_detail; the other
    -- three from sales.sale_order_advance_alloc. Balance is what the company
    -- still HOLDS, and ck_so_advance_balance keeps it honest.
    so_advance_recd_amt     numeric(15,2)  NOT NULL DEFAULT 0,
    so_advance_adjusted_amt numeric(15,2)  NOT NULL DEFAULT 0,
    so_advance_refund_amt   numeric(15,2)  NOT NULL DEFAULT 0,
    so_advance_forfeit_amt  numeric(15,2)  NOT NULL DEFAULT 0,
    so_advance_balance_amt  numeric(15,2)  NOT NULL DEFAULT 0,
    so_advance_status       character varying(20) NOT NULL DEFAULT 'NONE',
    so_advance_recd_on      timestamp(6) with time zone,   -- first instalment

    -- Settlement roll-ups for the order itself (tender rows live in
    -- accounts.acc_tender_detail; these are caches so a counter can balance
    -- without a join).
    so_pay_mode             character varying(20),
    so_surcharge_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    so_tender_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    so_refund_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    so_pay_status           character varying(20) NOT NULL DEFAULT 'UNPAID',

    -- ── Fulfilment caches (sale_bill / sale_bill_item are the truth) ─────
    so_billed_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    so_cancelled_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    so_pending_amt          numeric(15,2)  NOT NULL DEFAULT 0,
    so_fulfil_status        character varying(20) NOT NULL DEFAULT 'PENDING',
    so_last_billed_on       timestamp(6) with time zone,
    so_completed_on         timestamp(6) with time zone,   -- last line delivered

    -- ── Terms ────────────────────────────────────────────────────────────
    so_payment_terms        character varying(250),
    so_delivery_terms       character varying(250),
    so_terms_conditions     text,
    so_remarks              character varying(500),

    -- ── Pricing policy, snapshotted as this order was priced ─────────────
    so_freight_calc_type    character varying(12),
    so_loading_calc_type    character varying(12),
    so_disc_alter_base      boolean,
    so_round_off_step       numeric(15,2)  NOT NULL DEFAULT 1,

    -- ── Lifecycle ────────────────────────────────────────────────────────
    -- so_status is the CURRENT state and the ONLY lifecycle column here — a
    -- cache of the newest log row's tsl_to_status, which is what the list
    -- screen filters on.
    --
    -- Everything else about how the order got here — who confirmed, who
    -- approved an override, who cancelled and why, when each step happened —
    -- is owned by public.txn_status_log (20260808120000), the trail every
    -- document in every module shares. That is what the History button on the
    -- entry screen shows:
    --     SELECT tsl_seq_no, tsl_event, tsl_from_status, tsl_to_status,
    --            tsl_changed_on, tsl_changed_by, tsl_remarks
    --       FROM public.txn_status_log
    --      WHERE tsl_src_module = 'SALES' AND tsl_src_doc_type = 'SALES_ORDER'
    --        AND tsl_src_doc_id = $1 AND tsl_acc_year = $2
    --      ORDER BY tsl_seq_no;
    --
    -- The cancellation reason therefore lives in that row's tsl_remarks, and
    -- the "a cancelled order must say why" invariant is enforced there by
    -- ck_tsl_reason_required — not by a duplicate column on this table.
    so_status               character varying(20) NOT NULL DEFAULT 'DRAFT',
    so_version_no           integer        NOT NULL DEFAULT 1,
    so_print_count          integer        NOT NULL DEFAULT 0,

    -- ── Audit ────────────────────────────────────────────────────────────
    so_is_deleted           boolean NOT NULL DEFAULT false,
    so_sync_date            timestamp(6) with time zone,
    so_created_on           timestamp(6) with time zone NOT NULL DEFAULT now(),
    so_created_by           character varying(50) NOT NULL,
    so_modified_on          timestamp(6) with time zone,
    so_modified_by          character varying(50),

    CONSTRAINT pk_sale_order PRIMARY KEY (so_id, so_acc_year),

    CONSTRAINT fk_so_cust FOREIGN KEY (so_cust_id)
        REFERENCES sales.customers (cus_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_so_pos_state FOREIGN KEY (so_pos_stcd)
        REFERENCES fixed.state_codes (state_code) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_so_ship_state FOREIGN KEY (so_ship_stcd)
        REFERENCES fixed.state_codes (state_code) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_so_price_level FOREIGN KEY (so_price_level)
        REFERENCES inventory.item_price_levels (ipl_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_so_salesman_agent FOREIGN KEY (so_agent_id)
        REFERENCES public.employee_master (emp_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_so_advance_ledger FOREIGN KEY (so_advance_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    -- RESTRICT, not SET NULL: the device owns this document's number series,
    -- so it can be blocked or deactivated but never unlinked.
    CONSTRAINT fk_so_device FOREIGN KEY (so_device_id)
        REFERENCES fixed.device_master (dev_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_so_doc_type CHECK (so_doc_type::text = ANY (ARRAY[
        'SALES_ORDER'::text, 'BOOKING'::text, 'CUSTOM_ORDER'::text])),
    CONSTRAINT ck_so_order_type CHECK (so_order_type::text = ANY (ARRAY[
        'CASH'::text, 'CREDIT'::text])),
    CONSTRAINT ck_so_priority CHECK (so_priority::text = ANY (ARRAY[
        'LOW'::text, 'NORMAL'::text, 'HIGH'::text, 'URGENT'::text])),
    CONSTRAINT ck_so_delivery_mode CHECK (so_delivery_mode::text = ANY (ARRAY[
        'STORE_PICKUP'::text, 'HOME_DELIVERY'::text, 'SHIP_FROM_STORE'::text,
        'COURIER'::text, 'TRANSPORT'::text])),
    CONSTRAINT ck_so_status CHECK (so_status::text = ANY (ARRAY[
        'DRAFT'::text, 'CONFIRMED'::text, 'PARTIAL'::text, 'COMPLETED'::text,
        'CANCELLED'::text, 'CLOSED'::text, 'EXPIRED'::text])),
    CONSTRAINT ck_so_fulfil_status CHECK (so_fulfil_status::text = ANY (ARRAY[
        'PENDING'::text, 'PARTIAL'::text, 'COMPLETED'::text, 'CANCELLED'::text])),
    CONSTRAINT ck_so_pay_status CHECK (so_pay_status::text = ANY (ARRAY[
        'UNPAID'::text, 'PARTIAL'::text, 'PAID'::text])),

    -- ── Advance invariants ───────────────────────────────────────────────
    CONSTRAINT ck_so_advance_policy CHECK (so_advance_policy::text = ANY (ARRAY[
        'NONE'::text, 'FIXED'::text, 'PERC'::text, 'FULL'::text])),
    CONSTRAINT ck_so_advance_status CHECK (so_advance_status::text = ANY (ARRAY[
        'NONE'::text, 'PENDING'::text, 'PARTIAL'::text, 'RECEIVED'::text,
        'ADJUSTED'::text, 'REFUNDED'::text, 'FORFEITED'::text])),
    CONSTRAINT ck_so_advance_amounts CHECK (
        so_advance_required     >= 0 AND so_advance_recd_amt    >= 0 AND
        so_advance_adjusted_amt >= 0 AND so_advance_refund_amt  >= 0 AND
        so_advance_forfeit_amt  >= 0 AND so_advance_balance_amt >= 0),
    -- What is still held = taken − used − given back − kept on cancellation.
    CONSTRAINT ck_so_advance_balance CHECK (
        so_advance_balance_amt = round(so_advance_recd_amt
                                     - so_advance_adjusted_amt
                                     - so_advance_refund_amt
                                     - so_advance_forfeit_amt, 2)),
    -- A percentage policy needs a percentage; a fixed one needs an amount.
    CONSTRAINT ck_so_advance_policy_input CHECK (
        (so_advance_policy = 'PERC'  AND so_advance_perc     > 0) OR
        (so_advance_policy = 'FIXED' AND so_advance_required > 0) OR
         so_advance_policy IN ('NONE', 'FULL'))
) PARTITION BY LIST (so_acc_year);


-- ───────────────────────────────────────────────────────────────────────────
--  Lines — one row per ORDERED LINE (not per batch: an order allocates no
--  stock). Fulfilment is tracked as three caches that must add up to the
--  ordered quantity, so "what is still pending" never needs the bill table.
-- ───────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sales.sale_order_item
(
    soi_id                  uuid           NOT NULL DEFAULT uuidv7(),
    soi_order_id            uuid           NOT NULL,
    soi_company_id          uuid           NOT NULL,
    soi_branch_id           uuid           NOT NULL,
    soi_tenant_id           uuid,
    soi_acc_year            character(9)   NOT NULL,

    soi_line_no             integer        NOT NULL,

    -- Which line of which source document this came from (quotation).
    soi_src_doc_type        character varying(30),
    soi_src_doc_id          uuid,
    soi_src_doc_acc_year    character(9),
    soi_src_doc_refno       character varying(100),
    soi_src_line_no         integer,

    -- ── What is being ordered ────────────────────────────────────────────
    soi_item_id             uuid           NOT NULL,
    soi_item_unit_id        uuid           NOT NULL,
    soi_to_base_factor      numeric(15,6)  NOT NULL DEFAULT 0,
    soi_hsn_code            character varying(8),
    soi_price_level         integer        NOT NULL,
    soi_ean_code            character varying(100),

    -- Free-text dimension the operator typed, e.g. a timber shop's
    -- "12*6*2*10" (length ft * width in * thickness in * pieces), which is
    -- what soi_order_qty was derived from. Stored verbatim so a reprint shows
    -- the size the customer agreed to, not just the cubic feet it became.
    soi_size                character varying(50),
    soi_size_uom            character varying(20),

    -- ── Reservation (a soft hold; inventory owns the hard one) ───────────
    soi_godown_id           uuid,
    soi_is_reserved         boolean        NOT NULL DEFAULT false,
    soi_reserved_qty        numeric(15,3)  NOT NULL DEFAULT 0,
    soi_reserve_expires_on  date,

    -- ── Flags ────────────────────────────────────────────────────────────
    soi_is_tax_incl         boolean NOT NULL DEFAULT false,
    soi_is_promo            boolean NOT NULL DEFAULT false,
    soi_is_free             boolean NOT NULL DEFAULT false,
    soi_free_type           character varying(20),
    soi_is_service          boolean NOT NULL DEFAULT false,
    soi_has_freight         boolean NOT NULL DEFAULT false,

    -- ── Quantities ───────────────────────────────────────────────────────
    soi_case_qty            numeric(15,3)  NOT NULL DEFAULT 0,
    soi_order_qty           numeric(15,3)  NOT NULL DEFAULT 0,
    soi_length_qty          numeric(15,3)  DEFAULT 0,
    soi_net_qty             numeric(15,3)  NOT NULL DEFAULT 0,
    soi_weight_qty          numeric(15,3)  DEFAULT 0,
    soi_available_stock     numeric(15,3)  NOT NULL DEFAULT 0,   -- at order time

    -- Fulfilment caches — sale_bill_item is the truth (sbi_src_doc_id).
    soi_delivered_qty       numeric(15,3)  NOT NULL DEFAULT 0,
    soi_cancelled_qty       numeric(15,3)  NOT NULL DEFAULT 0,
    soi_pending_qty         numeric(15,3)  NOT NULL DEFAULT 0,
    soi_billed_amt          numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── Rates ────────────────────────────────────────────────────────────
    soi_rate                numeric(15,4)  NOT NULL DEFAULT 0,
    soi_rate_pre_tax        numeric(15,4)  NOT NULL DEFAULT 0,
    soi_rate_diff           numeric(15,4)  NOT NULL DEFAULT 0,
    soi_act_price           numeric(15,4),
    soi_max_price           numeric(15,4),                        -- MRP
    soi_min_price           numeric(15,4),
    soi_cost_price          numeric(15,4),
    soi_cost_pre_tax        numeric(15,2),
    -- A confirmed order holds its price even if the price master moves;
    -- false lets the bill re-price at delivery (long-lead custom orders).
    soi_is_rate_locked      boolean        NOT NULL DEFAULT true,

    -- ── Discounts ────────────────────────────────────────────────────────
    soi_item_disc_perc      numeric(15,4)  NOT NULL DEFAULT 0,
    soi_item_disc_qty       numeric(15,3)  NOT NULL DEFAULT 0,
    soi_item_disc_amt       numeric(15,2)  NOT NULL DEFAULT 0,
    soi_spl_disc_perc       numeric(15,4)  NOT NULL DEFAULT 0,
    soi_spl_disc_qty        numeric(15,3)  NOT NULL DEFAULT 0,
    soi_spl_disc_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    soi_sch_disc_perc       numeric(15,4)  NOT NULL DEFAULT 0,
    soi_sch_disc_qty        numeric(15,3)  NOT NULL DEFAULT 0,
    soi_sch_disc_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    soi_bill_sch_perc       numeric(15,4)  NOT NULL DEFAULT 0,
    soi_bill_sch_qty        numeric(15,3)  NOT NULL DEFAULT 0,
    soi_bill_sch_amt        numeric(15,2)  NOT NULL DEFAULT 0,
    soi_addl_disc1_perc     numeric(15,4)  NOT NULL DEFAULT 0,
    soi_addl_disc1_amt      numeric(15,2)  NOT NULL DEFAULT 0,
    soi_addl_disc2_perc     numeric(15,4)  NOT NULL DEFAULT 0,
    soi_addl_disc2_amt      numeric(15,2)  NOT NULL DEFAULT 0,
    soi_cash_disc_perc      numeric(15,4)  NOT NULL DEFAULT 0,
    soi_cash_disc_amt       numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── The charge-distribution trio ─────────────────────────────────────
    soi_gross_amt           numeric(15,2)  NOT NULL DEFAULT 0,
    soi_net_gross           numeric(14,4),
    soi_chrg_before_tax     numeric(14,4),
    soi_chrg_after_tax      numeric(14,4),

    -- ── Tax (on the POST-charge taxable) ─────────────────────────────────
    soi_taxable_amt         numeric(15,2)  NOT NULL DEFAULT 0,
    soi_tax_perc            numeric(15,4)  NOT NULL DEFAULT 0,
    soi_tax_amt             numeric(15,2)  NOT NULL DEFAULT 0,
    soi_cgst_perc           numeric(15,4)  NOT NULL DEFAULT 0,
    soi_cgst_amt            numeric(15,2)  NOT NULL DEFAULT 0,
    soi_sgst_perc           numeric(15,4)  NOT NULL DEFAULT 0,
    soi_sgst_amt            numeric(15,2)  NOT NULL DEFAULT 0,
    soi_igst_perc           numeric(15,4)  NOT NULL DEFAULT 0,
    soi_igst_amt            numeric(15,2)  NOT NULL DEFAULT 0,
    soi_cess_perc           numeric(15,4)  NOT NULL DEFAULT 0,
    soi_cess_per_unit       numeric(15,4)  NOT NULL DEFAULT 0,
    soi_cess_amt            numeric(15,2)  NOT NULL DEFAULT 0,
    soi_acess_perc          numeric(15,4)  NOT NULL DEFAULT 0,
    soi_acess_per_unit      numeric(15,4)  NOT NULL DEFAULT 0,
    soi_acess_amt           numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── Per-line charges ─────────────────────────────────────────────────
    soi_freight_qty         numeric(15,3)  NOT NULL DEFAULT 0,
    soi_freight_amt         numeric(15,2)  NOT NULL DEFAULT 0,
    soi_load_qty            numeric(15,3)  NOT NULL DEFAULT 0,
    soi_load_amt            numeric(15,2)  NOT NULL DEFAULT 0,
    soi_unload_qty          numeric(15,3)  NOT NULL DEFAULT 0,
    soi_unload_amt          numeric(15,2)  NOT NULL DEFAULT 0,

    soi_round_off           numeric(15,2)  NOT NULL DEFAULT 0,
    soi_net_amt             numeric(15,2)  NOT NULL DEFAULT 0,

    -- ── Costing / margin, PER UNIT ───────────────────────────────────────
    soi_sold_price          numeric(15,4),
    soi_sold_pre_tax        numeric(15,2),
    soi_item_profit         numeric(15,2),
    soi_profit_pre_tax      numeric(15,2),
    soi_mrp_savings         numeric(15,3),
    soi_mrp_savings_perc    numeric(15,4),

    -- ── Line fulfilment / attribution ────────────────────────────────────
    soi_delivery_date       date,                    -- a split delivery per line
    soi_line_status         character varying(20) NOT NULL DEFAULT 'PENDING',
    soi_salesman_id         uuid,
    soi_scheme_id           uuid,
    soi_scheme_name         character varying(150),
    soi_remarks             character varying(250),

    -- ── Audit ────────────────────────────────────────────────────────────
    soi_is_deleted          boolean NOT NULL DEFAULT false,
    soi_sync_date           timestamp(6) with time zone,
    soi_created_on          timestamp(6) with time zone NOT NULL DEFAULT now(),
    soi_created_by          character varying(50) NOT NULL,
    soi_modified_on         timestamp(6) with time zone,
    soi_modified_by         character varying(50),

    CONSTRAINT pk_sale_order_item PRIMARY KEY (soi_id, soi_acc_year),

    CONSTRAINT fk_soi_order FOREIGN KEY (soi_order_id, soi_acc_year)
        REFERENCES sales.sale_order (so_id, so_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_soi_item FOREIGN KEY (soi_item_id)
        REFERENCES inventory.item_master (item_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_soi_item_unit FOREIGN KEY (soi_item_unit_id)
        REFERENCES inventory.item_unit_conversion (iuc_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_soi_price_level FOREIGN KEY (soi_price_level)
        REFERENCES inventory.item_price_levels (ipl_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_soi_free_type CHECK (
        soi_free_type IS NULL OR (soi_free_type::text = ANY (ARRAY[
            'SCHEME'::text, 'SAMPLE'::text, 'REPLACEMENT'::text]))),
    CONSTRAINT ck_soi_line_no CHECK (soi_line_no >= 1),
    CONSTRAINT ck_soi_line_status CHECK (soi_line_status::text = ANY (ARRAY[
        'PENDING'::text, 'PARTIAL'::text, 'DELIVERED'::text, 'CANCELLED'::text])),
    CONSTRAINT ck_soi_qty_signs CHECK (
        soi_order_qty >= 0 AND soi_delivered_qty >= 0 AND
        soi_cancelled_qty >= 0 AND soi_pending_qty >= 0),
    -- Nothing may go missing: every ordered unit is delivered, cancelled or
    -- still pending. This is the invariant the pending-orders report leans on.
    CONSTRAINT ck_soi_qty_balance CHECK (
        round(soi_order_qty, 3) = round(soi_delivered_qty
                                      + soi_cancelled_qty
                                      + soi_pending_qty, 3)),
    CONSTRAINT ck_soi_reserved CHECK (
        soi_reserved_qty >= 0 AND soi_reserved_qty <= soi_order_qty),
    CONSTRAINT ck_soi_size CHECK (
        soi_size IS NULL OR length(btrim(soi_size)) > 0)
) PARTITION BY LIST (soi_acc_year);


-- ───────────────────────────────────────────────────────────────────────────
--  Advance allocation — where the money taken up front actually went.
--
--  One row per application of one advance tender. The tender row
--  (accounts.acc_tender_detail) is the money coming IN; this is the money
--  being USED. Both sides carry their own accounting year because an advance
--  taken in March is routinely adjusted into an April invoice.
--
--  Sum(soa_amount) per order, grouped by soa_alloc_type, reproduces the four
--  header roll-ups exactly — that is the point of the table.
-- ───────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sales.sale_order_advance_alloc
(
    soa_id                  uuid           NOT NULL DEFAULT uuidv7(),
    soa_company_id          uuid           NOT NULL,
    soa_branch_id           uuid           NOT NULL,   -- branch that applied it
    soa_tenant_id           uuid,
    soa_acc_year            character(9)   NOT NULL,   -- year of the APPLICATION

    -- The order the advance was taken against.
    soa_order_id            uuid           NOT NULL,
    soa_order_acc_year      character(9)   NOT NULL,
    soa_order_refno         character varying(100),

    -- The tender row that brought the money in. Nullable only for opening
    -- balances migrated from the legacy system, which have no tender history.
    soa_tender_id           uuid,
    soa_tender_acc_year     character(9),

    soa_alloc_type          character varying(20) NOT NULL,
    soa_alloc_date          date           NOT NULL,
    soa_amount              numeric(15,2)  NOT NULL DEFAULT 0,

    -- ADJUSTED → the invoice it was set against (cross-year FK).
    soa_bill_id             uuid,
    soa_bill_acc_year       character(9),
    soa_bill_refno          character varying(100),

    -- TRANSFERRED → the order it was moved to (chain stores move a booking
    -- from one order to another rather than refunding and re-taking cash).
    soa_target_order_id     uuid,
    soa_target_acc_year     character(9),

    -- REFUNDED → how the money went back out. The refund is itself a tender
    -- row (CR); this is its reference.
    soa_refund_tender_id    uuid,
    soa_refund_mode         character varying(20),

    -- Filled at posting, server-side, like every other accounts link here.
    soa_voucher_id          uuid,
    soa_ledger_id           uuid,                    -- advance ledger relieved
    soa_remarks             character varying(250),
    soa_approved_by         uuid,                    -- refunds/forfeits need a sign-off

    -- ── Audit ────────────────────────────────────────────────────────────
    soa_is_deleted          boolean NOT NULL DEFAULT false,
    soa_sync_date           timestamp(6) with time zone,
    soa_created_on          timestamp(6) with time zone NOT NULL DEFAULT now(),
    soa_created_by          character varying(50) NOT NULL,
    soa_modified_on         timestamp(6) with time zone,
    soa_modified_by         character varying(50),

    CONSTRAINT pk_sale_order_advance_alloc PRIMARY KEY (soa_id, soa_acc_year),

    CONSTRAINT fk_soa_order FOREIGN KEY (soa_order_id, soa_order_acc_year)
        REFERENCES sales.sale_order (so_id, so_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_soa_target_order FOREIGN KEY (soa_target_order_id, soa_target_acc_year)
        REFERENCES sales.sale_order (so_id, so_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_soa_bill FOREIGN KEY (soa_bill_id, soa_bill_acc_year)
        REFERENCES sales.sale_bill (sb_id, sb_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_soa_tender FOREIGN KEY (soa_tender_id, soa_tender_acc_year)
        REFERENCES accounts.acc_tender_detail (td_id, td_acc_year) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_soa_ledger FOREIGN KEY (soa_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_soa_alloc_type CHECK (soa_alloc_type::text = ANY (ARRAY[
        'ADJUSTED'::text, 'REFUNDED'::text, 'FORFEITED'::text, 'TRANSFERRED'::text])),
    CONSTRAINT ck_soa_amount CHECK (soa_amount > 0),
    CONSTRAINT ck_soa_refund_mode CHECK (soa_refund_mode IS NULL OR
        soa_refund_mode::text = ANY (ARRAY[
            'CASH'::text, 'BANK'::text, 'UPI'::text, 'CARD'::text,
            'CREDIT_NOTE'::text, 'ADJUSTMENT'::text])),

    -- Each allocation type must name its target, and only its own target —
    -- otherwise a row cannot be replayed into the ledger unambiguously.
    CONSTRAINT ck_soa_target CHECK (
        (soa_alloc_type = 'ADJUSTED'
            AND soa_bill_id IS NOT NULL AND soa_bill_acc_year IS NOT NULL
            AND soa_target_order_id IS NULL)
     OR (soa_alloc_type = 'TRANSFERRED'
            AND soa_target_order_id IS NOT NULL AND soa_target_acc_year IS NOT NULL
            AND soa_bill_id IS NULL)
     OR (soa_alloc_type IN ('REFUNDED', 'FORFEITED')
            AND soa_bill_id IS NULL AND soa_target_order_id IS NULL)),
    CONSTRAINT ck_soa_no_self_transfer CHECK (
        soa_target_order_id IS NULL OR soa_target_order_id <> soa_order_id),
    CONSTRAINT ck_soa_tender_pair CHECK (
        (soa_tender_id IS NULL) = (soa_tender_acc_year IS NULL))
) PARTITION BY LIST (soa_acc_year);


-- ───────────────────────────────────────────────────────────────────────────
--  Indexes — header
-- ───────────────────────────────────────────────────────────────────────────

-- The list screen's exact filter shape, newest first.
CREATE INDEX IF NOT EXISTS ix_so_list
    ON sales.sale_order USING btree
    (so_company_id, so_branch_id, so_acc_year, so_order_date DESC, so_order_slno DESC)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE so_is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_so_cust
    ON sales.sale_order USING btree (so_cust_id)
    WITH (fillfactor=100, deduplicate_items=True);

CREATE INDEX IF NOT EXISTS ix_so_status
    ON sales.sale_order USING btree (so_status)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE so_is_deleted = false;

-- The pending-orders worklist: what a branch still owes, oldest promise
-- first. This is the query the counter runs all day, so it is partial on
-- exactly the rows that are still open.
CREATE INDEX IF NOT EXISTS ix_so_pending
    ON sales.sale_order USING btree
    (so_company_id, so_branch_id, so_acc_year, so_delivery_date)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE so_is_deleted = false
      AND so_fulfil_status::text = ANY (ARRAY['PENDING'::text, 'PARTIAL'::text]);

-- Advance still held — the liability the accounts team reconciles, and the
-- refund-due list when bookings lapse.
CREATE INDEX IF NOT EXISTS ix_so_advance_held
    ON sales.sale_order USING btree
    (so_company_id, so_branch_id, so_acc_year, so_advance_due_date)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE so_is_deleted = false AND so_advance_balance_amt > 0;

-- Walk back from a quotation (or any source document) to the orders it made.
CREATE INDEX IF NOT EXISTS ix_so_src_doc
    ON sales.sale_order USING btree (so_src_doc_type, so_src_doc_id)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE so_src_doc_id IS NOT NULL;

-- Offline chain: the serial is per DEVICE (fixed.device_master is the counter
-- register); the printed refno embeds that device's series and is unique per
-- branch/year.
CREATE UNIQUE INDEX IF NOT EXISTS ux_so_slno
    ON sales.sale_order USING btree
    (so_company_id, so_branch_id, so_acc_year, so_device_id, so_order_slno)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE so_is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS ux_so_order_no
    ON sales.sale_order USING btree
    (so_company_id, so_branch_id, so_acc_year, so_order_refno)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE so_is_deleted = false;


-- ───────────────────────────────────────────────────────────────────────────
--  Indexes — lines
-- ───────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS ix_soi_order
    ON sales.sale_order_item USING btree (soi_order_id)
    WITH (fillfactor=100, deduplicate_items=True);

CREATE UNIQUE INDEX IF NOT EXISTS ux_soi_order_line
    ON sales.sale_order_item USING btree
    (soi_order_id, soi_acc_year, soi_line_no)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE soi_is_deleted = false;

-- What is on back-order for an item, per branch — drives purchase
-- indent and the "we can get it by" answer at the counter.
CREATE INDEX IF NOT EXISTS ix_soi_pending_item
    ON sales.sale_order_item USING btree
    (soi_item_id, soi_company_id, soi_branch_id, soi_acc_year)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE soi_is_deleted = false AND soi_pending_qty > 0;

-- Stock held against open orders, by godown.
CREATE INDEX IF NOT EXISTS ix_soi_reserved
    ON sales.sale_order_item USING btree (soi_godown_id, soi_item_id)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE soi_is_deleted = false AND soi_is_reserved = true;


-- ───────────────────────────────────────────────────────────────────────────
--  Indexes — advance allocation
-- ───────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS ix_soa_order
    ON sales.sale_order_advance_alloc USING btree
    (soa_order_id, soa_order_acc_year)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE soa_is_deleted = false;

-- Which advances a given invoice consumed (bill reprint, audit).
CREATE INDEX IF NOT EXISTS ix_soa_bill
    ON sales.sale_order_advance_alloc USING btree
    (soa_bill_id, soa_bill_acc_year)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE soa_bill_id IS NOT NULL AND soa_is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_soa_tender
    ON sales.sale_order_advance_alloc USING btree
    (soa_tender_id, soa_tender_acc_year)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE soa_tender_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_soa_type_date
    ON sales.sale_order_advance_alloc USING btree
    (soa_company_id, soa_branch_id, soa_acc_year, soa_alloc_type, soa_alloc_date)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE soa_is_deleted = false;


-- ───────────────────────────────────────────────────────────────────────────
--  Partitions
--
--  The three tables above are parent shells: without a partition for the
--  accounting year being saved, every insert fails with
--
--    no partition of relation "sale_order" found for row
--    (Partition key of the failing row contains (so_acc_year) = (2026-2027).)
--
--  public.ensure_acc_year_partitions (20260804112944, extended by
--  20260808120000 for txn_status_log) is the one place that knows which tables
--  need a partition per year. Extend it rather than creating partitions here,
--  so opening a new fiscal year stays a single idempotent call:
--
--    SELECT public.ensure_acc_year_partitions('2027-2028');
--
--  Indexes and constraints declared on the parents are inherited by partitions
--  created with PARTITION OF, so nothing above has to be replayed per year.
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character(9))
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    -- The partition bound is a literal, so the year is validated rather than
    -- interpolated blind. char(9) makes 'YYYY-YYYY' the only well-formed value.
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order FOR VALUES IN (%L)',
        'sale_order_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_item FOR VALUES IN (%L)',
        'sale_order_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_advance_alloc FOR VALUES IN (%L)',
        'sale_order_advance_alloc_' || v_suffix, v_year);
END;
$$;

COMMENT ON FUNCTION public.ensure_acc_year_partitions(character(9)) IS
    'Idempotently creates the sale_bill / sale_bill_item / acc_tender_detail / txn_status_log / sale_order / sale_order_item / sale_order_advance_alloc LIST partitions for one accounting year (YYYY-YYYY). Run it whenever a fiscal year is opened.';

-- Bootstrap every accounting year on record. fiscal_years is the authority on
-- which years exist; deleted rows are skipped. Re-running the helper for years
-- that already have their other four partitions is a no-op for those and
-- creates only the new sale_order ones.
DO
$$
    DECLARE
        v_year text;
    BEGIN
        FOR v_year IN
            SELECT DISTINCT btrim(fy_year_name)
            FROM public.fiscal_years
            WHERE is_deleted = false
              AND btrim(fy_year_name) ~ '^[0-9]{4}-[0-9]{4}$'
            ORDER BY 1
            LOOP
                PERFORM public.ensure_acc_year_partitions(v_year::character(9));
            END LOOP;
    END;
$$;
