-- Move sales.sale_charge_detail to public.txn_charge_detail and make it a
-- declaratively LIST-partitioned table keyed on cd_acc_year, the way sale_bill
-- (20260731070026), acc_tender_detail (20260731090000), txn_status_log
-- (20260808120000), sale_order (20260808132323) and sale_quotation
-- (20260810130000) already are.
--
-- Two things change beyond the storage layout:
--
--   1. The table is no longer a sales table. Its rows are the applied charge
--      lines of ANY module's document -- the cd_doc_type discriminator already
--      spans PURCHASE / SALES / GRN / QUOTATION / INVOICE -- so it moves to the
--      public schema under the txn_ prefix that txn_status_log and
--      txn_charge_detail's sibling cross-module tables use.
--   2. The primary key gains the partition key: pk_txn_charge_detail is
--      (cd_id, cd_acc_year). Postgres requires every unique constraint on a
--      partitioned table to contain the partition key, so callers must address
--      a charge line by the pair, not by the id alone.
--
-- Postgres cannot ALTER an ordinary table into a partitioned one, so the table
-- is rebuilt: the partitioned parent is created alongside the old one, the rows
-- are copied over, and the old table is dropped. Column order, defaults, FKs
-- and index predicates are carried over unchanged; only the index NAMES follow
-- the table (ix_sale_charge_detail_* -> ix_txn_charge_detail_*).
--
-- Note the CHECK constraints that 20260728140000 added never made it past the
-- 20260729071620 rebuild of this table, so there are none to carry over. The
-- value sets they guarded are enforced app-side by CHARGE_DETAIL_VALUE_GUARDS.
--
-- Prisma Migrate can express none of PARTITION BY, composite partition-aware
-- primary keys or a cross-schema table move, so this migration is hand-written
-- rather than generated by `prisma migrate dev`.


-- ───────────────────────────────────────────────────────────────────────────
--  1. Partitioned parent
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE public.txn_charge_detail
(
    cd_id             uuid DEFAULT gen_random_uuid() NOT NULL,

    -- ── Parent document (polymorphic — no single FK possible) ─────────────
    cd_doc_type       character varying(12) NOT NULL,
    cd_doc_id         uuid NOT NULL,
    cd_slno           integer,

    -- ── Denormalised context ─────────────────────────────────────────────
    cd_comp_id        uuid NOT NULL,
    cd_branch_id      uuid NOT NULL,
    cd_acc_year       character(9) NOT NULL,
    cd_voucher_no     bigint,

    -- ── Charge reference + snapshots ─────────────────────────────────────
    cd_chg_id         uuid NOT NULL,
    cd_chg_name       character varying(100),
    cd_role           character varying(15),
    cd_method         character varying(10),
    cd_type           character varying(10) DEFAULT 'ADD'::character varying NOT NULL,
    cd_apply_on       character varying(10),
    cd_ledger_code    uuid NOT NULL,

    -- ── Landing cost + posting flags ─────────────────────────────────────
    cd_landing_cost   boolean DEFAULT false NOT NULL,
    cd_cost_alloc     character varying(10),
    cd_before_tax     boolean DEFAULT false NOT NULL,
    cd_tax_apl        boolean DEFAULT false NOT NULL,
    cd_sep_post       boolean DEFAULT false NOT NULL,

    -- ── Basis + amounts ──────────────────────────────────────────────────
    cd_unit           character varying(15),
    cd_qty_val        numeric(18,4),
    cd_weight         numeric(18,4),
    cd_rate           numeric(14,4),
    cd_amount         numeric(14,4),

    -- ── Tax ──────────────────────────────────────────────────────────────
    cd_tax_code       uuid,
    cd_hsn            character varying(15),
    cd_tax_perc       numeric(9,4),
    cd_tax_amt        numeric(14,4),
    cd_sgst_perc      numeric(9,4),
    cd_sgst_amt       numeric(14,4),
    cd_cgst_perc      numeric(9,4),
    cd_cgst_amt       numeric(14,4),
    cd_igst_perc      numeric(9,4),
    cd_igst_amt       numeric(14,4),
    cd_cess_perc      numeric(9,4),
    cd_cess_amt       numeric(14,4),
    cd_net_amt        numeric(14,4),

    -- ── Status + audit ───────────────────────────────────────────────────
    cd_remarks        character varying(255),
    cd_is_active      boolean DEFAULT true NOT NULL,
    cd_is_deleted     boolean DEFAULT false NOT NULL,
    cd_sync_date      timestamp with time zone,
    cd_created_on     timestamp with time zone DEFAULT now() NOT NULL,
    cd_created_by     text,
    cd_modified_on    timestamp with time zone,
    cd_modified_by    text,

    CONSTRAINT pk_txn_charge_detail PRIMARY KEY (cd_id, cd_acc_year),

    CONSTRAINT fk_cd_charge FOREIGN KEY (cd_chg_id)
        REFERENCES public.charge_master (chg_id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    -- The GL ledger the charge posts to. Restrict on delete: a ledger that has
    -- been posted to on any document must not disappear from under it.
    CONSTRAINT fk_cd_ledger FOREIGN KEY (cd_ledger_code)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_cd_company FOREIGN KEY (cd_comp_id)
        REFERENCES public.companys (comp_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_cd_branch FOREIGN KEY (cd_branch_id)
        REFERENCES public.branch_master (br_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT
) PARTITION BY LIST (cd_acc_year);


-- ───────────────────────────────────────────────────────────────────────────
--  2. Indexes
--
--  Declared on the parent, so partitions created later inherit them.
-- ───────────────────────────────────────────────────────────────────────────

-- Fetch all charge lines for one document (the hot path on entry load).
CREATE INDEX ix_txn_charge_detail_doc    ON public.txn_charge_detail (cd_doc_type, cd_doc_id);
CREATE INDEX ix_txn_charge_detail_chg    ON public.txn_charge_detail (cd_chg_id);
CREATE INDEX ix_txn_charge_detail_ledger ON public.txn_charge_detail (cd_ledger_code);
CREATE INDEX ix_txn_charge_detail_comp   ON public.txn_charge_detail (cd_comp_id);
CREATE INDEX ix_txn_charge_detail_branch ON public.txn_charge_detail (cd_branch_id);


-- ───────────────────────────────────────────────────────────────────────────
--  3. Teach public.ensure_acc_year_partitions about the new parent
--
--  Same helper the bill / tender / status-log / order / quotation tables use
--  (20260804112944, extended by 20260808120000, 20260808132323, 20260810130000).
--  Idempotent -- call it whenever a fiscal year is opened:
--
--      SELECT public.ensure_acc_year_partitions('2027-2028');
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character(9))
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    -- The partition bound is a literal, so the year is validated rather than
    -- interpolated blind. char(9) makes 'YYYY-YYYY' the only well-formed value.
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order FOR VALUES IN (%L)',
        'sale_order_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_item FOR VALUES IN (%L)',
        'sale_order_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_advance_alloc FOR VALUES IN (%L)',
        'sale_order_advance_alloc_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation FOR VALUES IN (%L)',
        'sale_quotation_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation_item FOR VALUES IN (%L)',
        'sale_quotation_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_charge_detail FOR VALUES IN (%L)',
        'txn_charge_detail_' || v_suffix, v_year);
END;
$$;

COMMENT ON FUNCTION public.ensure_acc_year_partitions(character(9)) IS
    'Idempotently creates the sale_bill / sale_bill_item / acc_tender_detail / txn_status_log / sale_order / sale_order_item / sale_order_advance_alloc / sale_quotation / sale_quotation_item / txn_charge_detail LIST partitions for one accounting year (YYYY-YYYY). Run it whenever a fiscal year is opened.';


-- ───────────────────────────────────────────────────────────────────────────
--  4. Partitions
--
--  Every year on record in fiscal_years, plus -- belt and braces -- any year
--  the existing charge lines actually carry, so nothing can fail to find a home
--  below.
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_year text;
    BEGIN
        FOR v_year IN
            SELECT DISTINCT btrim(fy_year_name)
            FROM public.fiscal_years
            WHERE is_deleted = false
              AND btrim(fy_year_name) ~ '^[0-9]{4}-[0-9]{4}$'
            UNION
            SELECT DISTINCT btrim(cd_acc_year) FROM sales.sale_charge_detail
            ORDER BY 1
            LOOP
                IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
                    RAISE EXCEPTION 'sale_charge_detail carries accounting year %, which is not YYYY-YYYY', v_year;
                END IF;
                PERFORM public.ensure_acc_year_partitions(v_year::character(9));
            END LOOP;
    END;
$$;


-- ───────────────────────────────────────────────────────────────────────────
--  5. Move the rows over
-- ───────────────────────────────────────────────────────────────────────────

INSERT INTO public.txn_charge_detail (
    cd_id, cd_doc_type, cd_doc_id, cd_slno, cd_comp_id, cd_branch_id, cd_acc_year,
    cd_voucher_no, cd_chg_id, cd_chg_name, cd_role, cd_method, cd_type, cd_apply_on,
    cd_ledger_code, cd_landing_cost, cd_cost_alloc, cd_before_tax, cd_tax_apl,
    cd_sep_post, cd_unit, cd_qty_val, cd_weight, cd_rate, cd_amount, cd_tax_code,
    cd_hsn, cd_tax_perc, cd_tax_amt, cd_sgst_perc, cd_sgst_amt, cd_cgst_perc,
    cd_cgst_amt, cd_igst_perc, cd_igst_amt, cd_cess_perc, cd_cess_amt, cd_net_amt,
    cd_remarks, cd_is_active, cd_is_deleted, cd_sync_date, cd_created_on,
    cd_created_by, cd_modified_on, cd_modified_by
)
SELECT
    cd_id, cd_doc_type, cd_doc_id, cd_slno, cd_comp_id, cd_branch_id, cd_acc_year,
    cd_voucher_no, cd_chg_id, cd_chg_name, cd_role, cd_method, cd_type, cd_apply_on,
    cd_ledger_code, cd_landing_cost, cd_cost_alloc, cd_before_tax, cd_tax_apl,
    cd_sep_post, cd_unit, cd_qty_val, cd_weight, cd_rate, cd_amount, cd_tax_code,
    cd_hsn, cd_tax_perc, cd_tax_amt, cd_sgst_perc, cd_sgst_amt, cd_cgst_perc,
    cd_cgst_amt, cd_igst_perc, cd_igst_amt, cd_cess_perc, cd_cess_amt, cd_net_amt,
    cd_remarks, cd_is_active, cd_is_deleted, cd_sync_date, cd_created_on,
    cd_created_by, cd_modified_on, cd_modified_by
FROM sales.sale_charge_detail;


-- ───────────────────────────────────────────────────────────────────────────
--  6. Prove nothing was lost, then drop the old table
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_old bigint;
        v_new bigint;
    BEGIN
        SELECT count(*) INTO v_old FROM sales.sale_charge_detail;
        SELECT count(*) INTO v_new FROM public.txn_charge_detail;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'sale_charge_detail copy lost rows: % -> %', v_old, v_new;
        END IF;
    END;
$$;

DROP TABLE sales.sale_charge_detail;
