-- CreateTable
-- accounts.acc_tender_types / accounts.acc_tender_master use partial unique
-- indexes, partial btree indexes, and CHECK constraints that Prisma Migrate
-- cannot express, so this migration is hand-written rather than generated by
-- `prisma migrate dev` (see prisma/accounts/accountTenderTypes.prisma and
-- accountTenderMaster.prisma for the corresponding models + documentation of
-- which indexes are DB-only).
--
-- Note: tnd_tally_guid was added below even though the original spec's
-- CREATE TABLE omitted it — ix_tnd_tally_guid indexes that column, and the
-- sibling *_tally_guid columns elsewhere (acc_ledger_master, acc_group) show
-- the intended shape.
--
-- Both tables already existed physically with an older, narrower shape
-- (acc_ttm_type_id/acc_tnd_id etc. — from the now-deleted
-- prisma/accounts/AccountTenderTypes.prisma + AccounttenderMaster.prisma
-- fragments) but were never wired to any application code and hold zero
-- rows, so they are dropped and recreated here rather than altered in place.

DROP TABLE IF EXISTS accounts.acc_tender_master;
DROP TABLE IF EXISTS accounts.acc_tender_types;

-- ═══════════════════════════════════════════════════════════════════════════
--  1. Tender types (fixed, tenant-agnostic catalogue)
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS accounts.acc_tender_types
(
    ttm_type_id           integer NOT NULL,
    ttm_type_name         character varying(50) NOT NULL,
    ttm_display_name      character varying(50) NOT NULL,
    ttm_is_cash           boolean NOT NULL DEFAULT false,   -- counts in the cash drawer
    ttm_needs_ref         boolean NOT NULL DEFAULT false,   -- ref no mandatory (card/UPI/cheque)
    ttm_ref_label         character varying(30),            -- "UTR No", "Cheque No", "Card Last 4"
    ttm_sale_only         boolean NOT NULL DEFAULT false,
    ttm_allow_change      boolean NOT NULL DEFAULT false,   -- over-tender + change return allowed
    ttm_allow_in_return   boolean NOT NULL DEFAULT true,    -- refund can go back on this tender
    ttm_display_order     integer NOT NULL DEFAULT 0,
    ttm_is_active         boolean NOT NULL DEFAULT true,
    ttm_is_deleted        boolean NOT NULL DEFAULT false,
    ttm_sync_date         timestamp(6) with time zone,
    ttm_created_on        timestamp(6) with time zone NOT NULL DEFAULT now(),
    ttm_created_by        character varying(50),
    ttm_modified_on       timestamp(6) with time zone,
    ttm_modified_by       character varying(50),

    CONSTRAINT pk_acc_tender_types PRIMARY KEY (ttm_type_id),
    CONSTRAINT ux_ttm_name UNIQUE (ttm_type_name),
    CONSTRAINT ck_ttm_ref_label
        CHECK (ttm_needs_ref = false OR ttm_ref_label IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_ttm_display_order
    ON accounts.acc_tender_types USING btree (ttm_display_order)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE ttm_is_active = true AND ttm_is_deleted = false;


INSERT INTO accounts.acc_tender_types
    (ttm_type_id, ttm_type_name, ttm_display_name, ttm_is_cash, ttm_needs_ref,
     ttm_ref_label, ttm_sale_only, ttm_allow_change, ttm_allow_in_return, ttm_display_order)
VALUES
    ( 1, 'CASH',    'Cash',            true,  false, NULL,            false, true,  true,   10),
    ( 2, 'CARD',    'Card',            false, true,  'Card Last 4',   false, false, true,   20),
    ( 3, 'UPI',     'UPI',             false, true,  'UTR No',        false, false, true,   30),
    ( 4, 'WALLET',  'Wallet',          false, true,  'Txn Ref',       false, false, true,   40),
    ( 5, 'CHEQUE',  'Cheque',          false, true,  'Cheque No',     false, false, true,   50),
    ( 6, 'BANK',    'Bank Transfer',   false, true,  'UTR / Ref No',  false, false, true,   60),
    ( 7, 'RRN',     'RRN',             false, true,  'RRN',           true,  false, false,  70),
    ( 8, 'TEMP_CR', 'Temporary Credit',false, true,  'Approved By',   true,  false, false,  80),
    ( 9, 'CREDIT',  'Credit',          false, false, NULL,            true,  false, false,  90),
    (10, 'LOYALTY', 'Loyalty Points',  false, false, NULL,            true,  false, false, 100),
    (11, 'VOUCHER', 'Gift Voucher',    false, true,  'Voucher No',    true,  false, false, 110)
ON CONFLICT (ttm_type_name) DO NOTHING;


-- ═══════════════════════════════════════════════════════════════════════════
--  2. Tender master (tenant scoped)
--     A concrete tender the cashier picks (e.g. "HDFC Card", "GPay"),
--     mapped to the ledger it posts to.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS accounts.acc_tender_master
(
    tnd_id                  uuid NOT NULL DEFAULT uuidv7(),

    -- tenant scope
    tnd_company_id          uuid NOT NULL,
    tnd_branch_id           uuid,                            -- NULL = available to all branches

    -- identity
    tnd_type_id             integer NOT NULL,
    tnd_name                character varying(100) NOT NULL,
    tnd_short_name          character varying(30)  NOT NULL,

    -- accounting
    tnd_ledger_id           uuid NOT NULL,                   -- final posting ledger
    tnd_settlement_ledger_id uuid,                           -- clearing/suspense (card, UPI)
    tnd_settlement_days     smallint NOT NULL DEFAULT 0,     -- T+n expected credit
    tnd_bank_account_id     uuid,                            -- acc_ledger_bank_accounts (cheque/bank)

    -- limits
    tnd_min_amount          numeric(14,2) NOT NULL DEFAULT 0,
    tnd_max_amount          numeric(14,2),
    tnd_daily_limit         numeric(14,2),

    -- surcharge / MDR
    tnd_surcharge_perc      numeric(6,3)  NOT NULL DEFAULT 0,
    tnd_surcharge_amount    numeric(14,2) NOT NULL DEFAULT 0,
    tnd_surcharge_ledger_id uuid,
    tnd_edit_surcharge      boolean NOT NULL DEFAULT false,
    tnd_edit_ledger         boolean NOT NULL DEFAULT false,

    -- payment instrument details
    tnd_upi_vpa             character varying(100),
    tnd_upi_qr_payload      text,                            -- static QR string shown on device
    tnd_merchant_id         character varying(50),           -- MID
    tnd_terminal_id         character varying(50),           -- TID
    tnd_conversion_rate     numeric(10,4) NOT NULL DEFAULT 1, -- loyalty points / voucher -> INR

    -- behaviour overrides (NULL = inherit from tender type)
    tnd_needs_ref           boolean,
    tnd_allow_change        boolean,
    tnd_allow_in_return     boolean,
    tnd_open_cash_drawer    boolean NOT NULL DEFAULT false,
    tnd_is_default          boolean NOT NULL DEFAULT false,

    -- POS presentation
    tnd_display_position    integer NOT NULL DEFAULT 0,
    tnd_hotkey              character varying(10),
    tnd_colour              character varying(9),            -- #RRGGBB / #RRGGBBAA

    -- validity
    tnd_effective_from      date,
    tnd_effective_to        date,

    tnd_remarks             character varying(250),
    tnd_is_active           boolean NOT NULL DEFAULT true,
    tnd_is_deleted          boolean NOT NULL DEFAULT false,
    tnd_tally_guid          character varying(64),           -- Tally sync identity

    -- audit
    tnd_sync_date           timestamp(6) with time zone,
    tnd_created_on          timestamp(6) with time zone NOT NULL DEFAULT now(),
    tnd_created_by          character varying(50),
    tnd_modified_on         timestamp(6) with time zone,
    tnd_modified_by         character varying(50),

    CONSTRAINT pk_acc_tender_master PRIMARY KEY (tnd_id),

    CONSTRAINT fk_tnd_type FOREIGN KEY (tnd_type_id)
        REFERENCES accounts.acc_tender_types (ttm_type_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_tnd_ledger FOREIGN KEY (tnd_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_tnd_settlement_ledger FOREIGN KEY (tnd_settlement_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_tnd_surcharge_ledger FOREIGN KEY (tnd_surcharge_ledger_id)
        REFERENCES accounts.acc_ledger_master (led_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_tnd_amount_range
        CHECK (tnd_max_amount IS NULL OR tnd_max_amount >= tnd_min_amount),
    CONSTRAINT ck_tnd_min_amount     CHECK (tnd_min_amount    >= 0),
    CONSTRAINT ck_tnd_daily_limit    CHECK (tnd_daily_limit IS NULL OR tnd_daily_limit >= 0),
    CONSTRAINT ck_tnd_surcharge_perc CHECK (tnd_surcharge_perc BETWEEN 0 AND 100),
    CONSTRAINT ck_tnd_surcharge_amt  CHECK (tnd_surcharge_amount >= 0),
    CONSTRAINT ck_tnd_settlement_days CHECK (tnd_settlement_days BETWEEN 0 AND 90),
    CONSTRAINT ck_tnd_conversion_rate CHECK (tnd_conversion_rate > 0),
    CONSTRAINT ck_tnd_effective_range
        CHECK (tnd_effective_to IS NULL OR tnd_effective_from IS NULL
               OR tnd_effective_to >= tnd_effective_from),
    CONSTRAINT ck_tnd_colour
        CHECK (tnd_colour IS NULL OR tnd_colour ~ '^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$')
);

-- ── uniqueness (soft-delete safe, tenant scoped; NULL branch = company wide) ──
CREATE UNIQUE INDEX IF NOT EXISTS ux_tnd_name
    ON accounts.acc_tender_master
       (tnd_company_id, COALESCE(tnd_branch_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(tnd_name))
    WHERE tnd_is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS ux_tnd_short_name
    ON accounts.acc_tender_master
       (tnd_company_id, COALESCE(tnd_branch_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(tnd_short_name))
    WHERE tnd_is_deleted = false;

-- only one default tender per company/branch
CREATE UNIQUE INDEX IF NOT EXISTS ux_tnd_default
    ON accounts.acc_tender_master
       (tnd_company_id, COALESCE(tnd_branch_id, '00000000-0000-0000-0000-000000000000'::uuid))
    WHERE tnd_is_default = true AND tnd_is_active = true AND tnd_is_deleted = false;

-- one hotkey per company/branch
CREATE UNIQUE INDEX IF NOT EXISTS ux_tnd_hotkey
    ON accounts.acc_tender_master
       (tnd_company_id, COALESCE(tnd_branch_id, '00000000-0000-0000-0000-000000000000'::uuid), tnd_hotkey)
    WHERE tnd_hotkey IS NOT NULL AND tnd_is_deleted = false;

-- ── lookup indexes ──────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS ix_tnd_company_branch
    ON accounts.acc_tender_master USING btree (tnd_company_id, tnd_branch_id)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE tnd_is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_tnd_type
    ON accounts.acc_tender_master USING btree (tnd_type_id)
    WITH (fillfactor=100, deduplicate_items=True);

CREATE INDEX IF NOT EXISTS ix_tnd_ledger
    ON accounts.acc_tender_master USING btree (tnd_ledger_id)
    WITH (fillfactor=100, deduplicate_items=True);

CREATE INDEX IF NOT EXISTS ix_tnd_settlement_ledger
    ON accounts.acc_tender_master USING btree (tnd_settlement_ledger_id)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE tnd_settlement_ledger_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_tnd_position
    ON accounts.acc_tender_master USING btree (tnd_company_id, tnd_display_position)
    WITH (fillfactor=100, deduplicate_items=True)
    WHERE tnd_is_active = true AND tnd_is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_tnd_tally_guid
    ON accounts.acc_tender_master USING btree (tnd_tally_guid)
    WITH (fillfactor=100)
    WHERE tnd_tally_guid IS NOT NULL;
