import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsEnum, IsObject, IsOptional } from 'class-validator';
import {
  NullableDate,
  NullableStringStrict,
  NullableUuid,
  OptionalBoolean,
  OptionalDate,
  OptionalInteger,
  OptionalNumber,
  OptionalTrimmedString,
  OptionalUpperMaxString,
  OptionalUuid,
} from 'src/common/dto/dtoDecorators';
import {
  TransactionHoldDeviceType,
  TransactionHoldDocType,
  TransactionHoldStatus,
} from '../types/transaction-hold-api.types';
// th_acc_year is SMALLINT — the fiscal year the hold belongs to, held as its
// starting year (2026 for 2026-2027). The bounds are the column's, not a
// business rule.
const ACC_YEAR_MIN = 1;
const ACC_YEAR_MAX = 32767;
// One transaction_hold row. Nothing is required by the decorators: a create needs
// the scope plus thHoldNo / thDeviceId / thDeviceType, an update needs only thId
// and the fields that change, so "required on create" is enforced in the service
// (TransactionHoldService.requireField) where the stored row fills the gaps.
export class SaveTransactionHoldDto {
  @ApiPropertyOptional({
    format: 'uuid',
    description: 'When provided, updates that hold; otherwise a new hold is created',
  })
  @OptionalUuid()
  thId?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'Required on create, immutable afterwards' })
  @OptionalUuid()
  thCompanyId?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'Required on create, immutable afterwards' })
  @OptionalUuid()
  thBranchId?: string;

  @ApiPropertyOptional({
    minimum: ACC_YEAR_MIN,
    maximum: ACC_YEAR_MAX,
    description:
      'Fiscal year the hold belongs to, as its starting year (2026 for 2026-2027). ' +
      'Required on create, immutable afterwards',
  })
  @OptionalInteger(ACC_YEAR_MIN, ACC_YEAR_MAX)
  thAccYear?: number;

  @ApiPropertyOptional({
    maxLength: 30,
    description:
      'Hold number, generated by the till. Required on create and unique per ' +
      'company / branch / accounting year',
  })
  @OptionalTrimmedString(30)
  thHoldNo?: string;

  @ApiPropertyOptional({
    type: 'string',
    format: 'date-time',
    description: 'When the transaction was parked. Defaults to now',
  })
  @OptionalDate()
  thHoldDate?: Date;

  @ApiPropertyOptional({
    enum: TransactionHoldDocType,
    enumName: 'TransactionHoldDocType',
    default: TransactionHoldDocType.SALE_INVOICE,
    description: 'What the parked screen was raising',
  })
  @OptionalUpperMaxString(20)
  @IsEnum(TransactionHoldDocType)
  thDocType?: TransactionHoldDocType;

  @ApiPropertyOptional({
    format: 'uuid',
    nullable: true,
    description: 'Till the hold was taken on',
  })
  @NullableUuid()
  thCounterId?: string | null;

  @ApiPropertyOptional({
    format: 'uuid',
    nullable: true,
    description: 'audit.user_login_sessions.ulsId',
  })
  @NullableUuid()
  thSessionId?: string | null;

  @ApiPropertyOptional({ format: 'uuid', nullable: true, description: 'Operator who parked it' })
  @NullableUuid()
  thUserId?: string | null;

  @ApiPropertyOptional({ maxLength: 64, description: 'Required on create' })
  @OptionalTrimmedString(64)
  thDeviceId?: string;

  @ApiPropertyOptional({
    enum: TransactionHoldDeviceType,
    enumName: 'TransactionHoldDeviceType',
    description: 'Hardware the hold was taken on. Required on create',
  })
  @OptionalUpperMaxString(20)
  @IsEnum(TransactionHoldDeviceType)
  thDeviceType?: TransactionHoldDeviceType;

  @ApiPropertyOptional({
    maxLength: 150,
    nullable: true,
    description: 'Walk-in name shown on the held-bills list; the cart itself lives in thUiState',
  })
  @NullableStringStrict(150)
  thCustomerName?: string | null;

  @ApiPropertyOptional({ minimum: 0, default: 0, description: 'Lines parked with the hold' })
  @OptionalInteger(0)
  thItemCount?: number;

  @ApiPropertyOptional({
    default: 0,
    description: 'Signed: a SALE_RETURN hold parks a negative quantity',
  })
  @OptionalNumber()
  thTotalQty?: number;

  // ck_th_total_amount — the parked total is a gross value, never negative, even
  // on a return hold.
  @ApiPropertyOptional({ minimum: 0, default: 0 })
  @OptionalNumber(0)
  thTotalAmount?: number;

  @ApiPropertyOptional({
    enum: TransactionHoldStatus,
    enumName: 'TransactionHoldStatus',
    default: TransactionHoldStatus.HELD,
    description:
      'CONVERTED / CANCELLED / EXPIRED are terminal — a hold in one of them cannot be reopened',
  })
  @OptionalUpperMaxString(15)
  @IsEnum(TransactionHoldStatus)
  thStatus?: TransactionHoldStatus;

  @ApiPropertyOptional({ maxLength: 100, nullable: true, description: 'Why it was parked' })
  @NullableStringStrict(100)
  thHoldReason?: string | null;

  @ApiPropertyOptional({ maxLength: 255, nullable: true })
  @NullableStringStrict(255)
  thRemarks?: string | null;

  @ApiPropertyOptional({
    type: 'string',
    format: 'date-time',
    nullable: true,
    description: 'When the hold lapses; must be after thHoldDate',
  })
  @NullableDate()
  thExpiresAt?: Date | null;

  // Device id, not a user id: the edit lock is held by the till (X-Device-Id),
  // which is why this matches thDeviceId's 64 rather than the audit columns' 50.
  // The lock endpoints (resume / release / convert) are what normally move it —
  // setting it through this payload bypasses the ownership check.
  @ApiPropertyOptional({
    maxLength: 64,
    nullable: true,
    description: 'Device id holding the edit lock',
  })
  @NullableStringStrict(64)
  thLockedBy?: string | null;

  @ApiPropertyOptional({ type: 'string', format: 'date-time', nullable: true })
  @NullableDate()
  thLockedAt?: Date | null;

  @ApiPropertyOptional({ maxLength: 64, nullable: true, description: 'Device id' })
  @NullableStringStrict(64)
  thResumedBy?: string | null;

  @ApiPropertyOptional({ type: 'string', format: 'date-time', nullable: true })
  @NullableDate()
  thResumedAt?: Date | null;

  @ApiPropertyOptional({
    minimum: 0,
    default: 0,
    description: 'How often the hold was pulled back',
  })
  @OptionalInteger(0)
  thResumeCount?: number;

  @ApiPropertyOptional({
    enum: TransactionHoldDocType,
    enumName: 'TransactionHoldDocType',
    nullable: true,
    description: 'Kind of document the hold became; required once thConvertedDocId is set',
  })
  @OptionalUpperMaxString(20)
  @IsEnum(TransactionHoldDocType)
  thConvertedDocType?: TransactionHoldDocType | null;

  @ApiPropertyOptional({
    format: 'uuid',
    nullable: true,
    description: 'Document the hold became (polymorphic, no FK). Required when thStatus=CONVERTED',
  })
  @NullableUuid()
  thConvertedDocId?: string | null;

  @ApiPropertyOptional({ maxLength: 30, nullable: true, description: 'That document’s number' })
  @NullableStringStrict(30)
  thConvertedNo?: string | null;

  @ApiPropertyOptional({ type: 'string', format: 'date-time', nullable: true })
  @NullableDate()
  thConvertedAt?: Date | null;

  @ApiPropertyOptional({ maxLength: 50, nullable: true, description: 'Actor id or name' })
  @NullableStringStrict(50)
  thConvertedBy?: string | null;

  @ApiPropertyOptional({
    default: false,
    description: 'Whether the hold soft-blocks stock; this module only records the flag',
  })
  @OptionalBoolean()
  thIsStockReserved?: boolean;

  @ApiPropertyOptional({
    type: 'object',
    additionalProperties: true,
    nullable: true,
    description: 'Screen state (cart lines, discounts, focus) stored and returned verbatim',
  })
  @IsOptional()
  @IsObject()
  thUiState?: Record<string, unknown> | null;

  // th_created_by / th_modified_by are varchar(50), not uuid: the actor is
  // whatever resolveActor settles on — a user id, but equally a name or login
  // the caller passed.
  @ApiPropertyOptional({
    maxLength: 50,
    nullable: true,
    description: 'Actor id or name; defaults to the caller',
  })
  @NullableStringStrict(50)
  thCreatedBy?: string | null;

  @ApiPropertyOptional({
    maxLength: 50,
    nullable: true,
    description: 'Actor id or name; defaults to the caller',
  })
  @NullableStringStrict(50)
  thModifiedBy?: string | null;
}
