/*
  Warnings:

  - You are about to drop the column `sqi_unit_id` on the `sale_quotation_item` table. All the data in the column will be lost.
  - The `sale_quotation_item` quantity columns are renamed: sqi_qty_case -> sqi_case_qty, sqi_qty_bill -> sqi_bill_qty,
    sqi_qty_length -> sqi_length_qty, sqi_qty_net_qty -> sqi_net_qty. New columns: sqi_weight_qty, sqi_mrp_savings,
    sqi_mrp_savings_perc, sq_mrp_savings, sq_mrp_savings_perc.

  Column order for sale_quotation and sale_quotation_item is rebuilt to match the field order in the
  prisma/sales fragment files (Postgres has no in-place ALTER TABLE column reorder, so both tables are recreated).
*/

-- CreateTable (sale_quotation, rebuilt with target column order)
CREATE TABLE "sales"."sale_quotation_new" (
    "sq_id" uuid DEFAULT uuidv7() NOT NULL,
    "sq_company_id" uuid NOT NULL,
    "sq_branch_id" uuid NOT NULL,
    "sq_tenant_id" uuid NOT NULL,
    "sq_acc_year" character(9) NOT NULL,
    "sq_session_id" uuid,
    "sq_category_id" uuid,
    "sq_price_level" integer NOT NULL,
    "sq_doc_type" character varying(30) DEFAULT 'QUOTATION'::character varying NOT NULL,
    "sq_quote_slno" bigint NOT NULL,
    "sq_quote_refno" character varying(100) NOT NULL,
    "sq_usr_refno" character varying(100),
    "sq_quote_date" date NOT NULL,
    "sq_quote_datetime" timestamp(6) with time zone DEFAULT now() NOT NULL,
    "sq_valid_until" date,
    "sq_validity_days" integer,
    "sq_revision_no" integer DEFAULT 0 NOT NULL,
    "sq_parent_quote_id" uuid,
    "sq_src_doc_type" character varying(30),
    "sq_src_doc_id" uuid,
    "sq_src_doc_refno" character varying(100),
    "sq_src_doc_date" timestamp(6) with time zone,
    "sq_cust_id" uuid,
    "sq_cust_area_id" uuid,
    "sq_cust_name" character varying(200) NOT NULL,
    "sq_cust_addr" character varying(500),
    "sq_cust_place" character varying(100),
    "sq_cust_phone" character varying(20),
    "sq_cust_email" character varying(150),
    "sq_cust_gstin" character varying(15),
    "sq_cust_gst_type" character varying(20),
    "sq_cust_stcd" character(2),
    "sq_pos_stcd" character(2),
    "sq_contact_person" character varying(150),
    "sq_contact_phone" character varying(20),
    "sq_has_load" boolean DEFAULT false NOT NULL,
    "sq_has_unload" boolean DEFAULT false NOT NULL,
    "sq_has_freight" boolean DEFAULT false NOT NULL,
    "sq_has_promo" boolean DEFAULT false NOT NULL,
    "sq_has_comm" boolean DEFAULT false NOT NULL,
    "sq_user_id" uuid NOT NULL,
    "sq_salesman_id" uuid,
    "sq_agent_id" uuid,
    "sq_tot_items" integer DEFAULT 0 NOT NULL,
    "sq_tot_weight" numeric(15,3) DEFAULT 0 NOT NULL,
    "sq_tot_bags" numeric(15,3) DEFAULT 0 NOT NULL,
    "sq_gross_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_item_disc" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_spl_disc" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_sch_disc" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_bill_sch_disc" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_addl_disc1" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_addl_disc2" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_taxable_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_cgst_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_sgst_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_igst_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_cess_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_tax_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_freight_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_load_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_unload_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_other_amt1" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_other_amt2" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_round_off" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_quote_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sq_total_cost" numeric(15,2),
    "sq_margin_amt" numeric(15,2),
    "sq_margin_perc" numeric(15,4),
    "sq_payment_terms" character varying(250),
    "sq_delivery_terms" character varying(250),
    "sq_terms_conditions" text,
    "sq_status" character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    "sq_sent_on" timestamp(6) with time zone,
    "sq_accepted_on" timestamp(6) with time zone,
    "sq_rejected_on" timestamp(6) with time zone,
    "sq_reject_reason" character varying(250),
    "sq_converted_doc_type" character varying(30),
    "sq_converted_doc_id" uuid,
    "sq_converted_on" timestamp(6) with time zone,
    "sq_approved_on" timestamp(6) with time zone,
    "sq_approved_by" uuid,
    "sq_cancelled_on" timestamp(6) with time zone,
    "sq_cancelled_by" uuid,
    "sq_cancel_reason" character varying(250),
    "sq_mrp_savings" numeric(15,3) DEFAULT 0,
    "sq_mrp_savings_perc" numeric(15,4) DEFAULT 0,
    "sq_print_count" integer DEFAULT 0 NOT NULL,
    "sq_device_type" character varying(20),
    "sq_device_id" uuid,
    "sq_remarks" character varying(500),
    "sq_is_deleted" boolean DEFAULT false NOT NULL,
    "sq_sync_date" timestamp(6) with time zone,
    "sq_created_on" timestamp(6) with time zone DEFAULT now() NOT NULL,
    "sq_created_by" uuid NOT NULL,
    "sq_modified_on" timestamp(6) with time zone,
    "sq_modified_by" uuid,
    CONSTRAINT "ck_sq_status" CHECK (((sq_status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SENT'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'EXPIRED'::character varying, 'CONVERTED'::character varying, 'CANCELLED'::character varying])::text[])))
);

-- CreateTable (sale_quotation_item, rebuilt with target column order)
CREATE TABLE "sales"."sale_quotation_item_new" (
    "sqi_id" uuid DEFAULT uuidv7() NOT NULL,
    "sqi_quote_id" uuid NOT NULL,
    "sqi_company_id" uuid NOT NULL,
    "sqi_branch_id" uuid NOT NULL,
    "sqi_tenant_id" uuid NOT NULL,
    "sqi_acc_year" character(9) NOT NULL,
    "sqi_src_doc_type" character varying(30),
    "sqi_src_item_id" uuid,
    "sqi_src_unit_id" uuid,
    "sqi_src_doc_refno" character varying(100),
    "sqi_src_item_qty" numeric(15,3),
    "sqi_line_no" integer NOT NULL,
    "sqi_item_id" uuid NOT NULL,
    "sqi_item_unit_id" uuid NOT NULL,
    "sqi_hsn_code" character varying(8),
    "sqi_price_level" integer NOT NULL,
    "sqi_ean_code" character varying(100),
    "sqi_batch_no" character varying(100),
    "sqi_batch_date" date,
    "sqi_expiry_date" date,
    "sqi_is_tax_incl" boolean DEFAULT false NOT NULL,
    "sqi_is_promo" boolean DEFAULT false NOT NULL,
    "sqi_is_free" boolean DEFAULT false NOT NULL,
    "sqi_free_type" character varying(20),
    "sqi_is_service" boolean DEFAULT false NOT NULL,
    "sqi_case_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_bill_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_length_qty" numeric(15,3) DEFAULT 0,
    "sqi_net_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_weight_qty" numeric(15,3) DEFAULT 0,
    "sqi_available_stock" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_rate" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_rate_pre_tax" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_item_disc_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_item_disc_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_item_disc_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_spl_disc_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_spl_disc_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_spl_disc_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_sch_disc_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_sch_disc_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_sch_disc_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_bill_sch_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_bill_sch_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_bill_sch_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_addl_disc1_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_addl_disc1_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_addl_disc2_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_addl_disc2_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_cash_disc_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_cash_disc_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_gross_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_taxable_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_tax_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_tax_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_cgst_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_cgst_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_sgst_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_sgst_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_igst_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_igst_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_cess_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_cess_per_unit" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_cess_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_acess_perc" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_acess_per_unit" numeric(15,4) DEFAULT 0 NOT NULL,
    "sqi_acess_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_freight_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_freight_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_load_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_load_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_unload_qty" numeric(15,3) DEFAULT 0 NOT NULL,
    "sqi_unload_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_round_off" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_net_amt" numeric(15,2) DEFAULT 0 NOT NULL,
    "sqi_cost_price" numeric(15,4),
    "sqi_max_price" numeric(15,4),
    "sqi_min_price" numeric(15,4),
    "sqi_act_price" numeric(15,4),
    "sqi_quote_price" numeric(15,4),
    "sqi_item_profit" numeric(15,2),
    "sqi_cost_pre_tax" numeric(15,2),
    "sqi_quote_pre_tax" numeric(15,2),
    "sqi_profit_pre_tax" numeric(15,2),
    "sqi_mrp_savings" numeric(15,3),
    "sqi_mrp_savings_perc" numeric(15,4),
    "sqi_scheme_id" uuid,
    "sqi_scheme_name" character varying(150),
    "sqi_remarks" character varying(250),
    "sqi_is_deleted" boolean DEFAULT false NOT NULL,
    "sqi_sync_date" timestamp(6) with time zone,
    "sqi_created_on" timestamp(6) with time zone DEFAULT now() NOT NULL,
    "sqi_created_by" uuid NOT NULL,
    "sqi_modified_on" timestamp(6) with time zone,
    "sqi_modified_by" uuid,
    CONSTRAINT "ck_sqi_free_type" CHECK (((sqi_free_type IS NULL) OR ((sqi_free_type)::text = ANY (ARRAY[('SCHEME'::character varying)::text, ('SAMPLE'::character varying)::text]))))
);

-- CopyData (sale_quotation) -- sq_mrp_savings / sq_mrp_savings_perc are new here, take their DEFAULT 0
INSERT INTO "sales"."sale_quotation_new" (
    "sq_id",
    "sq_company_id",
    "sq_branch_id",
    "sq_tenant_id",
    "sq_acc_year",
    "sq_session_id",
    "sq_category_id",
    "sq_price_level",
    "sq_doc_type",
    "sq_quote_slno",
    "sq_quote_refno",
    "sq_usr_refno",
    "sq_quote_date",
    "sq_quote_datetime",
    "sq_valid_until",
    "sq_validity_days",
    "sq_revision_no",
    "sq_parent_quote_id",
    "sq_src_doc_type",
    "sq_src_doc_id",
    "sq_src_doc_refno",
    "sq_src_doc_date",
    "sq_cust_id",
    "sq_cust_area_id",
    "sq_cust_name",
    "sq_cust_addr",
    "sq_cust_place",
    "sq_cust_phone",
    "sq_cust_email",
    "sq_cust_gstin",
    "sq_cust_gst_type",
    "sq_cust_stcd",
    "sq_pos_stcd",
    "sq_contact_person",
    "sq_contact_phone",
    "sq_has_load",
    "sq_has_unload",
    "sq_has_freight",
    "sq_has_promo",
    "sq_has_comm",
    "sq_user_id",
    "sq_salesman_id",
    "sq_agent_id",
    "sq_tot_items",
    "sq_tot_weight",
    "sq_tot_bags",
    "sq_gross_amt",
    "sq_item_disc",
    "sq_spl_disc",
    "sq_sch_disc",
    "sq_bill_sch_disc",
    "sq_addl_disc1",
    "sq_addl_disc2",
    "sq_taxable_amt",
    "sq_cgst_amt",
    "sq_sgst_amt",
    "sq_igst_amt",
    "sq_cess_amt",
    "sq_tax_amt",
    "sq_freight_amt",
    "sq_load_amt",
    "sq_unload_amt",
    "sq_other_amt1",
    "sq_other_amt2",
    "sq_round_off",
    "sq_quote_amt",
    "sq_total_cost",
    "sq_margin_amt",
    "sq_margin_perc",
    "sq_payment_terms",
    "sq_delivery_terms",
    "sq_terms_conditions",
    "sq_status",
    "sq_sent_on",
    "sq_accepted_on",
    "sq_rejected_on",
    "sq_reject_reason",
    "sq_converted_doc_type",
    "sq_converted_doc_id",
    "sq_converted_on",
    "sq_approved_on",
    "sq_approved_by",
    "sq_cancelled_on",
    "sq_cancelled_by",
    "sq_cancel_reason",
    "sq_print_count",
    "sq_device_type",
    "sq_device_id",
    "sq_remarks",
    "sq_is_deleted",
    "sq_sync_date",
    "sq_created_on",
    "sq_created_by",
    "sq_modified_on",
    "sq_modified_by"
)
SELECT
    "sq_id",
    "sq_company_id",
    "sq_branch_id",
    "sq_tenant_id",
    "sq_acc_year",
    "sq_session_id",
    "sq_category_id",
    "sq_price_level",
    "sq_doc_type",
    "sq_quote_slno",
    "sq_quote_refno",
    "sq_usr_refno",
    "sq_quote_date",
    "sq_quote_datetime",
    "sq_valid_until",
    "sq_validity_days",
    "sq_revision_no",
    "sq_parent_quote_id",
    "sq_src_doc_type",
    "sq_src_doc_id",
    "sq_src_doc_refno",
    "sq_src_doc_date",
    "sq_cust_id",
    "sq_cust_area_id",
    "sq_cust_name",
    "sq_cust_addr",
    "sq_cust_place",
    "sq_cust_phone",
    "sq_cust_email",
    "sq_cust_gstin",
    "sq_cust_gst_type",
    "sq_cust_stcd",
    "sq_pos_stcd",
    "sq_contact_person",
    "sq_contact_phone",
    "sq_has_load",
    "sq_has_unload",
    "sq_has_freight",
    "sq_has_promo",
    "sq_has_comm",
    "sq_user_id",
    "sq_salesman_id",
    "sq_agent_id",
    "sq_tot_items",
    "sq_tot_weight",
    "sq_tot_bags",
    "sq_gross_amt",
    "sq_item_disc",
    "sq_spl_disc",
    "sq_sch_disc",
    "sq_bill_sch_disc",
    "sq_addl_disc1",
    "sq_addl_disc2",
    "sq_taxable_amt",
    "sq_cgst_amt",
    "sq_sgst_amt",
    "sq_igst_amt",
    "sq_cess_amt",
    "sq_tax_amt",
    "sq_freight_amt",
    "sq_load_amt",
    "sq_unload_amt",
    "sq_other_amt1",
    "sq_other_amt2",
    "sq_round_off",
    "sq_quote_amt",
    "sq_total_cost",
    "sq_margin_amt",
    "sq_margin_perc",
    "sq_payment_terms",
    "sq_delivery_terms",
    "sq_terms_conditions",
    "sq_status",
    "sq_sent_on",
    "sq_accepted_on",
    "sq_rejected_on",
    "sq_reject_reason",
    "sq_converted_doc_type",
    "sq_converted_doc_id",
    "sq_converted_on",
    "sq_approved_on",
    "sq_approved_by",
    "sq_cancelled_on",
    "sq_cancelled_by",
    "sq_cancel_reason",
    "sq_print_count",
    "sq_device_type",
    "sq_device_id",
    "sq_remarks",
    "sq_is_deleted",
    "sq_sync_date",
    "sq_created_on",
    "sq_created_by",
    "sq_modified_on",
    "sq_modified_by"
FROM "sales"."sale_quotation";

-- CopyData (sale_quotation_item) -- renamed qty columns are read from their old names;
-- sqi_weight_qty / sqi_mrp_savings / sqi_mrp_savings_perc are new here, take their DEFAULT
INSERT INTO "sales"."sale_quotation_item_new" (
    "sqi_id",
    "sqi_quote_id",
    "sqi_company_id",
    "sqi_branch_id",
    "sqi_tenant_id",
    "sqi_acc_year",
    "sqi_src_doc_type",
    "sqi_src_item_id",
    "sqi_src_unit_id",
    "sqi_src_doc_refno",
    "sqi_src_item_qty",
    "sqi_line_no",
    "sqi_item_id",
    "sqi_item_unit_id",
    "sqi_hsn_code",
    "sqi_price_level",
    "sqi_ean_code",
    "sqi_batch_no",
    "sqi_batch_date",
    "sqi_expiry_date",
    "sqi_is_tax_incl",
    "sqi_is_promo",
    "sqi_is_free",
    "sqi_free_type",
    "sqi_is_service",
    "sqi_case_qty",
    "sqi_bill_qty",
    "sqi_length_qty",
    "sqi_net_qty",
    "sqi_available_stock",
    "sqi_rate",
    "sqi_rate_pre_tax",
    "sqi_item_disc_perc",
    "sqi_item_disc_qty",
    "sqi_item_disc_amt",
    "sqi_spl_disc_perc",
    "sqi_spl_disc_qty",
    "sqi_spl_disc_amt",
    "sqi_sch_disc_perc",
    "sqi_sch_disc_qty",
    "sqi_sch_disc_amt",
    "sqi_bill_sch_perc",
    "sqi_bill_sch_qty",
    "sqi_bill_sch_amt",
    "sqi_addl_disc1_perc",
    "sqi_addl_disc1_amt",
    "sqi_addl_disc2_perc",
    "sqi_addl_disc2_amt",
    "sqi_cash_disc_perc",
    "sqi_cash_disc_amt",
    "sqi_gross_amt",
    "sqi_taxable_amt",
    "sqi_tax_perc",
    "sqi_tax_amt",
    "sqi_cgst_perc",
    "sqi_cgst_amt",
    "sqi_sgst_perc",
    "sqi_sgst_amt",
    "sqi_igst_perc",
    "sqi_igst_amt",
    "sqi_cess_perc",
    "sqi_cess_per_unit",
    "sqi_cess_amt",
    "sqi_acess_perc",
    "sqi_acess_per_unit",
    "sqi_acess_amt",
    "sqi_freight_qty",
    "sqi_freight_amt",
    "sqi_load_qty",
    "sqi_load_amt",
    "sqi_unload_qty",
    "sqi_unload_amt",
    "sqi_round_off",
    "sqi_net_amt",
    "sqi_cost_price",
    "sqi_max_price",
    "sqi_min_price",
    "sqi_act_price",
    "sqi_quote_price",
    "sqi_item_profit",
    "sqi_cost_pre_tax",
    "sqi_quote_pre_tax",
    "sqi_profit_pre_tax",
    "sqi_scheme_id",
    "sqi_scheme_name",
    "sqi_remarks",
    "sqi_is_deleted",
    "sqi_sync_date",
    "sqi_created_on",
    "sqi_created_by",
    "sqi_modified_on",
    "sqi_modified_by"
)
SELECT
    "sqi_id",
    "sqi_quote_id",
    "sqi_company_id",
    "sqi_branch_id",
    "sqi_tenant_id",
    "sqi_acc_year",
    "sqi_src_doc_type",
    "sqi_src_item_id",
    "sqi_src_unit_id",
    "sqi_src_doc_refno",
    "sqi_src_item_qty",
    "sqi_line_no",
    "sqi_item_id",
    "sqi_item_unit_id",
    "sqi_hsn_code",
    "sqi_price_level",
    "sqi_ean_code",
    "sqi_batch_no",
    "sqi_batch_date",
    "sqi_expiry_date",
    "sqi_is_tax_incl",
    "sqi_is_promo",
    "sqi_is_free",
    "sqi_free_type",
    "sqi_is_service",
    "sqi_qty_case",
    "sqi_qty_bill",
    "sqi_qty_length",
    "sqi_qty_net_qty",
    "sqi_available_stock",
    "sqi_rate",
    "sqi_rate_pre_tax",
    "sqi_item_disc_perc",
    "sqi_item_disc_qty",
    "sqi_item_disc_amt",
    "sqi_spl_disc_perc",
    "sqi_spl_disc_qty",
    "sqi_spl_disc_amt",
    "sqi_sch_disc_perc",
    "sqi_sch_disc_qty",
    "sqi_sch_disc_amt",
    "sqi_bill_sch_perc",
    "sqi_bill_sch_qty",
    "sqi_bill_sch_amt",
    "sqi_addl_disc1_perc",
    "sqi_addl_disc1_amt",
    "sqi_addl_disc2_perc",
    "sqi_addl_disc2_amt",
    "sqi_cash_disc_perc",
    "sqi_cash_disc_amt",
    "sqi_gross_amt",
    "sqi_taxable_amt",
    "sqi_tax_perc",
    "sqi_tax_amt",
    "sqi_cgst_perc",
    "sqi_cgst_amt",
    "sqi_sgst_perc",
    "sqi_sgst_amt",
    "sqi_igst_perc",
    "sqi_igst_amt",
    "sqi_cess_perc",
    "sqi_cess_per_unit",
    "sqi_cess_amt",
    "sqi_acess_perc",
    "sqi_acess_per_unit",
    "sqi_acess_amt",
    "sqi_freight_qty",
    "sqi_freight_amt",
    "sqi_load_qty",
    "sqi_load_amt",
    "sqi_unload_qty",
    "sqi_unload_amt",
    "sqi_round_off",
    "sqi_net_amt",
    "sqi_cost_price",
    "sqi_max_price",
    "sqi_min_price",
    "sqi_act_price",
    "sqi_quote_price",
    "sqi_item_profit",
    "sqi_cost_pre_tax",
    "sqi_quote_pre_tax",
    "sqi_profit_pre_tax",
    "sqi_scheme_id",
    "sqi_scheme_name",
    "sqi_remarks",
    "sqi_is_deleted",
    "sqi_sync_date",
    "sqi_created_on",
    "sqi_created_by",
    "sqi_modified_on",
    "sqi_modified_by"
FROM "sales"."sale_quotation_item";

-- DropTable (also drops old FKs: fk_sqi_unit, fk_sqi_item, fk_sqi_item_unit, fk_sqi_price_level, fk_sqi_quote)
DROP TABLE "sales"."sale_quotation_item";

-- DropTable (also drops old FKs: fk_sq_cust, fk_sq_cust_area, fk_sq_parent, fk_sq_price_level)
DROP TABLE "sales"."sale_quotation";

-- RenameTable
ALTER TABLE "sales"."sale_quotation_new" RENAME TO "sale_quotation";
ALTER TABLE "sales"."sale_quotation_item_new" RENAME TO "sale_quotation_item";

-- AddPrimaryKey
ALTER TABLE "sales"."sale_quotation" ADD CONSTRAINT "pk_sale_quotation" PRIMARY KEY ("sq_id");
ALTER TABLE "sales"."sale_quotation_item" ADD CONSTRAINT "pk_sale_quotation_item" PRIMARY KEY ("sqi_id");

-- CreateIndex (sale_quotation)
CREATE INDEX "ix_sq_conv" ON "sales"."sale_quotation"("sq_converted_doc_id") WHERE "sq_converted_doc_id" IS NOT NULL;
CREATE INDEX "ix_sq_cust" ON "sales"."sale_quotation"("sq_cust_id") WHERE "sq_cust_id" IS NOT NULL;
CREATE INDEX "ix_sq_date" ON "sales"."sale_quotation"("sq_company_id", "sq_branch_id", "sq_quote_date");
CREATE INDEX "ix_sq_parent" ON "sales"."sale_quotation"("sq_parent_quote_id") WHERE "sq_parent_quote_id" IS NOT NULL;
CREATE INDEX "ix_sq_status" ON "sales"."sale_quotation"("sq_status") WHERE "sq_is_deleted" = false;
CREATE INDEX "ix_sq_valid" ON "sales"."sale_quotation"("sq_valid_until") WHERE ("sq_status" IN ('SENT','ACCEPTED') AND "sq_is_deleted" = false);
CREATE UNIQUE INDEX "ux_sq_quote_no" ON "sales"."sale_quotation"("sq_company_id","sq_branch_id","sq_acc_year","sq_quote_refno","sq_revision_no") WHERE "sq_is_deleted" = false;
CREATE UNIQUE INDEX "ux_sq_slno" ON "sales"."sale_quotation"("sq_company_id","sq_branch_id","sq_acc_year","sq_quote_slno") WHERE "sq_is_deleted" = false;

-- CreateIndex (sale_quotation_item)
CREATE INDEX "ix_sqi_hsn" ON "sales"."sale_quotation_item"("sqi_hsn_code");
CREATE INDEX "ix_sqi_item" ON "sales"."sale_quotation_item"("sqi_item_id");
CREATE INDEX "ix_sqi_quote" ON "sales"."sale_quotation_item"("sqi_quote_id");
CREATE UNIQUE INDEX "ux_sqi_quote_line" ON "sales"."sale_quotation_item"("sqi_quote_id", "sqi_line_no") WHERE "sqi_is_deleted" = false;

-- AddForeignKey (sale_quotation)
ALTER TABLE "sales"."sale_quotation" ADD CONSTRAINT "fk_sq_cust" FOREIGN KEY ("sq_cust_id") REFERENCES "sales"."customers"("cus_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales"."sale_quotation" ADD CONSTRAINT "fk_sq_cust_area" FOREIGN KEY ("sq_cust_area_id") REFERENCES "sales"."area_master"("arm_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales"."sale_quotation" ADD CONSTRAINT "fk_sq_parent" FOREIGN KEY ("sq_parent_quote_id") REFERENCES "sales"."sale_quotation"("sq_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "sales"."sale_quotation" ADD CONSTRAINT "fk_sq_price_level" FOREIGN KEY ("sq_price_level") REFERENCES "inventory"."item_price_levels"("ipl_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey (sale_quotation_item)
ALTER TABLE "sales"."sale_quotation_item" ADD CONSTRAINT "fk_sqi_item" FOREIGN KEY ("sqi_item_id") REFERENCES "inventory"."item_master"("item_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales"."sale_quotation_item" ADD CONSTRAINT "fk_sqi_item_unit" FOREIGN KEY ("sqi_item_unit_id") REFERENCES "inventory"."item_unit_conversion"("iuc_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales"."sale_quotation_item" ADD CONSTRAINT "fk_sqi_item_unit_id" FOREIGN KEY ("sqi_item_unit_id") REFERENCES "inventory"."item_unit_master"("unit_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales"."sale_quotation_item" ADD CONSTRAINT "fk_sqi_price_level" FOREIGN KEY ("sqi_price_level") REFERENCES "inventory"."item_price_levels"("ipl_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales"."sale_quotation_item" ADD CONSTRAINT "fk_sqi_quote" FOREIGN KEY ("sqi_quote_id") REFERENCES "sales"."sale_quotation"("sq_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
