-- Convert sales.sale_quotation / sales.sale_quotation_item to declaratively
-- LIST-partitioned tables keyed on acc_year, the way sale_bill (20260731070026),
-- acc_tender_detail (20260731090000) and sale_order (20260808132323) already
-- are. A quotation is an accounting-year document: every read is scoped by
-- company/branch/year, and a closed year should be prunable as a unit.
--
-- Postgres cannot ALTER an ordinary table into a partitioned one, so the two
-- tables are rebuilt: the existing ones are parked under `_unpart` names, the
-- partitioned parents are created with the same columns, their rows are copied
-- over, and the parked tables are dropped.
--
-- Three things change beyond the storage layout:
--
--   1. The primary keys gain the partition key -- pk_sale_quotation is now
--      (sq_id, sq_acc_year) and pk_sale_quotation_item (sqi_id, sqi_acc_year).
--      Postgres requires every unique constraint on a partitioned table to
--      contain the partition key. Callers must therefore address a row by the
--      pair, not by the id alone.
--   2. ux_sqi_quote_line gains sqi_acc_year for the same reason. It stays a
--      partial index over the active lines, so the "one active line number per
--      quotation" rule is unchanged (a line always carries its header's year).
--   3. fk_sq_parent -- the revision self-reference -- needs the parent's year to
--      point at the composite key, so sq_parent_acc_year is added alongside
--      sq_parent_quote_id and the two are kept null-or-set together
--      (ck_sq_parent_pair). This mirrors soi_src_doc_acc_year /
--      soa_target_acc_year on sale_order.
--
-- Column order follows the prisma/sales/*.prisma field order, which the
-- rebuild is a free opportunity to restore (sq_state_name and the charge
-- calculation columns had drifted to the end of the table when later
-- migrations added them).
--
-- Prisma Migrate can express none of PARTITION BY, composite partition-aware
-- primary keys, partial indexes or CHECK constraints, so this migration is
-- hand-written rather than generated by `prisma migrate dev`.


-- ───────────────────────────────────────────────────────────────────────────
--  1. Park the unpartitioned tables
--
--  Constraint names are per-table, but index names are per-schema, so every
--  index the rebuilt tables re-declare has to be moved out of the way first.
--  Renaming a constraint renames the index behind it.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE sales.sale_quotation      RENAME TO sale_quotation_unpart;
ALTER TABLE sales.sale_quotation_item RENAME TO sale_quotation_item_unpart;

ALTER TABLE sales.sale_quotation_unpart
    RENAME CONSTRAINT pk_sale_quotation TO pk_sale_quotation_unpart;
ALTER TABLE sales.sale_quotation_item_unpart
    RENAME CONSTRAINT pk_sale_quotation_item TO pk_sale_quotation_item_unpart;

ALTER INDEX sales.ux_sq_quote_no    RENAME TO ux_sq_quote_no_unpart;
ALTER INDEX sales.ux_sq_slno        RENAME TO ux_sq_slno_unpart;
ALTER INDEX sales.ix_sq_date        RENAME TO ix_sq_date_unpart;
ALTER INDEX sales.ix_sq_cust        RENAME TO ix_sq_cust_unpart;
ALTER INDEX sales.ix_sq_status      RENAME TO ix_sq_status_unpart;
ALTER INDEX sales.ix_sq_valid       RENAME TO ix_sq_valid_unpart;
ALTER INDEX sales.ix_sq_conv        RENAME TO ix_sq_conv_unpart;
ALTER INDEX sales.ix_sq_parent      RENAME TO ix_sq_parent_unpart;
ALTER INDEX sales.ux_sqi_quote_line RENAME TO ux_sqi_quote_line_unpart;
ALTER INDEX sales.ix_sqi_quote      RENAME TO ix_sqi_quote_unpart;
ALTER INDEX sales.ix_sqi_item       RENAME TO ix_sqi_item_unpart;
ALTER INDEX sales.ix_sqi_hsn        RENAME TO ix_sqi_hsn_unpart;


-- ───────────────────────────────────────────────────────────────────────────
--  2. Partitioned parents
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE sales.sale_quotation
(
    sq_id                  uuid DEFAULT uuidv7() NOT NULL,
    sq_company_id          uuid NOT NULL,
    sq_branch_id           uuid NOT NULL,
    sq_tenant_id           uuid,
    sq_acc_year            character(9) NOT NULL,
    sq_session_id          uuid,
    sq_category_id         uuid,
    sq_price_level         integer NOT NULL,

    -- ── Document identity ────────────────────────────────────────────────
    sq_doc_type            character varying(30) DEFAULT 'QUOTATION'::character varying NOT NULL,
    sq_quote_slno          bigint NOT NULL,
    sq_quote_refno         character varying(100) NOT NULL,
    sq_usr_refno           character varying(100),
    sq_quote_date          date NOT NULL,
    sq_quote_datetime      timestamp(6) with time zone DEFAULT now() NOT NULL,
    sq_valid_until         date,
    sq_validity_days       integer,

    -- ── Revision / versioning ────────────────────────────────────────────
    -- sq_parent_acc_year completes the reference to the parent revision's
    -- composite key; it is set exactly when sq_parent_quote_id is.
    sq_revision_no         integer DEFAULT 0 NOT NULL,
    sq_parent_quote_id     uuid,
    sq_parent_acc_year     character(9),

    -- ── Source (enquiry / lead) -- polymorphic, no FK ─────────────────────
    sq_src_doc_type        character varying(30),
    sq_src_doc_id          uuid,
    sq_src_doc_refno       character varying(100),
    sq_src_doc_date        timestamp(6) with time zone,

    -- ── Customer / prospect snapshot ─────────────────────────────────────
    sq_cust_id             uuid,
    sq_cust_area_id        uuid,
    sq_cust_name           character varying(200) NOT NULL,
    sq_cust_addr           character varying(500),
    sq_cust_place          character varying(100),
    sq_cust_phone          character varying(20),
    sq_cust_email          character varying(150),
    sq_cust_gstin          character varying(15),
    sq_cust_gst_type       character varying(20),
    sq_cust_stcd           character(2),
    sq_pos_stcd            character(2),
    sq_state_name          character varying(100),
    sq_contact_person      character varying(150),
    sq_contact_phone       character varying(20),

    -- ── Applicability flags ──────────────────────────────────────────────
    sq_has_load            boolean DEFAULT false NOT NULL,
    sq_has_unload          boolean DEFAULT false NOT NULL,
    sq_has_freight         boolean DEFAULT false NOT NULL,
    sq_has_promo           boolean DEFAULT false NOT NULL,
    sq_has_comm            boolean DEFAULT false NOT NULL,

    -- ── People ───────────────────────────────────────────────────────────
    sq_user_id             uuid NOT NULL,
    sq_salesman_id         uuid,
    sq_agent_id            uuid,

    -- ── Counts / weight ──────────────────────────────────────────────────
    sq_tot_items           integer DEFAULT 0 NOT NULL,
    sq_tot_weight          numeric(15,3) DEFAULT 0 NOT NULL,
    sq_tot_bags            numeric(15,3) DEFAULT 0 NOT NULL,

    -- ── Amounts (priced-out offer) ───────────────────────────────────────
    sq_gross_amt           numeric(15,2) DEFAULT 0 NOT NULL,
    sq_item_disc           numeric(15,2) DEFAULT 0 NOT NULL,
    sq_spl_disc            numeric(15,2) DEFAULT 0 NOT NULL,
    sq_sch_disc            numeric(15,2) DEFAULT 0 NOT NULL,
    sq_bill_sch_disc       numeric(15,2) DEFAULT 0 NOT NULL,
    sq_addl_disc1          numeric(15,2) DEFAULT 0 NOT NULL,
    sq_addl_disc2          numeric(15,2) DEFAULT 0 NOT NULL,
    sq_taxable_amt         numeric(15,2) DEFAULT 0 NOT NULL,
    sq_cgst_amt            numeric(15,2) DEFAULT 0 NOT NULL,
    sq_sgst_amt            numeric(15,2) DEFAULT 0 NOT NULL,
    sq_igst_amt            numeric(15,2) DEFAULT 0 NOT NULL,
    sq_cess_amt            numeric(15,2) DEFAULT 0 NOT NULL,
    sq_tax_amt             numeric(15,2) DEFAULT 0 NOT NULL,
    sq_freight_amt         numeric(15,2) DEFAULT 0 NOT NULL,
    sq_load_amt            numeric(15,2) DEFAULT 0 NOT NULL,
    sq_unload_amt          numeric(15,2) DEFAULT 0 NOT NULL,
    sq_other_amt1          numeric(15,2) DEFAULT 0 NOT NULL,
    sq_other_amt2          numeric(15,2) DEFAULT 0 NOT NULL,
    sq_round_off           numeric(15,2) DEFAULT 0 NOT NULL,
    sq_quote_amt           numeric(15,2) DEFAULT 0 NOT NULL,

    -- ── Internal margin (never printed) ──────────────────────────────────
    sq_total_cost          numeric(15,2),
    sq_margin_amt          numeric(15,2),
    sq_margin_perc         numeric(15,4),

    -- ── Terms ────────────────────────────────────────────────────────────
    sq_payment_terms       character varying(250),
    sq_delivery_terms      character varying(250),
    sq_terms_conditions    text,

    -- ── Status + conversion tracking ─────────────────────────────────────
    sq_status              character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    sq_sent_on             timestamp(6) with time zone,
    sq_accepted_on         timestamp(6) with time zone,
    sq_rejected_on         timestamp(6) with time zone,
    sq_reject_reason       character varying(250),
    sq_converted_doc_type  character varying(30),
    sq_converted_doc_id    uuid,
    sq_converted_on        timestamp(6) with time zone,

    -- ── Approval / cancel ────────────────────────────────────────────────
    sq_approved_on         timestamp(6) with time zone,
    sq_approved_by         uuid,
    sq_cancelled_on        timestamp(6) with time zone,
    sq_cancelled_by        uuid,
    sq_cancel_reason       character varying(250),
    sq_mrp_savings         numeric(15,3) DEFAULT 0,
    sq_mrp_savings_perc    numeric(15,4) DEFAULT 0,

    -- ── Print / device / sync + audit ────────────────────────────────────
    sq_print_count         integer DEFAULT 0 NOT NULL,
    sq_device_type         character varying(20),
    sq_device_id           text,
    sq_remarks             character varying(500),
    sq_is_deleted          boolean DEFAULT false NOT NULL,
    sq_sync_date           timestamp(6) with time zone,
    sq_created_on          timestamp(6) with time zone DEFAULT now() NOT NULL,
    sq_created_by          text NOT NULL,
    sq_modified_on         timestamp(6) with time zone,
    sq_modified_by         text,

    -- ── Charge calculation preferences ───────────────────────────────────
    sq_freight_calc_type   character varying(12),
    sq_loading_calc_type   character varying(12),
    sq_disc_alter_base     boolean,

    CONSTRAINT pk_sale_quotation PRIMARY KEY (sq_id, sq_acc_year),

    CONSTRAINT fk_sq_cust FOREIGN KEY (sq_cust_id)
        REFERENCES sales.customers (cus_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sq_cust_area FOREIGN KEY (sq_cust_area_id)
        REFERENCES sales.area_master (arm_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sq_pos_state FOREIGN KEY (sq_pos_stcd)
        REFERENCES fixed.state_codes (state_code) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sq_price_level FOREIGN KEY (sq_price_level)
        REFERENCES inventory.item_price_levels (ipl_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sq_salesman FOREIGN KEY (sq_salesman_id)
        REFERENCES public.employee_master (emp_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    -- ck_sq_parent_pair and fk_sq_parent are added after the copy below:
    -- sq_parent_acc_year is backfilled from the parent row, which does not
    -- exist yet while the headers are still being inserted.
    CONSTRAINT ck_sq_status CHECK (sq_status::text = ANY (ARRAY[
        'DRAFT'::text, 'SENT'::text, 'ACCEPTED'::text, 'REJECTED'::text,
        'EXPIRED'::text, 'CONVERTED'::text, 'CANCELLED'::text]))
) PARTITION BY LIST (sq_acc_year);


CREATE TABLE sales.sale_quotation_item
(
    sqi_id                uuid DEFAULT uuidv7() NOT NULL,
    sqi_quote_id          uuid NOT NULL,
    sqi_company_id        uuid NOT NULL,
    sqi_branch_id         uuid NOT NULL,
    sqi_tenant_id         uuid,
    sqi_acc_year          character(9) NOT NULL,

    -- ── Source (enquiry line -> quote line) -- polymorphic, no FK ────────
    sqi_src_doc_type      character varying(30),
    sqi_src_item_id       uuid,
    sqi_src_unit_id       uuid,
    sqi_src_doc_refno     character varying(100),
    sqi_src_item_qty      numeric(15,3),

    sqi_line_no           integer NOT NULL,
    sqi_item_id           uuid NOT NULL,
    sqi_item_unit_id      uuid NOT NULL,
    sqi_hsn_code          character varying(8),
    sqi_price_level       integer NOT NULL,
    sqi_ean_code          character varying(100),
    sqi_batch_no          character varying(100),
    sqi_batch_date        date,
    sqi_expiry_date       date,

    -- ── Line flags ───────────────────────────────────────────────────────
    sqi_is_tax_incl       boolean DEFAULT false NOT NULL,
    sqi_is_promo          boolean DEFAULT false NOT NULL,
    sqi_is_free           boolean DEFAULT false NOT NULL,
    sqi_free_type         character varying(20),
    sqi_is_service        boolean DEFAULT false NOT NULL,

    -- ── Quantities ───────────────────────────────────────────────────────
    sqi_case_qty          numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_bill_qty          numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_length_qty        numeric(15,3) DEFAULT 0,
    sqi_net_qty           numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_weight_qty        numeric(15,3) DEFAULT 0,
    sqi_available_stock   numeric(15,3) DEFAULT 0 NOT NULL,

    -- ── Rate / price ─────────────────────────────────────────────────────
    sqi_rate              numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_rate_pre_tax      numeric(15,4) DEFAULT 0 NOT NULL,

    -- ── Discounts ────────────────────────────────────────────────────────
    sqi_item_disc_perc    numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_item_disc_qty     numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_item_disc_amt     numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_spl_disc_perc     numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_spl_disc_qty      numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_spl_disc_amt      numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_sch_disc_perc     numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_sch_disc_qty      numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_sch_disc_amt      numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_bill_sch_perc     numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_bill_sch_qty      numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_bill_sch_amt      numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_addl_disc1_perc   numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_addl_disc1_amt    numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_addl_disc2_perc   numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_addl_disc2_amt    numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_cash_disc_perc    numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_cash_disc_amt     numeric(15,2) DEFAULT 0 NOT NULL,

    -- ── Amounts + tax ────────────────────────────────────────────────────
    sqi_gross_amt         numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_taxable_amt       numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_tax_perc          numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_tax_amt           numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_cgst_perc         numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_cgst_amt          numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_sgst_perc         numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_sgst_amt          numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_igst_perc         numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_igst_amt          numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_cess_perc         numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_cess_per_unit     numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_cess_amt          numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_acess_perc        numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_acess_per_unit    numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_acess_amt         numeric(15,2) DEFAULT 0 NOT NULL,

    -- ── Line charges + net ───────────────────────────────────────────────
    sqi_freight_qty       numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_freight_amt       numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_load_qty          numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_load_amt          numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_unload_qty        numeric(15,3) DEFAULT 0 NOT NULL,
    sqi_unload_amt        numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_round_off         numeric(15,2) DEFAULT 0 NOT NULL,
    sqi_net_amt           numeric(15,2) DEFAULT 0 NOT NULL,

    -- ── Internal margin ──────────────────────────────────────────────────
    sqi_cost_price        numeric(15,4),
    sqi_max_price         numeric(15,4),
    sqi_min_price         numeric(15,4),
    sqi_act_price         numeric(15,4),
    sqi_quote_price       numeric(15,4),
    sqi_item_profit       numeric(15,2),
    sqi_cost_pre_tax      numeric(15,2),
    sqi_quote_pre_tax     numeric(15,2),
    sqi_profit_pre_tax    numeric(15,2),
    sqi_mrp_savings       numeric(15,3),
    sqi_mrp_savings_perc  numeric(15,4),

    -- ── Scheme ref (display only on a quote) ─────────────────────────────
    sqi_scheme_id         uuid,
    sqi_scheme_name       character varying(150),
    sqi_remarks           character varying(250),
    sqi_is_deleted        boolean DEFAULT false NOT NULL,
    sqi_sync_date         timestamp(6) with time zone,
    sqi_created_on        timestamp(6) with time zone DEFAULT now() NOT NULL,
    sqi_created_by        text NOT NULL,
    sqi_modified_on       timestamp(6) with time zone,
    sqi_modified_by       text,

    -- ── Line net/gross basis + charge split ──────────────────────────────
    sqi_net_gross         numeric(14,4),
    sqi_chrg_before_tax   numeric(14,4),
    sqi_chrg_after_tax    numeric(14,4),
    sqi_to_base_factor    numeric(15,6) DEFAULT 0 NOT NULL,
    sqi_rate_diff         numeric(15,4) DEFAULT 0 NOT NULL,
    sqi_has_freight       boolean DEFAULT false NOT NULL,
    sqi_item_size         character varying(50),

    CONSTRAINT pk_sale_quotation_item PRIMARY KEY (sqi_id, sqi_acc_year),

    -- A line lives in its header's partition, so the header reference carries
    -- the year rather than a second copy of it.
    CONSTRAINT fk_sqi_quote FOREIGN KEY (sqi_quote_id, sqi_acc_year)
        REFERENCES sales.sale_quotation (sq_id, sq_acc_year) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_sqi_item FOREIGN KEY (sqi_item_id)
        REFERENCES inventory.item_master (item_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sqi_item_unit FOREIGN KEY (sqi_item_unit_id)
        REFERENCES inventory.item_unit_conversion (iuc_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sqi_price_level FOREIGN KEY (sqi_price_level)
        REFERENCES inventory.item_price_levels (ipl_id) MATCH SIMPLE
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_sqi_free_type CHECK (
        sqi_free_type IS NULL
        OR sqi_free_type::text = ANY (ARRAY['SCHEME'::text, 'SAMPLE'::text]))
) PARTITION BY LIST (sqi_acc_year);


-- ───────────────────────────────────────────────────────────────────────────
--  3. Indexes
--
--  Declared on the parents, so partitions created later inherit them. Every
--  predicate is carried over unchanged from 20260708120000 except
--  ux_sqi_quote_line, which gains the partition key.
-- ───────────────────────────────────────────────────────────────────────────

CREATE UNIQUE INDEX ux_sq_quote_no
    ON sales.sale_quotation
    (sq_company_id, sq_branch_id, sq_acc_year, sq_quote_refno, sq_revision_no)
    WHERE sq_is_deleted = false;
CREATE UNIQUE INDEX ux_sq_slno
    ON sales.sale_quotation
    (sq_company_id, sq_branch_id, sq_acc_year, sq_quote_slno)
    WHERE sq_is_deleted = false;

CREATE INDEX ix_sq_date   ON sales.sale_quotation (sq_company_id, sq_branch_id, sq_quote_date);
CREATE INDEX ix_sq_cust   ON sales.sale_quotation (sq_cust_id) WHERE sq_cust_id IS NOT NULL;
CREATE INDEX ix_sq_status ON sales.sale_quotation (sq_status) WHERE sq_is_deleted = false;
CREATE INDEX ix_sq_valid  ON sales.sale_quotation (sq_valid_until)
    WHERE sq_status::text IN ('SENT', 'ACCEPTED') AND sq_is_deleted = false;   -- expiry sweep
CREATE INDEX ix_sq_conv   ON sales.sale_quotation (sq_converted_doc_id) WHERE sq_converted_doc_id IS NOT NULL;
CREATE INDEX ix_sq_parent ON sales.sale_quotation (sq_parent_quote_id) WHERE sq_parent_quote_id IS NOT NULL;

CREATE UNIQUE INDEX ux_sqi_quote_line
    ON sales.sale_quotation_item (sqi_quote_id, sqi_acc_year, sqi_line_no)
    WHERE sqi_is_deleted = false;
CREATE INDEX ix_sqi_quote ON sales.sale_quotation_item (sqi_quote_id);
CREATE INDEX ix_sqi_item  ON sales.sale_quotation_item (sqi_item_id);
CREATE INDEX ix_sqi_hsn   ON sales.sale_quotation_item (sqi_hsn_code);


-- ───────────────────────────────────────────────────────────────────────────
--  4. Teach public.ensure_acc_year_partitions about the two new parents
--
--  Same helper the bill / tender / order tables use (20260804112944, extended
--  by 20260808132323). Idempotent -- call it whenever a fiscal year is opened:
--
--      SELECT public.ensure_acc_year_partitions('2027-2028');
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character(9))
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    -- The partition bound is a literal, so the year is validated rather than
    -- interpolated blind. char(9) makes 'YYYY-YYYY' the only well-formed value.
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order FOR VALUES IN (%L)',
        'sale_order_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_item FOR VALUES IN (%L)',
        'sale_order_item_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_advance_alloc FOR VALUES IN (%L)',
        'sale_order_advance_alloc_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation FOR VALUES IN (%L)',
        'sale_quotation_' || v_suffix, v_year);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation_item FOR VALUES IN (%L)',
        'sale_quotation_item_' || v_suffix, v_year);
END;
$$;

COMMENT ON FUNCTION public.ensure_acc_year_partitions(character(9)) IS
    'Idempotently creates the sale_bill / sale_bill_item / acc_tender_detail / txn_status_log / sale_order / sale_order_item / sale_order_advance_alloc / sale_quotation / sale_quotation_item LIST partitions for one accounting year (YYYY-YYYY). Run it whenever a fiscal year is opened.';


-- ───────────────────────────────────────────────────────────────────────────
--  5. Partitions
--
--  Every year on record in fiscal_years, plus -- belt and braces -- any year
--  the parked rows actually carry, so nothing can fail to find a home below.
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_year text;
    BEGIN
        FOR v_year IN
            SELECT DISTINCT btrim(fy_year_name)
            FROM public.fiscal_years
            WHERE is_deleted = false
              AND btrim(fy_year_name) ~ '^[0-9]{4}-[0-9]{4}$'
            UNION
            SELECT DISTINCT btrim(sq_acc_year) FROM sales.sale_quotation_unpart
            UNION
            SELECT DISTINCT btrim(sqi_acc_year) FROM sales.sale_quotation_item_unpart
            ORDER BY 1
            LOOP
                IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
                    RAISE EXCEPTION 'sale_quotation carries accounting year %, which is not YYYY-YYYY', v_year;
                END IF;
                PERFORM public.ensure_acc_year_partitions(v_year::character(9));
            END LOOP;
    END;
$$;


-- ───────────────────────────────────────────────────────────────────────────
--  6. Move the rows over
--
--  Headers first: fk_sqi_quote is checked as each line lands. sq_parent_acc_year
--  is backfilled afterwards from the parent revision's own year -- it is a new
--  column, so the parked table has nothing to copy from.
-- ───────────────────────────────────────────────────────────────────────────

INSERT INTO sales.sale_quotation (
    sq_id, sq_company_id, sq_branch_id, sq_tenant_id, sq_acc_year, sq_session_id,
    sq_category_id, sq_price_level, sq_doc_type, sq_quote_slno, sq_quote_refno,
    sq_usr_refno, sq_quote_date, sq_quote_datetime, sq_valid_until, sq_validity_days,
    sq_revision_no, sq_parent_quote_id, sq_src_doc_type, sq_src_doc_id,
    sq_src_doc_refno, sq_src_doc_date, sq_cust_id, sq_cust_area_id, sq_cust_name,
    sq_cust_addr, sq_cust_place, sq_cust_phone, sq_cust_email, sq_cust_gstin,
    sq_cust_gst_type, sq_cust_stcd, sq_pos_stcd, sq_state_name, sq_contact_person,
    sq_contact_phone, sq_has_load, sq_has_unload, sq_has_freight, sq_has_promo,
    sq_has_comm, sq_user_id, sq_salesman_id, sq_agent_id, sq_tot_items, sq_tot_weight,
    sq_tot_bags, sq_gross_amt, sq_item_disc, sq_spl_disc, sq_sch_disc, sq_bill_sch_disc,
    sq_addl_disc1, sq_addl_disc2, sq_taxable_amt, sq_cgst_amt, sq_sgst_amt, sq_igst_amt,
    sq_cess_amt, sq_tax_amt, sq_freight_amt, sq_load_amt, sq_unload_amt, sq_other_amt1,
    sq_other_amt2, sq_round_off, sq_quote_amt, sq_total_cost, sq_margin_amt,
    sq_margin_perc, sq_payment_terms, sq_delivery_terms, sq_terms_conditions, sq_status,
    sq_sent_on, sq_accepted_on, sq_rejected_on, sq_reject_reason, sq_converted_doc_type,
    sq_converted_doc_id, sq_converted_on, sq_approved_on, sq_approved_by,
    sq_cancelled_on, sq_cancelled_by, sq_cancel_reason, sq_mrp_savings,
    sq_mrp_savings_perc, sq_print_count, sq_device_type, sq_device_id, sq_remarks,
    sq_is_deleted, sq_sync_date, sq_created_on, sq_created_by, sq_modified_on,
    sq_modified_by, sq_freight_calc_type, sq_loading_calc_type, sq_disc_alter_base
)
SELECT
    sq_id, sq_company_id, sq_branch_id, sq_tenant_id, sq_acc_year, sq_session_id,
    sq_category_id, sq_price_level, sq_doc_type, sq_quote_slno, sq_quote_refno,
    sq_usr_refno, sq_quote_date, sq_quote_datetime, sq_valid_until, sq_validity_days,
    sq_revision_no, sq_parent_quote_id, sq_src_doc_type, sq_src_doc_id,
    sq_src_doc_refno, sq_src_doc_date, sq_cust_id, sq_cust_area_id, sq_cust_name,
    sq_cust_addr, sq_cust_place, sq_cust_phone, sq_cust_email, sq_cust_gstin,
    sq_cust_gst_type, sq_cust_stcd, sq_pos_stcd, sq_state_name, sq_contact_person,
    sq_contact_phone, sq_has_load, sq_has_unload, sq_has_freight, sq_has_promo,
    sq_has_comm, sq_user_id, sq_salesman_id, sq_agent_id, sq_tot_items, sq_tot_weight,
    sq_tot_bags, sq_gross_amt, sq_item_disc, sq_spl_disc, sq_sch_disc, sq_bill_sch_disc,
    sq_addl_disc1, sq_addl_disc2, sq_taxable_amt, sq_cgst_amt, sq_sgst_amt, sq_igst_amt,
    sq_cess_amt, sq_tax_amt, sq_freight_amt, sq_load_amt, sq_unload_amt, sq_other_amt1,
    sq_other_amt2, sq_round_off, sq_quote_amt, sq_total_cost, sq_margin_amt,
    sq_margin_perc, sq_payment_terms, sq_delivery_terms, sq_terms_conditions, sq_status,
    sq_sent_on, sq_accepted_on, sq_rejected_on, sq_reject_reason, sq_converted_doc_type,
    sq_converted_doc_id, sq_converted_on, sq_approved_on, sq_approved_by,
    sq_cancelled_on, sq_cancelled_by, sq_cancel_reason, sq_mrp_savings,
    sq_mrp_savings_perc, sq_print_count, sq_device_type, sq_device_id, sq_remarks,
    sq_is_deleted, sq_sync_date, sq_created_on, sq_created_by, sq_modified_on,
    sq_modified_by, sq_freight_calc_type, sq_loading_calc_type, sq_disc_alter_base
FROM sales.sale_quotation_unpart;

UPDATE sales.sale_quotation AS child
SET sq_parent_acc_year = parent.sq_acc_year
FROM sales.sale_quotation AS parent
WHERE child.sq_parent_quote_id IS NOT NULL
  AND parent.sq_id = child.sq_parent_quote_id;

-- A parent that no longer exists cannot get a year, and ck_sq_parent_pair /
-- fk_sq_parent would both reject the row. Such a pointer was already dangling
-- under the old FK-less-than-strict setup; clear it rather than fail the
-- migration on data that was never valid.
UPDATE sales.sale_quotation
SET sq_parent_quote_id = NULL
WHERE sq_parent_quote_id IS NOT NULL
  AND sq_parent_acc_year IS NULL;

ALTER TABLE sales.sale_quotation
    ADD CONSTRAINT ck_sq_parent_pair CHECK (
        (sq_parent_quote_id IS NULL) = (sq_parent_acc_year IS NULL));

ALTER TABLE sales.sale_quotation
    ADD CONSTRAINT fk_sq_parent FOREIGN KEY (sq_parent_quote_id, sq_parent_acc_year)
        REFERENCES sales.sale_quotation (sq_id, sq_acc_year) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;


INSERT INTO sales.sale_quotation_item (
    sqi_id, sqi_quote_id, sqi_company_id, sqi_branch_id, sqi_tenant_id, sqi_acc_year,
    sqi_src_doc_type, sqi_src_item_id, sqi_src_unit_id, sqi_src_doc_refno,
    sqi_src_item_qty, sqi_line_no, sqi_item_id, sqi_item_unit_id, sqi_hsn_code,
    sqi_price_level, sqi_ean_code, sqi_batch_no, sqi_batch_date, sqi_expiry_date,
    sqi_is_tax_incl, sqi_is_promo, sqi_is_free, sqi_free_type, sqi_is_service,
    sqi_case_qty, sqi_bill_qty, sqi_length_qty, sqi_net_qty, sqi_weight_qty,
    sqi_available_stock, sqi_rate, sqi_rate_pre_tax, sqi_item_disc_perc,
    sqi_item_disc_qty, sqi_item_disc_amt, sqi_spl_disc_perc, sqi_spl_disc_qty,
    sqi_spl_disc_amt, sqi_sch_disc_perc, sqi_sch_disc_qty, sqi_sch_disc_amt,
    sqi_bill_sch_perc, sqi_bill_sch_qty, sqi_bill_sch_amt, sqi_addl_disc1_perc,
    sqi_addl_disc1_amt, sqi_addl_disc2_perc, sqi_addl_disc2_amt, sqi_cash_disc_perc,
    sqi_cash_disc_amt, sqi_gross_amt, sqi_taxable_amt, sqi_tax_perc, sqi_tax_amt,
    sqi_cgst_perc, sqi_cgst_amt, sqi_sgst_perc, sqi_sgst_amt, sqi_igst_perc,
    sqi_igst_amt, sqi_cess_perc, sqi_cess_per_unit, sqi_cess_amt, sqi_acess_perc,
    sqi_acess_per_unit, sqi_acess_amt, sqi_freight_qty, sqi_freight_amt, sqi_load_qty,
    sqi_load_amt, sqi_unload_qty, sqi_unload_amt, sqi_round_off, sqi_net_amt,
    sqi_cost_price, sqi_max_price, sqi_min_price, sqi_act_price, sqi_quote_price,
    sqi_item_profit, sqi_cost_pre_tax, sqi_quote_pre_tax, sqi_profit_pre_tax,
    sqi_mrp_savings, sqi_mrp_savings_perc, sqi_scheme_id, sqi_scheme_name, sqi_remarks,
    sqi_is_deleted, sqi_sync_date, sqi_created_on, sqi_created_by, sqi_modified_on,
    sqi_modified_by, sqi_net_gross, sqi_chrg_before_tax, sqi_chrg_after_tax,
    sqi_to_base_factor, sqi_rate_diff, sqi_has_freight, sqi_item_size
)
SELECT
    sqi_id, sqi_quote_id, sqi_company_id, sqi_branch_id, sqi_tenant_id, sqi_acc_year,
    sqi_src_doc_type, sqi_src_item_id, sqi_src_unit_id, sqi_src_doc_refno,
    sqi_src_item_qty, sqi_line_no, sqi_item_id, sqi_item_unit_id, sqi_hsn_code,
    sqi_price_level, sqi_ean_code, sqi_batch_no, sqi_batch_date, sqi_expiry_date,
    sqi_is_tax_incl, sqi_is_promo, sqi_is_free, sqi_free_type, sqi_is_service,
    sqi_case_qty, sqi_bill_qty, sqi_length_qty, sqi_net_qty, sqi_weight_qty,
    sqi_available_stock, sqi_rate, sqi_rate_pre_tax, sqi_item_disc_perc,
    sqi_item_disc_qty, sqi_item_disc_amt, sqi_spl_disc_perc, sqi_spl_disc_qty,
    sqi_spl_disc_amt, sqi_sch_disc_perc, sqi_sch_disc_qty, sqi_sch_disc_amt,
    sqi_bill_sch_perc, sqi_bill_sch_qty, sqi_bill_sch_amt, sqi_addl_disc1_perc,
    sqi_addl_disc1_amt, sqi_addl_disc2_perc, sqi_addl_disc2_amt, sqi_cash_disc_perc,
    sqi_cash_disc_amt, sqi_gross_amt, sqi_taxable_amt, sqi_tax_perc, sqi_tax_amt,
    sqi_cgst_perc, sqi_cgst_amt, sqi_sgst_perc, sqi_sgst_amt, sqi_igst_perc,
    sqi_igst_amt, sqi_cess_perc, sqi_cess_per_unit, sqi_cess_amt, sqi_acess_perc,
    sqi_acess_per_unit, sqi_acess_amt, sqi_freight_qty, sqi_freight_amt, sqi_load_qty,
    sqi_load_amt, sqi_unload_qty, sqi_unload_amt, sqi_round_off, sqi_net_amt,
    sqi_cost_price, sqi_max_price, sqi_min_price, sqi_act_price, sqi_quote_price,
    sqi_item_profit, sqi_cost_pre_tax, sqi_quote_pre_tax, sqi_profit_pre_tax,
    sqi_mrp_savings, sqi_mrp_savings_perc, sqi_scheme_id, sqi_scheme_name, sqi_remarks,
    sqi_is_deleted, sqi_sync_date, sqi_created_on, sqi_created_by, sqi_modified_on,
    sqi_modified_by, sqi_net_gross, sqi_chrg_before_tax, sqi_chrg_after_tax,
    sqi_to_base_factor, sqi_rate_diff, sqi_has_freight, sqi_item_size
FROM sales.sale_quotation_item_unpart;


-- ───────────────────────────────────────────────────────────────────────────
--  7. Prove nothing was lost, then drop the parked tables
-- ───────────────────────────────────────────────────────────────────────────

DO
$$
    DECLARE
        v_old bigint;
        v_new bigint;
    BEGIN
        SELECT count(*) INTO v_old FROM sales.sale_quotation_unpart;
        SELECT count(*) INTO v_new FROM sales.sale_quotation;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'sale_quotation copy lost rows: % -> %', v_old, v_new;
        END IF;

        SELECT count(*) INTO v_old FROM sales.sale_quotation_item_unpart;
        SELECT count(*) INTO v_new FROM sales.sale_quotation_item;
        IF v_old <> v_new THEN
            RAISE EXCEPTION 'sale_quotation_item copy lost rows: % -> %', v_old, v_new;
        END IF;
    END;
$$;

DROP TABLE sales.sale_quotation_item_unpart;
DROP TABLE sales.sale_quotation_unpart;
