-- Convert the four GST document tables --
--
--   accounts.acc_voucher_doc_register   one row per outward/inward document
--   accounts.acc_voucher_doc_detail     its HSN/tax lines
--   accounts.acc_voucher_doc_einvoice   the IRN leg of that document
--   accounts.acc_voucher_doc_ewaybill   the e-way bill leg of that document
--
-- -- to declaratively LIST-partitioned tables keyed on their own acc_year
-- column, the way sale_bill (20260731070026), the account bill tables
-- (20260811060000), the vouchers (20260915120000) and the six sales documents
-- (20260921200000) already are:
--
--   acc_voucher_doc_register -> gdr_acc_year
--   acc_voucher_doc_detail   -> vtx_acc_year
--   acc_voucher_doc_einvoice -> gde_acc_year
--   acc_voucher_doc_ewaybill -> gdw_acc_year
--
-- This is the one band that is READ a whole year at a time: GSTR-1 and GSTR-3B
-- are filed per return period out of the register and its details, and the
-- annual return reads a full financial year. Every one of those queries already
-- carries the year in its WHERE clause, so they prune to a single partition;
-- and a closed year detaches as a unit once its returns are filed and its
-- e-invoices can no longer be cancelled. Unlike the bill tables, nothing here
-- is cross-year by nature: a document, its IRN and its e-way bill all belong to
-- the year the document was raised in and never move.
--
-- Postgres cannot ALTER an ordinary table into a partitioned one, so all four
-- are rebuilt: the existing tables are parked under `_unpart` names, the
-- partitioned parents are created with the same columns, their rows are copied
-- over, and the parked tables are dropped.
--
-- What changes beyond the storage layout:
--
--   1. Every primary key gains the partition key, because Postgres requires
--      each unique constraint on a partitioned table to contain it. The four
--      are now (gdr_id, gdr_acc_year), (vtx_id, vtx_acc_year),
--      (gde_id, gde_acc_year) and (gdw_id, gdw_acc_year). They are also named
--      at last -- pk_acc_voucher_doc_* rather than the *_pkey that Prisma
--      generated in 20260323073223. A caller addresses a row by the pair, not
--      by the id alone.
--   2. The three links to the register -- fk_acc_voucher_doc_detail_gdr,
--      fk_gde_gdr and fk_gdw_gdr -- point at that composite key now. No column
--      had to be added: vtx_acc_year, gde_acc_year and gdw_acc_year already
--      carry the register row's year, which is what makes this band cheaper to
--      partition than the bill tables were.
--   3. uq_gde_gdr and uq_gdw_gdr gain the year for the same reason. They still
--      say "at most one IRN / e-way bill per document", since a document lives
--      in exactly one year.
--   4. Three partial unique indexes gain the year as a trailing column:
--      uq_acc_voucher_doc_register_source, uq_acc_voucher_doc_einvoice_irn and
--      uq_acc_voucher_doc_ewaybill_no. This is the one real weakening here --
--      the same IRN or e-way bill number could now be stored twice in two
--      different years. In practice it cannot happen: an IRN is a hash of
--      supplier GSTIN + document type + document number + FINANCIAL YEAR, and
--      an e-way bill number is a portal-issued running number, so neither
--      repeats across years. The year is trailing, so lookups by IRN or by
--      e-way bill number alone still use the index.
--      uq_acc_voucher_doc_register_voucher and uq_acc_voucher_doc_register_doc
--      already contained gdr_acc_year.
--
-- Column order follows the prisma/accounts/*.prisma field order, which the
-- rebuild is a free opportunity to restore: gdr_igst_on_intra (20260917120000)
-- and the provenance/reconciliation columns on the e-invoice and e-way bill
-- (20260921120000, 20260922020000) had drifted to the end of the tables.
--
-- Prisma Migrate can express none of PARTITION BY, composite partition-aware
-- primary keys, partial indexes or CHECK constraints, so this migration is
-- hand-written rather than generated by `prisma migrate dev`.


-- ───────────────────────────────────────────────────────────────────────────
--  1. Park the unpartitioned tables
--
--  Constraint names are per-table, but index names are per-schema, so every
--  index and unique/primary-key constraint the rebuilt tables re-declare has
--  to be moved out of the way first. Renaming a constraint renames the index
--  behind it. CHECK constraints carry no index, so they are left alone and go
--  away with the parked tables.
--
--  The three foreign keys into the register are dropped outright rather than
--  parked: they are re-added against the composite key in section 3, and a
--  parked child still pointing at the parked register would block its DROP.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE accounts.acc_voucher_doc_detail   DROP CONSTRAINT fk_acc_voucher_doc_detail_gdr;
ALTER TABLE accounts.acc_voucher_doc_einvoice DROP CONSTRAINT fk_gde_gdr;
ALTER TABLE accounts.acc_voucher_doc_ewaybill DROP CONSTRAINT fk_gdw_gdr;

ALTER TABLE accounts.acc_voucher_doc_register RENAME TO acc_voucher_doc_register_unpart;
ALTER TABLE accounts.acc_voucher_doc_detail   RENAME TO acc_voucher_doc_detail_unpart;
ALTER TABLE accounts.acc_voucher_doc_einvoice RENAME TO acc_voucher_doc_einvoice_unpart;
ALTER TABLE accounts.acc_voucher_doc_ewaybill RENAME TO acc_voucher_doc_ewaybill_unpart;

ALTER TABLE accounts.acc_voucher_doc_register_unpart
    RENAME CONSTRAINT acc_voucher_doc_register_pkey TO acc_voucher_doc_register_pkey_unpart;
ALTER TABLE accounts.acc_voucher_doc_detail_unpart
    RENAME CONSTRAINT acc_voucher_doc_detail_pkey TO acc_voucher_doc_detail_pkey_unpart;
ALTER TABLE accounts.acc_voucher_doc_einvoice_unpart
    RENAME CONSTRAINT acc_voucher_doc_einvoice_pkey TO acc_voucher_doc_einvoice_pkey_unpart;
ALTER TABLE accounts.acc_voucher_doc_ewaybill_unpart
    RENAME CONSTRAINT acc_voucher_doc_ewaybill_pkey TO acc_voucher_doc_ewaybill_pkey_unpart;

ALTER TABLE accounts.acc_voucher_doc_einvoice_unpart
    RENAME CONSTRAINT uq_gde_gdr TO uq_gde_gdr_unpart;
ALTER TABLE accounts.acc_voucher_doc_ewaybill_unpart
    RENAME CONSTRAINT uq_gdw_gdr TO uq_gdw_gdr_unpart;

ALTER INDEX accounts.uq_acc_voucher_doc_register_source RENAME TO uq_acc_voucher_doc_register_source_unpart;
ALTER INDEX accounts.uq_acc_voucher_doc_register_voucher RENAME TO uq_acc_voucher_doc_register_voucher_unpart;
ALTER INDEX accounts.uq_acc_voucher_doc_register_doc    RENAME TO uq_acc_voucher_doc_register_doc_unpart;
ALTER INDEX accounts.idx_gdr_branch_voucher_date        RENAME TO idx_gdr_branch_voucher_date_unpart;
ALTER INDEX accounts.idx_gdr_branch_doc_date            RENAME TO idx_gdr_branch_doc_date_unpart;
ALTER INDEX accounts.idx_gdr_party                      RENAME TO idx_gdr_party_unpart;
ALTER INDEX accounts.idx_gdr_doc_class                  RENAME TO idx_gdr_doc_class_unpart;
ALTER INDEX accounts.idx_gdr_doc_status                 RENAME TO idx_gdr_doc_status_unpart;

ALTER INDEX accounts.idx_acc_voucher_doc_detail_voucher RENAME TO idx_acc_voucher_doc_detail_voucher_unpart;

ALTER INDEX accounts.uq_acc_voucher_doc_einvoice_irn    RENAME TO uq_acc_voucher_doc_einvoice_irn_unpart;
ALTER INDEX accounts.idx_gde_status                     RENAME TO idx_gde_status_unpart;
ALTER INDEX accounts.ix_gde_retry                       RENAME TO ix_gde_retry_unpart;

ALTER INDEX accounts.uq_acc_voucher_doc_ewaybill_no     RENAME TO uq_acc_voucher_doc_ewaybill_no_unpart;
ALTER INDEX accounts.idx_gdw_status                     RENAME TO idx_gdw_status_unpart;
ALTER INDEX accounts.ix_gdw_retry                       RENAME TO ix_gdw_retry_unpart;
ALTER INDEX accounts.ix_gdw_vehicle                     RENAME TO ix_gdw_vehicle_unpart;


-- ───────────────────────────────────────────────────────────────────────────
--  2. Partitioned parents
--
--  Same columns, same CHECK constraints, same defaults. Only the storage
--  layout and the column order change here.
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE accounts.acc_voucher_doc_register
(
    gdr_id                     uuid                  NOT NULL DEFAULT uuidv7(),

    -- ── Source mapping ───────────────────────────────────────────────────
    gdr_source_module          accounts."GdrSourceModule" NOT NULL,
    gdr_tran_nature            accounts."GdrTranNature"   NOT NULL,
    gdr_doc_flow               accounts."GdrDocFlow"      NOT NULL,
    gdr_doc_sign               smallint              NOT NULL DEFAULT 1,
    gdr_source_doc_id          uuid                  NOT NULL,

    -- ── Multi-branch / financial identity ────────────────────────────────
    gdr_acc_year               character varying(9)  NOT NULL,
    gdr_company_id             uuid                  NOT NULL,
    gdr_branch_id              uuid                  NOT NULL,

    -- ── Internal voucher identity ────────────────────────────────────────
    gdr_voucher_type_id        integer               NOT NULL,
    gdr_voucher_id             uuid                  NOT NULL,
    gdr_voucher_no             bigint                NOT NULL,
    gdr_voucher_date           date                  NOT NULL,
    gdr_voucher_refno          character varying(50),

    -- ── Business document identity ───────────────────────────────────────
    gdr_doc_type               accounts."GdrDocType" NOT NULL,
    gdr_doc_no                 character varying(50) NOT NULL,
    gdr_doc_date               date                  NOT NULL,
    gdr_doc_ref_no             character varying(50),
    gdr_doc_status             accounts."GdrDocStatus" NOT NULL DEFAULT 'POSTED'::accounts."GdrDocStatus",
    gdr_doc_cancel_reason      character varying(200),
    gdr_doc_canceled_on        timestamp(6) with time zone,
    gdr_doc_note_no            character varying(50),
    gdr_doc_note_date          date,
    gdr_doc_note_reason        character varying(150),

    -- ── GST / supply classification ──────────────────────────────────────
    gdr_supply_class           accounts."GdrSupplyClass",
    gdr_taxability             accounts."GdrTaxability" NOT NULL DEFAULT 'TAXABLE'::accounts."GdrTaxability",
    gdr_supply_nature          accounts."GdrSupplyNature",
    gdr_place_of_supply_code   character(2),
    gdr_place_of_supply_name   character varying(100),

    gdr_is_reverse_charge      boolean               NOT NULL DEFAULT false,
    gdr_is_einvoice_applicable boolean               NOT NULL DEFAULT false,
    gdr_is_ewaybill_applicable boolean               NOT NULL DEFAULT false,

    -- ── Party snapshot ───────────────────────────────────────────────────
    gdr_party_type             accounts."GdrPartyType" NOT NULL DEFAULT 'OTHER'::accounts."GdrPartyType",
    gdr_party_id               uuid                  NOT NULL,
    gdr_party_name             character varying(200),
    gdr_party_addr1            character varying(200),
    gdr_party_addr2            character varying(200),
    gdr_party_addr3            character varying(200),
    gdr_party_location         character varying(100),
    gdr_party_pin              character varying(10),
    gdr_party_state_code       character(2),
    gdr_party_state_name       character varying(100),
    gdr_party_gst_type         character varying(30),
    gdr_party_gstin            character varying(15),
    gdr_party_ecom_gstin       character varying(15),

    -- ── Amount summary ───────────────────────────────────────────────────
    gdr_gross_value            numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_discount_value         numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_taxable_value          numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_cgst_value             numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_sgst_value             numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_igst_value             numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_cess_value             numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_state_cess_value       numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_tcs_value              numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_other_charge           numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_round_off              numeric(18,2)         NOT NULL DEFAULT 0,
    gdr_bill_value             numeric(18,2)         NOT NULL DEFAULT 0,

    gdr_remarks                character varying(500),

    -- ── Lifecycle / audit ────────────────────────────────────────────────
    gdr_is_active              boolean               NOT NULL DEFAULT true,
    gdr_igst_on_intra          boolean               NOT NULL DEFAULT false,
    gdr_is_deleted             boolean               NOT NULL DEFAULT false,
    gdr_sync_date              timestamp(6) with time zone,
    gdr_created_on             timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gdr_created_by             uuid,
    gdr_updated_on             timestamp(6) with time zone,
    gdr_updated_by             uuid,

    CONSTRAINT chk_gdr_source_module CHECK (gdr_source_module = ANY (ARRAY['SALES'::accounts."GdrSourceModule", 'PURCHASE'::accounts."GdrSourceModule", 'INVENTORY'::accounts."GdrSourceModule", 'ACCOUNTS'::accounts."GdrSourceModule", 'SERVICE'::accounts."GdrSourceModule", 'JOBWORK'::accounts."GdrSourceModule", 'POS'::accounts."GdrSourceModule", 'OTHER'::accounts."GdrSourceModule"])),
    CONSTRAINT chk_gdr_tran_nature CHECK (gdr_tran_nature = ANY (ARRAY['SALE'::accounts."GdrTranNature", 'SALES_RETURN'::accounts."GdrTranNature", 'PURCHASE'::accounts."GdrTranNature", 'PURCHASE_RETURN'::accounts."GdrTranNature", 'STOCK_TRANSFER'::accounts."GdrTranNature", 'DELIVERY_CHALLAN'::accounts."GdrTranNature", 'JOBWORK_SEND'::accounts."GdrTranNature", 'JOBWORK_RECEIVE'::accounts."GdrTranNature", 'DEBIT_NOTE'::accounts."GdrTranNature", 'CREDIT_NOTE'::accounts."GdrTranNature", 'EXPORT'::accounts."GdrTranNature", 'IMPORT'::accounts."GdrTranNature", 'ADVANCE'::accounts."GdrTranNature", 'ADV_ADJUSTMENT'::accounts."GdrTranNature", 'ADJUSTMENT'::accounts."GdrTranNature", 'OTHER'::accounts."GdrTranNature"])),
    CONSTRAINT chk_gdr_doc_flow CHECK (gdr_doc_flow = ANY (ARRAY['OUTWARD'::accounts."GdrDocFlow", 'INWARD'::accounts."GdrDocFlow", 'INTERNAL'::accounts."GdrDocFlow"])),
    CONSTRAINT chk_gdr_doc_sign CHECK (gdr_doc_sign = ANY (ARRAY[1, '-1'::integer])),
    CONSTRAINT chk_gdr_doc_type CHECK (gdr_doc_type = ANY (ARRAY['INVOICE'::accounts."GdrDocType", 'CREDIT_NOTE'::accounts."GdrDocType", 'DEBIT_NOTE'::accounts."GdrDocType", 'BILL_OF_SUPPLY'::accounts."GdrDocType", 'DELIVERY_CHALLAN'::accounts."GdrDocType", 'CHALLAN'::accounts."GdrDocType", 'ADVANCE'::accounts."GdrDocType", 'ADV_ADJUSTMENT'::accounts."GdrDocType", 'EXPORT_DOC'::accounts."GdrDocType", 'IMPORT_DOC'::accounts."GdrDocType", 'OTHER'::accounts."GdrDocType"])),
    CONSTRAINT chk_gdr_doc_status CHECK (gdr_doc_status = ANY (ARRAY['DRAFT'::accounts."GdrDocStatus", 'POSTED'::accounts."GdrDocStatus", 'CANCELED'::accounts."GdrDocStatus", 'ARCHIVED'::accounts."GdrDocStatus"])),
    CONSTRAINT chk_gdr_doc_cancel_date CHECK ((gdr_doc_status <> 'CANCELED'::accounts."GdrDocStatus") OR (gdr_doc_canceled_on IS NOT NULL)),
    CONSTRAINT chk_gdr_note_pair CHECK (((gdr_doc_note_no IS NULL) AND (gdr_doc_note_date IS NULL)) OR ((gdr_doc_note_no IS NOT NULL) AND (gdr_doc_note_date IS NOT NULL))),
    CONSTRAINT chk_gdr_supply_class CHECK ((gdr_supply_class IS NULL) OR (gdr_supply_class = ANY (ARRAY['GOODS'::accounts."GdrSupplyClass", 'SERVICES'::accounts."GdrSupplyClass", 'MIXED'::accounts."GdrSupplyClass"]))),
    CONSTRAINT chk_gdr_taxability CHECK (gdr_taxability = ANY (ARRAY['TAXABLE'::accounts."GdrTaxability", 'EXEMPT'::accounts."GdrTaxability", 'NIL_RATED'::accounts."GdrTaxability", 'NON_GST'::accounts."GdrTaxability", 'MIXED'::accounts."GdrTaxability"])),
    CONSTRAINT chk_gdr_supply_nature CHECK ((gdr_supply_nature IS NULL) OR (gdr_supply_nature = ANY (ARRAY['INTRA_STATE'::accounts."GdrSupplyNature", 'INTER_STATE'::accounts."GdrSupplyNature", 'IMPORT'::accounts."GdrSupplyNature", 'EXPORT'::accounts."GdrSupplyNature", 'SEZ'::accounts."GdrSupplyNature", 'OTHER'::accounts."GdrSupplyNature"]))),
    CONSTRAINT chk_gdr_party_type CHECK (gdr_party_type = ANY (ARRAY['CUSTOMER'::accounts."GdrPartyType", 'VENDOR'::accounts."GdrPartyType", 'BRANCH'::accounts."GdrPartyType", 'JOBWORKER'::accounts."GdrPartyType", 'TRANSPORTER'::accounts."GdrPartyType", 'OTHER'::accounts."GdrPartyType"])),
    CONSTRAINT chk_gdr_party_gstin_len CHECK ((gdr_party_gstin IS NULL) OR (char_length((gdr_party_gstin)::text) = 15)),
    CONSTRAINT chk_gdr_party_ecom_gstin_len CHECK ((gdr_party_ecom_gstin IS NULL) OR (char_length((gdr_party_ecom_gstin)::text) = 15)),
    CONSTRAINT chk_gdr_amounts CHECK ((gdr_gross_value >= (0)::numeric) AND (gdr_discount_value >= (0)::numeric) AND (gdr_taxable_value >= (0)::numeric) AND (gdr_cgst_value >= (0)::numeric) AND (gdr_sgst_value >= (0)::numeric) AND (gdr_igst_value >= (0)::numeric) AND (gdr_cess_value >= (0)::numeric) AND (gdr_state_cess_value >= (0)::numeric) AND (gdr_tcs_value >= (0)::numeric) AND (gdr_other_charge >= (0)::numeric) AND (gdr_bill_value >= (0)::numeric)),
    CONSTRAINT chk_gdr_bill_value_non_negative CHECK (gdr_bill_value >= (0)::numeric)
)
PARTITION BY LIST (gdr_acc_year);

CREATE TABLE accounts.acc_voucher_doc_detail
(
    vtx_id               uuid                  NOT NULL DEFAULT uuidv7(),

    -- ── Links ────────────────────────────────────────────────────────────
    vtx_gdr_id           uuid                  NOT NULL,
    vtx_voucher_id       uuid                  NOT NULL,
    vtx_row_no           integer               NOT NULL,

    -- ── Multi-branch snapshot ────────────────────────────────────────────
    vtx_acc_year         character varying(9)  NOT NULL,
    vtx_company_id       uuid                  NOT NULL,
    vtx_branch_id        uuid                  NOT NULL,

    -- ── Tax classification snapshot ──────────────────────────────────────
    vtx_taxability       accounts."VoucherDocDetailTaxability"   NOT NULL DEFAULT 'TAXABLE'::accounts."VoucherDocDetailTaxability",
    vtx_supply_nature    accounts."VoucherDocDetailSupplyNature" NOT NULL,

    -- ── Item snapshot ────────────────────────────────────────────────────
    vtx_item_id          uuid,
    vtx_item_code        character varying(50),
    vtx_item_name        character varying(200),
    vtx_item_description character varying(250),
    vtx_hsn_code         character varying(20),
    vtx_tally_hsn_source character varying(20),
    vtx_unit_id          uuid,
    vtx_item_qty         numeric(18,3)         NOT NULL DEFAULT 0,
    vtx_item_rate        numeric(18,4)         NOT NULL DEFAULT 0,
    vtx_item_discount    numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_is_service       boolean               NOT NULL DEFAULT false,

    -- ── Tax values ───────────────────────────────────────────────────────
    vtx_taxable_value    numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_total_tax_rate   numeric(9,3)          NOT NULL DEFAULT 0,
    vtx_tax_id           uuid,

    vtx_cgst_rate        numeric(9,3)          NOT NULL DEFAULT 0,
    vtx_sgst_rate        numeric(9,3)          NOT NULL DEFAULT 0,
    vtx_igst_rate        numeric(9,3)          NOT NULL DEFAULT 0,
    vtx_cess_rate        numeric(9,3)          NOT NULL DEFAULT 0,

    vtx_cgst_amount      numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_sgst_amount      numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_igst_amount      numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_cess_amount      numeric(18,2)         NOT NULL DEFAULT 0,

    vtx_total_tax_amount numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_other_amount     numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_total_value      numeric(18,2)         NOT NULL DEFAULT 0,
    vtx_bill_value       numeric(18,2)         NOT NULL DEFAULT 0,

    -- ── Tax ledger mapping ───────────────────────────────────────────────
    vtx_taxable_ledger_id uuid,
    vtx_cgst_ledger_id    uuid,
    vtx_sgst_ledger_id    uuid,
    vtx_igst_ledger_id    uuid,
    vtx_cess_ledger_id    uuid,

    -- ── Status / audit ───────────────────────────────────────────────────
    vtx_is_active        boolean               NOT NULL DEFAULT true,
    vtx_is_deleted       boolean               NOT NULL DEFAULT false,
    vtx_sync_date        timestamp(6) with time zone,
    vtx_created_on       timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vtx_created_by       uuid,
    vtx_updated_on       timestamp(6) with time zone,
    vtx_updated_by       uuid,

    CONSTRAINT chk_acc_voucher_doc_detail_row_no CHECK (vtx_row_no > 0),
    CONSTRAINT chk_acc_voucher_doc_detail_taxability CHECK (vtx_taxability = ANY (ARRAY['TAXABLE'::accounts."VoucherDocDetailTaxability", 'EXEMPT'::accounts."VoucherDocDetailTaxability", 'NIL_RATED'::accounts."VoucherDocDetailTaxability", 'NON_GST'::accounts."VoucherDocDetailTaxability", 'MIXED'::accounts."VoucherDocDetailTaxability"])),
    CONSTRAINT chk_acc_voucher_doc_detail_values CHECK ((vtx_item_qty >= (0)::numeric) AND (vtx_item_rate >= (0)::numeric) AND (vtx_item_discount >= (0)::numeric) AND (vtx_taxable_value >= (0)::numeric) AND (vtx_total_tax_rate >= (0)::numeric) AND (vtx_cgst_rate >= (0)::numeric) AND (vtx_sgst_rate >= (0)::numeric) AND (vtx_igst_rate >= (0)::numeric) AND (vtx_cess_rate >= (0)::numeric) AND (vtx_cgst_amount >= (0)::numeric) AND (vtx_sgst_amount >= (0)::numeric) AND (vtx_igst_amount >= (0)::numeric) AND (vtx_cess_amount >= (0)::numeric) AND (vtx_total_tax_amount >= (0)::numeric) AND (vtx_other_amount >= (0)::numeric) AND (vtx_total_value >= (0)::numeric) AND (vtx_bill_value >= (0)::numeric)),
    CONSTRAINT chk_acc_voucher_doc_detail_total_match CHECK (vtx_total_tax_amount = (((vtx_cgst_amount + vtx_sgst_amount) + vtx_igst_amount) + vtx_cess_amount)),
    CONSTRAINT chk_acc_voucher_doc_detail_line_value_match CHECK (vtx_total_value = ((vtx_taxable_value + vtx_total_tax_amount) + vtx_other_amount)),
    CONSTRAINT chk_acc_voucher_doc_detail_non_taxable_zero CHECK ((vtx_taxability = 'TAXABLE'::accounts."VoucherDocDetailTaxability") OR ((vtx_total_tax_rate = (0)::numeric) AND (vtx_cgst_rate = (0)::numeric) AND (vtx_sgst_rate = (0)::numeric) AND (vtx_igst_rate = (0)::numeric) AND (vtx_cess_rate = (0)::numeric) AND (vtx_cgst_amount = (0)::numeric) AND (vtx_sgst_amount = (0)::numeric) AND (vtx_igst_amount = (0)::numeric) AND (vtx_cess_amount = (0)::numeric) AND (vtx_total_tax_amount = (0)::numeric))),
    CONSTRAINT chk_acc_voucher_doc_detail_supply_tax_logic CHECK (((vtx_supply_nature = 'INTRA_STATE'::accounts."VoucherDocDetailSupplyNature") AND (vtx_igst_rate = (0)::numeric) AND (vtx_igst_amount = (0)::numeric)) OR ((vtx_supply_nature = 'INTER_STATE'::accounts."VoucherDocDetailSupplyNature") AND (vtx_cgst_rate = (0)::numeric) AND (vtx_sgst_rate = (0)::numeric) AND (vtx_cgst_amount = (0)::numeric) AND (vtx_sgst_amount = (0)::numeric)))
)
PARTITION BY LIST (vtx_acc_year);

CREATE TABLE accounts.acc_voucher_doc_einvoice
(
    gde_id               uuid                  NOT NULL DEFAULT uuidv7(),
    gde_gdr_id           uuid                  NOT NULL,
    gde_voucher_id       uuid                  NOT NULL,

    -- ── Multi-branch snapshot ────────────────────────────────────────────
    gde_acc_year         character varying(9)  NOT NULL,
    gde_company_id       uuid                  NOT NULL,
    gde_branch_id        uuid                  NOT NULL,

    gde_status           accounts."GdeStatus"  NOT NULL DEFAULT 'NA'::accounts."GdeStatus",
    gde_irn              character varying(200),
    gde_ack_no           character varying(100),
    gde_ack_on           timestamp(6) with time zone,
    gde_qrcode           text,

    gde_signed_invoice   text,
    gde_signed_qrcode    text,

    gde_cancel_reason    character varying(200),
    gde_cancelled_on     timestamp(6) with time zone,

    gde_last_error_code  character varying(50),
    gde_last_message     character varying(500),

    -- ── Provenance (20260921120000) ──────────────────────────────────────
    gde_gcc_id           uuid,
    gde_gpv_code         character varying(20),
    gde_irp_code         character varying(10),
    gde_next_attempt_on  timestamp(6) with time zone,

    gde_is_active        boolean               NOT NULL DEFAULT true,
    gde_is_deleted       boolean               NOT NULL DEFAULT false,
    gde_sync_date        timestamp(6) with time zone,
    gde_created_on       timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gde_created_by       uuid,
    gde_modified_on      timestamp(6) with time zone,
    gde_modified_by      uuid,

    -- ── Reconciled with the doc-register design (20260922020000) ─────────
    gde_tenant_id        uuid,
    gde_attempt_count    integer               NOT NULL DEFAULT 0,
    gde_last_attempt_on  timestamp(6) with time zone,
    gde_request_payload  jsonb,
    gde_response_payload jsonb,

    CONSTRAINT chk_gde_status CHECK (gde_status = ANY (ARRAY['NA'::accounts."GdeStatus", 'PENDING'::accounts."GdeStatus", 'GENERATED'::accounts."GdeStatus", 'FAILED'::accounts."GdeStatus", 'CANCELED'::accounts."GdeStatus"])),
    CONSTRAINT chk_gde_generated_irn CHECK ((gde_status <> 'GENERATED'::accounts."GdeStatus") OR (gde_irn IS NOT NULL)),
    CONSTRAINT chk_gde_canceled_date CHECK ((gde_status <> 'CANCELED'::accounts."GdeStatus") OR (gde_cancelled_on IS NOT NULL))
)
PARTITION BY LIST (gde_acc_year);

CREATE TABLE accounts.acc_voucher_doc_ewaybill
(
    gdw_id                uuid                 NOT NULL DEFAULT uuidv7(),
    gdw_gdr_id            uuid                 NOT NULL,
    gdw_voucher_id        uuid                 NOT NULL,

    -- ── Multi-branch snapshot ────────────────────────────────────────────
    gdw_acc_year          character varying(9) NOT NULL,
    gdw_company_id        uuid                 NOT NULL,
    gdw_branch_id         uuid                 NOT NULL,

    gdw_status            accounts."GdwStatus" NOT NULL DEFAULT 'NA'::accounts."GdwStatus",
    gdw_no                character varying(100),
    gdw_generated_on      timestamp(6) with time zone,
    gdw_valid_upto        timestamp(6) with time zone,

    gdw_cancel_reason     character varying(200),
    gdw_cancelled_on      timestamp(6) with time zone,

    gdw_vehicle_no        character varying(20),
    gdw_transport_mode    accounts."GdwTransportMode",
    gdw_transporter_id    character varying(15),
    gdw_transporter_name  character varying(150),
    gdw_distance_km       integer,
    gdw_doc_no            character varying(50),
    gdw_doc_date          date,
    gdw_vehicle_type      accounts."GdwVehicleType",
    gdw_transaction_type  character varying(30),
    gdw_sub_supply_type   character varying(50),

    gdw_last_error_code   character varying(50),
    gdw_last_message      character varying(500),

    -- ── Provenance (20260921120000) ──────────────────────────────────────
    gdw_gcc_id            uuid,
    gdw_gpv_code          character varying(20),
    gdw_generated_via     character varying(20),
    gdw_next_attempt_on   timestamp(6) with time zone,

    gdw_is_active         boolean              NOT NULL DEFAULT true,
    gdw_is_deleted        boolean              NOT NULL DEFAULT false,
    gdw_sync_date         timestamp(6) with time zone,
    gdw_created_on        timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gdw_created_by        uuid,
    gdw_modified_on       timestamp(6) with time zone,
    gdw_modified_by       uuid,

    -- ── Reconciled with the doc-register design (20260922020000) ─────────
    gdw_tenant_id         uuid,
    gdw_attempt_count     integer              NOT NULL DEFAULT 0,
    gdw_last_attempt_on   timestamp(6) with time zone,
    gdw_request_payload   jsonb,
    gdw_response_payload  jsonb,
    gdw_transport_doc_no  character varying(50),
    gdw_transport_doc_date date,
    gdw_vehicle_id        uuid,
    gdw_extended_upto     timestamp(6) with time zone,

    CONSTRAINT chk_gdw_status CHECK (gdw_status = ANY (ARRAY['NA'::accounts."GdwStatus", 'PENDING'::accounts."GdwStatus", 'GENERATED'::accounts."GdwStatus", 'FAILED'::accounts."GdwStatus", 'CANCELED'::accounts."GdwStatus", 'EXPIRED'::accounts."GdwStatus"])),
    CONSTRAINT chk_gdw_generated_no CHECK ((gdw_status <> 'GENERATED'::accounts."GdwStatus") OR (gdw_no IS NOT NULL)),
    CONSTRAINT chk_gdw_canceled_date CHECK ((gdw_status <> 'CANCELED'::accounts."GdwStatus") OR (gdw_cancelled_on IS NOT NULL)),
    CONSTRAINT chk_gdw_distance CHECK (COALESCE(gdw_distance_km, 0) >= 0),
    CONSTRAINT chk_gdw_transport_mode CHECK ((gdw_transport_mode IS NULL) OR (gdw_transport_mode = ANY (ARRAY['ROAD'::accounts."GdwTransportMode", 'RAIL'::accounts."GdwTransportMode", 'AIR'::accounts."GdwTransportMode", 'SHIP'::accounts."GdwTransportMode", 'OTHER'::accounts."GdwTransportMode"]))),
    CONSTRAINT chk_gdw_vehicle_type CHECK ((gdw_vehicle_type IS NULL) OR (gdw_vehicle_type = ANY (ARRAY['REGULAR'::accounts."GdwVehicleType", 'ODC'::accounts."GdwVehicleType", 'OTHER'::accounts."GdwVehicleType"]))),
    CONSTRAINT chk_gdw_transporter_id_len CHECK ((gdw_transporter_id IS NULL) OR (char_length((gdw_transporter_id)::text) <= 15))
)
PARTITION BY LIST (gdw_acc_year);


-- ───────────────────────────────────────────────────────────────────────────
--  3. Keys, indexes and foreign keys
--
--  Declared on the parents, so every partition -- including the ones created
--  later, for a year that has not been opened yet -- inherits them.
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE accounts.acc_voucher_doc_register
    ADD CONSTRAINT pk_acc_voucher_doc_register PRIMARY KEY (gdr_id, gdr_acc_year);
ALTER TABLE accounts.acc_voucher_doc_detail
    ADD CONSTRAINT pk_acc_voucher_doc_detail PRIMARY KEY (vtx_id, vtx_acc_year);
ALTER TABLE accounts.acc_voucher_doc_einvoice
    ADD CONSTRAINT pk_acc_voucher_doc_einvoice PRIMARY KEY (gde_id, gde_acc_year);
ALTER TABLE accounts.acc_voucher_doc_ewaybill
    ADD CONSTRAINT pk_acc_voucher_doc_ewaybill PRIMARY KEY (gdw_id, gdw_acc_year);

-- One IRN row and one e-way bill row per document, as before -- with the year
-- added because the constraint has to contain the partition key.
ALTER TABLE accounts.acc_voucher_doc_einvoice
    ADD CONSTRAINT uq_gde_gdr UNIQUE (gde_gdr_id, gde_acc_year);
ALTER TABLE accounts.acc_voucher_doc_ewaybill
    ADD CONSTRAINT uq_gdw_gdr UNIQUE (gdw_gdr_id, gdw_acc_year);

-- Register: one register row per source document, per internal voucher and per
-- business document number. The last two already carried gdr_acc_year; the
-- first gains it as a trailing column.
CREATE UNIQUE INDEX uq_acc_voucher_doc_register_source
    ON accounts.acc_voucher_doc_register (gdr_source_module, gdr_source_doc_id, gdr_acc_year)
    WHERE gdr_is_deleted = false;
CREATE UNIQUE INDEX uq_acc_voucher_doc_register_voucher
    ON accounts.acc_voucher_doc_register (gdr_company_id, gdr_branch_id, gdr_acc_year, gdr_voucher_type_id, gdr_voucher_no)
    WHERE gdr_is_deleted = false;
CREATE UNIQUE INDEX uq_acc_voucher_doc_register_doc
    ON accounts.acc_voucher_doc_register (gdr_company_id, gdr_branch_id, gdr_acc_year, gdr_doc_type, gdr_doc_no, gdr_doc_date)
    WHERE gdr_is_deleted = false;

CREATE INDEX idx_gdr_branch_voucher_date
    ON accounts.acc_voucher_doc_register (gdr_company_id, gdr_branch_id, gdr_acc_year, gdr_voucher_date)
    WHERE gdr_is_deleted = false;
CREATE INDEX idx_gdr_branch_doc_date
    ON accounts.acc_voucher_doc_register (gdr_company_id, gdr_branch_id, gdr_acc_year, gdr_doc_date)
    WHERE gdr_is_deleted = false;
CREATE INDEX idx_gdr_party
    ON accounts.acc_voucher_doc_register (gdr_company_id, gdr_branch_id, gdr_party_id)
    WHERE gdr_is_deleted = false AND gdr_party_id IS NOT NULL;
CREATE INDEX idx_gdr_doc_class
    ON accounts.acc_voucher_doc_register (gdr_source_module, gdr_tran_nature, gdr_doc_flow, gdr_doc_type)
    WHERE gdr_is_deleted = false;
CREATE INDEX idx_gdr_doc_status
    ON accounts.acc_voucher_doc_register (gdr_doc_status)
    WHERE gdr_is_deleted = false;

CREATE INDEX idx_acc_voucher_doc_detail_voucher
    ON accounts.acc_voucher_doc_detail (vtx_company_id, vtx_branch_id, vtx_acc_year, vtx_voucher_id)
    WHERE vtx_is_deleted = false;

-- The IRN and the e-way bill number stay unique, now per year. See the note at
-- the top: neither repeats across financial years.
CREATE UNIQUE INDEX uq_acc_voucher_doc_einvoice_irn
    ON accounts.acc_voucher_doc_einvoice (gde_irn, gde_acc_year)
    WHERE gde_irn IS NOT NULL AND gde_is_deleted = false;
CREATE INDEX idx_gde_status
    ON accounts.acc_voucher_doc_einvoice (gde_status)
    WHERE gde_is_deleted = false;
CREATE INDEX ix_gde_retry
    ON accounts.acc_voucher_doc_einvoice (gde_company_id, gde_next_attempt_on)
    WHERE gde_is_deleted = false AND gde_status = 'FAILED'::accounts."GdeStatus";

CREATE UNIQUE INDEX uq_acc_voucher_doc_ewaybill_no
    ON accounts.acc_voucher_doc_ewaybill (gdw_no, gdw_acc_year)
    WHERE gdw_no IS NOT NULL AND gdw_is_deleted = false;
CREATE INDEX idx_gdw_status
    ON accounts.acc_voucher_doc_ewaybill (gdw_status)
    WHERE gdw_is_deleted = false;
CREATE INDEX ix_gdw_retry
    ON accounts.acc_voucher_doc_ewaybill (gdw_company_id, gdw_next_attempt_on)
    WHERE gdw_is_deleted = false AND gdw_status = 'FAILED'::accounts."GdwStatus";
CREATE INDEX ix_gdw_vehicle
    ON accounts.acc_voucher_doc_ewaybill (gdw_vehicle_id)
    WHERE gdw_vehicle_id IS NOT NULL AND gdw_is_deleted = false;

ALTER TABLE accounts.acc_voucher_doc_register
    ADD CONSTRAINT fk_gdr_voucher_company FOREIGN KEY (gdr_company_id)
        REFERENCES public.companys (comp_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE accounts.acc_voucher_doc_register
    ADD CONSTRAINT fk_gdr_voucher_branch FOREIGN KEY (gdr_branch_id)
        REFERENCES public.branch_master (br_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE accounts.acc_voucher_doc_register
    ADD CONSTRAINT fk_gdr_voucher_party FOREIGN KEY (gdr_party_id)
        REFERENCES accounts.acc_ledger_master (led_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE accounts.acc_voucher_doc_register
    ADD CONSTRAINT fk_gdr_voucher_type FOREIGN KEY (gdr_voucher_type_id)
        REFERENCES accounts.acc_voucher_types (vchr_type_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE accounts.acc_voucher_doc_detail
    ADD CONSTRAINT fk_acc_voucher_doc_detail_company FOREIGN KEY (vtx_company_id)
        REFERENCES public.companys (comp_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE accounts.acc_voucher_doc_detail
    ADD CONSTRAINT fk_acc_voucher_doc_detail_branch FOREIGN KEY (vtx_branch_id)
        REFERENCES public.branch_master (br_id) ON UPDATE CASCADE ON DELETE RESTRICT;

-- The three links into the register, now against its composite key. The line,
-- the IRN and the e-way bill each already carry the register row's year.
ALTER TABLE accounts.acc_voucher_doc_detail
    ADD CONSTRAINT fk_acc_voucher_doc_detail_gdr FOREIGN KEY (vtx_gdr_id, vtx_acc_year)
        REFERENCES accounts.acc_voucher_doc_register (gdr_id, gdr_acc_year)
        ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE accounts.acc_voucher_doc_einvoice
    ADD CONSTRAINT fk_gde_gdr FOREIGN KEY (gde_gdr_id, gde_acc_year)
        REFERENCES accounts.acc_voucher_doc_register (gdr_id, gdr_acc_year)
        ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE accounts.acc_voucher_doc_ewaybill
    ADD CONSTRAINT fk_gdw_gdr FOREIGN KEY (gdw_gdr_id, gdw_acc_year)
        REFERENCES accounts.acc_voucher_doc_register (gdr_id, gdr_acc_year)
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE accounts.acc_voucher_doc_ewaybill
    ADD CONSTRAINT fk_gdw_vehicle FOREIGN KEY (gdw_vehicle_id)
        REFERENCES public.vehicle_master (veh_id) ON UPDATE CASCADE ON DELETE RESTRICT;


-- ───────────────────────────────────────────────────────────────────────────
--  4. The column comments the rebuild dropped
-- ───────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN accounts.acc_voucher_doc_einvoice.gde_gcc_id IS
    'public.gst_company_credential that generated this IRN. A cancellation must be sent through the same provider and GSTIN.';
COMMENT ON COLUMN accounts.acc_voucher_doc_einvoice.gde_irp_code IS
    'Invoice Registration Portal that issued the IRN (NIC1, NIC2, CLEAR, CYGNET, EY, IRIS). A cancellation must reach this portal; the GSP used to reach it may differ.';
COMMENT ON COLUMN accounts.acc_voucher_doc_einvoice.gde_request_payload IS
    'Exactly what was sent to the IRP. With gde_response_payload this is the only answer to "what did we declare on that date" once the document has been amended.';

COMMENT ON COLUMN accounts.acc_voucher_doc_ewaybill.gdw_transporter_id IS
    'The portal''s transporterId, which IS a 15-character GSTIN — NOT our transporter_master uuid. The document''s *_transporter_id (uuid) maps to *_transporter_gstin, and THAT is what lands here.';
COMMENT ON COLUMN accounts.acc_voucher_doc_ewaybill.gdw_gcc_id IS
    'public.gst_company_credential that generated this e-way bill. Part-B updates, extensions and cancellation must go through the same provider.';
COMMENT ON COLUMN accounts.acc_voucher_doc_ewaybill.gdw_generated_via IS
    'EWB_PORTAL | IRP_WITH_IRN | IRP_BY_IRN — decides where a Part-B update may be sent, which the e-way bill number alone does not tell you.';
COMMENT ON COLUMN accounts.acc_voucher_doc_ewaybill.gdw_request_payload IS
    'Exactly what was sent to the portal. With gdw_response_payload this is the only answer to "what did we declare on that date" once the document has been amended.';
COMMENT ON COLUMN accounts.acc_voucher_doc_ewaybill.gdw_transport_doc_no IS
    'Part-B transDocNo — the LR / consignment note, from the document''s *_lr_no. What was DECLARED, so it is not re-derived from a document that may since have been amended.';
COMMENT ON COLUMN accounts.acc_voucher_doc_ewaybill.gdw_transport_doc_date IS
    'Part-B transDocDate, from the document''s *_lr_date.';
COMMENT ON COLUMN accounts.acc_voucher_doc_ewaybill.gdw_vehicle_id IS
    'Our public.vehicle_master row, beside gdw_vehicle_no which is the plate exactly as the portal received it. Two columns because the portal takes a string and we want the master.';


-- ───────────────────────────────────────────────────────────────────────────
--  5. The partition helper
--
--  public.ensure_acc_year_partitions is what the application calls when a
--  fiscal year is opened; a table missing from it is a table whose first save
--  of the new year fails with "no partition of relation ... found for row".
--  The four go in after the vouchers -- the register before its three
--  children, parent before child as everywhere else in this function.
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ensure_acc_year_partitions(p_acc_year character)
RETURNS void
LANGUAGE plpgsql
AS $ensure$

DECLARE
    v_year   text := btrim(p_acc_year);
    v_suffix text;
BEGIN
    IF v_year !~ '^[0-9]{4}-[0-9]{4}$' THEN
        RAISE EXCEPTION 'Invalid accounting year %, expected YYYY-YYYY', p_acc_year;
    END IF;

    v_suffix := replace(v_year, '-', '_');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill FOR VALUES IN (%L)',
        'sale_bill_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_bill_item FOR VALUES IN (%L)',
        'sale_bill_item_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_tender_detail FOR VALUES IN (%L)',
        'acc_tender_detail_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_status_log FOR VALUES IN (%L)',
        'txn_status_log_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_charge_detail FOR VALUES IN (%L)',
        'txn_charge_detail_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_hold FOR VALUES IN (%L)',
        'txn_hold_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order FOR VALUES IN (%L)',
        'sale_order_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_order_item FOR VALUES IN (%L)',
        'sale_order_item_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation FOR VALUES IN (%L)',
        'sale_quotation_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_quotation_item FOR VALUES IN (%L)',
        'sale_quotation_item_' || v_suffix, v_year);

    -- The bill is partitioned again as of 20260811090000: on the FY it was
    -- RAISED in, which it keeps for life.
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_bill_balance FOR VALUES IN (%L)',
        'acc_bill_balance_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_bill_adjustment FOR VALUES IN (%L)',
        'acc_bill_adjustment_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_opening_balance FOR VALUES IN (%L)',
        'acc_opening_balance_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_pdc_register FOR VALUES IN (%L)',
        'acc_pdc_register_' || v_suffix, v_year);

    -- ── Added by 20260915120000 ──────────────────────────────────────────
    --  Header BEFORE lines: acc_vouchers carries fk_av_header into it.
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_header FOR VALUES IN (%L)',
        'acc_voucher_header_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_vouchers FOR VALUES IN (%L)',
        'acc_vouchers_' || v_suffix, v_year);

    -- ── Added by 20260921120000 ──────────────────────────────────────────
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.gst_api_log FOR VALUES IN (%L)',
        'gst_api_log_' || v_suffix, v_year);

    -- ── Added by 20260921140000 ──────────────────────────────────────────
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.loyalty_ledger FOR VALUES IN (%L)',
        'loyalty_ledger_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.loyalty_gift_redeem FOR VALUES IN (%L)',
        'loyalty_gift_redeem_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.loyalty_gift_redeem_item FOR VALUES IN (%L)',
        'loyalty_gift_redeem_item_' || v_suffix, v_year);

    -- ── Added by 20260921160000 ──────────────────────────────────────────
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.loyalty_coupon_txn FOR VALUES IN (%L)',
        'loyalty_coupon_txn_' || v_suffix, v_year);

    -- ── Added by 20260921180000 ──────────────────────────────────────────
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.promotion_usage FOR VALUES IN (%L)',
        'promotion_usage_' || v_suffix, v_year);

    -- ── Added by 20260921200000 ──────────────────────────────────────────
    --  The six sales documents. Parent before child throughout.
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_return FOR VALUES IN (%L)',
        'sale_return_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_return_item FOR VALUES IN (%L)',
        'sale_return_item_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_dc FOR VALUES IN (%L)',
        'sale_dc_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_dc_item FOR VALUES IN (%L)',
        'sale_dc_item_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_dc_return FOR VALUES IN (%L)',
        'sale_dc_return_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS sales.%I PARTITION OF sales.sale_dc_return_item FOR VALUES IN (%L)',
        'sale_dc_return_item_' || v_suffix, v_year);

    -- ── Added by 20260922000000 ──────────────────────────────────────────
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_temp_credit FOR VALUES IN (%L)',
        'acc_temp_credit_' || v_suffix, v_year);

    -- ── Added by 20260922040000 ──────────────────────────────────────────
    --  The transport band. Written for every goods-moving document that has a
    --  consignment, so a missing partition stops a dispatch.
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.txn_transport_detail FOR VALUES IN (%L)',
        'txn_transport_detail_' || v_suffix, v_year);

    -- ── Added by 20260922100000 ──────────────────────────────────
    --  The GST document band. The register carries fk_*_gdr from the other
    --  three, so it is created first.
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_register FOR VALUES IN (%L)',
        'acc_voucher_doc_register_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_detail FOR VALUES IN (%L)',
        'acc_voucher_doc_detail_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_einvoice FOR VALUES IN (%L)',
        'acc_voucher_doc_einvoice_' || v_suffix, v_year);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_ewaybill FOR VALUES IN (%L)',
        'acc_voucher_doc_ewaybill_' || v_suffix, v_year);

    -- The stock engine's four, added by 20260907090000. This is the part the
    -- catalogue-driven helper does not reach.
    PERFORM stock.fn_create_stock_partitions(v_year::character(9));
END;
$ensure$;


-- ───────────────────────────────────────────────────────────────────────────
--  6. Partitions for every year that exists
--
--  Three sources, because none of them alone is complete on every deployment:
--  the fiscal years on record, the years that already have a sale_bill
--  partition (the convention 20260922040000 used), and -- the one that matters
--  for the copy below -- every acc_year actually present in the parked rows.
--  A year in the data but not in fiscal_years would otherwise fail the INSERT
--  with "no partition of relation ... found for row".
-- ───────────────────────────────────────────────────────────────────────────

DO $partitions$
DECLARE
    v_year   text;
    v_suffix text;
BEGIN
    FOR v_year IN
        SELECT DISTINCT y FROM (
            SELECT btrim(fy_year_name) AS y
              FROM public.fiscal_years
             WHERE is_deleted = false
            UNION
            SELECT replace(substring(c.relname from '([0-9]{4}_[0-9]{4})$'), '_', '-')
              FROM pg_class c
              JOIN pg_inherits i ON i.inhrelid = c.oid
              JOIN pg_class    p ON p.oid      = i.inhparent
             WHERE p.relname = 'sale_bill'
               AND c.relname ~ '[0-9]{4}_[0-9]{4}$'
            UNION SELECT btrim(gdr_acc_year) FROM accounts.acc_voucher_doc_register_unpart
            UNION SELECT btrim(vtx_acc_year) FROM accounts.acc_voucher_doc_detail_unpart
            UNION SELECT btrim(gde_acc_year) FROM accounts.acc_voucher_doc_einvoice_unpart
            UNION SELECT btrim(gdw_acc_year) FROM accounts.acc_voucher_doc_ewaybill_unpart
        ) s
        WHERE y ~ '^[0-9]{4}-[0-9]{4}$'
        ORDER BY 1
    LOOP
        v_suffix := replace(v_year, '-', '_');

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_register FOR VALUES IN (%L)',
            'acc_voucher_doc_register_' || v_suffix, v_year);
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_detail FOR VALUES IN (%L)',
            'acc_voucher_doc_detail_' || v_suffix, v_year);
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_einvoice FOR VALUES IN (%L)',
            'acc_voucher_doc_einvoice_' || v_suffix, v_year);
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS accounts.%I PARTITION OF accounts.acc_voucher_doc_ewaybill FOR VALUES IN (%L)',
            'acc_voucher_doc_ewaybill_' || v_suffix, v_year);

        RAISE NOTICE 'acc_voucher_doc_* partitions ensured for %', v_year;
    END LOOP;
END
$partitions$;


-- ───────────────────────────────────────────────────────────────────────────
--  7. Copy the rows over, register first
--
--  Column lists are explicit, so the reordering in section 2 does not matter.
-- ───────────────────────────────────────────────────────────────────────────

INSERT INTO accounts.acc_voucher_doc_register
    (gdr_id, gdr_source_module, gdr_tran_nature, gdr_doc_flow, gdr_doc_sign,
     gdr_source_doc_id, gdr_acc_year, gdr_company_id, gdr_branch_id,
     gdr_voucher_type_id, gdr_voucher_id, gdr_voucher_no, gdr_voucher_date,
     gdr_voucher_refno, gdr_doc_type, gdr_doc_no, gdr_doc_date, gdr_doc_ref_no,
     gdr_doc_status, gdr_doc_cancel_reason, gdr_doc_canceled_on,
     gdr_doc_note_no, gdr_doc_note_date, gdr_doc_note_reason,
     gdr_supply_class, gdr_taxability, gdr_supply_nature,
     gdr_place_of_supply_code, gdr_place_of_supply_name,
     gdr_is_reverse_charge, gdr_is_einvoice_applicable, gdr_is_ewaybill_applicable,
     gdr_party_type, gdr_party_id, gdr_party_name, gdr_party_addr1,
     gdr_party_addr2, gdr_party_addr3, gdr_party_location, gdr_party_pin,
     gdr_party_state_code, gdr_party_state_name, gdr_party_gst_type,
     gdr_party_gstin, gdr_party_ecom_gstin,
     gdr_gross_value, gdr_discount_value, gdr_taxable_value, gdr_cgst_value,
     gdr_sgst_value, gdr_igst_value, gdr_cess_value, gdr_state_cess_value,
     gdr_tcs_value, gdr_other_charge, gdr_round_off, gdr_bill_value,
     gdr_remarks, gdr_is_active, gdr_igst_on_intra, gdr_is_deleted,
     gdr_sync_date, gdr_created_on, gdr_created_by, gdr_updated_on, gdr_updated_by)
SELECT
     gdr_id, gdr_source_module, gdr_tran_nature, gdr_doc_flow, gdr_doc_sign,
     gdr_source_doc_id, gdr_acc_year, gdr_company_id, gdr_branch_id,
     gdr_voucher_type_id, gdr_voucher_id, gdr_voucher_no, gdr_voucher_date,
     gdr_voucher_refno, gdr_doc_type, gdr_doc_no, gdr_doc_date, gdr_doc_ref_no,
     gdr_doc_status, gdr_doc_cancel_reason, gdr_doc_canceled_on,
     gdr_doc_note_no, gdr_doc_note_date, gdr_doc_note_reason,
     gdr_supply_class, gdr_taxability, gdr_supply_nature,
     gdr_place_of_supply_code, gdr_place_of_supply_name,
     gdr_is_reverse_charge, gdr_is_einvoice_applicable, gdr_is_ewaybill_applicable,
     gdr_party_type, gdr_party_id, gdr_party_name, gdr_party_addr1,
     gdr_party_addr2, gdr_party_addr3, gdr_party_location, gdr_party_pin,
     gdr_party_state_code, gdr_party_state_name, gdr_party_gst_type,
     gdr_party_gstin, gdr_party_ecom_gstin,
     gdr_gross_value, gdr_discount_value, gdr_taxable_value, gdr_cgst_value,
     gdr_sgst_value, gdr_igst_value, gdr_cess_value, gdr_state_cess_value,
     gdr_tcs_value, gdr_other_charge, gdr_round_off, gdr_bill_value,
     gdr_remarks, gdr_is_active, gdr_igst_on_intra, gdr_is_deleted,
     gdr_sync_date, gdr_created_on, gdr_created_by, gdr_updated_on, gdr_updated_by
FROM accounts.acc_voucher_doc_register_unpart;

INSERT INTO accounts.acc_voucher_doc_detail
    (vtx_id, vtx_gdr_id, vtx_voucher_id, vtx_row_no, vtx_acc_year,
     vtx_company_id, vtx_branch_id, vtx_taxability, vtx_supply_nature,
     vtx_item_id, vtx_item_code, vtx_item_name, vtx_item_description,
     vtx_hsn_code, vtx_tally_hsn_source, vtx_unit_id, vtx_item_qty,
     vtx_item_rate, vtx_item_discount, vtx_is_service,
     vtx_taxable_value, vtx_total_tax_rate, vtx_tax_id,
     vtx_cgst_rate, vtx_sgst_rate, vtx_igst_rate, vtx_cess_rate,
     vtx_cgst_amount, vtx_sgst_amount, vtx_igst_amount, vtx_cess_amount,
     vtx_total_tax_amount, vtx_other_amount, vtx_total_value, vtx_bill_value,
     vtx_taxable_ledger_id, vtx_cgst_ledger_id, vtx_sgst_ledger_id,
     vtx_igst_ledger_id, vtx_cess_ledger_id,
     vtx_is_active, vtx_is_deleted, vtx_sync_date, vtx_created_on,
     vtx_created_by, vtx_updated_on, vtx_updated_by)
SELECT
     vtx_id, vtx_gdr_id, vtx_voucher_id, vtx_row_no, vtx_acc_year,
     vtx_company_id, vtx_branch_id, vtx_taxability, vtx_supply_nature,
     vtx_item_id, vtx_item_code, vtx_item_name, vtx_item_description,
     vtx_hsn_code, vtx_tally_hsn_source, vtx_unit_id, vtx_item_qty,
     vtx_item_rate, vtx_item_discount, vtx_is_service,
     vtx_taxable_value, vtx_total_tax_rate, vtx_tax_id,
     vtx_cgst_rate, vtx_sgst_rate, vtx_igst_rate, vtx_cess_rate,
     vtx_cgst_amount, vtx_sgst_amount, vtx_igst_amount, vtx_cess_amount,
     vtx_total_tax_amount, vtx_other_amount, vtx_total_value, vtx_bill_value,
     vtx_taxable_ledger_id, vtx_cgst_ledger_id, vtx_sgst_ledger_id,
     vtx_igst_ledger_id, vtx_cess_ledger_id,
     vtx_is_active, vtx_is_deleted, vtx_sync_date, vtx_created_on,
     vtx_created_by, vtx_updated_on, vtx_updated_by
FROM accounts.acc_voucher_doc_detail_unpart;

INSERT INTO accounts.acc_voucher_doc_einvoice
    (gde_id, gde_gdr_id, gde_voucher_id, gde_acc_year, gde_company_id,
     gde_branch_id, gde_status, gde_irn, gde_ack_no, gde_ack_on, gde_qrcode,
     gde_signed_invoice, gde_signed_qrcode, gde_cancel_reason, gde_cancelled_on,
     gde_last_error_code, gde_last_message,
     gde_gcc_id, gde_gpv_code, gde_irp_code, gde_next_attempt_on,
     gde_is_active, gde_is_deleted, gde_sync_date, gde_created_on,
     gde_created_by, gde_modified_on, gde_modified_by,
     gde_tenant_id, gde_attempt_count, gde_last_attempt_on,
     gde_request_payload, gde_response_payload)
SELECT
     gde_id, gde_gdr_id, gde_voucher_id, gde_acc_year, gde_company_id,
     gde_branch_id, gde_status, gde_irn, gde_ack_no, gde_ack_on, gde_qrcode,
     gde_signed_invoice, gde_signed_qrcode, gde_cancel_reason, gde_cancelled_on,
     gde_last_error_code, gde_last_message,
     gde_gcc_id, gde_gpv_code, gde_irp_code, gde_next_attempt_on,
     gde_is_active, gde_is_deleted, gde_sync_date, gde_created_on,
     gde_created_by, gde_modified_on, gde_modified_by,
     gde_tenant_id, gde_attempt_count, gde_last_attempt_on,
     gde_request_payload, gde_response_payload
FROM accounts.acc_voucher_doc_einvoice_unpart;

INSERT INTO accounts.acc_voucher_doc_ewaybill
    (gdw_id, gdw_gdr_id, gdw_voucher_id, gdw_acc_year, gdw_company_id,
     gdw_branch_id, gdw_status, gdw_no, gdw_generated_on, gdw_valid_upto,
     gdw_cancel_reason, gdw_cancelled_on, gdw_vehicle_no, gdw_transport_mode,
     gdw_transporter_id, gdw_transporter_name, gdw_distance_km, gdw_doc_no,
     gdw_doc_date, gdw_vehicle_type, gdw_transaction_type, gdw_sub_supply_type,
     gdw_last_error_code, gdw_last_message,
     gdw_gcc_id, gdw_gpv_code, gdw_generated_via, gdw_next_attempt_on,
     gdw_is_active, gdw_is_deleted, gdw_sync_date, gdw_created_on,
     gdw_created_by, gdw_modified_on, gdw_modified_by,
     gdw_tenant_id, gdw_attempt_count, gdw_last_attempt_on,
     gdw_request_payload, gdw_response_payload, gdw_transport_doc_no,
     gdw_transport_doc_date, gdw_vehicle_id, gdw_extended_upto)
SELECT
     gdw_id, gdw_gdr_id, gdw_voucher_id, gdw_acc_year, gdw_company_id,
     gdw_branch_id, gdw_status, gdw_no, gdw_generated_on, gdw_valid_upto,
     gdw_cancel_reason, gdw_cancelled_on, gdw_vehicle_no, gdw_transport_mode,
     gdw_transporter_id, gdw_transporter_name, gdw_distance_km, gdw_doc_no,
     gdw_doc_date, gdw_vehicle_type, gdw_transaction_type, gdw_sub_supply_type,
     gdw_last_error_code, gdw_last_message,
     gdw_gcc_id, gdw_gpv_code, gdw_generated_via, gdw_next_attempt_on,
     gdw_is_active, gdw_is_deleted, gdw_sync_date, gdw_created_on,
     gdw_created_by, gdw_modified_on, gdw_modified_by,
     gdw_tenant_id, gdw_attempt_count, gdw_last_attempt_on,
     gdw_request_payload, gdw_response_payload, gdw_transport_doc_no,
     gdw_transport_doc_date, gdw_vehicle_id, gdw_extended_upto
FROM accounts.acc_voucher_doc_ewaybill_unpart;


-- ───────────────────────────────────────────────────────────────────────────
--  8. Drop the parked tables. Children first, they still hold the parked FKs.
-- ───────────────────────────────────────────────────────────────────────────

DROP TABLE accounts.acc_voucher_doc_ewaybill_unpart;
DROP TABLE accounts.acc_voucher_doc_einvoice_unpart;
DROP TABLE accounts.acc_voucher_doc_detail_unpart;
DROP TABLE accounts.acc_voucher_doc_register_unpart;
