export {
  DEFAULT_ACTOR,
  DEFAULT_ACTOR as DEFAULT_AUDIT_ACTOR,
  DEFAULT_LIMIT,
  DEFAULT_PAGE,
  applyPresentFields,
  buildErrorResponse,
  buildErrorResponse as buildAccountsErrorResponse,
  buildErrorResponse as buildFixedErrorResponse,
  buildErrorResponse as buildInventoryErrorResponse,
  buildErrorResponse as buildPurchaseErrorResponse,
  buildErrorResponse as buildSalesErrorResponse,
  buildErrorResponse as buildMasterErrorResponse,
  buildErrorResponse as buildSettingsErrorResponse,
  buildErrorResponse as buildStockErrorResponse,
  hasOwnProperty,
  isExclusionConstraintError,
  isForeignKeyConstraintError,
  isPrismaErrorCode,
  isUniqueConstraintError,
  normalizeNullableString,
  normalizeRequiredText,
  resolveActor,
  throwBadRequest,
  throwBadRequest as throwAccountsBadRequest,
  throwBadRequest as throwMasterBadRequest,
  throwBadRequest as throwFixedBadRequest,
  throwBadRequest as throwInventoryBadRequest,
  throwBadRequest as throwPurchaseBadRequest,
  throwBadRequest as throwSalesBadRequest,
  throwBadRequest as throwSettingsBadRequest,
  throwBadRequest as throwStockBadRequest,
  throwConflict,
  throwConflict as throwAccountsConflict,
  throwConflict as throwMasterConflict,
  throwConflict as throwFixedConflict,
  throwConflict as throwInventoryConflict,
  throwConflict as throwPurchaseConflict,
  throwConflict as throwSalesConflict,
  throwConflict as throwSettingsConflict,
  throwConflict as throwStockConflict,
  throwForbidden,
  throwForbidden as throwAccountsForbidden,
  throwForbidden as throwMasterForbidden,
  throwForbidden as throwFixedForbidden,
  throwForbidden as throwInventoryForbidden,
  throwForbidden as throwPurchaseForbidden,
  throwForbidden as throwSalesForbidden,
  throwForbidden as throwSettingsForbidden,
  throwForbidden as throwStockForbidden,
  throwNotFound,
  throwNotFound as throwAccountsNotFound,
  throwNotFound as throwMasterNotFound,
  throwNotFound as throwFixedNotFound,
  throwNotFound as throwInventoryNotFound,
  throwNotFound as throwPurchaseNotFound,
  throwNotFound as throwSalesNotFound,
  throwNotFound as throwSettingsNotFound,
  throwNotFound as throwStockNotFound,
  throwOnUniqueConstraintError,
  throwUnprocessable,
  throwUnprocessable as throwStockUnprocessable,
  toNullableNumber,
  toNumber,
} from './module-shared.utils';
export type {
  ModuleErrorDetail,
  ModuleErrorDetail as AccountsErrorDetail,
  ModuleErrorDetail as MasterErrorDetail,
  ModuleErrorDetail as FixedErrorDetail,
  ModuleErrorDetail as InventoryErrorDetail,
  ModuleErrorDetail as PurchaseErrorDetail,
  ModuleErrorDetail as SalesErrorDetail,
  ModuleErrorDetail as SettingsErrorDetail,
  ModuleErrorDetail as StockErrorDetail,
  ModuleErrorResponse,
  ModuleErrorResponse as AccountsErrorResponse,
  ModuleErrorResponse as MasterErrorResponse,
  ModuleErrorResponse as FixedErrorResponse,
  ModuleErrorResponse as InventoryErrorResponse,
  ModuleErrorResponse as PurchaseErrorResponse,
  ModuleErrorResponse as SalesErrorResponse,
  ModuleErrorResponse as SettingsErrorResponse,
  ModuleErrorResponse as StockErrorResponse,
  ModuleWriteClient,
  ModuleWriteClient as AccountsWriteClient,
  ModuleWriteClient as MasterWriteClient,
  ModuleWriteClient as FixedWriteClient,
  ModuleWriteClient as InventoryWriteClient,
  ModuleWriteClient as PurchaseWriteClient,
  ModuleWriteClient as SalesWriteClient,
  ModuleWriteClient as SettingsWriteClient,
  ModuleWriteClient as StockWriteClient,
  PresentFieldTransform,
} from './module-shared.utils';
