export {
  DEFAULT_ACTOR,
  DEFAULT_ACTOR as DEFAULT_AUDIT_ACTOR,
  DEFAULT_LIMIT,
  DEFAULT_PAGE,
  applyPresentFields,
  buildErrorResponse,
  buildErrorResponse as buildAccountsErrorResponse,
  buildErrorResponse as buildFixedErrorResponse,
  buildErrorResponse as buildInventoryErrorResponse,
  buildErrorResponse as buildPurchaseErrorResponse,
  buildErrorResponse as buildSalesErrorResponse,
  buildErrorResponse as buildSettingsErrorResponse,
  hasOwnProperty,
  isForeignKeyConstraintError,
  isPrismaErrorCode,
  isUniqueConstraintError,
  normalizeNullableString,
  normalizeRequiredText,
  resolveActor,
  throwBadRequest,
  throwBadRequest as throwAccountsBadRequest,
  throwBadRequest as throwFixedBadRequest,
  throwBadRequest as throwInventoryBadRequest,
  throwBadRequest as throwPurchaseBadRequest,
  throwBadRequest as throwSalesBadRequest,
  throwBadRequest as throwSettingsBadRequest,
  throwConflict,
  throwConflict as throwAccountsConflict,
  throwConflict as throwFixedConflict,
  throwConflict as throwInventoryConflict,
  throwConflict as throwPurchaseConflict,
  throwConflict as throwSalesConflict,
  throwConflict as throwSettingsConflict,
  throwNotFound,
  throwNotFound as throwAccountsNotFound,
  throwNotFound as throwFixedNotFound,
  throwNotFound as throwInventoryNotFound,
  throwNotFound as throwPurchaseNotFound,
  throwNotFound as throwSalesNotFound,
  throwNotFound as throwSettingsNotFound,
  throwOnUniqueConstraintError,
  toNullableNumber,
  toNumber,
} from './module-shared.utils';
export type {
  ModuleErrorDetail,
  ModuleErrorDetail as AccountsErrorDetail,
  ModuleErrorDetail as FixedErrorDetail,
  ModuleErrorDetail as InventoryErrorDetail,
  ModuleErrorDetail as PurchaseErrorDetail,
  ModuleErrorDetail as SalesErrorDetail,
  ModuleErrorDetail as SettingsErrorDetail,
  ModuleErrorResponse,
  ModuleErrorResponse as AccountsErrorResponse,
  ModuleErrorResponse as FixedErrorResponse,
  ModuleErrorResponse as InventoryErrorResponse,
  ModuleErrorResponse as PurchaseErrorResponse,
  ModuleErrorResponse as SalesErrorResponse,
  ModuleErrorResponse as SettingsErrorResponse,
  ModuleWriteClient,
  ModuleWriteClient as AccountsWriteClient,
  ModuleWriteClient as FixedWriteClient,
  ModuleWriteClient as InventoryWriteClient,
  ModuleWriteClient as PurchaseWriteClient,
  ModuleWriteClient as SalesWriteClient,
  ModuleWriteClient as SettingsWriteClient,
  PresentFieldTransform,
} from './module-shared.utils';
