-- Seed: fixed.form_field -- the fields inside each widget-master tab (378 rows).
--
-- Runs after Form_Section.sql -- field_section_id is a foreign key into it, ON DELETE
-- CASCADE.
--
-- field_name MUST equal the form field's binding key (item_retail_item, cus_credit_days,
-- ...), not a label-derived name: the widget-master popup matches on it, and a field
-- whose name does not bind shows up as "not on form" and controls nothing.
-- field_gui_name is the label shown, field_secondary_text the helper line under it.
--
-- Two guards, because this is a grandchild of the menu tree:
--   * a section that ALREADY HAS ANY FIELD is skipped, so local re-labelling survives;
--   * a section that does not exist in the target database is skipped as well, instead
--     of failing the foreign key and aborting the file -- that is what happens to every
--     menu whose sections Form_Section.sql left alone.
-- Regenerate with: npm run seed:export:ui-config
-- Run: psql "$DATABASE_URL" -f prisma/seed/Form_Field.sql
--      or: npm run seed:run -- --only=Form_Field.sql

BEGIN;

INSERT INTO fixed.form_field
    (field_id, field_section_id, field_name, field_gui_name, field_secondary_text, field_position, field_visibility, field_created_by)
SELECT v.* FROM (VALUES
    -- ============ Item Group Master / group master (id 1) ============
     (138::integer, 1::integer, 'itg_name'::varchar, 'Item Group Name'::varchar, NULL::varchar, 1::integer, true::boolean, 'system'::text)
    ,(139, 1 , 'itg_short'                   , 'Short Name'              , NULL                  , 2 , true , 'system')
    ,(140, 1 , 'itg_position'                , 'Position'                , NULL                  , 3 , true , 'system')
    ,(141, 1 , 'itg_parent'                  , 'Parent Group'            , NULL                  , 4 , true , 'system')
    ,(142, 1 , 'itg_description'             , 'Description'             , NULL                  , 5 , true , 'system')
    ,(143, 1 , 'itg_image'                   , 'Image'                   , NULL                  , 6 , true , 'system')
    -- ============ Item Brand Master / basic (id 2) ============
    ,(5  , 2 , 'name'                        , 'name'                    , 'name'                , 1 , true , 'system')
    -- ============ Unit Master / MAIN SECTION (id 6) ============
    ,(12 , 6 , 'unit_is_pack_unit'           , 'Pack Unit'               , NULL                  , 1 , true , 'system')
    ,(13 , 6 , 'unit_base_unit_id'           , 'Base Unit'               , NULL                  , 2 , true , 'system')
    ,(14 , 6 , 'unit_conversion'             , 'Conversion'              , NULL                  , 3 , true , 'system')
    ,(15 , 6 , 'unit_loading'                , 'Loading charge'          , NULL                  , 4 , true , 'system')
    ,(16 , 6 , 'unit_unloading'              , 'Unloading charge'        , NULL                  , 5 , true , 'system')
    ,(17 , 6 , 'unit_attach_charge'          , 'Attach Charge'           , NULL                  , 6 , true , 'system')
    ,(18 , 6 , 'unit_description'            , 'Unit Description'        , NULL                  , 7 , true , 'system')
    ,(19 , 6 , 'unit_is_active'              , 'Active'                  , NULL                  , 8 , true , 'system')
    -- ============ State Master / basic (id 7) ============
    ,(20 , 7 , 'state_name'                  , 'State name'              , ''                    , 1 , true , 'system')
    ,(21 , 7 , 'state_alias'                 , 'Alias'                   , ''                    , 2 , true , 'system')
    ,(22 , 7 , 'state_short'                 , 'Short name'              , ''                    , 3 , true , 'system')
    ,(23 , 7 , 'state_order'                 , 'Order'                   , ''                    , 4 , true , 'system')
    ,(24 , 7 , 'state_is_active'             , 'status'                  , ''                    , 4 , true , 'system')
    ,(104, 7 , 'stm_decription'              , 'Description'             , ''                    , 5 , true , 'system')
    -- ============ City Master / basic (id 8) ============
    ,(25 , 8 , 'cty_name'                    , 'City name'               , NULL                  , 1 , true , 'system')
    ,(26 , 8 , 'cty_alias'                   , 'Alias'                   , NULL                  , 2 , true , 'system')
    ,(27 , 8 , 'cty_short'                   , 'Short name'              , NULL                  , 3 , true , 'system')
    ,(29 , 8 , 'cty_state'                   , 'State'                   , NULL                  , 4 , true , 'system')
    ,(28 , 8 , 'cty_order'                   , 'Order'                   , NULL                  , 5 , true , 'system')
    ,(30 , 8 , 'cty_is_active'               , 'Status'                  , NULL                  , 6 , true , 'system')
    -- ============ Area Master / basic (id 9) ============
    ,(31 , 9 , 'area_name'                   , 'Area name'               , NULL                  , 1 , true , 'system')
    ,(32 , 9 , 'area_alias'                  , 'Alias'                   , NULL                  , 2 , true , 'system')
    ,(33 , 9 , 'area_short'                  , 'Short name'              , NULL                  , 3 , true , 'system')
    ,(34 , 9 , 'area_city'                   , 'City'                    , NULL                  , 4 , true , 'system')
    ,(35 , 9 , 'area_distance'               , 'Distance'                , NULL                  , 5 , true , 'system')
    ,(36 , 9 , 'area_collection_days'        , 'Collection days'         , NULL                  , 6 , true , 'system')
    ,(37 , 9 , 'area_sort'                   , 'sort'                    , NULL                  , 7 , true , 'system')
    ,(38 , 9 , 'area_is_active'              , 'Status'                  , NULL                  , 8 , true , 'system')
    ,(103, 9 , 'arm_desc'                    , 'Description'             , NULL                  , 9 , true , 'system')
    -- ============ Customer Type Master / customer group (id 10) ============
    ,(39 , 10, 'cus_group_name'              , 'Group name'              , NULL                  , 1 , true , 'system')
    ,(40 , 10, 'cus_short_name'              , 'Short name'              , NULL                  , 2 , true , 'system')
    ,(41 , 10, 'cus_sort_order'              , 'Sort order'              , NULL                  , 3 , true , 'system')
    ,(42 , 10, 'cus_dis'                     , 'Discount'                , NULL                  , 4 , true , 'system')
    ,(43 , 10, 'cus_collection_days'         , 'Collection days'         , NULL                  , 5 , true , 'system')
    ,(44 , 10, 'cus_debit_days'              , 'Debit Days'              , NULL                  , 6 , true , 'system')
    ,(45 , 10, 'cus_debit_limit'             , 'Debit limit'             , NULL                  , 7 , true , 'system')
    ,(46 , 10, 'cus_bills_limit'             , 'Bills limit'             , NULL                  , 8 , true , 'system')
    ,(47 , 10, 'cus_debit_allowed'           , 'Debit allowed'           , NULL                  , 9 , true , 'system')
    ,(48 , 10, 'cus_overdue_billing'         , 'Overdue billing'         , NULL                  , 10, true , 'system')
    ,(49 , 10, 'cus_is_active'               , 'Status'                  , NULL                  , 10, true , 'system')
    ,(50 , 10, 'cus_narration'               , 'Narration'               , NULL                  , 11, true , 'system')
    -- ============ Tender Master / basic (id 11) ============
    ,(51 , 11, 'tender_name'                 , 'Tender Name'             , NULL                  , 1 , true , 'system')
    ,(52 , 11, 'tender_type'                 , 'Tender Type'             , NULL                  , 2 , true , 'system')
    ,(53 , 11, 'tnd_acc_ldger'               , 'Account Ledger'          , NULL                  , 3 , true , 'system')
    ,(54 , 11, 'tnd_min_amount'              , 'Min Amount'              , NULL                  , 4 , true , 'system')
    ,(55 , 11, 'tnd_max_amount'              , 'Max Amount'              , NULL                  , 5 , true , 'system')
    ,(56 , 11, 'tnd_Surcharge'               , 'Surcharge'               , NULL                  , 6 , true , 'system')
    ,(57 , 11, 'tnd_allow_edit_surcharge'    , 'Allow edit Surcharge'    , NULL                  , 7 , true , 'system')
    ,(58 , 11, 'tnd_allow_edit_ledger'       , 'Allow edit ledger'       , NULL                  , 8 , true , 'system')
    ,(59 , 11, 'tnd_remarks'                 , 'Remarks'                 , NULL                  , 9 , true , 'system')
    -- ============ Supplier Groups / basic (id 12) ============
    ,(60 , 12, 'spg_group_name'              , 'Group Name'              , NULL                  , 1 , true , 'system')
    ,(61 , 12, 'spg_short_name'              , 'Short Name'              , NULL                  , 2 , true , 'system')
    ,(62 , 12, 'spg_description'             , 'Description'             , NULL                  , 3 , true , 'system')
    -- ============ Item Brand Master / brand master (id 13) ============
    ,(63 , 13, 'item_brand_name'             , 'Item Brand Name'         , NULL                  , 1 , true , 'system')
    ,(64 , 13, 'item_short'                  , 'Short Name'              , NULL                  , 2 , true , 'system')
    ,(65 , 13, 'item_position'               , 'Position'                , NULL                  , 3 , true , 'system')
    ,(66 , 13, 'item_parent'                 , 'Parent Brand'            , NULL                  , 4 , true , 'system')
    ,(67 , 13, 'item_description'            , 'Description'             , NULL                  , 5 , true , 'system')
    ,(68 , 13, 'item_image'                  , 'Image'                   , NULL                  , 6 , true , 'system')
    -- ============ item category master / basic details (id 14) ============
    ,(69 , 14, 'iten_ctg_name'               , 'Category name'           , ''                    , 1 , true , 'system')
    ,(70 , 14, 'Itg_ctg_short_name'          , 'Short name'              , ''                    , 2 , true , 'system')
    ,(71 , 14, 'Itg_ctg_short_position'      , 'Position'                , ''                    , 3 , true , 'system')
    ,(72 , 14, 'itg_parent_category'         , 'Parent category'         , ''                    , 4 , true , 'system')
    ,(73 , 14, 'itg_description'             , 'Description'             , ''                    , 5 , true , 'system')
    ,(74 , 14, 'itg_category_image'          , 'Image'                   , ''                    , 6 , true , 'system')
    -- ============ Item Section Master / basic (id 15) ============
    ,(75 , 15, 'item_section_name'           , 'Item Section Name'       , NULL                  , 1 , true , 'system')
    ,(76 , 15, 'item_short'                  , 'Short Name'              , NULL                  , 2 , true , 'system')
    ,(77 , 15, 'item_position'               , 'Position'                , NULL                  , 3 , true , 'system')
    ,(78 , 15, 'item_parent'                 , 'Parent Section'          , NULL                  , 4 , true , 'system')
    ,(79 , 15, 'iten_description'            , 'Description'             , NULL                  , 5 , true , 'system')
    ,(80 , 15, 'item_image'                  , 'image'                   , NULL                  , 6 , true , 'system')
    -- ============ Unit Master / basic (id 16) ============
    ,(81 , 16, 'item_unit_name'              , 'Unit Name'               , NULL                  , 1 , true , 'system')
    ,(82 , 16, 'item_unit_alias'             , 'Unit Alias'              , NULL                  , 2 , true , 'system')
    ,(83 , 16, 'item_decimal_count'          , 'Decimal Count'           , NULL                  , 3 , true , 'system')
    ,(84 , 16, 'iten_unit_gst_code'          , 'Gst Unit Code'           , NULL                  , 4 , true , 'system')
    ,(85 , 16, 'item_unit_weight'            , 'Weight'                  , NULL                  , 5 , true , 'system')
    ,(86 , 16, 'item_pack_unit'              , 'Pack Unit'               , NULL                  , 6 , true , 'system')
    ,(87 , 16, 'item_base_unit'              , 'Base Unit'               , NULL                  , 6 , true , 'system')
    ,(88 , 16, 'item_unit_conversion'        , 'Conversion'              , NULL                  , 7 , true , 'system')
    ,(89 , 16, 'item_unit_loading_charge'    , 'Loading Charge'          , NULL                  , 8 , true , 'system')
    ,(90 , 16, 'item_unloading_charge'       , 'Unloading Charge'        , NULL                  , 9 , true , 'system')
    ,(91 , 16, 'item_attach_charge'          , 'Attach Charge'           , NULL                  , 10, true , 'system')
    ,(92 , 16, 'item_unit_Description'       , 'Unit Description'        , NULL                  , 11, true , 'system')
    -- ============ Godown Master / basic (id 17) ============
    ,(93 , 17, 'gdl_name'                    , 'Godown Name'             , NULL                  , 1 , true , 'system')
    ,(94 , 17, 'gdl_short'                   , 'Short Name'              , NULL                  , 2 , true , 'system')
    ,(95 , 17, 'gdl_branch'                  , 'Branch id'               , NULL                  , 3 , true , 'system')
    ,(96 , 17, 'gdl_parent'                  , 'Parent Location'         , NULL                  , 4 , true , 'system')
    ,(97 , 17, 'gdl_delivery'                , 'Delivery sheet'          , NULL                  , 5 , true , 'system')
    ,(98 , 17, 'gdl_split'                   , 'Split stock'             , NULL                  , 6 , true , 'system')
    ,(99 , 17, 'gdl_negative_stock'          , 'Allow Negative Stock'    , NULL                  , 7 , true , 'system')
    ,(100, 17, 'gdl_volume'                  , 'Volume'                  , NULL                  , 8 , true , 'system')
    ,(101, 17, 'gdl_active'                  , 'Active'                  , NULL                  , 9 , true , 'system')
    ,(102, 17, 'gdl_remarks'                 , 'Remarks'                 , NULL                  , 10, true , 'system')
    -- ============ Ledger Group Master / group master (id 19) ============
    ,(109, 19, 'group_name'                  , 'Group Name'              , ''                    , 1 , true , 'system')
    ,(110, 19, 'group_short'                 , 'Group Short'             , ''                    , 2 , true , 'system')
    ,(111, 19, 'group_parent'                , 'Group Parent'            , ''                    , 3 , true , 'system')
    ,(112, 19, 'group_sort'                  , 'Group Sort'              , ''                    , 4 , true , 'system')
    ,(113, 19, 'group_description'           , 'Group Description'       , ''                    , 5 , true , 'system')
    -- ============ gsp company service / gsp (id 20) ============
    ,(114, 20, 'gsp_company'                 , 'Company'                 , NULL                  , 1 , true , 'system')
    ,(115, 20, 'gsp_provide'                 , 'GSP Provider'            , NULL                  , 2 , true , 'system')
    ,(116, 20, 'gsp_service_type'            , 'Service Type'            , NULL                  , 3 , true , 'system')
    ,(117, 20, 'gsp_service_euser_name'      , 'E-User Name'             , NULL                  , 4 , true , 'system')
    ,(118, 20, 'gsp_user_password'           , 'E-User Password'         , NULL                  , 5 , true , 'system')
    ,(363, 20, 'gsp_status'                  , 'Status'                  , NULL                  , 6 , true , 'system')
    -- ============ Department Master / basic (id 21) ============
    ,(119, 21, 'department_name'             , 'Department Name'         , NULL                  , 1 , true , 'system')
    ,(120, 21, 'department_code'             , 'Department Code'         , NULL                  , 2 , true , 'system')
    ,(121, 21, 'department_remarks'          , 'Remarks'                 , NULL                  , 3 , true , 'system')
    ,(122, 21, 'department_status'           , 'Status'                  , NULL                  , 4 , true , 'system')
    -- ============ Designation Master / basic (id 22) ============
    ,(123, 22, 'designation_name'            , 'Designation Name'        , NULL                  , 1 , true , 'system')
    ,(124, 22, 'designation_code'            , 'Designation Code'        , NULL                  , 2 , true , 'system')
    ,(125, 22, 'designation_remarks'         , 'Remarks'                 , NULL                  , 3 , true , 'system')
    ,(126, 22, 'designation_default'         , 'Default'                 , NULL                  , 4 , true , 'system')
    ,(127, 22, 'designation_status'          , 'Status'                  , NULL                  , 5 , true , 'system')
    -- ============ device list master / basic (id 23) ============
    ,(128, 23, 'device_name'                 , 'Device Name'             , NULL                  , 1 , true , 'system')
    ,(129, 23, 'device_type'                 , 'Device Type'             , NULL                  , 2 , true , 'system')
    ,(130, 23, 'device_platform'             , 'Platform'                , NULL                  , 3 , true , 'system')
    ,(131, 23, 'device_user'                 , 'User'                    , NULL                  , 4 , true , 'system')
    ,(132, 23, 'device_company'              , 'Company'                 , NULL                  , 5 , true , 'system')
    ,(133, 23, 'device_branch'               , 'Branch'                  , NULL                  , 6 , true , 'system')
    ,(134, 23, 'device_mac_address'          , 'MAC Address'             , NULL                  , 7 , true , 'system')
    ,(135, 23, 'device_blocked'              , 'Blocked'                 , NULL                  , 8 , true , 'system')
    ,(136, 23, 'device_status'               , 'Status'                  , NULL                  , 9 , true , 'system')
    ,(137, 23, 'device_block_reason'         , 'Block Reason'            , NULL                  , 10, true , 'system')
    -- ============ Customers / Primary details (id 25) ============
    ,(150, 25, 'comp_name'                   , 'Company'                 , NULL                  , 1 , true , 'system')
    ,(151, 25, 'comp_area'                   , 'Area'                    , NULL                  , 2 , true , 'system')
    ,(152, 25, 'comp_salesman'               , 'Salesman'                , NULL                  , 3 , true , 'system')
    ,(153, 25, 'comp_branch'                 , 'Branch'                  , NULL                  , 4 , true , 'system')
    ,(154, 25, 'comp_cus_group'              , 'Customer group'          , NULL                  , 5 , true , 'system')
    ,(155, 25, 'comp_collection_days'        , 'Collection days'         , NULL                  , 6 , true , 'system')
    -- ============ Customers / Basic details (id 26) ============
    ,(156, 26, 'cus_name'                    , 'Customer Name'           , ''                    , 1 , true , 'system')
    ,(157, 26, 'cus_city'                    , 'City'                    , ''                    , 2 , true , 'system')
    ,(158, 26, 'cus_phone'                   , 'Phone1'                  , ''                    , 3 , true , 'system')
    ,(159, 26, 'cus_phone2'                  , 'Phone2'                  , ''                    , 4 , true , 'system')
    ,(160, 26, 'cus_code'                    , 'Customer Code'           , ''                    , 5 , true , 'system')
    ,(161, 26, 'cus_district'                , 'District'                , ''                    , 6 , true , 'system')
    ,(162, 26, 'cus_short'                   , 'Short name'              , ''                    , 7 , true , 'system')
    ,(163, 26, 'cus_state'                   , 'State'                   , ''                    , 8 , true , 'system')
    ,(164, 26, 'cus_pin'                     , 'PIN'                     , ''                    , 9 , true , 'system')
    ,(165, 26, 'cus_whatsapp'                , 'Whatsapp No'             , ''                    , 10, true , 'system')
    ,(166, 26, 'cus_address1'                , 'Address Line1'           , ''                    , 11, true , 'system')
    ,(167, 26, 'cus_landmark'                , 'Landmark'                , ''                    , 12, true , 'system')
    ,(168, 26, 'cus_tel'                     , 'Tel'                     , ''                    , 13, true , 'system')
    ,(169, 26, 'cus_email'                   , 'Email'                   , ''                    , 14, true , 'system')
    ,(170, 26, 'cus_address'                 , 'Addess line2'            , ''                    , 15, true , 'system')
    ,(171, 26, 'cus_transport'               , 'Transport name'          , ''                    , 16, true , 'system')
    ,(172, 26, 'cus_sort'                    , 'Sort Order'              , ''                    , 17, true , 'system')
    ,(173, 26, 'cus_address3'                , 'Address Line3'           , ''                    , 18, true , 'system')
    ,(174, 26, 'cus_price_level'             , 'Price Level'             , ''                    , 19, true , 'system')
    -- ============ Customers / Region Details (id 29) ============
    ,(186, 29, 'cus_region_name'             , 'Region Name'             , ''                    , 1 , true , 'system')
    ,(187, 29, 'cus_region_addr1'            , 'Region Address 1'        , ''                    , 2 , true , 'system')
    ,(188, 29, 'cus_region_addr2'            , 'Region Address 2'        , ''                    , 3 , true , 'system')
    ,(189, 29, 'cus_region_addr3'            , 'Region Address 3'        , ''                    , 4 , true , 'system')
    ,(190, 29, 'cus_region_city'             , 'Region City'             , ''                    , 5 , true , 'system')
    ,(191, 29, 'cus_region_district'         , 'Region District'         , ''                    , 6 , true , 'system')
    ,(192, 29, 'cus_region_state'            , 'Region State Name'       , ''                    , 7 , true , 'system')
    ,(193, 29, 'cus_region_country'          , 'Region Country'          , ''                    , 8 , true , 'system')
    -- ============ Customers / Credit details (id 31) ============
    ,(210, 31, 'cus_credit_days'             , 'Credit Days'             , ''                    , 1 , true , 'system')
    ,(211, 31, 'cus_credit_amount_limit'     , 'Credit Amount Limit'     , ''                    , 2 , true , 'system')
    ,(212, 31, 'cus_debit_balance'           , 'Debit Balance'           , ''                    , 3 , true , 'system')
    ,(213, 31, 'cus_credit_bill_limit'       , 'Credit Bill Limit'       , ''                    , 4 , true , 'system')
    ,(214, 31, 'cus_debit_grace_days'        , 'Debit Grace Days'        , ''                    , 5 , true , 'system')
    -- ============ Customers / Tax Details (id 34) ============
    ,(215, 34, 'cus_gst_type'                , 'GST Type'                , ''                    , 1 , true , 'system')
    ,(216, 34, 'cus_pan_no'                  , 'PAN No'                  , ''                    , 2 , true , 'system')
    ,(217, 34, 'cus_ecommerce_gstin'         , 'Ecommerce GSTIN'         , ''                    , 3 , true , 'system')
    ,(218, 34, 'cus_gst_no'                  , 'GST No'                  , ''                    , 4 , true , 'system')
    ,(219, 34, 'cus_aadhar_no'               , 'Aadhar No'               , ''                    , 5 , true , 'system')
    ,(220, 34, 'cus_distance'                , 'Distance (Km)'           , ''                    , 6 , true , 'system')
    -- ============ Customers / Status and Notes (id 36) ============
    ,(229, 36, 'cus_discount'                , 'Discount %'              , ''                    , 1 , true , 'system')
    ,(230, 36, 'cus_birt_date'               , 'Birth Date'              , ''                    , 2 , true , 'system')
    ,(231, 36, 'cus_anniversary_date'        , 'Anniversary Date'        , ''                    , 3 , true , 'system')
    ,(232, 36, 'cus_enable_sms'              , 'Enable SMS'              , ''                    , 4 , true , 'system')
    ,(233, 36, 'cus_overdue_sms'             , 'Overdue SMS'             , ''                    , 5 , true , 'system')
    ,(234, 36, 'cus_overdue_billing'         , 'Overdue Billing'         , ''                    , 6 , true , 'system')
    ,(235, 36, 'cus_allow_promotion'         , 'Allow Promotion'         , ''                    , 7 , true , 'system')
    ,(236, 36, 'cus_allow_loyalty'           , 'Allow Loyalty'           , ''                    , 8 , true , 'system')
    ,(237, 36, 'cus_allow_discount'          , 'Allow Discount'          , ''                    , 9 , true , 'system')
    ,(238, 36, 'cus_tcs_allowable'           , 'TCS Allowable'           , ''                    , 10, true , 'system')
    ,(239, 36, 'cus_it_collection_exempted'  , 'IT Collection Exempted'  , ''                    , 11, true , 'system')
    ,(240, 36, 'cus_freight_charge'          , 'Freight Charge'          , ''                    , 12, true , 'system')
    ,(241, 36, 'cus_loading_charge'          , 'Loading Charge'          , ''                    , 13, true , 'system')
    ,(242, 36, 'cus_unloading_charge'        , 'Unloading Charge'        , ''                    , 14, true , 'system')
    ,(243, 36, 'cus_active'                  , 'Active'                  , ''                    , 15, true , 'system')
    ,(244, 36, 'cus_notes'                   , 'Notes'                   , ''                    , 16, true , 'system')
    -- ============ Suppliers / Suppliers (id 37) ============
    ,(245, 37, 'sup_gst_no'                  , 'GST No'                  , NULL                  , 1 , true , 'system')
    ,(246, 37, 'sup_name'                    , 'Supplier Name'           , NULL                  , 2 , true , 'system')
    ,(247, 37, 'sup_company'                 , 'Company'                 , NULL                  , 3 , true , 'system')
    ,(248, 37, 'sup_gst_type'                , 'GST Type'                , NULL                  , 4 , true , 'system')
    ,(249, 37, 'sup_group'                   , 'Supplier Group'          , NULL                  , 5 , true , 'system')
    ,(250, 37, 'sup_branch'                  , 'Branch'                  , NULL                  , 6 , true , 'system')
    ,(251, 37, 'sup_pan'                     , 'PAN No'                  , NULL                  , 7 , true , 'system')
    ,(252, 37, 'sup_purchase_type'           , 'Purchase Type'           , NULL                  , 8 , true , 'system')
    ,(253, 37, 'sup_drug_license_no'         , 'Drug Licence No'         , NULL                  , 9 , true , 'system')
    ,(254, 37, 'sup_short_name'              , 'Short Name'              , NULL                  , 10, true , 'system')
    -- ============ Suppliers / Suppliers (id 38) ============
    ,(255, 38, 'sup_add1'                    , 'Address Line 1'          , NULL                  , 1 , true , 'system')
    ,(256, 38, 'sup_district'                , 'District'                , NULL                  , 2 , true , 'system')
    ,(257, 38, 'sup_phone'                   , 'Phone'                   , NULL                  , 3 , true , 'system')
    ,(258, 38, 'sup_add2'                    , 'Address Line 2'          , NULL                  , 4 , true , 'system')
    ,(259, 38, 'sup_state'                   , 'State'                   , NULL                  , 5 , true , 'system')
    ,(260, 38, 'sup_whatsapp'                , 'WhatsApp No'             , NULL                  , 6 , true , 'system')
    ,(261, 38, 'sup_add3'                    , 'Address Line 3'          , NULL                  , 7 , true , 'system')
    ,(262, 38, 'sup_panno'                   , 'PIN No'                  , NULL                  , 8 , true , 'system')
    ,(263, 38, 'sup_tel'                     , 'Telephone'               , NULL                  , 9 , true , 'system')
    ,(264, 38, 'sup_city'                    , 'City'                    , NULL                  , 10, true , 'system')
    ,(265, 38, 'sup_website'                 , 'Website'                 , NULL                  , 11, true , 'system')
    ,(266, 38, 'sup_email'                   , 'Email'                   , NULL                  , 12, true , 'system')
    -- ============ Suppliers / Suppliers (id 39) ============
    ,(267, 39, 'sup_collection_days'         , 'Credit Days'             , NULL                  , 1 , true , 'system')
    ,(268, 39, 'sup_cash_discount'           , 'Cash Discount %'         , NULL                  , 2 , true , 'system')
    ,(269, 39, 'sup_collection_days'         , 'Collection Days'         , NULL                  , 3 , true , 'system')
    -- ============ Suppliers / Suppliers (id 40) ============
    ,(270, 40, 'sup_region_name'             , 'Region Name'             , NULL                  , 1 , true , 'system')
    ,(271, 40, 'sup_region_address3'         , 'Region Address 3'        , NULL                  , 2 , true , 'system')
    ,(272, 40, 'sup_region_country'          , 'Region Country'          , NULL                  , 3 , true , 'system')
    ,(273, 40, 'sup_region_address1'         , 'Region Address 1'        , NULL                  , 4 , true , 'system')
    ,(274, 40, 'sup_region_city'             , 'Region City'             , NULL                  , 5 , true , 'system')
    ,(275, 40, 'sup_region_address2'         , 'Region Address 2'        , NULL                  , 6 , true , 'system')
    -- ============ Suppliers / Suppliers (id 41) ============
    ,(276, 41, 'sup_cheque_name'             , 'Cheque Name'             , NULL                  , 1 , true , 'system')
    ,(277, 41, 'sup_sort'                    , 'Sort Order'              , NULL                  , 2 , true , 'system')
    ,(278, 41, 'sup_status'                  , 'Status'                  , NULL                  , 3 , true , 'system')
    ,(279, 41, 'sup_notes'                   , 'Notes'                   , NULL                  , 4 , true , 'system')
    -- ============ Branch Master / Branch (id 42) ============
    ,(280, 42, 'br_name'                     , 'Branch Name'             , NULL                  , 1 , true , 'system')
    ,(281, 42, 'br_company'                  , 'Company'                 , NULL                  , 2 , true , 'system')
    ,(282, 42, 'br_tel'                      , 'Telephone'               , NULL                  , 3 , true , 'system')
    ,(283, 42, 'br_alias'                    , 'Alias'                   , NULL                  , 4 , true , 'system')
    ,(284, 42, 'br_contact_person'           , 'Contact Person'          , NULL                  , 5 , true , 'system')
    ,(285, 42, 'br_email'                    , 'Email'                   , NULL                  , 6 , true , 'system')
    ,(286, 42, 'br_branch'                   , 'Branch Code'             , NULL                  , 7 , true , 'system')
    ,(287, 42, 'br_phone'                    , 'Phone'                   , NULL                  , 8 , true , 'system')
    -- ============ Branch Master / Branch (id 43) ============
    ,(288, 43, 'br_address1'                 , 'Address 1'               , NULL                  , 1 , true , 'system')
    ,(289, 43, 'br_city'                     , 'City'                    , NULL                  , 2 , true , 'system')
    ,(290, 43, 'br_pincode'                  , 'Pincode'                 , NULL                  , 3 , true , 'system')
    ,(291, 43, 'br_address2'                 , 'Address 2'               , NULL                  , 4 , true , 'system')
    ,(292, 43, 'br_district'                 , 'District'                , NULL                  , 5 , true , 'system')
    ,(293, 43, 'br_landmark'                 , 'Landmark'                , NULL                  , 6 , true , 'system')
    ,(294, 43, 'br_address3'                 , 'Address 3'               , NULL                  , 7 , true , 'system')
    ,(295, 43, 'br_state'                    , 'State'                   , NULL                  , 8 , true , 'system')
    -- ============ Branch Master / Branch (id 44) ============
    ,(296, 44, 'br_region_address1'          , 'Region Address 1'        , NULL                  , 1 , true , 'system')
    ,(297, 44, 'br_region_city'              , 'Region City'             , NULL                  , 2 , true , 'system')
    ,(298, 44, 'br_region_country'           , 'Region Country'          , NULL                  , 3 , true , 'system')
    ,(299, 44, 'br_region_address2'          , 'Region Address 2'        , NULL                  , 4 , true , 'system')
    ,(300, 44, 'br_region_district'          , 'Region District'         , NULL                  , 5 , true , 'system')
    ,(301, 44, 'br_region_state'             , 'State'                   , NULL                  , 6 , true , 'system')
    ,(302, 44, 'br_region_address3'          , 'Region Address 3'        , NULL                  , 7 , true , 'system')
    ,(303, 44, 'br_region_name'              , 'Region Name'             , NULL                  , 8 , true , 'system')
    -- ============ Branch Master / Branch (id 45) ============
    ,(304, 45, 'br_invoice_prefix'           , 'Invoice Series Prefix'   , NULL                  , 1 , true , 'system')
    ,(305, 45, 'br_rounding_mode'            , 'Rounding Mode'           , NULL                  , 2 , true , 'system')
    ,(306, 45, 'br_rounding_value'           , 'Rounding Value'          , NULL                  , 3 , true , 'system')
    ,(307, 45, 'br_bill_greeting'            , 'Bill Greeting'           , NULL                  , 4 , true , 'system')
    ,(308, 45, 'br_bill_terms'               , 'Terms'                   , NULL                  , 5 , true , 'system')
    ,(309, 45, 'br_bill_default_godown'      , 'Default Godown Id'       , NULL                  , 6 , true , 'system')
    ,(310, 45, 'br_bank_id'                  , 'Bank Id'                 , NULL                  , 7 , true , 'system')
    -- ============ Branch Master / Branch (id 46) ============
    ,(311, 46, 'br_gstin'                    , 'GSTIN No'                , NULL                  , 1 , true , 'system')
    ,(312, 46, 'br_gst_registration'         , 'GST Registration Type'   , NULL                  , 2 , true , 'system')
    ,(313, 46, 'br_pan'                      , 'PAN No'                  , NULL                  , 3 , true , 'system')
    ,(314, 46, 'br_fssai_no'                 , 'FSSAI No'                , NULL                  , 4 , true , 'system')
    ,(315, 46, 'br_fssai_license_no'         , 'FSSAI License Type'      , NULL                  , 5 , true , 'system')
    ,(316, 46, 'br_fssai_valid'              , 'FSSAI Valid Upto'        , NULL                  , 6 , true , 'system')
    -- ============ Branch Master / Branch (id 47) ============
    ,(317, 47, 'br_allow_negative_stock'     , 'Allow Negative Stock'    , NULL                  , 1 , true , 'system')
    ,(318, 47, 'br_sms_applicable'           , 'SMS Applicable'          , NULL                  , 2 , true , 'system')
    ,(319, 47, 'br_default_branch'           , 'Default Branch'          , NULL                  , 3 , true , 'system')
    ,(320, 47, 'br_active'                   , 'Active'                  , NULL                  , 4 , true , 'system')
    -- ============ Employee Master / Employee master (id 48) ============
    ,(321, 48, 'emp_name'                    , 'Employee Name'           , NULL                  , 1 , true , 'system')
    ,(322, 48, 'emp_company'                 , 'Company'                 , NULL                  , 2 , true , 'system')
    ,(323, 48, 'emp_dob'                     , 'Date of Birth'           , NULL                  , 3 , true , 'system')
    ,(324, 48, 'emp_alias'                   , 'Alias'                   , NULL                  , 4 , true , 'system')
    ,(325, 48, 'emp_branch'                  , 'Branch'                  , NULL                  , 5 , true , 'system')
    ,(326, 48, 'emp_maritial_status'         , 'Marital Status'          , NULL                  , 6 , true , 'system')
    ,(327, 48, 'emp_code'                    , 'Employee Code'           , NULL                  , 7 , true , 'system')
    ,(328, 48, 'emp_department'              , 'Department'              , NULL                  , 8 , true , 'system')
    ,(329, 48, 'emp_blood_group'             , 'Blood Group'             , NULL                  , 9 , true , 'system')
    ,(330, 48, 'emp_gender'                  , 'Gender'                  , NULL                  , 10, true , 'system')
    ,(331, 48, 'emp_designation'             , 'Designation'             , NULL                  , 11, true , 'system')
    -- ============ Employee Master / Employee master (id 49) ============
    ,(332, 49, 'emp_address1'                , 'Address Line 1'          , NULL                  , 1 , true , 'system')
    ,(333, 49, 'emp_district'                , 'District'                , NULL                  , 2 , true , 'system')
    ,(334, 49, 'emp_email'                   , 'Email'                   , NULL                  , 3 , true , 'system')
    ,(335, 49, 'emp_address2'                , 'Address Line 2'          , NULL                  , 4 , true , 'system')
    ,(336, 49, 'emp_state'                   , 'State'                   , NULL                  , 5 , true , 'system')
    ,(337, 49, 'emp_mobile1'                 , 'Mobile 1'                , NULL                  , 6 , true , 'system')
    ,(338, 49, 'emp_address3'                , 'Address Line 3'          , NULL                  , 7 , true , 'system')
    ,(339, 49, 'emp_pincode'                 , 'Pincode'                 , NULL                  , 8 , true , 'system')
    ,(340, 49, 'emp_mobile2'                 , 'Mobile 2'                , NULL                  , 9 , true , 'system')
    ,(341, 49, 'emp_city'                    , 'City'                    , NULL                  , 10, true , 'system')
    -- ============ Employee Master / Employee master (id 50) ============
    ,(342, 50, 'emp_employment_status'       , 'Employment Status'       , NULL                  , 1 , true , 'system')
    ,(343, 50, 'emp_joined_on'               , 'Joined On'               , NULL                  , 2 , true , 'system')
    ,(344, 50, 'emp_probation_end_on'        , 'Probation End On'        , NULL                  , 3 , true , 'system')
    ,(345, 50, 'emp_confirmation'            , 'Confirmation On'         , NULL                  , 4 , true , 'system')
    ,(346, 50, 'emp_left'                    , 'Left On'                 , NULL                  , 5 , true , 'system')
    -- ============ Employee Master / Employee master (id 51) ============
    ,(347, 51, 'emp_shift_id'                , 'Shift Id'                , NULL                  , 1 , true , 'system')
    ,(348, 51, 'emp_attendance_constraint_id', 'Attendance Constraint Id', NULL                  , 2 , true , 'system')
    ,(349, 51, 'emp_holiday_group_id'        , 'Holiday Group Id'        , NULL                  , 3 , true , 'system')
    ,(350, 51, 'emp_overtime_allowed'        , 'Overtime Allowed'        , NULL                  , 4 , true , 'system')
    -- ============ Employee Master / Employee Master (id 52) ============
    ,(351, 52, 'emp_has_commission'          , 'Has Commission'          , NULL                  , 1 , true , 'system')
    ,(352, 52, 'emp_salary_type'             , 'Salary Type'             , NULL                  , 2 , true , 'system')
    ,(353, 52, 'emp_salary_amount'           , 'Salary Amount'           , NULL                  , 3 , true , 'system')
    ,(354, 52, 'emp_bata_amount'             , 'Bata Amount'             , NULL                  , 4 , true , 'system')
    ,(355, 52, 'emp_km_bata_amount'          , 'KM Bata Amount'          , NULL                  , 5 , true , 'system')
    -- ============ Employee Master / Employee master (id 53) ============
    ,(356, 53, 'emp_pan_no'                  , 'PAN No'                  , NULL                  , 1 , true , 'system')
    ,(357, 53, 'emp_aadhar_no'               , 'Aadhar No'               , NULL                  , 2 , true , 'system')
    ,(358, 53, 'emp_pf_no'                   , 'PF No'                   , NULL                  , 3 , true , 'system')
    ,(359, 53, 'emp_esi_no'                  , 'ESI No'                  , NULL                  , 4 , true , 'system')
    -- ============ Employee Master / Employee master (id 54) ============
    ,(360, 54, 'emp_upload_photo'            , 'Upload Photo'            , NULL                  , 1 , true , 'system')
    ,(361, 54, 'emp_remarks'                 , 'Remarks'                 , NULL                  , 2 , true , 'system')
    ,(362, 54, 'emp_record_active'           , 'Record Active'           , NULL                  , 3 , true , 'system')
    -- ============ Item Master / Core Details (id 55) ============
    ,(364, 55, 'item_name'                   , 'Item Name'               , ''                    , 1 , true , 'system')
    ,(365, 55, 'item_local'                  , 'Item Name (Local)'       , 'Item Name (Regional)', 2 , true , 'system')
    ,(366, 55, 'item_alias'                  , 'Alias'                   , ''                    , 3 , true , 'system')
    ,(367, 55, 'item_code'                   , 'Item Code'               , ''                    , 4 , true , 'system')
    ,(368, 55, 'item_barcode'                , 'Default Barcode'         , 'Barcode'             , 5 , true , 'system')
    ,(369, 55, 'item_batch_config'           , 'Batch Config'            , ''                    , 6 , true , 'system')
    ,(370, 55, 'item_hsn'                    , 'HSN Code'                , ''                    , 7 , true , 'system')
    ,(371, 55, 'item_default_tax'            , 'Default Tax'             , 'Tax'                 , 8 , true , 'system')
    ,(372, 55, 'item_is_active'              , 'Is Active'               , ''                    , 9 , true , 'system')
    -- ============ Item Master / Reference Links (id 56) ============
    ,(373, 56, 'item_company'                , 'Company'                 , ''                    , 1 , true , 'system')
    ,(374, 56, 'item_branch'                 , 'Branch'                  , ''                    , 2 , true , 'system')
    ,(375, 56, 'item_group'                  , 'Item Group'              , ''                    , 3 , true , 'system')
    ,(376, 56, 'Item_Brand'                  , 'Item Brand'              , ''                    , 4 , true , 'system')
    ,(377, 56, 'Item_Section'                , 'Item Section'            , ''                    , 5 , true , 'system')
    ,(378, 56, 'Item_category'               , 'Item Category'           , ''                    , 6 , true , 'system')
    ,(379, 56, 'item_default_supplier'       , 'Default Supplier'        , ''                    , 7 , false, 'system')
    ,(380, 56, 'Item_customer_group'         , 'Item Customer Group'     , ''                    , 8 , false, 'system')
    -- ============ Item Master / EAN Table (id 57) ============
    ,(382, 57, 'item_retail_item'            , 'Retail Item'             , ''                    , 1 , true , 'system')
    ,(383, 57, 'item_allow_sales'            , 'Allow Sales'             , ''                    , 2 , true , 'system')
    ,(384, 57, 'item_allow_loading'          , 'Allow Loading'           , ''                    , 3 , true , 'system')
    ,(385, 57, 'item_damagable_product'      , 'Damagable Product'       , ''                    , 4 , true , 'system')
    ,(386, 57, 'item_allow_neg_stock'        , 'Allow Negative Stock'    , ''                    , 5 , true , 'system')
    ,(387, 57, 'item_allow_promo'            , 'Allow Promo'             , ''                    , 6 , true , 'system')
    ,(388, 57, 'item_price_list'             , 'Price List'              , ''                    , 7 , true , 'system')
    ,(389, 57, 'item_allow_sales_return'     , 'Allow Sales Return'      , ''                    , 8 , true , 'system')
    ,(390, 57, 'item_allow_freight'          , 'Allow Freight'           , ''                    , 9 , true , 'system')
    ,(391, 57, 'item_is_kit'                 , 'Is Kit'                  , ''                    , 10, true , 'system')
    ,(392, 57, 'item_allow_negative_so'      , 'Allow Negative SO'       , ''                    , 11, true , 'system')
    ,(393, 57, 'item_allow_loyalty'          , 'Allow Loyalty'           , ''                    , 12, true , 'system')
    ,(394, 57, 'item_is_batch_based'         , 'Batch Based'             , ''                    , 13, true , 'system')
    ,(395, 57, 'item_allow_purchase'         , 'Allow Purchase'          , ''                    , 14, true , 'system')
    ,(396, 57, 'item_auto_break'             , 'Auto Break'              , ''                    , 15, true , 'system')
    ,(397, 57, 'item_is_demand'              , 'Is Demand'               , ''                    , 16, true , 'system')
    ,(398, 57, 'item_has_offer'              , 'Has Offer'               , ''                    , 17, true , 'system')
    ,(399, 57, 'item_barcode_sticker'        , 'Barcode Sticker'         , ''                    , 18, true , 'system')
    ,(400, 57, 'item_is_service'             , 'Service Item'            , ''                    , 19, true , 'system')
    ,(401, 57, 'item_allow_po'               , 'Allow PO'                , ''                    , 20, true , 'system')
    ,(402, 57, 'item_auto_make'              , 'Auto Make'               , ''                    , 21, true , 'system')
    ,(403, 57, 'item_is_expiry_item'         , 'Expiry Item'             , ''                    , 22, true , 'system')
    ,(404, 57, 'item_random_stock'           , 'Random Stock'            , ''                    , 23, true , 'system')
    ,(405, 57, 'item_allow_so'               , 'Allow SO'                , ''                    , 26, true , 'system')
    ,(406, 57, 'item_weigh_scale'            , 'Weigh Scale'             , ''                    , 27, true , 'system')
    ,(443, 57, 'item_expiry_days'            , 'Expiry Days'             , ''                    , 28, true , 'system')
    ,(442, 57, 'item_intimate_before_days'   , 'Intimate Before Days'    , ''                    , 29, true , 'system')
    -- ============ Item Master / Inventory & Notes (id 58) ============
    ,(381, 58, 'item_sort_order'             , 'Sort Order'              , ''                    , 1 , true , 'system')
    ,(407, 58, 'item_storage_location'       , 'Storage Location'        , ''                    , 2 , true , 'system')
    ,(408, 58, 'item_image_url'              , 'Image URL'               , ''                    , 3 , true , 'system')
    ,(409, 58, 'item_photo_file'             , 'Photo File'              , ''                    , 4 , true , 'system')
    ,(410, 58, 'item_notes'                  , 'Notes'                   , ''                    , 5 , true , 'system')
    -- ============ Quotation / Quoation entry (id 61) ============
    ,(444, 61, 'Existing Customer'           , 'Existing Customer'       , ''                    , 1 , true , 'system')
    ,(445, 61, 'Customer Name'               , 'Customer Name'           , ''                    , 2 , true , 'system')
    ,(446, 61, 'Address'                     , 'Address'                 , ''                    , 3 , true , 'system')
    ,(447, 61, 'Place'                       , 'Place'                   , ''                    , 4 , true , 'system')
    ,(448, 61, 'Phone'                       , 'Phone'                   , ''                    , 5 , true , 'system')
    ,(449, 61, 'GSTIN'                       , 'GSTIN'                   , ''                    , 5 , true , 'system')
    ,(450, 61, 'POS State Code'              , 'POS State Code'          , ''                    , 6 , true , 'system')
    ,(451, 61, 'Beat'                        , 'Beat'                    , ''                    , 7 , true , 'system')
    ,(452, 61, 'Salesman'                    , 'Salesman'                , ''                    , 8 , true , 'system')
    ,(453, 61, 'Agent'                       , 'Agent'                   , ''                    , 9 , true , 'system')
    ,(454, 61, 'Contact Person'              , 'Contact Person'          , ''                    , 10, true , 'system')
    ,(455, 61, 'Contact No'                  , 'Contact No'              , ''                    , 11, true , 'system')
    ,(456, 61, 'Freight'                     , 'Freight'                 , ''                    , 12, true , 'system')
    ,(457, 61, 'Load'                        , 'Load'                    , ''                    , 13, true , 'system')
    ,(458, 61, 'Unload'                      , 'Unload'                  , ''                    , 14, true , 'system')
    ,(459, 61, 'Promo'                       , 'Promo'                   , ''                    , 15, true , 'system')
    ,(460, 61, 'Quote No'                    , 'Quote No'                , ''                    , 16, true , 'system')
    ,(461, 61, 'Quote Date'                  , 'Quote Date'              , ''                    , 17, true , 'system')
    ,(462, 61, 'Valid Until'                 , 'Valid Until'             , ''                    , 18, true , 'system')
    ,(463, 61, 'Validity Days'               , 'Validity Days'           , ''                    , 19, true , 'system')
    ,(464, 61, 'Price Level'                 , 'Price Level'             , ''                    , 20, true , 'system')
) AS v(field_id, field_section_id, field_name, field_gui_name, field_secondary_text, field_position, field_visibility, field_created_by)
WHERE NOT EXISTS (
  SELECT 1 FROM fixed.form_field existing
   WHERE existing.field_section_id = v.field_section_id
)
  AND EXISTS (
  SELECT 1 FROM fixed.form_section parent
   WHERE parent.section_id = v.field_section_id
)
ON CONFLICT (field_id) DO NOTHING;

-- Keep the identity sequence ahead of the seeded ids, so the next row created from
-- the UI does not collide with one of them.
SELECT setval(
    pg_get_serial_sequence('fixed.form_field', 'field_id'),
    (SELECT GREATEST(COALESCE(MAX(field_id), 0), 1) FROM fixed.form_field),
    true
);

COMMIT;
