-- Seed: fixed.form_field -- the fields inside each widget-master tab (389 rows).
--
-- Runs after Form_Section.sql -- field_section_id is a foreign key into it, ON DELETE
-- CASCADE.
--
-- field_name MUST equal the form field's binding key (item_retail_item, cus_credit_days,
-- ...), not a label-derived name: the widget-master popup matches on it, and a field
-- whose name does not bind shows up as "not on form" and controls nothing.
-- field_gui_name is the label shown, field_secondary_text the helper line under it.
--
-- Two guards, because this is a grandchild of the menu tree:
--   * a section that ALREADY HAS ANY FIELD is skipped, so local re-labelling survives;
--   * a section that does not exist in the target database is skipped as well, instead
--     of failing the foreign key and aborting the file -- that is what happens to every
--     menu whose sections Form_Section.sql left alone.
-- Regenerate with: npm run seed:export:ui-config
-- Run: psql "$DATABASE_URL" -f prisma/seed/Form_Field.sql
--      or: npm run seed:run -- --only=Form_Field.sql

BEGIN;

INSERT INTO fixed.form_field
    (field_id, field_section_id, field_name, field_gui_name, field_secondary_text, field_position, field_visibility, field_created_by)
SELECT v.* FROM (VALUES
    -- ============ Item Group Master / group master (id 1) ============
     (138::integer, 1::integer, 'itg_name'::varchar, 'Item Group Name'::varchar, NULL::varchar, 1::integer, true::boolean, 'system'::text)
    ,(139, 1 , 'itg_short'                   , 'Short Name'              , NULL  , 2 , true, 'system')
    ,(140, 1 , 'itg_position'                , 'Position'                , NULL  , 3 , true, 'system')
    ,(141, 1 , 'itg_parent'                  , 'Parent Group'            , NULL  , 4 , true, 'system')
    ,(142, 1 , 'itg_description'             , 'Description'             , NULL  , 5 , true, 'system')
    ,(143, 1 , 'itg_image'                   , 'Image'                   , NULL  , 6 , true, 'system')
    -- ============ Item Brand Master / basic (id 2) ============
    ,(5  , 2 , 'name'                        , 'name'                    , 'name', 1 , true, 'system')
    -- ============ Unit Master / MAIN SECTION (id 6) ============
    ,(12 , 6 , 'unit_is_pack_unit'           , 'Pack Unit'               , NULL  , 1 , true, 'system')
    ,(13 , 6 , 'unit_base_unit_id'           , 'Base Unit'               , NULL  , 2 , true, 'system')
    ,(14 , 6 , 'unit_conversion'             , 'Conversion'              , NULL  , 3 , true, 'system')
    ,(15 , 6 , 'unit_loading'                , 'Loading charge'          , NULL  , 4 , true, 'system')
    ,(16 , 6 , 'unit_unloading'              , 'Unloading charge'        , NULL  , 5 , true, 'system')
    ,(17 , 6 , 'unit_attach_charge'          , 'Attach Charge'           , NULL  , 6 , true, 'system')
    ,(18 , 6 , 'unit_description'            , 'Unit Description'        , NULL  , 7 , true, 'system')
    ,(19 , 6 , 'unit_is_active'              , 'Active'                  , NULL  , 8 , true, 'system')
    -- ============ State Master / basic (id 7) ============
    ,(20 , 7 , 'state_name'                  , 'State name'              , ''    , 1 , true, 'system')
    ,(21 , 7 , 'state_alias'                 , 'Alias'                   , ''    , 2 , true, 'system')
    ,(22 , 7 , 'state_short'                 , 'Short name'              , ''    , 3 , true, 'system')
    ,(23 , 7 , 'state_order'                 , 'Order'                   , ''    , 4 , true, 'system')
    ,(24 , 7 , 'state_is_active'             , 'status'                  , ''    , 4 , true, 'system')
    ,(104, 7 , 'stm_decription'              , 'Description'             , ''    , 5 , true, 'system')
    -- ============ City Master / basic (id 8) ============
    ,(25 , 8 , 'cty_name'                    , 'City name'               , NULL  , 1 , true, 'system')
    ,(26 , 8 , 'cty_alias'                   , 'Alias'                   , NULL  , 2 , true, 'system')
    ,(27 , 8 , 'cty_short'                   , 'Short name'              , NULL  , 3 , true, 'system')
    ,(29 , 8 , 'cty_state'                   , 'State'                   , NULL  , 4 , true, 'system')
    ,(28 , 8 , 'cty_order'                   , 'Order'                   , NULL  , 5 , true, 'system')
    ,(30 , 8 , 'cty_is_active'               , 'Status'                  , NULL  , 6 , true, 'system')
    -- ============ Area Master / basic (id 9) ============
    ,(31 , 9 , 'area_name'                   , 'Area name'               , NULL  , 1 , true, 'system')
    ,(32 , 9 , 'area_alias'                  , 'Alias'                   , NULL  , 2 , true, 'system')
    ,(33 , 9 , 'area_short'                  , 'Short name'              , NULL  , 3 , true, 'system')
    ,(34 , 9 , 'area_city'                   , 'City'                    , NULL  , 4 , true, 'system')
    ,(35 , 9 , 'area_distance'               , 'Distance'                , NULL  , 5 , true, 'system')
    ,(36 , 9 , 'area_collection_days'        , 'Collection days'         , NULL  , 6 , true, 'system')
    ,(37 , 9 , 'area_sort'                   , 'sort'                    , NULL  , 7 , true, 'system')
    ,(38 , 9 , 'area_is_active'              , 'Status'                  , NULL  , 8 , true, 'system')
    ,(103, 9 , 'arm_desc'                    , 'Description'             , NULL  , 9 , true, 'system')
    -- ============ Customer Type Master / customer group (id 10) ============
    ,(39 , 10, 'cus_group_name'              , 'Group name'              , NULL  , 1 , true, 'system')
    ,(40 , 10, 'cus_short_name'              , 'Short name'              , NULL  , 2 , true, 'system')
    ,(41 , 10, 'cus_sort_order'              , 'Sort order'              , NULL  , 3 , true, 'system')
    ,(42 , 10, 'cus_dis'                     , 'Discount'                , NULL  , 4 , true, 'system')
    ,(43 , 10, 'cus_collection_days'         , 'Collection days'         , NULL  , 5 , true, 'system')
    ,(44 , 10, 'cus_debit_days'              , 'Debit Days'              , NULL  , 6 , true, 'system')
    ,(45 , 10, 'cus_debit_limit'             , 'Debit limit'             , NULL  , 7 , true, 'system')
    ,(46 , 10, 'cus_bills_limit'             , 'Bills limit'             , NULL  , 8 , true, 'system')
    ,(47 , 10, 'cus_debit_allowed'           , 'Debit allowed'           , NULL  , 9 , true, 'system')
    ,(48 , 10, 'cus_overdue_billing'         , 'Overdue billing'         , NULL  , 10, true, 'system')
    ,(49 , 10, 'cus_is_active'               , 'Status'                  , NULL  , 10, true, 'system')
    ,(50 , 10, 'cus_narration'               , 'Narration'               , NULL  , 11, true, 'system')
    -- ============ Tender Master / basic (id 11) ============
    ,(51 , 11, 'tender_name'                 , 'Tender Name'             , NULL  , 1 , true, 'system')
    ,(52 , 11, 'tender_type'                 , 'Tender Type'             , NULL  , 2 , true, 'system')
    ,(53 , 11, 'tnd_acc_ldger'               , 'Account Ledger'          , NULL  , 3 , true, 'system')
    ,(54 , 11, 'tnd_min_amount'              , 'Min Amount'              , NULL  , 4 , true, 'system')
    ,(55 , 11, 'tnd_max_amount'              , 'Max Amount'              , NULL  , 5 , true, 'system')
    ,(56 , 11, 'tnd_Surcharge'               , 'Surcharge'               , NULL  , 6 , true, 'system')
    ,(57 , 11, 'tnd_allow_edit_surcharge'    , 'Allow edit Surcharge'    , NULL  , 7 , true, 'system')
    ,(58 , 11, 'tnd_allow_edit_ledger'       , 'Allow edit ledger'       , NULL  , 8 , true, 'system')
    ,(59 , 11, 'tnd_remarks'                 , 'Remarks'                 , NULL  , 9 , true, 'system')
    -- ============ Supplier Groups / basic (id 12) ============
    ,(60 , 12, 'spg_group_name'              , 'Group Name'              , NULL  , 1 , true, 'system')
    ,(61 , 12, 'spg_short_name'              , 'Short Name'              , NULL  , 2 , true, 'system')
    ,(62 , 12, 'spg_description'             , 'Description'             , NULL  , 3 , true, 'system')
    -- ============ Item Brand Master / brand master (id 13) ============
    ,(63 , 13, 'item_brand_name'             , 'Item Brand Name'         , NULL  , 1 , true, 'system')
    ,(64 , 13, 'item_short'                  , 'Short Name'              , NULL  , 2 , true, 'system')
    ,(65 , 13, 'item_position'               , 'Position'                , NULL  , 3 , true, 'system')
    ,(66 , 13, 'item_parent'                 , 'Parent Brand'            , NULL  , 4 , true, 'system')
    ,(67 , 13, 'item_description'            , 'Description'             , NULL  , 5 , true, 'system')
    ,(68 , 13, 'item_image'                  , 'Image'                   , NULL  , 6 , true, 'system')
    -- ============ item category master / basic details (id 14) ============
    ,(69 , 14, 'iten_ctg_name'               , 'Category name'           , ''    , 1 , true, 'system')
    ,(70 , 14, 'Itg_ctg_short_name'          , 'Short name'              , ''    , 2 , true, 'system')
    ,(71 , 14, 'Itg_ctg_short_position'      , 'Position'                , ''    , 3 , true, 'system')
    ,(72 , 14, 'itg_parent_category'         , 'Parent category'         , ''    , 4 , true, 'system')
    ,(73 , 14, 'itg_description'             , 'Description'             , ''    , 5 , true, 'system')
    ,(74 , 14, 'itg_category_image'          , 'Image'                   , ''    , 6 , true, 'system')
    -- ============ Item Section Master / basic (id 15) ============
    ,(75 , 15, 'item_section_name'           , 'Item Section Name'       , NULL  , 1 , true, 'system')
    ,(76 , 15, 'item_short'                  , 'Short Name'              , NULL  , 2 , true, 'system')
    ,(77 , 15, 'item_position'               , 'Position'                , NULL  , 3 , true, 'system')
    ,(78 , 15, 'item_parent'                 , 'Parent Section'          , NULL  , 4 , true, 'system')
    ,(79 , 15, 'iten_description'            , 'Description'             , NULL  , 5 , true, 'system')
    ,(80 , 15, 'item_image'                  , 'image'                   , NULL  , 6 , true, 'system')
    -- ============ Unit Master / basic (id 16) ============
    ,(81 , 16, 'item_unit_name'              , 'Unit Name'               , NULL  , 1 , true, 'system')
    ,(82 , 16, 'item_unit_alias'             , 'Unit Alias'              , NULL  , 2 , true, 'system')
    ,(83 , 16, 'item_decimal_count'          , 'Decimal Count'           , NULL  , 3 , true, 'system')
    ,(84 , 16, 'iten_unit_gst_code'          , 'Gst Unit Code'           , NULL  , 4 , true, 'system')
    ,(85 , 16, 'item_unit_weight'            , 'Weight'                  , NULL  , 5 , true, 'system')
    ,(86 , 16, 'item_pack_unit'              , 'Pack Unit'               , NULL  , 6 , true, 'system')
    ,(87 , 16, 'item_base_unit'              , 'Base Unit'               , NULL  , 6 , true, 'system')
    ,(88 , 16, 'item_unit_conversion'        , 'Conversion'              , NULL  , 7 , true, 'system')
    ,(89 , 16, 'item_unit_loading_charge'    , 'Loading Charge'          , NULL  , 8 , true, 'system')
    ,(90 , 16, 'item_unloading_charge'       , 'Unloading Charge'        , NULL  , 9 , true, 'system')
    ,(91 , 16, 'item_attach_charge'          , 'Attach Charge'           , NULL  , 10, true, 'system')
    ,(92 , 16, 'item_unit_Description'       , 'Unit Description'        , NULL  , 11, true, 'system')
    -- ============ Godown Master / basic (id 17) ============
    ,(93 , 17, 'gdl_name'                    , 'Godown Name'             , NULL  , 1 , true, 'system')
    ,(94 , 17, 'gdl_short'                   , 'Short Name'              , NULL  , 2 , true, 'system')
    ,(95 , 17, 'gdl_branch'                  , 'Branch id'               , NULL  , 3 , true, 'system')
    ,(96 , 17, 'gdl_parent'                  , 'Parent Location'         , NULL  , 4 , true, 'system')
    ,(97 , 17, 'gdl_delivery'                , 'Delivery sheet'          , NULL  , 5 , true, 'system')
    ,(98 , 17, 'gdl_split'                   , 'Split stock'             , NULL  , 6 , true, 'system')
    ,(99 , 17, 'gdl_negative_stock'          , 'Allow Negative Stock'    , NULL  , 7 , true, 'system')
    ,(100, 17, 'gdl_volume'                  , 'Volume'                  , NULL  , 8 , true, 'system')
    ,(101, 17, 'gdl_active'                  , 'Active'                  , NULL  , 9 , true, 'system')
    ,(102, 17, 'gdl_remarks'                 , 'Remarks'                 , NULL  , 10, true, 'system')
    -- ============ Ledger Group Master / group master (id 19) ============
    ,(109, 19, 'group_name'                  , 'Group Name'              , ''    , 1 , true, 'system')
    ,(110, 19, 'group_short'                 , 'Group Short'             , ''    , 2 , true, 'system')
    ,(111, 19, 'group_parent'                , 'Group Parent'            , ''    , 3 , true, 'system')
    ,(112, 19, 'group_sort'                  , 'Group Sort'              , ''    , 4 , true, 'system')
    ,(113, 19, 'group_description'           , 'Group Description'       , ''    , 5 , true, 'system')
    -- ============ gsp company service / gsp (id 20) ============
    ,(114, 20, 'gsp_company'                 , 'Company'                 , NULL  , 1 , true, 'system')
    ,(115, 20, 'gsp_provide'                 , 'GSP Provider'            , NULL  , 2 , true, 'system')
    ,(116, 20, 'gsp_service_type'            , 'Service Type'            , NULL  , 3 , true, 'system')
    ,(117, 20, 'gsp_service_euser_name'      , 'E-User Name'             , NULL  , 4 , true, 'system')
    ,(118, 20, 'gsp_user_password'           , 'E-User Password'         , NULL  , 5 , true, 'system')
    ,(363, 20, 'gsp_status'                  , 'Status'                  , NULL  , 6 , true, 'system')
    -- ============ Department Master / basic (id 21) ============
    ,(119, 21, 'department_name'             , 'Department Name'         , NULL  , 1 , true, 'system')
    ,(120, 21, 'department_code'             , 'Department Code'         , NULL  , 2 , true, 'system')
    ,(121, 21, 'department_remarks'          , 'Remarks'                 , NULL  , 3 , true, 'system')
    ,(122, 21, 'department_status'           , 'Status'                  , NULL  , 4 , true, 'system')
    -- ============ Designation Master / basic (id 22) ============
    ,(123, 22, 'designation_name'            , 'Designation Name'        , NULL  , 1 , true, 'system')
    ,(124, 22, 'designation_code'            , 'Designation Code'        , NULL  , 2 , true, 'system')
    ,(125, 22, 'designation_remarks'         , 'Remarks'                 , NULL  , 3 , true, 'system')
    ,(126, 22, 'designation_default'         , 'Default'                 , NULL  , 4 , true, 'system')
    ,(127, 22, 'designation_status'          , 'Status'                  , NULL  , 5 , true, 'system')
    -- ============ device list master / basic (id 23) ============
    ,(128, 23, 'device_name'                 , 'Device Name'             , NULL  , 1 , true, 'system')
    ,(129, 23, 'device_type'                 , 'Device Type'             , NULL  , 2 , true, 'system')
    ,(130, 23, 'device_platform'             , 'Platform'                , NULL  , 3 , true, 'system')
    ,(131, 23, 'device_user'                 , 'User'                    , NULL  , 4 , true, 'system')
    ,(132, 23, 'device_company'              , 'Company'                 , NULL  , 5 , true, 'system')
    ,(133, 23, 'device_branch'               , 'Branch'                  , NULL  , 6 , true, 'system')
    ,(134, 23, 'device_mac_address'          , 'MAC Address'             , NULL  , 7 , true, 'system')
    ,(135, 23, 'device_blocked'              , 'Blocked'                 , NULL  , 8 , true, 'system')
    ,(136, 23, 'device_status'               , 'Status'                  , NULL  , 9 , true, 'system')
    ,(137, 23, 'device_block_reason'         , 'Block Reason'            , NULL  , 10, true, 'system')
    -- ============ Branch Master / Branch (id 42) ============
    ,(280, 42, 'br_name'                     , 'Branch Name'             , NULL  , 1 , true, 'system')
    ,(281, 42, 'br_company'                  , 'Company'                 , NULL  , 2 , true, 'system')
    ,(282, 42, 'br_tel'                      , 'Telephone'               , NULL  , 3 , true, 'system')
    ,(283, 42, 'br_alias'                    , 'Alias'                   , NULL  , 4 , true, 'system')
    ,(284, 42, 'br_contact_person'           , 'Contact Person'          , NULL  , 5 , true, 'system')
    ,(285, 42, 'br_email'                    , 'Email'                   , NULL  , 6 , true, 'system')
    ,(286, 42, 'br_branch'                   , 'Branch Code'             , NULL  , 7 , true, 'system')
    ,(287, 42, 'br_phone'                    , 'Phone'                   , NULL  , 8 , true, 'system')
    -- ============ Branch Master / Branch (id 43) ============
    ,(288, 43, 'br_address1'                 , 'Address 1'               , NULL  , 1 , true, 'system')
    ,(289, 43, 'br_city'                     , 'City'                    , NULL  , 2 , true, 'system')
    ,(290, 43, 'br_pincode'                  , 'Pincode'                 , NULL  , 3 , true, 'system')
    ,(291, 43, 'br_address2'                 , 'Address 2'               , NULL  , 4 , true, 'system')
    ,(292, 43, 'br_district'                 , 'District'                , NULL  , 5 , true, 'system')
    ,(293, 43, 'br_landmark'                 , 'Landmark'                , NULL  , 6 , true, 'system')
    ,(294, 43, 'br_address3'                 , 'Address 3'               , NULL  , 7 , true, 'system')
    ,(295, 43, 'br_state'                    , 'State'                   , NULL  , 8 , true, 'system')
    -- ============ Branch Master / Branch (id 44) ============
    ,(296, 44, 'br_region_address1'          , 'Region Address 1'        , NULL  , 1 , true, 'system')
    ,(297, 44, 'br_region_city'              , 'Region City'             , NULL  , 2 , true, 'system')
    ,(298, 44, 'br_region_country'           , 'Region Country'          , NULL  , 3 , true, 'system')
    ,(299, 44, 'br_region_address2'          , 'Region Address 2'        , NULL  , 4 , true, 'system')
    ,(300, 44, 'br_region_district'          , 'Region District'         , NULL  , 5 , true, 'system')
    ,(301, 44, 'br_region_state'             , 'State'                   , NULL  , 6 , true, 'system')
    ,(302, 44, 'br_region_address3'          , 'Region Address 3'        , NULL  , 7 , true, 'system')
    ,(303, 44, 'br_region_name'              , 'Region Name'             , NULL  , 8 , true, 'system')
    -- ============ Branch Master / Branch (id 45) ============
    ,(304, 45, 'br_invoice_prefix'           , 'Invoice Series Prefix'   , NULL  , 1 , true, 'system')
    ,(305, 45, 'br_rounding_mode'            , 'Rounding Mode'           , NULL  , 2 , true, 'system')
    ,(306, 45, 'br_rounding_value'           , 'Rounding Value'          , NULL  , 3 , true, 'system')
    ,(307, 45, 'br_bill_greeting'            , 'Bill Greeting'           , NULL  , 4 , true, 'system')
    ,(308, 45, 'br_bill_terms'               , 'Terms'                   , NULL  , 5 , true, 'system')
    ,(309, 45, 'br_bill_default_godown'      , 'Default Godown Id'       , NULL  , 6 , true, 'system')
    ,(310, 45, 'br_bank_id'                  , 'Bank Id'                 , NULL  , 7 , true, 'system')
    -- ============ Branch Master / Branch (id 46) ============
    ,(311, 46, 'br_gstin'                    , 'GSTIN No'                , NULL  , 1 , true, 'system')
    ,(312, 46, 'br_gst_registration'         , 'GST Registration Type'   , NULL  , 2 , true, 'system')
    ,(313, 46, 'br_pan'                      , 'PAN No'                  , NULL  , 3 , true, 'system')
    ,(314, 46, 'br_fssai_no'                 , 'FSSAI No'                , NULL  , 4 , true, 'system')
    ,(315, 46, 'br_fssai_license_no'         , 'FSSAI License Type'      , NULL  , 5 , true, 'system')
    ,(316, 46, 'br_fssai_valid'              , 'FSSAI Valid Upto'        , NULL  , 6 , true, 'system')
    -- ============ Branch Master / Branch (id 47) ============
    ,(317, 47, 'br_allow_negative_stock'     , 'Allow Negative Stock'    , NULL  , 1 , true, 'system')
    ,(318, 47, 'br_sms_applicable'           , 'SMS Applicable'          , NULL  , 2 , true, 'system')
    ,(319, 47, 'br_default_branch'           , 'Default Branch'          , NULL  , 3 , true, 'system')
    ,(320, 47, 'br_active'                   , 'Active'                  , NULL  , 4 , true, 'system')
    -- ============ Employee Master / Employee master (id 48) ============
    ,(321, 48, 'emp_name'                    , 'Employee Name'           , NULL  , 1 , true, 'system')
    ,(322, 48, 'emp_company'                 , 'Company'                 , NULL  , 2 , true, 'system')
    ,(323, 48, 'emp_dob'                     , 'Date of Birth'           , NULL  , 3 , true, 'system')
    ,(324, 48, 'emp_alias'                   , 'Alias'                   , NULL  , 4 , true, 'system')
    ,(325, 48, 'emp_branch'                  , 'Branch'                  , NULL  , 5 , true, 'system')
    ,(326, 48, 'emp_maritial_status'         , 'Marital Status'          , NULL  , 6 , true, 'system')
    ,(327, 48, 'emp_code'                    , 'Employee Code'           , NULL  , 7 , true, 'system')
    ,(328, 48, 'emp_department'              , 'Department'              , NULL  , 8 , true, 'system')
    ,(329, 48, 'emp_blood_group'             , 'Blood Group'             , NULL  , 9 , true, 'system')
    ,(330, 48, 'emp_gender'                  , 'Gender'                  , NULL  , 10, true, 'system')
    ,(331, 48, 'emp_designation'             , 'Designation'             , NULL  , 11, true, 'system')
    -- ============ Employee Master / Employee master (id 49) ============
    ,(332, 49, 'emp_address1'                , 'Address Line 1'          , NULL  , 1 , true, 'system')
    ,(333, 49, 'emp_district'                , 'District'                , NULL  , 2 , true, 'system')
    ,(334, 49, 'emp_email'                   , 'Email'                   , NULL  , 3 , true, 'system')
    ,(335, 49, 'emp_address2'                , 'Address Line 2'          , NULL  , 4 , true, 'system')
    ,(336, 49, 'emp_state'                   , 'State'                   , NULL  , 5 , true, 'system')
    ,(337, 49, 'emp_mobile1'                 , 'Mobile 1'                , NULL  , 6 , true, 'system')
    ,(338, 49, 'emp_address3'                , 'Address Line 3'          , NULL  , 7 , true, 'system')
    ,(339, 49, 'emp_pincode'                 , 'Pincode'                 , NULL  , 8 , true, 'system')
    ,(340, 49, 'emp_mobile2'                 , 'Mobile 2'                , NULL  , 9 , true, 'system')
    ,(341, 49, 'emp_city'                    , 'City'                    , NULL  , 10, true, 'system')
    -- ============ Employee Master / Employee master (id 50) ============
    ,(342, 50, 'emp_employment_status'       , 'Employment Status'       , NULL  , 1 , true, 'system')
    ,(343, 50, 'emp_joined_on'               , 'Joined On'               , NULL  , 2 , true, 'system')
    ,(344, 50, 'emp_probation_end_on'        , 'Probation End On'        , NULL  , 3 , true, 'system')
    ,(345, 50, 'emp_confirmation'            , 'Confirmation On'         , NULL  , 4 , true, 'system')
    ,(346, 50, 'emp_left'                    , 'Left On'                 , NULL  , 5 , true, 'system')
    -- ============ Employee Master / Employee master (id 51) ============
    ,(347, 51, 'emp_shift_id'                , 'Shift Id'                , NULL  , 1 , true, 'system')
    ,(348, 51, 'emp_attendance_constraint_id', 'Attendance Constraint Id', NULL  , 2 , true, 'system')
    ,(349, 51, 'emp_holiday_group_id'        , 'Holiday Group Id'        , NULL  , 3 , true, 'system')
    ,(350, 51, 'emp_overtime_allowed'        , 'Overtime Allowed'        , NULL  , 4 , true, 'system')
    -- ============ Employee Master / Employee Master (id 52) ============
    ,(351, 52, 'emp_has_commission'          , 'Has Commission'          , NULL  , 1 , true, 'system')
    ,(352, 52, 'emp_salary_type'             , 'Salary Type'             , NULL  , 2 , true, 'system')
    ,(353, 52, 'emp_salary_amount'           , 'Salary Amount'           , NULL  , 3 , true, 'system')
    ,(354, 52, 'emp_bata_amount'             , 'Bata Amount'             , NULL  , 4 , true, 'system')
    ,(355, 52, 'emp_km_bata_amount'          , 'KM Bata Amount'          , NULL  , 5 , true, 'system')
    -- ============ Employee Master / Employee master (id 53) ============
    ,(356, 53, 'emp_pan_no'                  , 'PAN No'                  , NULL  , 1 , true, 'system')
    ,(357, 53, 'emp_aadhar_no'               , 'Aadhar No'               , NULL  , 2 , true, 'system')
    ,(358, 53, 'emp_pf_no'                   , 'PF No'                   , NULL  , 3 , true, 'system')
    ,(359, 53, 'emp_esi_no'                  , 'ESI No'                  , NULL  , 4 , true, 'system')
    -- ============ Employee Master / Employee master (id 54) ============
    ,(360, 54, 'emp_upload_photo'            , 'Upload Photo'            , NULL  , 1 , true, 'system')
    ,(361, 54, 'emp_remarks'                 , 'Remarks'                 , NULL  , 2 , true, 'system')
    ,(362, 54, 'emp_record_active'           , 'Record Active'           , NULL  , 3 , true, 'system')
    -- ============ Quotation / Quoation entry (id 61) ============
    ,(444, 61, 'Existing Customer'           , 'Existing Customer'       , ''    , 1 , true, 'system')
    ,(445, 61, 'Customer Name'               , 'Customer Name'           , ''    , 2 , true, 'system')
    ,(446, 61, 'Address'                     , 'Address'                 , ''    , 3 , true, 'system')
    ,(447, 61, 'Place'                       , 'Place'                   , ''    , 4 , true, 'system')
    ,(448, 61, 'Phone'                       , 'Phone'                   , ''    , 5 , true, 'system')
    ,(449, 61, 'GSTIN'                       , 'GSTIN'                   , ''    , 5 , true, 'system')
    ,(450, 61, 'POS State Code'              , 'POS State Code'          , ''    , 6 , true, 'system')
    ,(451, 61, 'Beat'                        , 'Beat'                    , ''    , 7 , true, 'system')
    ,(452, 61, 'Salesman'                    , 'Salesman'                , ''    , 8 , true, 'system')
    ,(453, 61, 'Agent'                       , 'Agent'                   , ''    , 9 , true, 'system')
    ,(454, 61, 'Contact Person'              , 'Contact Person'          , ''    , 10, true, 'system')
    ,(455, 61, 'Contact No'                  , 'Contact No'              , ''    , 11, true, 'system')
    ,(456, 61, 'Freight'                     , 'Freight'                 , ''    , 12, true, 'system')
    ,(457, 61, 'Load'                        , 'Load'                    , ''    , 13, true, 'system')
    ,(458, 61, 'Unload'                      , 'Unload'                  , ''    , 14, true, 'system')
    ,(459, 61, 'Promo'                       , 'Promo'                   , ''    , 15, true, 'system')
    ,(460, 61, 'Quote No'                    , 'Quote No'                , ''    , 16, true, 'system')
    ,(461, 61, 'Quote Date'                  , 'Quote Date'              , ''    , 17, true, 'system')
    ,(462, 61, 'Valid Until'                 , 'Valid Until'             , ''    , 18, true, 'system')
    ,(463, 61, 'Validity Days'               , 'Validity Days'           , ''    , 19, true, 'system')
    ,(464, 61, 'Price Level'                 , 'Price Level'             , ''    , 20, true, 'system')
    -- ============ Suppliers / Identity (id 62) ============
    ,(465, 62, 'GST_No'                      , 'GST No'                  , ''    , 1 , true, 'system')
    ,(466, 62, 'Supplier_name'               , 'Supplier Name'           , ''    , 2 , true, 'system')
    ,(467, 62, 'Short Name'                  , 'Short Name'              , ''    , 3 , true, 'system')
    ,(468, 62, 'Group'                       , 'Group'                   , ''    , 4 , true, 'system')
    ,(469, 62, 'Company'                     , 'Company'                 , ''    , 5 , true, 'system')
    ,(470, 62, 'Branch'                      , 'Branch'                  , ''    , 6 , true, 'system')
    ,(471, 62, 'GST Type'                    , 'GST Type'                , ''    , 7 , true, 'system')
    ,(472, 62, 'Purchase Type'               , 'Purchase Type'           , ''    , 8 , true, 'system')
    ,(473, 62, 'PAN No'                      , 'PAN No'                  , ''    , 9 , true, 'system')
    ,(474, 62, 'Drug Licence No'             , 'Drug Licence No'         , ''    , 10, true, 'system')
    ,(475, 62, 'Active'                      , 'Active'                  , ''    , 11, true, 'system')
    ,(476, 62, 'Address 1'                   , 'Address 1'               , ''    , 12, true, 'system')
    ,(477, 62, 'Address 2'                   , 'Address 2'               , ''    , 13, true, 'system')
    ,(478, 62, 'Address 3'                   , 'Address 3'               , ''    , 14, true, 'system')
    ,(479, 62, 'City'                        , 'City'                    , ''    , 15, true, 'system')
    ,(480, 62, 'District'                    , 'District'                , ''    , 16, true, 'system')
    ,(481, 62, 'State'                       , 'State'                   , ''    , 17, true, 'system')
    ,(482, 62, 'Pincode'                     , 'Pincode'                 , ''    , 18, true, 'system')
    ,(483, 62, 'Country'                     , 'Country'                 , ''    , 19, true, 'system')
    ,(484, 62, 'Telephone'                   , 'Telephone'               , ''    , 20, true, 'system')
    ,(485, 62, 'Phone'                       , 'Phone'                   , ''    , 21, true, 'system')
    ,(486, 62, 'Email'                       , 'Email'                   , ''    , 22, true, 'system')
    ,(487, 62, 'WhatsApp'                    , 'WhatsApp'                , ''    , 23, true, 'system')
    ,(488, 62, 'Website'                     , 'Website'                 , ''    , 24, true, 'system')
    -- ============ Suppliers / Notes (id 63) ============
    ,(489, 63, 'Cheque Pre-Name'             , 'Cheque Pre-Name'         , ''    , 1 , true, 'system')
    ,(490, 63, 'Credit Days'                 , 'Credit Days'             , ''    , 2 , true, 'system')
    ,(491, 63, 'Cash Disc %'                 , 'Cash Disc %'             , ''    , 3 , true, 'system')
    ,(492, 63, 'Sort Order'                  , 'Sort Order'              , ''    , 4 , true, 'system')
    ,(493, 63, 'Collection Days'             , 'Collection Days'         , ''    , 5 , true, 'system')
    ,(494, 63, 'Notes'                       , 'Notes'                   , ''    , 6 , true, 'system')
    -- ============ Suppliers / Regional Details (id 64) ============
    ,(495, 64, 'Regional Name'               , 'Regional Name'           , ''    , 1 , true, 'system')
    ,(496, 64, 'Regional Address 1'          , 'Address 1'               , ''    , 2 , true, 'system')
    ,(497, 64, 'Regional Address 2'          , 'Address 2'               , ''    , 3 , true, 'system')
    ,(498, 64, 'Regional Address 3'          , 'Address 3'               , ''    , 4 , true, 'system')
    ,(499, 64, 'Regional City'               , 'City'                    , ''    , 5 , true, 'system')
    ,(500, 64, 'Regional District'           , 'District'                , ''    , 6 , true, 'system')
    ,(501, 64, 'Regional State'              , 'State'                   , ''    , 7 , true, 'system')
    ,(502, 64, 'Regional Country'            , 'Country'                 , ''    , 8 , true, 'system')
    -- ============ Quotation / Terms (id 65) ============
    ,(503, 65, 'Remarks'                     , 'Remarks'                 , ''    , 1 , true, 'system')
    ,(504, 65, 'Payment Terms'               , 'Payment Terms'           , ''    , 2 , true, 'system')
    ,(505, 65, 'Delivery Terms'              , 'Delivery Terms'          , ''    , 3 , true, 'system')
    ,(506, 65, 'Other Terms'                 , 'Other Terms'             , ''    , 4 , true, 'system')
    -- ============ Customers / Identify (id 66) ============
    ,(507, 66, 'Customer Name'               , 'Customer Name'           , ''    , 1 , true, 'system')
    ,(508, 66, 'GST No'                      , 'GST No'                  , ''    , 2 , true, 'system')
    ,(509, 66, 'Short Name'                  , 'Short Name'              , ''    , 3 , true, 'system')
    ,(510, 66, 'Group'                       , 'Group'                   , ''    , 4 , true, 'system')
    ,(511, 66, 'Company'                     , 'Company'                 , ''    , 5 , true, 'system')
    ,(512, 66, 'Branch'                      , 'Branch'                  , ''    , 6 , true, 'system')
    ,(513, 66, 'Area'                        , 'Area'                    , ''    , 7 , true, 'system')
    ,(514, 66, 'GST Type'                    , 'GST Type'                , ''    , 8 , true, 'system')
    ,(515, 66, 'Price Level'                 , 'Price Level'             , ''    , 9 , true, 'system')
    ,(516, 66, 'PAN No'                      , 'PAN No'                  , ''    , 10, true, 'system')
    ,(517, 66, 'e-Commerce GSTIN'            , 'E-Commerce GSTIN'        , ''    , 11, true, 'system')
    ,(518, 66, 'Active'                      , 'Active'                  , ''    , 12, true, 'system')
    ,(519, 66, 'Customer Code'               , 'Customer Code'           , ''    , 13, true, 'system')
    ,(520, 66, 'Sort Order'                  , 'Sort Order'              , ''    , 14, true, 'system')
    ,(521, 66, 'Salesman'                    , 'Salesman'                , ''    , 15, true, 'system')
    ,(522, 66, 'Address 1'                   , 'Address 1'               , ''    , 16, true, 'system')
    ,(523, 66, 'Address 2'                   , 'Address 2'               , ''    , 17, true, 'system')
    ,(524, 66, 'Address 3'                   , 'Address 3'               , ''    , 18, true, 'system')
    ,(525, 66, 'City'                        , 'City'                    , ''    , 19, true, 'system')
    ,(526, 66, 'District'                    , 'District'                , ''    , 20, true, 'system')
    ,(527, 66, 'State'                       , 'State'                   , ''    , 21, true, 'system')
    ,(528, 66, 'Pincode'                     , 'Pincode'                 , ''    , 22, true, 'system')
    ,(529, 66, 'Country'                     , 'Country'                 , ''    , 23, true, 'system')
    ,(530, 66, 'Telephone'                   , 'Telephone'               , ''    , 24, true, 'system')
    ,(531, 66, 'Phone 1'                     , 'Phone 1'                 , ''    , 25, true, 'system')
    ,(532, 66, 'Phone 2'                     , 'Phone 2'                 , ''    , 26, true, 'system')
    ,(533, 66, 'WhatsApp'                    , 'WhatsApp'                , ''    , 27, true, 'system')
    ,(534, 66, 'Email'                       , 'Email'                   , ''    , 28, true, 'system')
    ,(535, 66, 'Aadhaar'                     , 'Aadhaar'                 , ''    , 29, true, 'system')
    ,(536, 66, 'Credit Allowed'              , 'Credit Allowed'          , ''    , 30, true, 'system')
    ,(537, 66, 'Credit Days'                 , 'Credit Days'             , ''    , 31, true, 'system')
    ,(538, 66, 'Credit Bill Limit'           , 'Credit Bill Limit'       , ''    , 32, true, 'system')
    ,(539, 66, 'Credit Amt Limit'            , 'Credit Amt Limit'        , ''    , 33, true, 'system')
    ,(540, 66, 'Grace Days'                  , 'Grace Days'              , ''    , 34, true, 'system')
    ,(541, 66, 'Debit Balance'               , 'Debit Balance'           , ''    , 35, true, 'system')
    ,(542, 66, 'Discount %'                  , 'Discount %'              , ''    , 36, true, 'system')
    ,(543, 66, 'Allow Discount'              , 'Allow Discount'          , ''    , 37, true, 'system')
    ,(544, 66, 'Allow Loyalty'               , 'Allow Loyalty'           , ''    , 38, true, 'system')
    ,(545, 66, 'Allow Promotion'             , 'Allow Promotion'         , ''    , 39, true, 'system')
    ,(546, 66, 'Enable SMS'                  , 'Enable SMS'              , ''    , 40, true, 'system')
    ,(547, 66, 'Overdue SMS'                 , 'Overdue SMS'             , ''    , 41, true, 'system')
    ,(548, 66, 'Overdue Billing'             , 'Overdue Billing'         , ''    , 42, true, 'system')
    ,(549, 66, 'TCS Applicable'              , 'TCS Applicable'          , ''    , 43, true, 'system')
    ,(550, 66, 'IT Coll. Exempted'           , 'IT Coll. Exempted'       , ''    , 44, true, 'system')
    ,(551, 66, 'Freight Charge'              , 'Freight Charge'          , ''    , 45, true, 'system')
    ,(552, 66, 'Loading Charge'              , 'Loading Charge'          , ''    , 46, true, 'system')
    ,(553, 66, 'Unloading Charge'            , 'Unloading Charge'        , ''    , 46, true, 'system')
    -- ============ Customers / Notes (id 67) ============
    ,(554, 67, 'Contact Person'              , 'Contact Person'          , ''    , 1 , true, 'system')
    ,(555, 67, 'Transport Name'              , 'Transport Name'          , ''    , 2 , true, 'system')
    ,(556, 67, 'Landmark'                    , 'Landmark'                , ''    , 3 , true, 'system')
    ,(557, 67, 'Distance (km)'               , 'Distance (km)'           , ''    , 4 , true, 'system')
    ,(558, 67, 'Birth Date'                  , 'Birth Date'              , ''    , 5 , true, 'system')
    ,(559, 67, 'Marriage Date'               , 'Marriage Date'           , ''    , 6 , true, 'system')
    ,(560, 67, 'Collection Days'             , 'Collection Days'         , ''    , 7 , true, 'system')
    ,(561, 67, 'Notes'                       , 'Notes'                   , ''    , 8 , true, 'system')
    -- ============ Customers / Region Details (id 68) ============
    ,(562, 68, 'Regional Name'               , 'Regional Name'           , ''    , 1 , true, 'system')
    ,(563, 68, 'Regional Address 1'          , 'Address 1'               , ''    , 2 , true, 'system')
    ,(564, 68, 'Regional Address 2'          , 'Address 2'               , ''    , 3 , true, 'system')
    ,(565, 68, 'Regional Address 3'          , 'Address 3'               , ''    , 4 , true, 'system')
    ,(566, 68, 'Regional City'               , 'City'                    , ''    , 5 , true, 'system')
    ,(567, 68, 'Regional District'           , 'District'                , ''    , 6 , true, 'system')
    ,(568, 68, 'Regional State'              , 'State'                   , ''    , 7 , true, 'system')
    ,(569, 68, 'Regional Country'            , 'Country'                 , ''    , 8 , true, 'system')
    -- ============ Item Master / Core Details (id 69) ============
    ,(570, 69, 'Item Name'                   , 'Item Name'               , NULL  , 1 , true, 'system')
    ,(571, 69, 'Sku'                         , 'Sku'                     , NULL  , 2 , true, 'system')
    ,(572, 69, 'Item Name (Local)'           , 'Item Name (Local)'       , NULL  , 3 , true, 'system')
    ,(573, 69, 'Item Code'                   , 'Item Code'               , NULL  , 4 , true, 'system')
    ,(574, 69, 'Alias'                       , 'Alias'                   , NULL  , 5 , true, 'system')
    ,(575, 69, 'Default Barcode'             , 'Default Barcode'         , NULL  , 6 , true, 'system')
    ,(576, 69, 'Batch Config'                , 'Batch Config'            , NULL  , 7 , true, 'system')
    ,(577, 69, 'Hsn Code'                    , 'Hsn Code'                , NULL  , 8 , true, 'system')
    ,(578, 69, 'Default Tax'                 , 'Default Tax'             , NULL  , 9 , true, 'system')
    ,(579, 69, 'Sort Order'                  , 'Sort Order'              , NULL  , 10, true, 'system')
    ,(580, 69, 'Is Active'                   , 'Is Active'               , NULL  , 11, true, 'system')
    ,(581, 69, 'Company'                     , 'Company'                 , NULL  , 12, true, 'system')
    ,(582, 69, 'Branch'                      , 'Branch'                  , NULL  , 13, true, 'system')
    ,(583, 69, 'Item Group'                  , 'Item Group'              , NULL  , 14, true, 'system')
    ,(584, 69, 'Item Category'               , 'Item Category'           , NULL  , 15, true, 'system')
    ,(585, 69, 'Item Section'                , 'Item Section'            , NULL  , 16, true, 'system')
    ,(586, 69, 'Item Brand'                  , 'Item Brand'              , NULL  , 17, true, 'system')
    ,(587, 69, 'Default Supplier'            , 'Default Supplier'        , NULL  , 18, true, 'system')
    ,(588, 69, 'Item Customer Group'         , 'Item Customer Group'     , NULL  , 19, true, 'system')
    -- ============ Item Master / Ean Table (id 70) ============
    ,(589, 70, 'Retail Item'                 , 'Retail Item'             , NULL  , 1 , true, 'system')
    ,(590, 70, 'Allow Sales'                 , 'Allow Sales'             , NULL  , 2 , true, 'system')
    ,(591, 70, 'Allow Loading'               , 'Allow Loading'           , NULL  , 3 , true, 'system')
    ,(592, 70, 'Damagable Product'           , 'Damagable Product'       , NULL  , 4 , true, 'system')
    ,(593, 70, 'Allow Negative Stock'        , 'Allow Negative Stock'    , NULL  , 5 , true, 'system')
    ,(594, 70, 'Allow Promo'                 , 'Allow Promo'             , NULL  , 6 , true, 'system')
    ,(595, 70, 'Price List'                  , 'Price List'              , NULL  , 7 , true, 'system')
    ,(596, 70, 'Allow Sales Return'          , 'Allow Sales Return'      , NULL  , 8 , true, 'system')
    ,(597, 70, 'Allow Freight'               , 'Allow Freight'           , NULL  , 9 , true, 'system')
    ,(598, 70, 'Is Kit'                      , 'Is Kit'                  , NULL  , 10, true, 'system')
    ,(599, 70, 'Allow Negative So'           , 'Allow Negative So'       , NULL  , 11, true, 'system')
    ,(600, 70, 'Allow Loyalty'               , 'Allow Loyalty'           , NULL  , 12, true, 'system')
    ,(601, 70, 'Batch Based'                 , 'Batch Based'             , NULL  , 13, true, 'system')
    ,(602, 70, 'Allow Purchase'              , 'Allow Purchase'          , NULL  , 14, true, 'system')
    ,(603, 70, 'Auto Break'                  , 'Auto Break'              , NULL  , 15, true, 'system')
    ,(604, 70, 'Is Demand'                   , 'Is Demand'               , NULL  , 16, true, 'system')
    ,(605, 70, 'Has Offer'                   , 'Has Offer'               , NULL  , 17, true, 'system')
    ,(606, 70, 'Barcode Sticker'             , 'Barcode Sticker'         , NULL  , 18, true, 'system')
    ,(607, 70, 'Service Item'                , 'Service Item'            , NULL  , 19, true, 'system')
    ,(608, 70, 'Allow Po'                    , 'Allow Po'                , NULL  , 20, true, 'system')
    ,(609, 70, 'Auto Make'                   , 'Auto Make'               , NULL  , 21, true, 'system')
    ,(610, 70, 'Expiry Item'                 , 'Expiry Item'             , NULL  , 22, true, 'system')
    ,(611, 70, 'Random Stock'                , 'Random Stock'            , NULL  , 23, true, 'system')
    ,(612, 70, 'Allow So'                    , 'Allow So'                , NULL  , 24, true, 'system')
    ,(613, 70, 'Weigh Scale'                 , 'Weigh Scale'             , NULL  , 25, true, 'system')
    ,(614, 70, 'Expiry Days'                 , 'Expiry Days'             , NULL  , 26, true, 'system')
    ,(615, 70, 'Intimate Before Days'        , 'Intimate Before Days'    , NULL  , 27, true, 'system')
    -- ============ Item Master / Inventory&Notes (id 71) ============
    ,(616, 71, 'Storage Location'            , 'Storage Location'        , NULL  , 1 , true, 'system')
    ,(617, 71, 'Image Url'                   , 'Image Url'               , NULL  , 2 , true, 'system')
    ,(618, 71, 'Photo File'                  , 'Photo File'              , NULL  , 3 , true, 'system')
    ,(619, 71, 'Notes'                       , 'Notes'                   , NULL  , 4 , true, 'system')
) AS v(field_id, field_section_id, field_name, field_gui_name, field_secondary_text, field_position, field_visibility, field_created_by)
WHERE NOT EXISTS (
  SELECT 1 FROM fixed.form_field existing
   WHERE existing.field_section_id = v.field_section_id
)
  AND EXISTS (
  SELECT 1 FROM fixed.form_section parent
   WHERE parent.section_id = v.field_section_id
)
ON CONFLICT (field_id) DO NOTHING;

-- Keep the identity sequence ahead of the seeded ids, so the next row created from
-- the UI does not collide with one of them.
SELECT setval(
    pg_get_serial_sequence('fixed.form_field', 'field_id'),
    (SELECT GREATEST(COALESCE(MAX(field_id), 0), 1) FROM fixed.form_field),
    true
);

COMMIT;
