import { TemplateDefinitionInput } from '../dto/template-definition.schema';

/**
 * Thermal receipt — 58mm roll, 32 columns. ESC/POS.
 *
 * ── Why 32 columns needs its own template ───────────────────────────────────
 * The 80mm design puts qty, rate and amount on one line under the item name,
 * which needs 5 + 1 + 8 + 9 = 23 columns plus separation. At 32 columns that
 * leaves nothing, and more importantly the amount column would sit at column 23
 * where a right-aligned five-figure total has no room.
 *
 * So this layout drops the rate from the line entirely — a 58mm roll is a
 * counter/POS format where the customer wants item, quantity and amount — and
 * puts the rate inline with the quantity as `2 x 142.50` on the left, with the
 * amount right-aligned. Same information, one fewer column position.
 */

const COLUMNS = 32;
/** One column wider than the longest amount, so it never abuts the qty x rate. */
const AMOUNT_COL = 21;
const AMOUNT_WIDTH = 11;

export const THERMAL_RECEIPT_T58_NAME = 'Thermal Receipt — 58mm';

export const buildThermalReceiptT58 = (): TemplateDefinitionInput => ({
  schemaVersion: 1,
  layoutMode: 'GRID',
  meta: {
    gallery: 'thermal-receipt-t58',
    description: '32-column ESC/POS receipt for a 58mm thermal roll.',
  },
  paper: {
    code: 'T58',
    widthMm: 58,
    heightMm: null,
    orientation: 'PORTRAIT',
    margins: { top: 0, right: 0, bottom: 0, left: 0 },
    columns: COLUMNS,
  },
  datasets: [
    { name: 'company', provider: 'company.profile', cardinality: 'one' },
    { name: 'branch', provider: 'branch.profile', cardinality: 'one' },
    { name: 'invoice', provider: 'sales.invoice.header', cardinality: 'one' },
    { name: 'items', provider: 'sales.invoice.lines', cardinality: 'many' },
  ],
  bands: [
    {
      type: 'REPORT_HEADER',
      heightRows: 8,
      heightMm: 8,
      elements: [
        {
          id: 'shop',
          kind: 'TEXT',
          col: 0,
          row: 0,
          cols: COLUMNS,
          x: 0,
          y: 0,
          w: COLUMNS,
          h: 1,
          value: '{{ company.shortName|default(company.name)|truncate(16) }}',
          align: 'center',
          font: { size: 16, bold: true },
        },
        {
          id: 'addr',
          kind: 'TEXT',
          col: 0,
          row: 1,
          cols: COLUMNS,
          x: 0,
          y: 1,
          w: COLUMNS,
          h: 1,
          value:
            '{{ branch.city|default(company.city) }} {{ branch.phone|default(company.phone) }}',
          align: 'center',
          font: { size: 8 },
        },
        {
          id: 'gstin',
          kind: 'TEXT',
          col: 0,
          row: 2,
          cols: COLUMNS,
          x: 0,
          y: 2,
          w: COLUMNS,
          h: 1,
          value: 'GSTIN {{ branch.gstin|default(company.gstin) }}',
          align: 'center',
          font: { size: 8 },
        },
        {
          id: 'r1',
          kind: 'LINE',
          col: 0,
          row: 3,
          x1: 0,
          y1: 3,
          x2: COLUMNS - 1,
          y2: 3,
          x: 0,
          y: 3,
          gridChar: '=',
        },
        {
          id: 'no',
          kind: 'TEXT',
          col: 0,
          row: 4,
          cols: 20,
          x: 0,
          y: 4,
          w: 20,
          h: 1,
          value: '{{ invoice.billNo|truncate(20) }}',
          font: { size: 8 },
        },
        {
          id: 'dt',
          kind: 'TEXT',
          col: 20,
          row: 4,
          cols: 12,
          x: 20,
          y: 4,
          w: 12,
          h: 1,
          value: "{{ invoice.billDate|date('dd-MM-yy') }}",
          align: 'right',
          font: { size: 8 },
        },
        {
          id: 'cust',
          kind: 'TEXT',
          col: 0,
          row: 5,
          cols: COLUMNS,
          x: 0,
          y: 5,
          w: COLUMNS,
          h: 1,
          value: '{{ invoice.custName|truncate(32) }}',
          font: { size: 8 },
        },
        {
          id: 'ch',
          kind: 'TEXT',
          col: 0,
          row: 6,
          cols: 20,
          x: 0,
          y: 6,
          w: 20,
          h: 1,
          value: 'Item / Qty x Rate',
          font: { size: 8 },
        },
        {
          id: 'ch-amt',
          kind: 'TEXT',
          col: AMOUNT_COL,
          row: 6,
          cols: AMOUNT_WIDTH,
          x: AMOUNT_COL,
          y: 6,
          w: AMOUNT_WIDTH,
          h: 1,
          value: 'Amount',
          align: 'right',
          font: { size: 8 },
        },
        {
          id: 'r2',
          kind: 'LINE',
          col: 0,
          row: 7,
          x1: 0,
          y1: 7,
          x2: COLUMNS - 1,
          y2: 7,
          x: 0,
          y: 7,
          gridChar: '-',
        },
      ],
    },

    {
      type: 'DETAIL',
      dataset: 'items',
      // Fixed two rows, name truncated rather than wrapped: a wrapping name
      // would push into row 1 and overprint the figures, since elements sit at
      // fixed offsets inside a band even when the band grows.
      heightRows: 2,
      heightMm: 2,
      elements: [
        {
          id: 'r-name',
          kind: 'FIELD',
          col: 0,
          row: 0,
          cols: COLUMNS,
          x: 0,
          y: 0,
          w: COLUMNS,
          h: 1,
          value: '{{ row.itemName|truncate(32) }}',
          font: { size: 8 },
        },
        {
          id: 'r-qxr',
          kind: 'FIELD',
          col: 1,
          row: 1,
          cols: 20,
          x: 1,
          y: 1,
          w: 20,
          h: 1,
          value: "{{ row.qty|fmt('0.##') }} x {{ row.rate|fmt('#,##0.00') }}",
          font: { size: 8 },
        },
        {
          id: 'r-amt',
          kind: 'FIELD',
          col: AMOUNT_COL,
          row: 1,
          cols: AMOUNT_WIDTH,
          x: AMOUNT_COL,
          y: 1,
          w: AMOUNT_WIDTH,
          h: 1,
          value: "{{ row.netAmount|fmt('#,##0.00') }}",
          align: 'right',
          font: { size: 8 },
        },
      ],
    },

    {
      type: 'SUMMARY',
      heightRows: 9,
      heightMm: 9,
      keepWithLastDetail: true,
      elements: [
        {
          id: 's-r1',
          kind: 'LINE',
          col: 0,
          row: 0,
          x1: 0,
          y1: 0,
          x2: COLUMNS - 1,
          y2: 0,
          x: 0,
          y: 0,
          gridChar: '-',
        },
        {
          id: 's-cnt-l',
          kind: 'TEXT',
          col: 0,
          row: 1,
          cols: 20,
          x: 0,
          y: 1,
          w: 20,
          h: 1,
          value: 'Items',
          font: { size: 8 },
        },
        {
          id: 's-cnt',
          kind: 'FIELD',
          col: AMOUNT_COL,
          row: 1,
          cols: AMOUNT_WIDTH,
          x: AMOUNT_COL,
          y: 1,
          w: AMOUNT_WIDTH,
          h: 1,
          value: "{{ row.qty|fmt('0') }}",
          align: 'right',
          font: { size: 8 },
          aggregate: { fn: 'count', scope: 'REPORT', dataset: 'items' },
        },
        {
          id: 's-tax-l',
          kind: 'TEXT',
          col: 0,
          row: 2,
          cols: 20,
          x: 0,
          y: 2,
          w: 20,
          h: 1,
          value: 'GST',
          font: { size: 8 },
          visible: '{{ invoice.taxAmt != 0 }}',
        },
        {
          id: 's-tax',
          kind: 'TEXT',
          col: AMOUNT_COL,
          row: 2,
          cols: AMOUNT_WIDTH,
          x: AMOUNT_COL,
          y: 2,
          w: AMOUNT_WIDTH,
          h: 1,
          value: "{{ invoice.taxAmt|fmt('#,##0.00') }}",
          align: 'right',
          font: { size: 8 },
          visible: '{{ invoice.taxAmt != 0 }}',
        },
        {
          id: 's-rnd-l',
          kind: 'TEXT',
          col: 0,
          row: 3,
          cols: 20,
          x: 0,
          y: 3,
          w: 20,
          h: 1,
          value: 'Round Off',
          font: { size: 8 },
          visible: '{{ invoice.roundOff != 0 }}',
        },
        {
          id: 's-rnd',
          kind: 'TEXT',
          col: AMOUNT_COL,
          row: 3,
          cols: AMOUNT_WIDTH,
          x: AMOUNT_COL,
          y: 3,
          w: AMOUNT_WIDTH,
          h: 1,
          value: "{{ invoice.roundOff|fmt('#,##0.00') }}",
          align: 'right',
          font: { size: 8 },
          visible: '{{ invoice.roundOff != 0 }}',
        },
        {
          id: 's-r2',
          kind: 'LINE',
          col: 0,
          row: 4,
          x1: 0,
          y1: 4,
          x2: COLUMNS - 1,
          y2: 4,
          x: 0,
          y: 4,
          gridChar: '=',
        },
        {
          id: 's-total',
          kind: 'TEXT',
          col: 0,
          row: 5,
          cols: COLUMNS,
          x: 0,
          y: 5,
          w: COLUMNS,
          h: 1,
          value: "TOTAL {{ invoice.billAmt|fmt('#,##0.00') }}",
          align: 'center',
          font: { size: 16, bold: true },
        },
        {
          id: 's-mode',
          kind: 'TEXT',
          col: 0,
          row: 6,
          cols: COLUMNS,
          x: 0,
          y: 6,
          w: COLUMNS,
          h: 1,
          value: '{{ invoice.payMode }}',
          align: 'center',
          font: { size: 8 },
        },
        {
          id: 's-save',
          kind: 'TEXT',
          col: 0,
          row: 7,
          cols: COLUMNS,
          x: 0,
          y: 7,
          w: COLUMNS,
          h: 1,
          value: 'Saved Rs.{{ invoice.mrpSavings|fmt("#,##0.00") }}',
          align: 'center',
          font: { size: 8 },
          visible: '{{ invoice.mrpSavings > 0 }}',
        },
        {
          id: 's-greet',
          kind: 'TEXT',
          col: 0,
          row: 8,
          cols: COLUMNS,
          x: 0,
          y: 8,
          w: COLUMNS,
          h: 1,
          value: 'Thank you, visit again',
          align: 'center',
          font: { size: 8 },
        },
      ],
    },
  ],
});
